Repository vgstation-coders/vgstation13, pull requests merged in 2018-10, with the labels that each got.

#19870 Potentially fixes bad problems with fire, and definitely fixes a completely different bad problem with fire
  code/ZAS/Fire.dm
Labels: Bug / Fix

#19892 fixes starscreen 70+ range issue
  code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_gen.dm
Labels: Bug / Fix

#19897 Fixes jecties
  icons/obj/food.dmi
Labels: Bug / Fix

#19900 Chameleon Overlays fix
  code/game/objects/items/devices/chameleonproj.dm
Labels: Bug / Fix

#19881 Fixed num2hex not padding with the right number of zeros
  code/libs/s_html/hexadecimal.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/hexadecimal.dm
  code/modules/unit_tests/unit_test.dm
Labels: Bug / Fix, Port

#19911 Fixes one of the many MULE bugs
  code/game/machinery/bots/mulebot.dm
Labels: Bug / Fix

#19908 Adds female groins
  icons/mob/human_races/r_ghoul.dmi
  icons/mob/human_races/r_plasmaman_pb.dmi
  icons/mob/human_races/r_plasmaman_sb.dmi
  icons/mob/human_races/r_skeleton.dmi
Labels: Bug / Fix, Unable To Reproduce

#19920 Fixes Gender Hair Randomization in Character Preferences
  code/modules/client/preferences.dm
Labels: Bug / Fix

#19893 Mmis and Posibrains Can No Longer Drag Themselves out of Mechs
  code/game/mecha/mecha.dm
Labels: Bug / Fix

#19915 More cult fixes
  code/datums/gamemode/factions/legacy_cult/cult_items.dm
  code/datums/gamemode/factions/legacy_cult/ritual.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
  code/datums/gamemode/factions/legacy_cult/talisman.dm
  code/datums/gamemode/objectives/target/sacrifice.dm
Labels: Bug / Fix, Unatomic

#19896 Fixes Phazon Mutation Allowing Mobs with No Fat Sprites to Be Fat
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix

#19923 Fixes Mr. V.A.L.I.D. Portable Threat Detector
  code/game/machinery/metaldetector.dm
Labels: Bug / Fix

#19682 Do silicons dream of clockwork?
  code/__HELPERS/clockwork.dm
  code/game/objects/items/weapons/table_rack_parts.dm
  code/game/objects/objs.dm
  code/game/objects/structures/fullwindow.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_mineral.dm
  code/game/turfs/turf.dm
  code/modules/mob/mob.dm
  icons/effects/effects.dmi
  vgstation13.dme
Labels: Bug / Fix, Content

#19874 nullrod flavor text
  code/game/objects/items/weapons/null_rod.dm
Labels: Bug / Fix, Content

#19938 Fixed genetics console not working
  code/game/dna/dna2.dm
Labels: Hotfix

#19929 Fixes a runtime with attack delayers
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
Labels: Runtime Log

#19955 Right and wrong equalisation of opportunity
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/modules/admin/admin.dm
Labels: Bug / Fix

#19944 Various cult 2.0 bugfixes
  code/datums/gamemode/factions/legacy_cult/cult.dm
  code/datums/gamemode/factions/legacy_cult/ritual.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
  code/datums/gamemode/factions/legacy_cult/talisman.dm
  code/modules/library/lib_items.dm
  code/modules/spells/general/rune_write.dm
Labels: Bug / Fix

#19676 Ice mining
  __DEFINES/setup.dm
  code/game/gamemodes/endgame/xmas/snow.dm
  code/modules/mining/materials.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/minerals.dm
  code/modules/reagents/machinery/mortar.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  icons/obj/items.dmi
  icons/turf/mine_overlays.dmi
Labels: Content

#19852 Security and Captain can be traitors (again)
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Role Datums Issue

#19891 can now cut corncobs into pipes with anything sharp
  code/modules/hydroponics/grown_inedible.dm
Labels: Tweak

#19894 Fixes Doppelgangers Stunlocking Their Wizard
  code/modules/mob/living/simple_animal/hostile/human/wizard.dm
  code/modules/spells/targeted/projectile/magic_missile.dm
Labels: Bug / Fix

#19901 Supermatter grammar fixes
  code/modules/supermatter/supermatter.dm
Labels: Grammar / Formatting

#19905 MedHUD Buffs
  __DEFINES/setup.dm
  code/game/data_huds.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/paramedic.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/hud.dmi
Labels: Content, Tweak, Unatomic

#19916 Medbelt Buffs
  code/game/objects/items/weapons/storage/belt.dm
Labels: Tweak

#19918 Fixes Eternal Fire Safety
  code/modules/mob/living/living.dm
Labels: Bug / Fix

#19922 AI holograms no longer get sharded.
  code/modules/supermatter/supermatter.dm
Labels: Bug / Fix

#19942 Glare no longer costs 1u blood
  code/modules/spells/aoe_turf/glare.dm
Labels: Bug / Fix

#19943 Fixes invisible cult floors
  code/game/turfs/simulated/floor.dm
Labels: Bug / Fix

#19947 Syndicate uplink fix
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/role.dm
Labels: Bug / Fix, Unatomic

#19937 Fixes Akimbo dropping
  code/modules/mob/living/simple_animal/hologram/hologram.dm
  code/modules/projectiles/guns/akimbo.dm
  code/modules/projectiles/targeting.dm
Labels: Bug / Fix

#19982 Holy oversight, batman!
  code/modules/power/apc.dm
Labels: Hotfix, ⚠️ OH GOD IT'S LOOSE ⚠️

#19979 Fixes Bugs Related to Operator Precedence
  code/game/gamemodes/newobjective.dm
  code/modules/Economy/Accounts.dm
  code/modules/Economy/EFTPOS.dm
Labels: Bug / Fix

#19977 Fixes Lighters Getting Name Reset When Lit
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Bug / Fix

#19962 Fixes Getting Stunned off Vehicles Breaking Your Offset
  code/game/objects/structures/vehicles/cargo_tractor.dm
  code/game/objects/structures/vehicles/gigadrill.dm
  code/game/objects/structures/vehicles/gokart.dm
  code/game/objects/structures/vehicles/lightcycle.dm
  code/game/objects/structures/vehicles/secway.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/game/objects/structures/vehicles/wheelchair.dm
  code/game/objects/structures/vehicles/wizmobile.dm
Labels: Bug / Fix

#19941 Fixes Inability to Splash Monkey Cubes
  code/modules/reagents/reagent_containers.dm
Labels: Bug / Fix

#19976 Fixes Hulk Inverting Throw Damage
  code/modules/mob/living/living.dm
Labels: Bug / Fix

#19927 Fixes pAIs still displaying a !!! after their ghost becomes another ghost role
  code/datums/recruiter.dm
  code/modules/mob/living/silicon/pai/recruit.dm
Labels: Bug / Fix

#19888 full GPLv3 license
  COPYRIGHT
  LICENSE
Labels: help wanted

#19983 Fixing false walls not smoothing with their neighbors
  code/game/objects/structures/false_walls.dm
Labels: Bug / Fix

#19374 Dense atmos machines actually get cultified
  code/ATMOSPHERICS/atmospherics.dm
Labels: Bug / Fix

#19995 Fixes Book of Dimensional Push
  code/game/gamemodes/wizard/spellbook.dm
Labels: Bug / Fix, Exploitable

#19967 Removes an in world check for malf modules.
  code/__HELPERS/global_lists.dm
  code/game/gamemodes/malfunction/Malf_Modules.dm
  code/game/mecha/equipment/tools/tools.dm
  code/modules/RCD/engie.dm
Labels: Performance

#19968 Removes a 'in world' loop for effects.
  code/__HELPERS/global_lists.dm
  code/datums/gamemode/factions/legacy_cult/narsie.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
  code/modules/mob/living/silicon/ai/freelook/update_triggers.dm
Labels: Performance

#19970 Remove an in world check in observer code
  code/__HELPERS/global_lists.dm
  code/game/machinery/bots/bots.dm
  code/modules/mob/mob.dm
Labels: Performance

#19993 Fixes Magic Missile Being Listed Twice in the Spellbook
  code/modules/spells/targeted/projectile/magic_missile.dm
Labels: Bug / Fix

#19980 Fixes Cluwnes Being Untouchable by Items
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
Labels: Bug / Fix

#19994 Fixes Emergency Nitrogen Tanks Not Displaying Correctly in Tank Transfer Valves
  icons/obj/assemblies.dmi
Labels: Bug / Fix, Sprites

#20019 Fixes a bad oversight
  code/datums/gamemode/factions/legacy_cult/talisman.dm
Labels: Oversight

#19933 Digital Camouflage no longer has a "Please collect valids" examine text when a changeling uses it.
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/monkey/examine.dm
Labels: Balance, Tweak

#19988 Fixes Ghosts Being Able to Toggle Capacitors
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
Labels: Bug / Fix, Sanity / Ghosthands

#20044 Fixes Cloning Pods Having Their Sprite Reset When Their Panel Is Opened
  code/game/machinery/machinery.dm
Labels: Bug / Fix

#19953 Radials 0.21.3_c
  code/_onclick/hud/radial.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/game/machinery/kitchen/microwave.dm
  code/modules/client/client defines.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
  code/modules/tooltip/tooltip.html
  icons/mob/radial.dmi
  icons/obj/cult_radial.dmi
  icons/obj/cult_radial2.dmi
Labels: Tweak

#20039 Fixes supply talisman eating charges 4nr
  code/datums/gamemode/factions/legacy_cult/talisman.dm
Labels: 100% tested

#19845 Exporting some Dynamic Mode stats
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_debug.dm
  code/datums/gamemode/dynamic/dynamic_stats.dm
  code/datums/statistics/stat_helpers.dm
  code/datums/statistics/statcollection.dm
  vgstation13.dme
Labels: Role Datums

#20062 Fixes atmos sprites
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/game/machinery/atmoalter/canister.dm
  maps/randomvaults/objects.dm
Labels: Bug / Fix

#20071 Fixes Light Deconstruction
  code/modules/power/lighting.dm
Labels: Bug / Fix

#20064 Removes snowfkale plasmaman checks, removes variables associated with goliathplating and clothing extinguishing.
  __DEFINES/clothing.dm
  __DEFINES/setup.dm
  code/modules/bomberman/bomberman.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Labels: Tweak

#20055 Emagging a mommi lets it microwave food
  code/modules/mob/living/silicon/mommi/mommi.dm
Labels: Tweak

#19755 Basic Camera Cycling
  __DEFINES/cameranet.dm
  code/__HELPERS/lists.dm
  code/controllers/subsystem/init/more_init_stuff.dm
  code/game/area/areas.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/camera.dm
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
  code/modules/mob/living/silicon/ai/freelook/update_triggers.dm
  code/modules/mob/living/silicon/mommi/mommi_subtypes/NT.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  icons/obj/camera_buttons.dmi
Labels: Content, ✋ Do Not Merge ✋

#20013 Adds the Inquisitor's Clothing
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/feet.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Content

#20014 Destructive analyzer no longer requires science access (also fixes href exploits)
  code/modules/research/destructive_analyzer.dm
  code/modules/research/rdconsole.dm
Labels: Balance

#20095 Fixes Dead Human Mimics Leaving Humans Behind
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#20081 Restricting Summon Guns/Magic/Blades to roundstart wizards only
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/game/gamemodes/wizard/artifacts.dm
  code/game/gamemodes/wizard/spellbook.dm
  icons/logos.dmi
Labels: Role Datums Issue, Tweak

#20096 Fixes Mechs Being Unable to Pass Through Portals
  code/game/objects/effects/portals.dm
Labels: Bug / Fix

#20083 Adds the Super Shotgun
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/obj/gun.dmi
Labels: Content

#20093 Fixes Observer AntagHUD
  code/modules/mob/dead/observer/observer.dm
Labels: Bug / Fix, Role Datums

#20048 Fix martian eyes and hats
  code/modules/mob/living/carbon/complex/life.dm
  code/modules/mob/living/carbon/complex/martian/inventory.dm
Labels: Bug / Fix

#20077 Reworks simple animal door breaking
  __DEFINES/simple_animal_defines.dm
  code/game/machinery/doors/airlock.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: File Cleanup

#20076 Swap display of TEG circulators
  code/modules/power/generator.dm
Labels: UI, ❤️ Quality of Life ❤️

#20078 Fixes num2words Runtime
  code/__HELPERS/text.dm
Labels: Bug / Fix

#19910 Automates Easter
  code/game/gamemodes/events/holidays/Holidays.dm
Labels: ❤️ Quality of Life ❤️

#19924 Fixes DNA Consoles Labeling DNA of Disfigured People "Unknown"
  code/defines/obj.dm
  code/game/dna/dna_modifier.dm
Labels: Balance, Bug / Fix

#20104 Fixes Observer Runtime When Jumping to Bomberman Arena
  code/modules/mob/dead/observer/observer.dm
Labels: Bug / Fix, Runtime Log

#20050 More specific logging for exosuit attacks
  code/game/mecha/mecha.dm
Labels: Grammar / Formatting

#20114 Fixes rejuvenate() Not Un-Husking Mobs
  code/modules/mob/living/living.dm
Labels: Bug / Fix, Logging / Administration

#20121 removes the do_after from airlock attack_animal
  code/game/machinery/doors/airlock.dm
Labels: Balance, Hotfix

#20124 Fixes the light replacer emag act
  code/game/objects/items/devices/lightreplacer.dm
Labels: Bug / Fix, 🚓Fun Police🚓

#20120 update travis byond to 512.1453
  .travis.yml
Labels: System, T-Thanks BYOND

#20105 Fixes Constructed Lantern Hook Direction
  code/modules/mining/mine_structures.dm
Labels: Bug / Fix

#20127 Fixes Cult Gateways Being Layered Over Objects
  code/datums/gamemode/factions/legacy_cult/cult_structures.dm
Labels: Bug / Fix

#20130 Fixes Holidays.dm Runtime Error
  code/game/gamemodes/events/holidays/Holidays.dm
Labels: Bug / Fix

#20101 Allow cancelling out of the custom virus building menu
  code/modules/virus2/disease2.dm
Labels: ❤️ Quality of Life ❤️

#20135 Destroying kudzu now unlocks anyone caught up in it
  code/modules/hydroponics/spreading/spreading.dm
Labels: Bug / Fix

#20134 Fixes Bluespace Tomatoes Teleporting Buckled Players
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Bug / Fix

#20128 Fixes simple_animal Regeneration
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#20116 Fix hyperzine interaction with Phazon tiles
  code/modules/mob/living/carbon/carbon.dm
Labels: Bug / Fix

#20144 Fixes VV Disconnecting Admins
  code/datums/datumvars.dm
Labels: Bug / Fix, Logging / Administration, Needs Review, System

#20136 Fixes Wand of Destruction Being Able to Destroy Shuttle Floors
  code/modules/projectiles/guns/energy/special.dm
Labels: Bug / Fix

#20145 Fixes Subspace Tunneler Object Ejection
  code/modules/projectiles/guns/projectile/constructable/subspacetunneler.dm
Labels: Bug / Fix

#20143 Fixes Projectiles Not Being Able to Go Through Portals
  code/game/objects/effects/portals.dm
Labels: Bug / Fix

#20140 Fixes Being Unable to Spacewalk Along Pitch-Black Tiles
  code/game/atoms_movable.dm
Labels: Bug / Fix

#20073 Humanoid Mobs Spawned by Traitor Lazarus Belt No Longer Drop Weapons
  code/game/objects/items/weapons/storage/belt.dm
Labels: Balance, Tweak

#20036 Fixes/implements borg module lock
  code/game/machinery/computer/robot.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Content

#20100 Adds wizard potion bags: Git strikes back
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/bags.dm
  icons/mob/head.dmi
  icons/obj/pbag.dmi
Labels: Content

#19940 Fixes Getting Trapped Behind Transit Tubes
  code/game/objects/structures/transit_tubes.dm
Labels: Bug / Fix, Needs Review

#19886 Spessmen can now bash their (riot) shield with a telescopic baton.
  code/game/objects/items/weapons/shields.dm
Labels: Needs Changelog, Tweak

#20085 Adds the Automatic Ore Loader to the protolathe
  code/modules/research/designs/mining.dm
Labels: Content

#19990 Removes Insulated Pipes from the RPD
  code/modules/RCD/RPD.dm
Labels: Feature Loss

#20154 Faint is now a temporary knockdown
  code/modules/mob/living/emote.dm
Labels: Bug / Fix

#20160 Chaplains can't be vampires anymore
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix

#19926 Probably Fixes How pickweight() Works with Decimal Numbers
  code/__HELPERS/lists.dm
Labels: Bug / Fix

#19823 In Nitroglycerin recipe, replace sacid and pacid with formic and phenol
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Tweak, Update WIKI

#20131 Fixes Bombermen Not Being Able to Breathe in Space
  code/modules/bomberman/bomberman.dm
Labels: Bug / Fix

#20197 Revert "Fixes atmos sprites (#20062)"
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/game/machinery/atmoalter/canister.dm
  maps/randomvaults/objects.dm
Labels: T-Thanks BYOND

#20192 [Cult 3.0] Lots of construct-related stuff
  __DEFINES/setup.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/radial.dm
  code/_onclick/ventcrawl.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/legacy_cult/soulstone.dm
  code/game/atoms_movable.dm
  code/game/data_huds.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/vending.dm
  code/game/objects/explosion.dm
  code/game/turfs/simulated/walls.dm
  code/modules/media/jukebox.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/shade_powers.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  code/modules/spells/aoe_turf/conjure/construct.dm
  code/modules/spells/aoe_turf/conjure/forcewall.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
  code/modules/tooltip/tooltip.html
  icons/effects/96x96.dmi
  icons/effects/effects.dmi
  icons/mob/hud.dmi
  icons/mob/mob.dmi
  icons/mob/screen_spells.dmi
  icons/mob/species/plasmaman/head.dmi
  icons/mob/species/plasmaman/suit.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit_fat.dmi
  icons/obj/cult.dmi
  icons/obj/cult_radial.dmi
  icons/obj/cult_radial2.dmi
  icons/obj/cult_radial3.dmi
  icons/obj/doors/doorcult.dmi
  icons/obj/projectiles_experimental.dmi
  sound/effects/juggerdash.ogg
Labels: Unatomic

#19890 Can now carve out books with anything sharp
  code/modules/library/lib_items.dm
Labels: Tweak

#20088 Updated Summon Swords and Summon Magic
  code/game/gamemodes/wizard/rightandwrong.dm
Labels: Balance

#20205 Fixes Ghosts Getting Nullspaced By The Teleporter
  code/game/machinery/teleporter.dm
Labels: Bug / Fix

#20047 Fixes fart noises
  __DEFINES/surgery_defines.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/surgery/butt.dm
  vgstation13.dme
Labels: Bug / Fix

#20167 A rather bandaid fix for spiders spamming opening and closing doors
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix

#20188 re-adds metabuddy overlay icon
  code/modules/reagents/Chemistry-Reagents.dm
  icons/mob/hud.dmi
Labels: Bug / Fix, Conflicts

#20209 Switches to utf8 sanitizing
  code/__HELPERS/text.dm
  code/game/communications.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/camera/camera_assembly.dm
  code/game/machinery/computer/cargo.dm
  code/game/machinery/newscaster.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_control_console.dm
  code/modules/Economy/debit_card.dm
  code/modules/admin/topic.dm
  code/modules/assembly/assembly.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/paper.dm
  code/modules/reagents/machinery/chem_master.dm
Labels: Bug / Fix, Sanity / Ghosthands

#20216 Removed maps/fixes
  maps/fixes/r4401-to-vg.txt
  maps/fixes/tg-to-vg.txt
Labels: File Cleanup

#20217 Removed ancientstation
  maps/ancientstation.dm
  maps/ancientstation.dmm
  maps/ancientstation/areas.dm
  maps/ancientstation/turfs.dm
Labels: File Cleanup

#20218 Removed maps/randomvaults/backup
  maps/randomvaults/backup/ice_comet.dmm
  maps/randomvaults/backup/listening.dmm
  maps/randomvaults/backup/zoo_truck.dmm
Labels: File Cleanup

#20220 Removed hrrrm.dmm
  maps/hrrrm.dmm
Labels: File Cleanup

#20221 Removed ministation
  maps/ministation.dm
  maps/ministation.dmm
  maps/ministation/job/jobs.dm
  maps/ministation/job/removed.dm
  maps/ministation/misc.dm
  maps/ministation/readme.dm
  maps/ministation/telecomms.dm
  maps/ministation/uplink_item.dm
Labels: File Cleanup

#20222 Removed oldstation.dmm
  maps/oldstation.dmm
Labels: File Cleanup

#20223 Removed heart station
  maps/heartstation.0.1.0.dmm
Labels: File Cleanup

#20224 Remove exodus.dmm
  maps/exodus.dmm
Labels: File Cleanup

#20225 Removed unused AME files
  code/modules/power/antimatter/computer.dm
  code/modules/power/antimatter/engine.dm
  code/modules/power/antimatter/fuel.dm
Labels: File Cleanup

#20226 code/game/gamemodes cleanup
  code/game/gamemodes/antag_spawner.dm
  code/game/gamemodes/autotraitor/autotraitor.dm
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/blob/blob_finish.dm
  code/game/gamemodes/blob/blob_report.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/modularchangling.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/cult/cult_items.dm
  code/game/gamemodes/cult/cult_structures.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/cult/narsie.dm
  code/game/gamemodes/cult/ritual.dm
  code/game/gamemodes/cult/rune_controller.dm
  code/game/gamemodes/cult/runes.dm
  code/game/gamemodes/epidemic/epidemic.dm
  code/game/gamemodes/events/PortalStorm.dm
  code/game/gamemodes/events/VirusEpidemic.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/factions.dm
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/heist/objectives.dm
  code/game/gamemodes/malfunction/malfunction.dm
  code/game/gamemodes/meme/meme.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/mixed/mixed.dm
  code/game/gamemodes/mutiny/directives/ipc_virus_directive.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/revolution/anti_revolution.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/revolution/revsquad.dm
  code/game/gamemodes/revolution/rp-revolution.dm
  code/game/gamemodes/revolution/rp_revolution.dm
  code/game/gamemodes/sandbox/sandbox.dm
  code/game/gamemodes/traitor/doubleagent.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/raginmages.dm
  code/game/gamemodes/wizard/veilrender.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: File Cleanup

#20227 Removed unused genetics oldcode
  code/modules/genetics2/computer.dm
  code/modules/genetics2/genetree.dm
  code/modules/genetics2/sectors.dm
Labels: File Cleanup

#20228 Xenoarcheology cleanup
  code/modules/research/xenoarchaeology/artifact/artifact_unknown_old.dm
  code/modules/research/xenoarchaeology/artifact/effect_old.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser_old.dm
  code/modules/research/xenoarchaeology/machinery/artifact_db_old.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
Labels: File Cleanup

#20229 Removed coins.dm and ores.dm
  code/modules/mining/coins.dm
  code/modules/mining/ores.dm
Labels: File Cleanup

#20182 Layer adapters now only adapt the layer they are supposed to
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/burstpipe.dm
  code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/oxygen_generator.dm
  code/ATMOSPHERICS/components/unary/portables_connector.dm
  code/ATMOSPHERICS/components/unary/unary_base.dm
  code/ATMOSPHERICS/components/unary/vent.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/pipes.dm
  code/game/machinery/Freezer.dm
  code/game/machinery/cryo.dm
Labels: Bug / Fix

#20174 Fix runtimes with beams trying to draw while being fed null locs; runtime with projectile resetting
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Bug / Fix, Runtime Log

#20235 top quality changelogs
  html/changelogs/SonixApache.yml
  html/changelogs/cptwad.yml
Labels: 100% tested

#20236 small manual changelog edit
  html/changelog.html
Labels: help wanted

#20172 Fix bats trying to check if they're biting their dads when they never had a father to begin with
  code/modules/mob/living/simple_animal/hostile/bat.dm
Labels: Bug / Fix, Runtime Log

#20181 Makes all machines wrenchable on top of tables
  code/game/objects/objs.dm
Labels: Tweak

#20176 Medical nanobots now treat internal bleeding
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance

#19913 Adds Piccolyn
  __DEFINES/reagents.dm
  code/__HELPERS/text.dm
  code/modules/mob/inventory.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Unable To Reproduce

#19946 Fixing Latejoining
  code/game/objects/items/devices/radio/intercom.dm
  code/modules/mob/new_player/new_player.dm
Labels: Secret repo conflict.

#20239 Fixes an href exploit with the holodeck
  code/game/machinery/computer/HolodeckControl.dm
Labels: Bug / Fix, Exploitable

#20233 Mist/bat form summons a bat again
  code/modules/spells/targeted/ethereal_jaunt.dm
Labels: Bug / Fix

#20175 SMGs now count as handguns
  code/modules/projectiles/guns/projectile/automatic.dm
Labels: Balance

#20231 ashtray.dm cleanup
  code/WorkInProgress/Chinsky/ashtray.dm
  code/game/objects/items/ashtray.dm
  vgstation13.dme
Labels: File Cleanup

#20232 Remove research_shuttle.dm
  code/modules/research/research_shuttle.dm
Labels: File Cleanup

#20164 Disease analyzer shows more details
  code/modules/virus2/analyser.dm
Labels: UI, ❤️ Quality of Life ❤️

#20262 Fixed capitalization in virology things
  code/modules/virus2/diseasesplicer.dm
  code/modules/virus2/items_devices.dm
Labels: Grammar / Formatting

#19966 Blob faction
  code/datums/gamemode/factions/faction.dm
  code/game/gamemodes/blob/blobs/core.dm
  icons/logos.dmi
  icons/mob/blob/blob_64x64.dmi
  icons/mob/blob/blob_AME_64x64.dmi
Labels: Content, Role Datums

#20163 Virologist can open virus crates
  code/datums/supplypacks.dm
  code/game/jobs/access.dm
  code/game/jobs/job/medical.dm
  code/game/objects/items/weapons/cards_ids.dm
Labels: Balance

#20244 Check antagonists panel infos for dynamic mode.
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/gamemode.dm
  code/modules/admin/check_antagonists.dm
Labels: Role Datums

#20194 Fixes Eat Power Not Allowing You to Eat Handcuffs
  __DEFINES/spell_defines.dm
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/game/dna/genes/goon_powers.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/spells/spell_code.dm
Labels: Bug / Fix

#20102 readds NO_PAIN functionality and updated manifested ghosts to use exi…
  code/modules/mob/living/carbon/human/life/handle_shock.dm
  code/modules/mob/living/carbon/species.dm
Labels: Bug / Fix

#20119 QoL options for development
  .gitignore
  .travis.yml
  __DEFINES/__compile_options.dm
  code/game/gamemodes/gameticker.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/error_handler/error_handler.dm
  code/modules/mob/login.dm
  code/modules/mob/new_player/login.dm
  code/modules/unit_tests/README.md
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/_unit_test.dm
  maps/_map_override.dm
  maps/bagelstation.dm
  maps/defficiency.dm
  maps/metaclub.dm
  maps/packedstation.dm
  maps/roidstation.dm
  maps/test_box.dm
  maps/test_tiny.dm
  maps/tgstation.dm
  tools/travis/build.py
  tools/travis/run_tests.py
  vgstation13.dme
Labels: System, Unatomic, ❤️ Quality of Life ❤️

#20264 Fixed evidence bag + IED interaction
  code/modules/detectivework/evidence.dm
Labels: Bug / Fix

#20166 Diseases now don't autocure over time.
  code/modules/virus2/disease2.dm
Labels: Balance
