Repository vgstation-coders/vgstation13, pull requests merged in 2018-02, with the labels that each got.

#17281 Extinguishercreep
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance

#17394 Fixes a goof in AI Click() code
  code/_onclick/click.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
Labels: Bug / Fix

#17218 Revert "Wizard Mode can now have groups of Wizards"
  code/game/gamemodes/wizard/wizard.dm
Labels: Balance, Discussion, Role Datums, ⛔ Requires Server Vote ⛔, ✋ Do Not Merge ✋

#17397 small hotfixes
  __DEFINES/planes+layers.dm
  code/_onclick/hud/parallax.dm
  code/game/area/areas.dm
  code/game/gamemodes/blob/overmind.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix, Hotfix

#17409 Fixes lightning spell doing zero damage
  code/modules/spells/general/lightning.dm
Labels: Bug / Fix

#17407 Fixes cells inside the crank charger not updating their icon
  code/game/machinery/cell_charger.dm
Labels: Bug / Fix

#17401 Fixes cell chargers not showing their charge status from 50% to 75%.
  icons/obj/power.dmi
Labels: Bug / Fix, Sprites

#17361 Raises photo album storage capacity to 50
  code/modules/paperwork/photography.dm
Labels: Tweak

#17420 Fixes runtime on trying to build a console with a soldered circuit board
  code/game/machinery/computer/buildandrepair.dm
Labels: Bug / Fix

#17408 Fixes #17349
  code/game/machinery/bots/farmbot.dm
Labels: Bug / Fix, Needs Changelog

#17351 Flamethrowers are more effective against blobs
  code/game/objects/effects/fire_blast.dm
Labels: Balance

#17402 Makes xenobio potion bottles tiny.
  code/modules/mob/living/carbon/slime/slime.dm
Labels: Tweak

#17440 Windoor fixes
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/windoor_assembly.dm
Labels: Bug / Fix, Tweak

#17414 Automatic shuttlecalls fix
  code/game/machinery/computer/communications.dm
Labels: Bug / Fix

#17355 Changes the look/colors of some sec hud icons.
  code/game/data_huds.dm
  code/game/jobs/access.dm
  icons/mob/hud.dmi
Labels: Sprites

#17406 Fixes decoy balloons examine
  code/modules/mob/living/carbon/human/examine.dm
Labels: Bug / Fix

#17364 Emagging vending machines now hacks and unlocks them
  code/game/machinery/vending.dm
Labels: Tweak

#17415 Fixes Vox Armalis breathing oxygen instead of nitrogen.
  code/modules/mob/living/simple_animal/vox.dm
Labels: Bug / Fix, Tweak

#17432 Cult 3.0 : Faction Code + Tracing Runes & Paying in Blood + Communication Rune
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/_macros.dm
  code/__HELPERS/globalaccess.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/spell_screen_objects.dm
  code/_onclick/observer.dm
  code/datums/gamemode/cult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_cultify_exceptions.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_hell_rising.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_narsie.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_tattoos.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_words.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/role.dm
  code/datums/religions.dm
  code/game/gamemodes/cult/narsie.dm
  code/game/gamemodes/cult/ritual.dm
  code/game/gamemodes/wizard/soulstone.dm
  code/game/machinery/bots/draculabot.dm
  code/game/magic/Uristrunes.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/weapons/null_rod.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/masks/stone.dm
  code/modules/library/lib_items.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/mob_movement.dm
  code/modules/organs/blood.dm
  code/modules/paperwork/paperbin.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/spells/general/rune_write.dm
  code/modules/spells/spell_code.dm
  data/mode.txt
  icons/effects/effects.dmi
  icons/effects/uristrunes.dmi
  icons/mob/screen_spells.dmi
  icons/obj/cult.dmi
  vgstation13.dme
Labels: Role Datums

#16991 xeno disarms now take into account the targets armor
  code/modules/mob/living/carbon/alien/humanoid/combat.dm
Labels: Balance, Controversial, ⛔ Requires Server Vote ⛔

#17448 fixes a problem where ice would recursively make more water, flooding the player and causing the server to crash
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Hotfix

#17443 Restores mouse speech
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Tweak

#17441 Makes soldering iron fillable with any open reagent containers
  code/game/objects/items/weapons/tools.dm
Labels: Bug / Fix

#17379 adds red & security sunglasses
  code/datums/supplypacks.dm
  code/game/machinery/vending.dm
  code/modules/clothing/glasses/glasses.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Content

#17433 Fishtanks, Episode 7: Despair vs. Hope
  code/__HELPERS/lists.dm
  code/datums/supplypacks.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/vending.dm
  code/modules/fish/fish_eggs.dm
  code/modules/fish/fish_items.dm
  code/modules/fish/fish_tank.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/fish_items.dmi
  icons/obj/seafood.dmi
Labels: Content

#17436 No tracking footprints while on a vehicle
  code/game/turfs/simulated.dm
Labels: Bug / Fix

#17457 Fix for admins not being able to jump to oathbreaking mimes
  code/game/jobs/job/civilian.dm
Labels: Bug / Fix

#17430 All vending machines start connected to the cargo account
  code/game/machinery/vending.dm
Labels: Bug / Fix

#17403 Snow-map Salvage Project PR#2
  __DEFINES/planes+layers.dm
  code/game/area/areas.dm
  code/game/area/shadows.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/human/human.dm
  vgstation13.dme
Labels: Content, Mapping (❄ Snowmap ❄)

#17113 Reverts hypno change and gives vampires 10 starting blood
  __DEFINES/setup.dm
  code/game/gamemodes/vampire/vampire.dm
  code/game/gamemodes/vampire/vampire_powers.dm
Labels: Balance, Gameplay / Gamemode

#17396 Revert "Make Wizard not low-pop gamemode"
  code/game/gamemodes/wizard/wizard.dm
Labels: Balance, Gameplay / Gamemode

#17308 fixes bug where plasmamen don't cool down due to accidental feature loss:
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
Labels: Hotfix, Needs Review

#17455 Sounds and feedback for cyborg restart board
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Sound, ❤️ Quality of Life ❤️

#17477 Prevents duplicate sand decals
  code/modules/mining/ores_coins.dm
Labels: Bug / Fix

#17354 Ports TGs silicon camera expansion
  __DEFINES/game.dm
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/wires/robot.dm
  code/game/machinery/newscaster.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob_defines.dm
  code/modules/paperwork/photography.dm
  icons/mob/screen1_robot.dmi
Labels: Content, Port, Unatomic

#17447 pAI positioning system refactor
  code/modules/mob/living/silicon/pai/death.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/telesci/gps.dm
Labels: Tweak, Unatomic

#17451 Projectile attack logs for player-controlled simple mobs
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Logging / Administration

#17399 Snow-map Salvage Project PR#1
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  icons/obj/closet.dmi
Labels: Content, Mapping (❄ Snowmap ❄)

#17344 Adds powercreep to Supply Borgs
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/telesci/gps.dm
  icons/obj/mining.dmi
  icons/obj/telescience.dmi
Labels: Balance, Content, Port

#17228 Adds the asthma disability, albuterol, and inhalers
  __DEFINES/global.dm
  __DEFINES/reagents.dm
  __DEFINES/setup.dm
  code/game/dna/genes/vg_disabilities.dm
  code/game/gamemodes/setupgame.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items/devices/inhaler.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/inhaler.dmi
  vgstation13.dme
Labels: Content, Secret repo conflict., Update WIKI

#17011 Add a built in welding mask toggle to the Vox Robotics Helmet
  code/datums/action.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
Labels: Balance, Content, ✋ Do Not Merge ✋

#17485 Fixes two unrelated runtimes
  code/game/area/areas.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Bug / Fix

#17181 Adds a variety of contact lenses
  code/datums/supplypacks.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/research/designs/misc.dm
  icons/obj/items.dmi
Labels: Balance, Content, Needs Fixing

#17310 adds white glubs to premium goods in autodrobe
  code/game/machinery/vending.dm
Labels: Content, Controversial

#17378 Refactors suit dispenser code
  code/__HELPERS/globalaccess.dm
  code/game/machinery/suit_dispenser.dm
  code/game/striketeams/emergency_response_team.dm
Labels: Tweak

#17472 Normalizes capitalization in religion/bible strings.
  code/datums/religions.dm
  code/game/jobs/job/civilian_chaplain.dm
Labels: Consistency Issue, Grammar / Formatting

#17376 Fixes ID cards in hands not being detected by vending machines
  code/game/machinery/vending.dm
  code/modules/mob/inventory.dm
Labels: Bug / Fix, Needs Review

#17491 Trader access on trader air alarms
  code/game/machinery/alarm.dm
Labels: Bug / Fix

#17498 Fixes bug where bare skin was not correctly observed
  code/game/objects/items/weapons/defib.dm
Labels: Muh Immulsions

#17499 Beakers are now layered above pills
  code/modules/reagents/reagent_containers/glass.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#17487 Role Panel & rune fix
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/unsorted.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/malf.dm
  code/datums/gamemode/factions/vampire_faction.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/objectives/absorb.dm
  code/datums/gamemode/objectives/acquire_blood.dm
  code/datums/gamemode/objectives/block.dm
  code/datums/gamemode/objectives/die.dm
  code/datums/gamemode/objectives/escape.dm
  code/datums/gamemode/objectives/hijack.dm
  code/datums/gamemode/objectives/minimize_casualties.dm
  code/datums/gamemode/objectives/nuclear.dm
  code/datums/gamemode/objectives/objective.dm
  code/datums/gamemode/objectives/silence.dm
  code/datums/gamemode/objectives/survive.dm
  code/datums/gamemode/objectives/survive_silicon.dm
  code/datums/gamemode/objectives/target/assassinate.dm
  code/datums/gamemode/objectives/target/debrain.dm
  code/datums/gamemode/objectives/target/harm.dm
  code/datums/gamemode/objectives/target/nanotrasen/brig.dm
  code/datums/gamemode/objectives/target/nanotrasen/demote.dm
  code/datums/gamemode/objectives/target/nanotrasen/execute.dm
  code/datums/gamemode/objectives/target/protection.dm
  code/datums/gamemode/objectives/target/sacrifice.dm
  code/datums/gamemode/objectives/target/syndicate/brig.dm
  code/datums/gamemode/objectives/target/syndicate/steal.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/traitor.dm
  code/datums/mind.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/check_antagonists.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/mapping.dm
  icons/mob/mob.dmi
Labels: Role Datums

#17508 icon hotfixes
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Hotfix

#17446 Spiderbot misc. fixes
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
Labels: Bug / Fix, Content

#17469 Snow-map Salvage Project PR#3
  __DEFINES/planes+layers.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ores_coins.dm
  icons/obj/mining.dmi
  icons/turf/floors.dmi
  icons/turf/mine_overlays.dmi
  icons/turf/rock_overlay.dmi
  icons/turf/spookycave.dmi
  icons/turf/walls.dmi
Labels: Content, Mapping (❄ Snowmap ❄)

#17516 Rewrites some shitty code with slightly less shitty code so tables don't delete each other when being placed.
  code/game/objects/items/weapons/table_rack_parts.dm
Labels: Bug / Fix

#17521 Fixes silicon view_photo()
  code/modules/paperwork/photography.dm
Labels: Bug / Fix

#17470 Hypozine TC cost reduction
  code/datums/uplink_item.dm
Labels: Balance

#17507 Replaces empty parent spawner with proper child spawners that contain populated lists.
  maps/randomvaults/dungeons/satellite_deployment.dmm
Labels: Bug / Fix, Mapping (Vault)

#17526 Fixes inflatables dispenser grammar
  code/modules/mob/living/silicon/robot/robot_items.dm
Labels: Grammar / Formatting

#17524 Fixes the alien drone evolution message
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
Labels: File Cleanup, Grammar / Formatting

#17519 Fixes circuit imprinter printing with less than needed materials
  code/modules/research/fabricators.dm
Labels: Bug / Fix

#17527 Moved logos and role HUD icons away from mob.dmi
  code/datums/gamemode/factions/cult.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/role/role.dm
  code/game/gamemodes/gameticker.dm
  icons/logos.dmi
  icons/mob/mob.dmi
  icons/role_HUD_icons.dmi
Labels: File Cleanup, Role Datums, Sprites

#17298 Vaporizer Redux
  code/game/machinery/atmoalter/vaporizer.dm
  code/game/machinery/vending.dm
  icons/obj/atmos.dmi
  nano/templates/vaporizer.tmpl
Labels: Needs Review, Tweak

#17534 Undoes accidental kitchen spike nerf
  code/game/objects/structures/kitchen_spike.dm
Labels: Bug / Fix

#17504 Role Panel addendum
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/mind.dm
  code/world.dm
Labels: Role Datums

#17515 Material synth whitelist
  code/game/objects/items/devices/mat_synth.dm
Labels: Bug / Fix

#17542 Updates maps to have new scanner/sleeper path as well as deletes some bad paths on maps that aren't in circulation.
  maps/RandomZLevels/assistantChamber.dmm
  maps/RandomZLevels/hive.dmm
  maps/randomvaults/lightspeedship.dmm
  maps/randomvaults/syndiecargo.dmm
Labels: Hotfix, Mapping (Away Mission), Mapping (Vault)

#17544 Fixed helmet mask being on the Vox suit
  code/modules/clothing/spacesuits/alien.dm
Labels: 100% tested, Bug / Fix

#17478 VV and AtomProcCall quality of life changes
  code/datums/datumvars.dm
  code/modules/admin/verbs/modifyvariables.dm
Labels: Content, ❤️ Quality of Life ❤️

#17488 Fixes MoMMIs having no action buttons at all besides the hardcoded jetpack upgrade
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/mommi/inventory.dm
Labels: Bug / Fix

#17484 Improving Trader Options
  code/game/machinery/vending.dm
  code/game/objects/items/trader.dm
  code/game/turfs/unsimulated/walls.dm
  maps/randomvaults/dungeons/mecha_graveyard.dmm
Labels: Balance, Content, Mapping (Vault), Tweak

#17475 People in the roundstart cube should no longer be able to damage each other.
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Bug / Fix, IT'S A FEAAAATUUUUREEEEEEEEE

#17474 Spams the admin logs with debug informations related to the job controller
  code/game/jobs/job_controller.dm
Labels: 100% tested, Needs Moar Testing

#17535 Fixes kitchen spike getting bricked
  code/game/objects/structures/kitchen_spike.dm
Labels: Bug / Fix

#17548 Fixes mob AI bug with targeting objects
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix

#17458 Adds death sounds for the SPS
  code/game/sound.dm
  code/modules/telesci/gps.dm
  sound/items/_comma.wav
  sound/items/allteamsrespondcode3.wav
  sound/items/attention.wav
  sound/items/die1.wav
  sound/items/die2.wav
  sound/items/die3.wav
  sound/items/die4.wav
  sound/items/eight.wav
  sound/items/five.wav
  sound/items/four.wav
  sound/items/investigateandreport.wav
  sound/items/lostbiosignalforunit.wav
  sound/items/nine.wav
  sound/items/off2.wav
  sound/items/on1.wav
  sound/items/on3.wav
  sound/items/one.wav
  sound/items/seven.wav
  sound/items/six.wav
  sound/items/three.wav
  sound/items/two.wav
  sound/items/unitdeserviced.wav
  sound/items/unitdownat.wav
  sound/items/zero.wav
Labels: Sound

#17501 ROLE DATUMS - rounds now actually end
  code/datums/gamemode/gamemode.dm
Labels: Oversight, Role Datums

#17495 Fixes holy water not blocking jaunt
  code/game/turfs/turf.dm
  code/modules/mob/mob_movement.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance, Bug / Fix, Legacy Bug

#17502 Snowmap Salvage Project PR#7 - changes 'cold breath' damage threshold
  code/game/gamemodes/changeling/horror.dm
  code/modules/mob/living/carbon/_defines.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/internal/lungs/lung.dm
Labels: Mapping (❄ Snowmap ❄), Tweak

#17421 Vampire, antag datums : take 2
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/vampire_gamemode.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/clothing/masks/stone.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/spells/aoe_turf/glare.dm
  code/modules/spells/general/rejuvenate.dm
  code/modules/spells/general/shapeshift.dm
  code/modules/spells/targeted/disease.dm
  code/modules/spells/targeted/hypnotise.dm
  code/modules/virus2/effect/effect.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Needs Fixing, Role Datums, WiP

#17551 Fixed a bug that caused only the first implant to show up on secHUDs
  code/game/data_huds.dm
Labels: 100% tested, Bug / Fix

#17560 hotfix for #17559
  code/game/machinery/Sleeper.dm
Labels: Hotfix

#17561 Swaps a empty holder spawner for a real engineering spawner on satellite_deployment.dmm, defeating a runtime.
  maps/randomvaults/dungeons/satellite_deployment.dmm
Labels: Bug / Fix, Mapping (Vault)

#17565 Fixes the supply cyborg automatic ore loader missing its icon
  icons/obj/mining.dmi
Labels: Sprites

#17546 Change how action buttons move
  code/_onclick/hud/action_button.dm
Labels: UI, ❤️ Quality of Life ❤️

#17558 Fix for cyborg deathgasp
  code/modules/mob/living/silicon/robot/emote.dm
Labels: Bug / Fix

#17575 Uncucks roundstart
  code/modules/mob/transform_procs.dm
  code/modules/research/xenoarchaeology/finds/finds_strangeball.dm
Labels: Feature Loss, Hotfix, IT'S A FEAAAATUUUUREEEEEEEEE

#17437 Adds two features to the custom vending machines.
  code/game/machinery/vending.dm
Labels: Conflicts, Content

#17576 Fixes cats magically killing mice through solid windows
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Bug / Fix

#17563 Adjusts the shuttle sounds to be 25% quieter
  code/controllers/shuttle_controller.dm
Labels: Sound, Tweak

#17450 Antique Matter Synth
  __DEFINES/math_physics.dm
  code/ATMOSPHERICS/components/binary_devices/MSGS.dm
  code/game/machinery/antiquemattersynth.dm
  code/game/machinery/vending.dm
  code/game/objects/items/stacks/sheets/bigstacks.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/modules/projectiles/guns/projectile/constructable/railgun.dm
  nano/templates/antiquems.tmpl
  vgstation13.dme
Labels: Content

#17578 Fixing a couple of runtimes
  code/game/machinery/bees_apiary.dm
  code/modules/clothing/accessories/holomap.dm
  code/modules/mob/living/simple_animal/bees/bees_items.dm
Labels: Bug / Fix

#17482 Alien acid now takes 3 seconds to apply on nuclear bombs with bonus sanity code.
  code/game/atoms.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
Labels: Balance, Bug / Fix

#17486 Snow-map Salvage Project PR#4 - clothing tweaks edition!
  code/game/objects/items.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/wintercoat.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Content, Mapping (❄ Snowmap ❄), Tweak

#17489 Allows Traders to Latejoin
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/whitelisted.dm
  code/modules/mob/new_player/new_player.dm
Labels: Content, Needs Fixing, Secret repo conflict.

#17596 Trader Latejoin Hotfix
  code/modules/mob/new_player/new_player.dm
Labels: Secret repo conflict.

#17594 human monkeyization now returns the monkey created.
  code/modules/mob/transform_procs.dm
Labels: Hotfix

#17595 Fixes silicon album showing duplicated info when examining a photo
  code/modules/paperwork/photography.dm
Labels: 100% tested, Bug / Fix

#17528 Makes admin teleports clear a mob's locked_to
  code/modules/admin/verbs/adminjump.dm
Labels: Bug / Fix

#17590 Sleeper Sanity HF
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
Labels: Sanity / Ghosthands

#17599 Component human mob fixes
  code/modules/components/ai/human/brain.dm
  code/modules/components/ai/human/human_target_finder.dm
Labels: Bug / Fix

#17537 Adds mech_flags to grenades
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/chronogrenade.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/inflatable.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
Labels: Balance, Feature Loss, IT'S A FEAAAATUUUUREEEEEEEEE, Tweak

#17610 Updates fancy containers' icons after mice eat out of them
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#17618 deitypo
  code/modules/projectiles/guns/projectile/osipr.dm
Labels: Bug / Fix, Consistency Issue

#17577 Faction/Role Hud Icons
  __DEFINES/planes+layers.dm
  code/__HELPERS/_macros.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/mind.dm
  code/modules/mob/living/login.dm
  icons/logos.dmi
  icons/role_HUD_icons.dmi
Labels: Role Datums

#17624 Fixes Blind and Mutate not appearing on the spellbook
  code/modules/spells/targeted/genetic.dm
Labels: 100% tested, Bug / Fix

#17625 Mecha Graveyard Hotfix
  maps/randomvaults/dungeons/mecha_graveyard.dmm
Labels: Bug / Fix, Mapping (Vault)

#17612 GOTTA GO FAST
  code/controllers/subsystem/objects.dm
  code/game/atoms.dm
  code/game/objects/objs.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/mining/mine_turfs.dm
  code/modules/power/apc.dm
  maps/randomvaults/spessmart.dm
Labels: 100% tested, Performance, T-Thanks BYOND

#17627 Readds update if initialized
  code/modules/power/apc.dm
Labels: Hotfix

#17631 Fuck byond
  __DEFINES/planes+layers.dm
  code/_onclick/hud/parallax.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
Labels: Hotfix, T-Thanks BYOND

#17603 Role Panel extras
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/mind.dm
Labels: Role Datums

#17582 Multitooling a cable shows network load
  code/modules/power/cable.dm
Labels: Tweak

#17188 SMES improvements
  code/game/machinery/constructable_frame.dm
  code/modules/power/battery.dm
  code/modules/power/battery_ion.dm
  code/modules/power/battery_port.dm
  code/modules/power/smes.dm
  nano/templates/smes.tmpl
Labels: Bug / Fix, Content, Needs Review, Tweak, UI

#17552 Fixed incorrect storage_slots on some lockboxes and boxes
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/lockbox.dm
Labels: Bug / Fix, Needs Review

#17635 Fixing proc spelling (injest v ingest)
  code/modules/power/antimatter/fuel.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Grammar / Formatting

#17637 Remove unused plugin system
  __DEFINES/global.dm
  code/__HELPERS/globalaccess.dm
  code/datums/plugin.dm
  code/world.dm
  vgstation13.dme
Labels: File Cleanup

#17518 Snowmap Salvage Project PR#9 - Saint Corgi
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  icons/mob/animal.dmi
Labels: Content, Mapping (❄ Snowmap ❄), Sprites

#17564 Fixes automated emotes from NPC mobs
  code/modules/mob/emote.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/human/nazi.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#17615 Revert cuck cube logging
  code/game/jobs/job_controller.dm
Labels: System

#17648 Uncucks the cube 2.0: AI camera boogaloo
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/login.dm
Labels: Bug / Fix

#17650 Fixes invisible ushankas
  icons/obj/clothing/hats.dmi
Labels: Bug / Fix, Sprites

#17500 Snowmap Salvage Project PR#6 - Deer
  code/__DEFINES/mob.dm
  code/datums/helper_datums/butchering.dm
  code/game/objects/items/mountable_frames/paintings.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/clothing/head/leather.dm
  code/modules/clothing/suits/leather.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/simple_animal/hostile/deer.dm
  code/modules/mob/living/simple_animal/hostile/wolf.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/mob/animal.dmi
  icons/obj/butchering_products.dmi
  icons/obj/paintings.dmi
  vgstation13.dme
Labels: Content, Mapping (❄ Snowmap ❄), Sprites

#16891 The not so big and less unatomic silicon update
  __DEFINES/game.dm
  __DEFINES/global.dm
  __DEFINES/setup.dm
  code/__HELPERS/icons.dm
  code/datums/ai_laws.dm
  code/datums/diseases/robotic_transformation.dm
  code/game/jobs/job_controller.dm
  code/game/machinery/mommi_spawner.dm
  code/game/objects/items/devices/radio/cyborg.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/RCD/RSF.dm
  code/modules/RCD/schematics/service.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/mommi/emote.dm
  code/modules/mob/living/silicon/mommi/examine.dm
  code/modules/mob/living/silicon/mommi/inventory.dm
  code/modules/mob/living/silicon/mommi/login.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/mommi/mommi_modules.dm
  code/modules/mob/living/silicon/mommi/mommi_movement.dm
  code/modules/mob/living/silicon/mommi/soviet_mommi.dm
  code/modules/mob/living/silicon/mommi/update_icons.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/transform_procs.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/research/xenoarchaeology/finds/finds_strangeball.dm
  icons/mob/mommi.dmi
  icons/mob/robots.dmi
  maps/randomvaults/spessmart.dm
  sound/misc/soviet.ogg
  vgstation13.dme
Labels: Balance, Bug / Fix, Content, File Cleanup, Gameplay / Gamemode, Unatomic, Update WIKI, ❤️ Quality of Life ❤️

#17523 Bones from the gibber
  code/game/machinery/kitchen/gibber.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  icons/mob/in-hand/left/sheets_n_ores.dmi
  icons/mob/in-hand/right/sheets_n_ores.dmi
  icons/obj/items.dmi
Labels: Bug / Fix

#17608 Dock lights
  code/game/objects/structures/docking_port.dm
  icons/obj/stationobjs.dmi
Labels: Content

#17655 Supply total display for light replacers
  code/game/objects/items/devices/lightreplacer.dm
Labels: ❤️ Quality of Life ❤️

#17641 Fixes borer arm-hook firing on shift-click
  code/modules/mob/living/simple_animal/borer.dm
Labels: Bug / Fix

#17619 Removes harmless weapons generating blood overlays or splatters
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Tweak

#17659 Fix welding mask issues
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
Labels: Bug / Fix

#17666 Fixed a bug that prevented new AIs from being constructed
  code/modules/mob/living/silicon/ai/ai.dm
Labels: 100% tested, I'M FUCKING DONE

#17662 Makes ventcrawlers able to cancel from exiting vents
  code/ATMOSPHERICS/atmospherics.dm
Labels: Tweak

#17638 Remove area_in_map proc
  code/__HELPERS/_macros.dm
  code/__HELPERS/unsorted.dm
  code/controllers/shuttle_controller.dm
Labels: System, T-Thanks BYOND

#17661 Soviet MoMMI examine fix
  code/modules/mob/living/silicon/mommi/login.dm
Labels: Oversight

#17663 Runtime hunting: cyborgs recharging edition
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Bug / Fix, Runtime Log

#17674 Creating a barricade on a door won't open said door
  code/game/objects/items/weapons/barricade_kit.dm
Labels: Bug / Fix

#17673 Makes barricades layered above doors
  code/game/objects/structures/barricade.dm
Labels: Bug / Fix
