Repository vgstation-coders/vgstation13, pull requests merged in 2018-07, with the labels that each got.

#18675 Makes HONK upgrade's clown stamp work
  __DEFINES/silicon.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/paperwork/paper.dm
Labels: Honk

#18694 its
  code/modules/mob/living/carbon/brain/MMI.dm
Labels: Grammar / Formatting

#18692 Fixes an error in parameters order that resulted in factions not being able to be set up properly
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/role/role.dm
Labels: Role Datums

#18666 Added separate attack verbs for lit and unlit states in matches, lighters, and cigarettes to fix issue #18572
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Grammar / Formatting

#18673 Quantity selection for making changelings and vampires
  code/modules/admin/verbs/one_click_antag.dm
Labels: Logging / Administration

#18689 Can now attack pods
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  code/_onclick/item_attack.dm
  code/game/machinery/bees_apiary.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/shade.dm
Labels: Bug / Fix

#18513 Flashbang tweaks.
  code/game/objects/items/weapons/grenades/flashbang.dm
Labels: Balance

#18707 Fixes backwards borg holomap sanity
  code/modules/mob/living/silicon/robot/robot_verbs.dm
Labels: 100% tested

#18697 Fixes pulled from the attempted rebase
  __DEFINES/role_datums_defines.dm
  __DEFINES/spell_defines.dm
  code/__DEFINES/role_defines.dm
  code/__DEFINES/spell_users.dm
  code/__DEFINES/spells_users.dm
  code/__HELPERS/_macros.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/malf.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/setupgame.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/power/apc.dm
  code/modules/spells/vampire_helpers.dm
  vgstation13.dme
Labels: Role Datums

#18713 Added /data/statfiles to gitignore
  .gitignore
Labels: System

#18710 Fixed some Vaults having parts not properly covered with /area/vault
  maps/randomvaults/AIsat.dmm
  maps/randomvaults/ejectedengine.dmm
  maps/randomvaults/hivebot_factory.dmm
  maps/randomvaults/house.dmm
  maps/randomvaults/meteorlogical_station.dmm
  maps/randomvaults/prison_ship.dmm
  maps/randomvaults/research_facility.dmm
  maps/randomvaults/spessmart.dmm
  maps/randomvaults/taxi_engineering.dmm
  maps/randomvaults/tommyboyasteroid.dmm
Labels: Mapping (Vault)

#18695 Fixes scoreboard not showing anything at all about antags
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/gamemode.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/scoreboard.dm
Labels: Bug / Fix

#18672 Beekeeping 3.6.2
  code/game/machinery/bees_apiary.dm
  code/modules/mob/living/simple_animal/bees/bees_datums.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
Labels: NOT THE BEES, Tweak

#18708 Fix an #elif breaking linter and possibly other things.
  code/world.dm
Labels: File Cleanup, System

#18728 Hostile mob stopping
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix

#18732 Fixed asteroid artifact rooms appearing on holominimaps
  code/modules/html_interface/map/station_map.dm
Labels: Bug / Fix

#18730 Holopeople no longer behind admin intervention
  code/game/machinery/computer/HolodeckControl.dm
Labels: Content, Logging / Administration

#18680 And his music was electric.
  __DEFINES/archaeo_defines.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
  code/modules/research/xenoarchaeology/finds/finds_guitar.dm
  vgstation13.dme
Labels: Content

#18745 Removed most 'in world' loops
  code/__HELPERS/global_lists.dm
  code/game/gamemodes/nuclear/pinpointer.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/prisoner.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/mecha/mecha_control_console.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/mop_bucket.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/pai/recruit.dm
  code/modules/power/apc.dm
Labels: Performance

#18746 Removed duplicated check from AI tracking
  code/game/machinery/camera/tracking.dm
Labels: Performance

#18733 Made plant_controller into a proper subsystem
  __DEFINES/hydro.dm
  __DEFINES/hydroponics.dm
  __DEFINES/subsystem.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/plant.dm
  code/game/gamemodes/cult/narsie.dm
  code/game/gamemodes/events/spacevines.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/hydroponics/seed_controller.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/hydroponics/seeds.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/world.dm
  nano/templates/botany_isolator.tmpl
  vgstation13.dme
Labels: Bug / Fix, System, Tweak

#18705 SPS announces now use the (proper) number wavs.
  code/modules/telesci/gps.dm
Labels: Bug / Fix

#18739 Enables lasertag for holopeople
  code/modules/clothing/suits/miscellaneous.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#18748 Fixes the OSIPR magazine icon not showing. Renames the variable used.
  code/modules/projectiles/guns/projectile/osipr.dm
Labels: Bug / Fix

#18762 Less annoying projectile logging
  code/modules/projectiles/projectile.dm
Labels: Logging / Administration

#18758 Can now carry gibtonite again
  code/modules/mining/ores_coins.dm
Labels: Bug / Fix

#18756 Maybe fixing a bug preventing some people from clicking on a gravpult's Launch button
  code/_onclick/hud/screen_objects.dm
Labels: Bug / Fix

#18754 Warning stripes now inherit their pixel_x and pixel_y mapping values
  code/game/objects/effects/decals/warning_stripes.dm
Labels: Bug / Fix, Mapping (General)

#18747 Gives admin ids trader access
  code/game/jobs/access.dm
Labels: Logging / Administration, Oversight

#18725 Makes autoinjectors closed containers
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance, Feature Loss

#18664 Switch the wonderful wardrobe to a predefined list of possible items.
  code/game/objects/items/trader.dm
Labels: Tweak

#17770 Messing with component mobs further
  __DEFINES/component_signals.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/modules/components/ai/controllers/mob_controller.dm
  code/modules/components/ai/controllers/movement.dm
  code/modules/components/ai/def_zone_handler.dm
  code/modules/components/ai/get_damtype.dm
  code/modules/components/ai/hostile/melee/melee.dm
  code/modules/components/ai/human/brain.dm
  code/modules/components/ai/human/human_attack.dm
  code/modules/components/ai/human/human_target_finder.dm
  code/modules/components/ai/human/retaliate.dm
  code/modules/components/ai/human/throw_attack.dm
  code/modules/components/ai/mobs/component_mob.dm
  code/modules/components/ai/mobs/giant_spider.dm
  code/modules/components/component.dm
  code/modules/components/component_container.dm
  code/modules/components/debugger.dm
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/combat.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  vgstation13.dme
Labels: File Cleanup, Unatomic

#18686 Summon Pastry spell
  code/game/gamemodes/wizard/spellbook.dm
  code/modules/spells/targeted/projectile/pie_throw.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Content

#18740 Stops "You can't pick things up!" spam for holopeople
  code/game/objects/items.dm
Labels: Bug / Fix

#18742 Buckshot can now hit lying mobs, and gets the proper point-blank damage bonus
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Bug / Fix

#18736 Adds a supply cyborg hookshot upgrade to the premium items in the dwaven vend.
  code/game/machinery/vending.dm
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Content, Update WIKI

#18769 Removes reagent scanner from Toxins PDA cartridge
  code/game/objects/items/devices/PDA/cart.dm
Labels: Feature Loss

#18777 Hasty fix to a round-ending runtime
  code/modules/mob/living/living.dm
Labels: Hotfix

#18785 A revialver runtime
  code/modules/projectiles/guns/projectile/constructable/revialver.dm
Labels: Bug / Fix, Runtime Log

#18783 Can point at equipped items, pointing at an item in your hands uses Show Held Item instead
  code/modules/mob/mob.dm
Labels: Content, ❤️ Quality of Life ❤️

#18774 More verbose assembly frame import errors
  code/modules/assembly/assembly_frame.dm
Labels: ❤️ Quality of Life ❤️

#18770 Updates reagent grinder item limit to use item sizes instead of flat amount
  code/modules/reagents/machinery/reagentgrinder.dm
Labels: Tweak

#18786 event datums unfucking, part 1
  code/datums/helper_datums/events.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/mecha.dm
  code/modules/events/event.dm
  code/modules/events/event_manager.dm
  vgstation13.dme
Labels: File Cleanup, System, Unatomic

#18802 Callbacks and weakrefs datums
  __DEFINES/callbacks.dm
  code/datums/callback.dm
  code/datums/datum.dm
  code/datums/weakref.dm
  vgstation13.dme
Labels: System

#18797 Defibrillators no longer have a 25% chance to cause spicy heart damage upon use.
  code/game/objects/items/weapons/defib.dm
Labels: Feature Loss, ❤️ Quality of Life ❤️

#18789 Pointing arrow spawns on top of the pointed item rather than the center of the tile
  code/modules/mob/mob.dm
Labels: ❤️ Quality of Life ❤️

#18805 Added a small delay to 'show held item' and pointing
  __DEFINES/mobs.dm
  code/game/objects/items.dm
  code/modules/mob/mob.dm
Labels: Tweak

#18339 simple animals now accept reagents
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hologram/hologram.dm
  code/modules/mob/living/simple_animal/hostile/monster.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/Chemistry-Reagents.dm
  icons/mob/animal.dmi
  icons/mob/cyber_horror.dmi
Labels: Balance, Content, Unatomic

#18815 Gets rid of nullspace monkeys
  code/modules/reagents/reagent_containers/food/mobcube.dm
Labels: File Cleanup

#18808 Moved posibrain recruitment to a recruiter datum
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: File Cleanup, ❤️ Quality of Life ❤️

#18816 Fixes magnificent magboots sprite toggle
  code/modules/clothing/shoes/magboots.dm
Labels: Bug / Fix

#18794 Lets cyborgs unload storage onto tables
  code/game/objects/items/weapons/storage/storage.dm
Labels: Tweak

#18782 Micro uzi, akimbo tweaks
  code/game/gamemodes/wizard/rightandwrong.dm
  code/modules/maps/spawners/spawners.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/akimbo.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Balance, Content

#18768 Mining mob tweaks
  __DEFINES/simple_animal_defines.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Labels: Content, Unatomic

#18791 Greys out internal organ items when they die
  code/modules/organs/organ_objects.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#18778 Altclicking paper folds it
  code/game/objects/items/devices/radio/radio.dm
  code/modules/clothing/clothing.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/photography.dm
Labels: Content, Sanity / Ghosthands, Unatomic, Update WIKI

#18817 [Cult 3.0] Tomes & Talismans, Runes III & IV, Books in-hands
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/library/lib_items.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/paperwork/paperbin.dm
  code/modules/spells/spell_code.dm
  icons/effects/effects.dmi
  icons/effects/uristrunes.dmi
  icons/mob/in-hand/left/books.dmi
  icons/mob/in-hand/right/books.dmi
  icons/mob/talk.dmi
  icons/obj/cult.dmi
  icons/tomebg.png
  sound/effects/talisman_attune.ogg
  sound/effects/talisman_imbue.ogg
Labels: Role Datums

#18821 Component datums
  __DEFINES/components.dm
  __DEFINES/global.dm
  code/__HELPERS/type2type.dm
  code/_onclick/item_attack.dm
  code/controllers/garbage.dm
  code/datums/component.dm
  code/datums/components/README.md
  code/datums/datum.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/combat.dm
  code/modules/mob/living/living.dm
  vgstation13.dme
Labels: System

#18822 Initialize() refactor
  __DEFINES/global.dm
  __DEFINES/setup.dm
  __DEFINES/subsystem.dm
  code/controllers/mc/subsystem.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/objects.dm
  code/game/atoms.dm
  code/game/machinery/station_map.dm
  code/game/objects/structures/gravpult.dm
  code/game/turfs/turf.dm
  code/modules/awaymissions/corpse.dm
  code/modules/html_interface/map/station_map.dm
  code/modules/power/apc.dm
  vgstation13.dme
Labels: System, help wanted

#18825 Atmospherics initialize() refactor
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/burstpipe.dm
  code/ATMOSPHERICS/components/binary_devices/MSGS.dm
  code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
  code/ATMOSPHERICS/components/binary_devices/circulator.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/binary_devices/valve.dm
  code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/t_valve.dm
  code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
  code/ATMOSPHERICS/components/unary/heat_exchanger.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/unary_base.dm
  code/ATMOSPHERICS/components/unary/vent.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/he_pipes.dm
  code/ATMOSPHERICS/pipes.dm
Labels: System

#18831 Fixing being able to use some harmful antag powers/spells while pacified.
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/gamemodes/vampire/vampire_powers.dm
  code/modules/spells/general/ring_of_fire.dm
Labels: Bug / Fix

#18827 Lube stops affecting you if you get locked to something mid-slip
  code/game/objects/effects/overlays.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: Bug / Fix, Unatomic

#18848 Talisman examine() fixes
  code/game/gamemodes/cult/talisman.dm
Labels: Bug / Fix

#18771 Prevent chemmaster dialog if buffer is empty
  code/modules/reagents/machinery/chem_master.dm
Labels: ❤️ Quality of Life ❤️

#18812 Makes knight armor able to get reinforced by goliath plates
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance, Tweak

#18738 Refactors emotes to use datums.
  code/__HELPERS/global_lists.dm
  code/datums/emotes.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/carbon/alien/humanoid/emote.dm
  code/modules/mob/living/carbon/alien/larva/emote.dm
  code/modules/mob/living/carbon/brain/emote.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/monkey/emote.dm
  code/modules/mob/living/carbon/slime/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/ai/emote.dm
  code/modules/mob/living/silicon/emote.dm
  code/modules/mob/living/silicon/mommi/death.dm
  code/modules/mob/living/silicon/mommi/emote.dm
  code/modules/mob/living/silicon/pai/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/say.dm
  code/modules/reagents/Chemistry-Reagents.dm
  vgstation13.dme
Labels: File Cleanup, Tweak, ❤️ Quality of Life ❤️

#18854 Remove a fetish line
  code/modules/mob/living/carbon/human/emote.dm
Labels: File Cleanup, why

#18864 Disarm stun now checks the targets armor, rather than the users
  code/modules/mob/living/carbon/human/combat.dm
Labels: Oversight

#18870 Makes silicons able to use emotes
  code/modules/mob/living/silicon/emote.dm
Labels: Oversight

#18868 More emotes fixes
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
Labels: 100% tested

#18850 Transmog mask fixes
  code/modules/clothing/masks/transmog.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix

#18866 Adds a helper macro to swap the contents of two vars
  __DEFINES/_macros.dm
Labels: System

#18883 Fixes "me" being broken half the time.
  code/modules/mob/emote.dm
Labels: Bug / Fix

#18880 Radstorms cause mutations and disabilities again
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/damage_procs.dm
Labels: Bug / Fix

#18889 Revert "Mining rigsuits have visual changes as they are upgraded (#18752)"
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  icons/mob/head.dmi
  icons/mob/in-hand/left/items_lefthand.dmi
  icons/mob/in-hand/right/items_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#18847 Rockernauts
  __DEFINES/global.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  icons/mob/animal.dmi
  icons/mob/attackanims.dmi
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
  icons/turf/mine_overlays.dmi
Labels: Content

#18888 Chemistry is no longer top shelf
  code/game/machinery/kitchen/smartfridge.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#18891 big if(TRUE)
  __DEFINES/mobs.dm
  code/modules/mining/mine_turfs.dm
Labels: why

#18885 More initialize() fixes
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/pipe/construction.dm
  code/ATMOSPHERICS/pipe/pipe_dispenser.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/bots/secbot.dm
  code/game/machinery/computer/HolodeckControl.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/machinery/computer/arcade/arcade_game.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/station_map.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/objects/effects/gibs.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/floor_types.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/html_interface/map/station_map.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/blood.dm
  code/modules/paperwork/photocopier.dm
  code/modules/power/smes.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/virus2/effect/effect.dm
Labels: System

#18890 Unpowered Air Alarm (De)construction Fix
  code/game/machinery/alarm.dm
Labels: Bug / Fix

#18901 Fixes silicon interaction when adjacent to airlocks (and possibly other machines)
  code/game/objects/objs.dm
Labels: Bug / Fix

#18902 Moved some defines where they belong
  __DEFINES/mobs.dm
  __DEFINES/turfs.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Labels: File Cleanup

#18906 Fixes "ghost not in body" defib message so it actually displays
  code/game/objects/items/weapons/defib.dm
Labels: Bug / Fix

#18781 Removes the ablative vests from the Experimental Energy Gear crate
  code/datums/supplypacks.dm
Labels: Balance, Tweak, Update WIKI

#18919 Deathgasp fix
  code/modules/mob/living/carbon/human/death.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: 100% tested

#18894 Makes rollerbeds not shit
  code/game/dna/dna_modifier.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/cryo.dm
Labels: ❤️ Quality of Life ❤️

#18900 Aghost Christmas
  code/WorkInProgress/Mini/ATM.dm
  code/WorkInProgress/kilakk/fax.dm
  code/game/machinery/ai_slipper.dm
  code/game/machinery/computer/cargo.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/turrets.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/Economy/Accounts.dm
  code/modules/Economy/utils.dm
  code/modules/power/battery.dm
  code/modules/research/fabricators.dm
  code/modules/telesci/telesci_computer.dm
Labels: Sanity / Ghosthands

#18918 Fixing the Custom Strike Teams' dispensers
  code/game/machinery/suit_dispenser.dm
Labels: Bug / Fix

#18896 Enables pointing shortcut for robots
  code/_onclick/cyborg.dm
Labels: Content

#18922 restores missing *halt emote on secborgs
  code/modules/mob/living/silicon/emote.dm
Labels: Feature Loss

#18923 more emotes *aflap
  __DEFINES/_macros.dm
  code/datums/emotes.dm
  code/modules/mob/living/emote.dm
Labels: Bug / Fix, System

#18909 Do_weld proc
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/hvac/spaceheater.dm
  code/WorkInProgress/Cael_Aislinn/Rust/fuel_assembly_port_construction.dm
  code/WorkInProgress/Cael_Aislinn/Rust/fuel_compressor_construction.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  code/datums/helper_datums/construction_datum.dm
  code/game/gamemodes/blob/theblob.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/secbot.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/ai_core.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/mineral.dm
  code/game/machinery/igniter.dm
  code/game/machinery/machinery.dm
  code/game/machinery/mass_driver.dm
  code/game/machinery/portable_turret.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/items/devices/fuse_bomb.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/shooting_range.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/switchtool.dm
  code/game/objects/items/weapons/table_rack_parts.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/mannequin.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/floor_glass.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/modules/assembly/bomb.dm
  code/modules/assembly/holder.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/effects.dm
  code/modules/optics/mirrors/frame.dm
  code/modules/power/apc.dm
  code/modules/projectiles/guns/projectile/bow.dm
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
  code/modules/projectiles/guns/projectile/constructable/swords.dm
  code/modules/recycling/conveyor2.dm
  code/modules/recycling/disposal-construction.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/telesci/rcs.dm
Labels: Content, File Cleanup

#18937 Yet another emote fix PR wew
  code/datums/emotes.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/emote.dm
Labels: 100% tested

#18920 Adds the survivor's hardsuit
  code/modules/clothing/spacesuits/rig.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Content

#18731 Doctor P. Holden, Surgeon Miniboss added to the Research Facility Vault
  __DEFINES/global.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/masks/transmog.dm
  code/modules/mob/living/simple_animal/hostile/human/surgeon.dm
  icons/mob/surgeon.dmi
  icons/obj/clothing/masks.dmi
  maps/randomvaults/research_facility.dmm
Labels: Content, Needs Fixing

#18396 adds liches and phylacteries
  __DEFINES/_macros.dm
  __DEFINES/global.dm
  code/datums/helper_datums/teleport.dm
  code/datums/shuttle.dm
  code/game/atoms.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/gamemodes/wizard/artifacts.dm
  code/game/objects/items/weapons/scrolls.dm
  code/game/turfs/turf.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/spells/targeted/equip/robesummon.dm
  icons/mob/feet.dmi
  icons/mob/head.dmi
  icons/mob/human_races/r_lich.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/wizard.dmi
Labels: Balance, Content

#18949 Phylacteries now check if they're just in the inventory of a person.
  code/game/atoms.dm
  code/game/gamemodes/wizard/artefact.dm
Labels: Bug / Fix

#18957 Dying with nightvision fix
  code/modules/mob/death.dm
Labels: Bug / Fix

#18964 Attaching Clarke's launchers now checks if there's space for them
  code/game/mecha/equipment/weapons/weapons.dm
Labels: Bug / Fix

#18961 More phylactery fixes.
  code/game/atoms_movable.dm
  code/game/gamemodes/wizard/artefact.dm
Labels: Bug / Fix

#18960 bugfix for doctor placeholder and slight buff
  code/modules/mob/living/simple_animal/hostile/human/surgeon.dm
Labels: Bug / Fix, Tweak, Unatomic

#18820 Unchumped wonder closet.
  code/game/objects/items/trader.dm
Labels: Tweak

#18963 Emote Restriction Tweaks
  code/WorkInProgress/Ported/policetape.dm
  code/datums/diseases/brainrot.dm
  code/datums/diseases/fake_gbs.dm
  code/datums/diseases/gbs.dm
  code/datums/diseases/rhumba_beat.dm
  code/datums/emotes.dm
  code/datums/religions.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/transformer.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/morgue.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/simple_animal/hostile/human/cult.dm
  code/modules/mob/living/simple_animal/hostile/human/mummy.dm
  code/modules/organs/internal/lungs/lung.dm
  code/modules/organs/organ_external.dm
  code/modules/power/singularity/singularity.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/surgery/genderchange.dm
  code/modules/surgery/surgery.dm
  code/modules/virus2/effect/effect.dm
Labels: Bug / Fix

#18969 remove_reagents() no longer ignores reagents in volumes less than the amount to be removed
  code/modules/reagents/Chemistry-Holder.dm
Labels: Bug / Fix

#18936 Large cardboard boxes are no longer giant
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Tweak

#18968 Cleaned up unused vars and comments
  code/modules/power/singularity/singularity.dm
Labels: File Cleanup

#18976 Cleans up the stripdrag situation
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mob/mob.dm
Labels: Hotfix

#18907 Turning into a ghoul or slimepeople sets cloneloss to 0.
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#18966 take_overall_damage() now returns the amount of damage taken
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
Labels: Legacy Bug

#18942 Mining suit sprite changes, again
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  icons/mob/head.dmi
  icons/mob/in-hand/left/mining_suit.dmi
  icons/mob/in-hand/right/mining_suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#18956 Masks are now logged.
  code/modules/clothing/masks/transmog.dm
Labels: Logging / Administration

#18911 Standardizes toxic and chemical waste
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content

#18845 [Clockwork] Adds replicant alloy and brass as adminbus materials
  __DEFINES/setup.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/mining/materials.dm
  icons/obj/items.dmi
Labels: Content

#18471 Adds mech spells.
  __DEFINES/spell_defines.dm
  code/_onclick/hud/spell_screen_objects.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/sec_tools.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/modules/spells/spell_code.dm
  icons/mecha/mecha_equipment.dmi
Labels: Content

#18722 explosions inside bodies / open containers no longer remove all chems
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Balance, Controversial

#18982 Fixes punished NT cyborgs
  __DEFINES/silicon.dm
Labels: Hotfix

#18983 Silicon unbolt hotkey hotfix
  code/_onclick/ai.dm
Labels: 100% tested

#18985 Moves clickdrag nudge to ctrl+clickdrag due to conflicting controls/ease to use accidentally
  code/ATMOSPHERICS/pipe/pipe_dispenser.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  code/_onclick/drag_drop.dm
  code/game/atoms.dm
  code/game/dna/dna_modifier.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/cryo.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/kitchen/monkeyrecycler.dm
  code/game/machinery/kitchen/processor.dm
  code/game/machinery/vending.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/deskbell.dm
  code/game/objects/items/weapons/game_kit.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/storage/coat.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/statue.dm
  code/game/objects/structures/mannequin.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/vehicles/carts/cargo.dm
  code/game/objects/structures/vehicles/carts/cart.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/game/turfs/turf.dm
  code/modules/games/cards/playing_cards.dm
  code/modules/medical/cloning.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/nano_paper_bin.dm
  code/modules/paperwork/paperbin.dm
  code/modules/paperwork/photocopier.dm
  code/modules/reagents/reagent_containers/food.dm
  code/modules/recycling/conveyor2.dm
  code/modules/recycling/disposal.dm
  code/modules/research/mechanic/flatpack.dm
  code/modules/research/xenoarchaeology/tools/anomaly_container.dm
  code/unused/mining/rail_unused.dm
Labels: Tweak

#18970 Advanced lungs adjust their settings when inserted like they're supposed to
  code/modules/organs/internal/lungs/filter.dm
  code/modules/surgery/organs_internal.dm
Labels: Bug / Fix

#18979 Revert "explosions inside bodies / open containers no longer remove all chems"
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Controversial, why

#18991 Revert "Revert "explosions inside bodies / open containers no longer remove all chems""
  code/modules/reagents/Chemistry-Recipes.dm
Labels: I'M FUCKING DONE

#18995 Fixes some mech-related projectile runtime
  code/modules/projectiles/projectile.dm
Labels: Bug / Fix

#18993 fixed pooling bug
  code/__HELPERS/datumpool.dm
Labels: System

#18994 Fixed qdel/pooling oversight
  code/controllers/garbage.dm
Labels: System

#18998 Revert "Fixed qdel/pooling oversight"
  code/controllers/garbage.dm
Labels: Hotfix

#19000 Fixes another goof in GetAvailableRobotModules()
  __DEFINES/silicon.dm
Labels: Hotfix

#19004 Removes a big unintended buff to rad_tick
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
Labels: Hotfix

#18910 Absolute pathing for brigdoors.dm
  code/game/machinery/doors/brigdoors.dm
Labels: File Cleanup

#18743 Buffs syndiepaper to a usable state
  code/game/objects/items/stacks/packagewrap.dm
  code/modules/mob/living/living.dm
Labels: Balance

#19005 Fixed pooling bug (Now with 100% less lag)
  code/__HELPERS/datumpool.dm
  code/controllers/garbage.dm
Labels: System

#18893 [Cult 3.0] Conversions & Stuns, Runes V & VI
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/fullscreen.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/mind.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/living/living.dm
  code/modules/organs/blood.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  icons/effects/64x64.dmi
  icons/mob/head.dmi
  icons/mob/screen1.dmi
  icons/mob/screen1_full.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/storage/storage.dmi
  sound/effects/convert_abort.ogg
  sound/effects/convert_failure.ogg
  sound/effects/convert_process.ogg
  sound/effects/convert_start.ogg
  sound/effects/convert_success.ogg
  sound/effects/stun_rune.ogg
  sound/effects/stun_talisman.ogg
Labels: Role Datums

#19002 Fixes silicons interfacing with doors they have no access to
  code/game/machinery/doors/airlock.dm
Labels: Bug / Fix

#18975 Nightvision Color Resets on Login
  code/modules/clothing/glasses/scanners.dm
  code/modules/mob/living/carbon/human/login.dm
  code/modules/mob/mob_helpers.dm
Labels: Bug / Fix

#19008 Fixes screaming
  code/WorkInProgress/Ported/policetape.dm
  code/datums/emotes.dm
  code/datums/religions.dm
  code/game/gamemodes/vampire/vampire.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/transformer.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/structures/morgue.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/simple_animal/hostile/human/mummy.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/power/singularity/singularity.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/surgery/genderchange.dm
  code/modules/surgery/surgery.dm
  code/modules/virus2/effect/effect.dm
Labels: I'M FUCKING DONE

#19019 Ghosts can ghostread doors with access requirements again
  code/game/machinery/doors/airlock.dm
Labels: Bug / Fix

#19017 Tweaks robot access, again.
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_subtypes/syndicate.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#19010 Xenos disarms actually take the target's armour into account
  code/modules/mob/living/carbon/alien/humanoid/combat.dm
Labels: Bug / Fix

#19014 Fixes shuttle being called midflight
  __DEFINES/setup.dm
  code/controllers/shuttle_controller.dm
  code/game/machinery/computer/communications.dm
  code/modules/mob/living/silicon/ai/death.dm
Labels: Bug / Fix, File Cleanup

#18905 Adds uranium to Discount Chocolate
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Content, Discussion, Tweak

#18921 Improved Custom Vendor Usability
  __DEFINES/setup.dm
  code/game/machinery/vending.dm
  code/game/machinery/vending_packs.dm
Labels: Tweak

#19034 Fixes screaming
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/emote.dm
Labels: Bug / Fix

#19028 Deconstructing partially-constructed machine frames gives back all item-type objects
  code/game/machinery/constructable_frame.dm
  code/modules/fish/fish_tank.dm
Labels: Bug / Fix

#19038 Deathgasp roundup
  code/modules/mob/living/carbon/alien/humanoid/death.dm
  code/modules/mob/living/carbon/alien/larva/death.dm
  code/modules/mob/living/carbon/monkey/death.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix, Tweak
