Repository vgstation-coders/vgstation13, pull requests merged in 2018-04, with the labels that each got.

#17985 Extends Some Clown-Compatibility to Borgs
  code/game/objects/effects/overlays.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Balance, Honk

#17970 Allow you to choose your pronouns at will.
  code/modules/mob/living/carbon/human/examine.dm
Labels: Content, Honk

#17962 bully roundstart on april fools day
  code/game/gamemodes/gameticker.dm
Labels: Honk

#17973 beekeeping 4.1.18
  icons/effects/plasma.dmi
  icons/effects/tile_effects.dmi
  icons/obj/atmospherics/miner.dmi
Labels: Honk, Sprites

#17968 Baby, I love the way you move
  code/game/objects/structures/displaycase.dm
  code/modules/clothing/shoes/magboots.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Honk

#17961 bully cargo for april fools day
  code/game/supplyshuttle.dm
Labels: Honk

#17966 fixes bug with Mime Equipment
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: 100% tested, Honk, Needs Changelog

#17964 Remove flashbangs from the game.
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Gameplay / Gamemode, Honk, ❤️ Quality of Life ❤️

#17957 adds not_human and gondolas
  __DEFINES/_macros.dm
  code/_onclick/other_mobs.dm
  code/datums/helper_datums/butchering.dm
  code/game/machinery/martian_printer.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/media/broadcast/transmitter.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/complex/combat.dm
  code/modules/mob/living/carbon/complex/complex_defines.dm
  code/modules/mob/living/carbon/complex/examine.dm
  code/modules/mob/living/carbon/complex/gondola/gondola.dm
  code/modules/mob/living/carbon/complex/gondola/gondola_receive_music.dm
  code/modules/mob/living/carbon/complex/inventory.dm
  code/modules/mob/living/carbon/complex/life.dm
  code/modules/mob/living/carbon/complex/martian/combat.dm
  code/modules/mob/living/carbon/complex/martian/inventory.dm
  code/modules/mob/living/carbon/complex/martian/life.dm
  code/modules/mob/living/carbon/complex/martian/martian.dm
  code/modules/mob/living/carbon/complex/martian/update_icons.dm
  code/modules/mob/living/carbon/complex/update_icons.dm
  code/modules/mob/living/carbon/not_human/gondola/gondola.dm
  code/modules/mob/living/carbon/not_human/gondola/gondola_receive_music.dm
  code/modules/mob/living/carbon/not_human/martian/combat.dm
  code/modules/mob/living/carbon/not_human/martian/inventory.dm
  code/modules/mob/living/carbon/not_human/martian/life.dm
  code/modules/mob/living/carbon/not_human/martian/martian.dm
  code/modules/mob/living/carbon/not_human/martian/update_icons.dm
  code/modules/mob/transform_procs.dm
  code/modules/virus2/helpers.dm
  icons/mob/gondola.dmi
  icons/obj/butchering_products.dmi
  vgstation13.dme
Labels: Honk, Needs Changelog, Port, Ready to Merge, ❤️ Quality of Life ❤️

#17825 Implementation of Peace Implants
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantcase.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/modules/mob/mob.dm
Labels: Content

#17993 Fixes soul stones deleting items held by non-humans
  code/game/gamemodes/wizard/soulstone.dm
Labels: Bug / Fix

#17928 NT Port can be closed to trade
  code/datums/shuttle.dm
  code/game/machinery/computer/communications.dm
  code/game/shuttles/trade.dm
  nano/templates/comm_console.tmpl
Labels: Gameplay / Gamemode, ❤️ Quality of Life ❤️

#17996 Removes fun
  code/_onclick/other_mobs.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/silicon/robot/robot.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
Labels: Feature Loss, Honk, Unatomic

#17960 track times cloned
  code/game/dna/dna_modifier.dm
  code/modules/medical/cloning.dm
  code/modules/medical/computer/cloning.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Content

#17997 fixes the funk from causing an infinite loop
  code/modules/clothing/shoes/magboots.dm
Labels: Bug / Fix

#17871 adds mushroom people
  __DEFINES/_macros.dm
  __DEFINES/setup.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/toys.dm
  code/modules/clothing/gloves/color.dm
  code/modules/hydroponics/seed_mobs.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/carbon/species_powers.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/research/xenoarchaeology/finds/finds_fossils.dm
  icons/mob/human_races/r_mushman.dmi
  vgstation13.dme
Labels: Content, Unatomic

#17998 Revert "beekeeping (#17973)"
  icons/effects/plasma.dmi
  icons/effects/tile_effects.dmi
  icons/obj/atmospherics/miner.dmi
Labels: Feature Loss

#18006 Fixes robotic remains having no icon
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Bug / Fix

#17978 Fixes NT MoMMIs not appearing in the Engineering Cameras Console
  code/game/machinery/computer/camera.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Bug / Fix

#18010 mushrom fixes
  __DEFINES/_macros.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species_powers.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  icons/mob/human_races/r_mushman.dmi
Labels: Bug / Fix, Hotfix

#18011 Bag of holding in a bag won't cause the space time continuum to say fuck
  code/game/objects/items/weapons/storage/bluespace.dm
Labels: Bug / Fix

#18013 grab drag fix
  code/modules/mob/mob_movement.dm
Labels: Bug / Fix

#18014 simple animal growing up stuff
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/nurse.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#18017 TK works again, thank you YRED for debugging
  code/modules/mob/inventory.dm
Labels: Hotfix

#18009 Spread Free Cultist damage between invokers.
  code/game/gamemodes/cult/runes.dm
Labels: Bug / Fix

#18018 Make law update sound play properly.
  code/game/machinery/computer/law.dm
Labels: Bug / Fix

#17972 Added a threshold to the dizziness effect.
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
Labels: Bug / Fix, Oversight, WiP

#17974 Adds tobacco to cigarettes and similar items.
  __DEFINES/reagents.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Content

#17995 Lets dextrous monkeys do more
  __DEFINES/_macros.dm
Labels: Content

#17885 Constructable Weapon Rechargers
  code/game/machinery/constructable_frame.dm
  code/game/machinery/recharger.dm
  code/modules/research/designs/boards/machine_misc.dm
Labels: Balance, Content

#18026 Specific humanoid message for the Staff of Change
  code/modules/projectiles/projectile/change.dm
Labels: Bug / Fix

#17950 BS anomalies don't affect INVULNERABLE objs
  code/modules/events/bluespaceanomaly.dm
Labels: Tweak

#17935 Role datums tator, double agents, and nuclear operatives
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/syndicate/traitor.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/traitor.dm
  code/datums/mind.dm
  vgstation13.dme
Labels: Role Datums

#18031 Fixes Lightning spell doing no damage.
  code/modules/projectiles/projectile.dm
Labels: Bug / Fix

#18043 Return the Slab
  code/datums/religions.dm
  code/game/jobs/job/civilian_chaplain.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#18012 shocking now passes the siemens coefficient of whatever you're hitting the thing with.
  __DEFINES/_macros.dm
  code/datums/wires/airlock.dm
  code/datums/wires/alarm.dm
  code/datums/wires/apc.dm
  code/datums/wires/jukebox.dm
  code/datums/wires/transmitter.dm
  code/datums/wires/vending.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/objs.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/grille.dm
  code/modules/power/cable.dm
  code/modules/research/rdmachines.dm
Labels: Balance, Bug / Fix, Tweak

#18030 Mousing over a spell gives you its description now.
  code/_onclick/hud/spell_screen_objects.dm
  code/game/dna/genes/powers.dm
  code/modules/mob/living/carbon/species_powers.dm
Labels: Content, ❤️ Quality of Life ❤️

#18025 Make Free and Summon Cultist rune damage flatter.
  code/game/gamemodes/cult/runes.dm
Labels: Balance, Gameplay / Gamemode

#18000 Revert "Blood runes now actually cost blood" (7957319..adca572)
  code/game/gamemodes/cult/ritual.dm
Labels: Balance, Feature Loss, Gameplay / Gamemode

#18039 knifeboot
  code/datums/action.dm
  code/datums/uplink_item.dm
  code/modules/clothing/shoes/miscellaneous.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Content

#17857 Removes action buttons. Ready for server side testing after successful test server testing.
  code/WorkInProgress/pomf/spacepods/actions.dm
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/hud.dm
  code/datums/action.dm
  code/game/striketeams/striketeam_datums.dm
  code/modules/clothing/accessories/holomap.dm
  code/modules/clothing/head/tactical.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/silicon/mommi/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/login.dm
Labels: 100% tested, ⚠️ OH GOD IT'S LOOSE ⚠️

#18067 Removes action buttons. Ready for server side testing after successfull test server testing: take 2
  code/WorkInProgress/pomf/spacepods/actions.dm
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/hud.dm
  code/datums/action.dm
  code/game/striketeams/striketeam_datums.dm
  code/modules/clothing/accessories/holomap.dm
  code/modules/clothing/head/tactical.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/silicon/mommi/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/new_player/login.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#18065 Fixes golem death runtime
  code/modules/mob/living/carbon/species.dm
Labels: Bug / Fix

#18062 Make bluespace tomatoes teleport every time on hitting a nonmob
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Tweak

#18035 True Knock
  code/modules/spells/aoe_turf/knock.dm
Labels: Balance, Gameplay / Gamemode

#18076 Re-adds amanatin to destroying angels, reduces potency.
  code/modules/hydroponics/seeds.dm
Labels: Bug / Fix, Update WIKI

#18086 Add alt-click toggle lid to hydro trays.
  code/modules/hydroponics/hydro_tray.dm
Labels: Update WIKI, ❤️ Quality of Life ❤️

#18004 dorf fort mommi spawner now doesn't spawn as wrench2move
  code/game/machinery/mommi_spawner.dm
Labels: Bug / Fix

#18081 Wizard staves and tele scrolls now fit in gemsuit storage.
  code/modules/clothing/spacesuits/rig.dm
Labels: ❤️ Quality of Life ❤️

#18088 Fixes a goof in Admin religion panel
  code/modules/admin/topic.dm
Labels: 100% tested, Bug / Fix

#18071 Tweaks the metabolism rate of inaprovaline to be slower so it lasts longer.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance, Tweak

#18079 "Projectile" for shotgun blanks
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Content

#18044 In-Hand-Radio Fix.
  code/game/objects/items/devices/radio/headset.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#18049 fixes the wine > vinegar bug again
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#18068 Makes virus analyser buttons reference dishes instead of names
  code/modules/virus2/analyser.dm
Labels: Bug / Fix

#18060 Re-enables slime surgery
  code/__HELPERS/unsorted.dm
  code/modules/surgery/surgery.dm
Labels: Bug / Fix

#18022 mobprinter
  code/game/machinery/martian_printer.dm
  icons/mob/martian.dmi
Labels: Content, Logging / Administration

#18098 Difficulty levels for The Hive
  maps/RandomZLevels/hive.dm
Labels: Balance, Tweak

#18053 Bee Tweaks
  code/game/machinery/bees_apiary.dm
  code/modules/mob/living/simple_animal/bees/bees_items.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
Labels: Tweak

#18087 Unstable mutagen now enlarges cockroaches
  code/modules/mob/living/simple_animal/hostile/bigroach.dm
  code/modules/mob/living/simple_animal/roach.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/reagent_containers/food/snacks/egg.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  icons/mob/animal.dmi
  icons/obj/food.dmi
  sound/effects/bug_hiss.ogg
  vgstation13.dme
Labels: Content

#18091 Fixes nanopaste for prosthetics
  code/game/objects/items/stacks/nanopaste.dm
Labels: Bug / Fix

#18085 Make Summon Cultist display visibility or dead status when actually summoning.
  code/game/gamemodes/cult/runes.dm
Labels: Balance, Gameplay / Gamemode, Update WIKI

#18120 Changes confusing flavor text on an item nobody will ever see.
  code/game/objects/items/weapons/dna_injector.dm
Labels: Grammar / Formatting, Oversight

#18127 Fixes pen suicide spacing
  code/modules/paperwork/pen.dm
Labels: Grammar / Formatting

#18125 Makes AME shut down when out of fuel
  code/modules/power/antimatter/control.dm
Labels: ❤️ Quality of Life ❤️

#18136 the admin command for add reagent now has a default value for temperature
  code/datums/datumvars.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#18135 Adds an alert prompt to the delay_round_end
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#18115 Increase cigarette and cigar capacity by 5.
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Tweak

#18106 Comm talisman buff
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/cult/runes.dm
  code/game/gamemodes/cult/talisman.dm
Labels: Balance, Gameplay / Gamemode

#18146 Adds ability to use inhalers on others
  code/game/objects/items/devices/inhaler.dm
Labels: Tweak

#18132 Species with no blood no longer bleed when hit
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bug / Fix

#18108 Fixes loyalty immunity to greytides
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/implants/implant.dm
Labels: Bug / Fix, Legacy Bug

#18024 UNATOMIC LANGUAGE TWEAKS/FIXES
  __DEFINES/setup.dm
  code/modules/client/preferences.dm
  code/modules/mob/language.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Bug / Fix, Tweak, Unatomic

#18143 Solves sleeper anchoring issue
  code/game/machinery/Sleeper.dm
Labels: Bug / Fix, Needs Moar Testing

#18167 Fixes AIs not understanding Gal Common
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Bug / Fix, Hotfix

#18139 Gravekeeper spiders
  __DEFINES/game.dm
  __DEFINES/global.dm
  code/__HELPERS/globalaccess.dm
  code/datums/ai_laws.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/silicon/mommi/cogspider.dm
  code/modules/mob/living/silicon/mommi/laws.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/mommi/mommi_modules.dm
  code/modules/mob/living/silicon/mommi/soviet_mommi.dm
  vgstation13.dme
Labels: Content

#17870 Cup Ramen self heating again
  __DEFINES/reagents.dm
  code/game/machinery/vending.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Tweak, WiP

#18124 Allows radiation collectors to pick up rads from mob sources
  code/game/dna/genes/goon_disabilities.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
  code/modules/power/singularity/collector.dm
  code/modules/power/singularity/singularity.dm
  code/modules/supermatter/supermatter.dm
Labels: Tweak

#18188 Fixes Corpus
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#18192 fixes ai job listing in cargo
  code/game/machinery/computer/cargo.dm
Labels: Bug / Fix

#18171 Buffs greytide kit plus adds syndishades
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance, Content, Tweak, Update WIKI

#18170 Unrestricts cult armor species
  code/game/gamemodes/cult/cult_items.dm
Labels: Tweak, Unatomic
