Repository vgstation-coders/vgstation13, pull requests merged in 2018-12, with the labels that each got.

#20797 Allows fluff computers to have admin-specified HTML content
  code/datums/browser.dm
  code/game/machinery/computer/fluff.dm
Labels: Content

#20333 [done][needs test merge][waiting for test merge since 3 weeks ago] curb your roundend 2: curb harder: return of curb
  __DEFINES/global.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/init/more_init_stuff.dm
  code/game/dna/dna_modifier.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/scoreboard.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/client/client procs.dm
  code/modules/credits/credit_disclaimers.dm
  code/modules/credits/credits.dm
  code/modules/credits/credits.html
  code/modules/credits/episode_name.dm
  code/modules/medical/cloning.dm
  code/modules/medical/computer/cloning.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/world.dm
  config-example/config.txt
  icons/credits/1zas.png
  icons/credits/2cluck.png
  icons/credits/3MPAOSA.png
  interface/skin.dmf
  sound/music/Frolic_Luciano_Michelini.ogg
  sound/music/Frolic_Luciano_Michelini_Short.ogg
  vgstation13.dme
Labels: Content, Secret repo conflict., WiP

#20866 Stops gibber from shooting gibs through walls
  code/game/machinery/kitchen/gibber.dm
Labels: Bug / Fix

#20851 Cold drinks cool
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#20802 Added speed setting for spacepods
  code/WorkInProgress/pomf/spacepods/actions.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  icons/pods/button_icons.dmi
Labels: Content

#20740 giant syringes are now giant
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Sprites

#20795 Makes bullets faster
  code/modules/projectiles/projectile/bullets.dm
Labels: Balance

#20889 Actually prevent admins from editing their perms
  code/modules/admin/verbs/modifyvariables.dm
Labels: Logging / Administration, 🚓Fun Police🚓

#20859 Confusion rune disguises humans and silicons now
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/mommi/login.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: 100% tested, Bug / Fix, Gameplay / Gamemode

#20713 Re-adds revs to the rotation.
  __DEFINES/role_datums_defines.dm
  code/_hooks/mob.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/objectives/objective.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/role/rev.dm
  code/game/objects/items/devices/flash.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/new_player/new_player.dm
  vgstation13.dme
Labels: Role Datums, Secret repo conflict.

#20252 [DNM] Noir greyscale colours are now properly set and unset
  __DEFINES/setup.dm
  code/game/dna/genes/vg_powers.dm
  code/modules/client/client defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species_powers.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#20884 Cult balance of the week #2
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/legacy_cult/cult_structures.dm
  code/datums/gamemode/factions/legacy_cult/soulstone.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/helper_datums/command_alerts.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/walls_misc.dm
  code/modules/detectivework/detective_scanner.dm
  code/modules/mob/living/simple_animal/shade_powers.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cultify.dm
  icons/mob/monkey_head.dmi
  icons/obj/cult.dmi
  icons/obj/cult_64x64.dmi
Labels: Balance, Bug / Fix, Gameplay / Gamemode

#20893 thank you
  html/changelog.html
  html/templates/header.html
Labels: Grammar / Formatting

#20894 Fixes cameras crashing the serb (sometimes)
  code/game/machinery/computer/camera.dm
Labels: 100% tested

#19463 Player Shuttle Construction
  code/datums/supplypacks.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/computer/shuttle_computers.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/weapons/manuals.dm
  code/game/shuttle_engines.dm
  code/game/turfs/turf.dm
  icons/obj/library.dmi
Labels: Content, Update WIKI

#20702 Added workaround for nanoui bug
  code/modules/nano/nanoui.dm
Labels: System

#20895 Remove nonsense
  code/modules/mob/living/carbon/alien/humanoid/life.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/complex/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/silicon/mommi/life.dm
Labels: File Cleanup

#20882 Adds holo pipes
  code/game/machinery/vending.dm
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Content

#20892 adds some shotgun sounds
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  sound/weapons/shotgun_open.ogg
  sound/weapons/shotgun_shell_bounce.ogg
  sound/weapons/shotgun_shell_insert.ogg
  sound/weapons/shotgun_small.ogg
Labels: Sound

#20927 Xenoarch fixes
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
Labels: Bug / Fix

#20926 Runtime hunting: portable pumps altclick
  code/game/machinery/atmoalter/portable_atmospherics.dm
Labels: Bug / Fix, Runtime Log

#19948 Pillowbugs
  __DEFINES/setup.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/holders.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/mob/mob.dm
  icons/mob/animal.dmi
  icons/mob/head.dmi
  icons/mob/in-hand/left/mob_holders.dmi
  icons/mob/in-hand/right/mob_holders.dmi
Labels: Content, Ready to Merge

#20931 Fixes fart runtimes
  code/modules/mob/living/carbon/human/emote.dm
Labels: Bug / Fix

#20486 Replaces mass specs in the protolathe with reagent scanners.
  code/game/objects/items/devices/scanners.dm
  code/modules/research/designs/medical.dm
Labels: Balance, Tweak

#20919 Potentially fixing a weird cult bug
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/objectives/bloodcult.dm
Labels: Bug / Fix

#20945 Allow configuration to be VVed
  code/modules/admin/verbs/modifyvariables.dm
Labels: Logging / Administration, System

#20887 Robotic limb unsucking
  __DEFINES/setup.dm
  code/game/objects/items/devices/multitool.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/organs/organ_external.dm
Labels: Tweak

#20932 Cult balance of the week #3
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/modules/spells/aoe_turf/conjure/construct.dm
Labels: Role Datums, Tweak

#20875 Superglue can be applied to chairs, beds, vehicles
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Content

#20888 Adds the NT-12 semi-automatic magazine-fed shotgun.
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  sound/weapons/shotgun_nt12.ogg
Labels: Content

#20732 Clockwork GraveKEEPER Role
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/factions/clockwork.dm
  code/datums/gamemode/role/clockwork.dm
  code/game/machinery/mommi_spawner.dm
  code/game/objects/items/robot/robot_items/robot_spawner.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/silicon/mommi/mommi_subtypes/cogspider.dm
  icons/logos.dmi
  icons/role_HUD_icons.dmi
  vgstation13.dme
Labels: Role Datums, Unatomic

#20956 Fixes being able to put a bag of holding inside of itself
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug / Fix

#20940 Hotfix. Replaced/added reagent scanners in place of mass specs where appropriate.
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/mining/surprises/tg.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  maps/dorffort.dm
  maps/randomvaults/spessmart.dm
Labels: Balance, Hotfix

#20957 Rather than mecha having their own Destroy proc, combines the two
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/sec_tools.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_wreckage.dm
Labels: Tweak

#20976 Runtime fixes - Mecha object removal
  code/game/mecha/mecha.dm
Labels: Bug / Fix

#20971 Fixes Cauldron Filling (SBO3)
  icons/obj/reagentfillings.dmi
Labels: Bug / Fix, Sprites

#20966 SPS beeps on cult conversion wherever carried
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix, Tweak

#20965 fix cult hud flash bug
  code/_onclick/hud/screen_objects.dm
Labels: Bug / Fix

#20981 Fixed syringe injection logging
  code/modules/mob/living/living.dm
Labels: Bug / Fix

#20987 Fixes Shuttle Coord Disks (SBO6)
  code/game/machinery/computer/shuttle_computers.dm
Labels: Bug / Fix

#20891 Ports snowmap's flora clearing
  __DEFINES/_macros.dm
  code/game/gamemodes/endgame/xmas/snow.dm
  code/game/objects/structures/flora/flora.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/snow.dm
  code/game/turfs/unsimulated/snow.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/soil.dm
Labels: Content

#20636 Ports the new anomaly container/analyser/pad icons from Bay
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/research/xenoarchaeology/machinery/artifact_scanner.dm
  icons/obj/xenoarchaeology.dmi
Labels: Port, Sprites

#20990 Fixed a uhh
  code/game/objects/items/ashtray.dm
Labels: Bug / Fix

#20986 Fixes Payment (SBO4&5)
  code/modules/Economy/utils.dm
Labels: Bug / Fix

#20982 Fixed hair selection arrows
  code/modules/client/preferences.dm
Labels: Bug / Fix

#20972 Chameleon projector passes the explosion value on to you! (SBO4)
  code/game/objects/items/devices/chameleonproj.dm
Labels: Bug / Fix

#20984 Bigger and thicker supply console UI
  code/controllers/subsystem/supply_shuttle.dm
  code/game/machinery/computer/cargo.dm
  nano/templates/order_console.tmpl
  nano/templates/supply_console.tmpl
Labels: UI

#20834 Quack
  __DEFINES/global.dm
  code/modules/mob/living/simple_animal/hostile/duck.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  icons/mob/animal.dmi
  sound/misc/quacktivated.ogg
  sound/misc/roboquack.ogg
  sound/misc/roboquack_death.ogg
  vgstation13.dme
Labels: Content

#20949 Skree2
  code/datums/emotes.dm
  code/datums/gamemode/role/vampire_role.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/structures/mirror.dm
  code/game/sound.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/simple_animal/hostile/human/cult.dm
  config/names/verbs.txt
  sound/misc/shriek1.ogg
Labels: Sound

#21002 Updated cult objective description
  code/datums/gamemode/objectives/bloodcult.dm
Labels: Bug / Fix

#21004 Better logging for PDA
  code/game/objects/items/devices/uplinks.dm
Labels: Logging / Administration

#19738 Trader: It Came From Alcatraz IV!
  code/defines/obj/weapon.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/vending.dm
  code/game/objects/items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/stacks/sheets/bigstacks.dm
  code/game/objects/items/trader.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/clothing/suits/armor.dm
  code/modules/detectivework/detective_scanner.dm
  code/modules/media/jukebox.dm
  icons/mob/uniform.dmi
  icons/obj/cage.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/device.dmi
Labels: Content, Tweak, Unatomic

#21009 buckets now have a reagent overlay
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/reagentfillings.dmi
Labels: Content

#20996 Limbs and organs preferences menu QoL
  code/modules/client/preferences/subsections/limbs.dm
  code/modules/client/preferences/subsections/organs.dm
Labels: UI

#20983 Yet more blacksmithing tweaks
  code/WorkInProgress/MadmanMartian/blacksmithing/misc_components.dm
  code/game/objects/objs.dm
  code/modules/mining/materials.dm
Labels: Tweak

#20826 Makes forcesay work in hotkey mode
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/say.dm
  interface/skin.dmf
Labels: Needs Review

#20953 Make revs less likely to happen.
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Role Datums, Tweak

#21018 Fixes the .dmf for the new say thing.
  interface/skin.dmf
Labels: Hotfix, ✋ Do Not Merge ✋

#21015 Fixes malf dying on Delta not triggering round end
  code/datums/gamemode/factions/malf.dm
Labels: Bug / Fix

#21029 Fixes stack splitting losing material type
  code/game/objects/items/stacks/stack.dm
Labels: Bug / Fix, Consistency Issue

#21021 Revert hotkey mode say menu
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/say.dm
  interface/skin.dmf
Labels: Feature Loss

#21016 Fixes antag HuDs sometimes going away on cloning
  code/datums/mind.dm
Labels: Oversight

#21030 Manifast Replaces Manislow (SFO13)
  code/datums/datacore.dm
  code/game/gamemodes/gameticker.dm
Labels: Bug / Fix

#21013 Improves VV for lists
  code/datums/datumvars.dm
  code/modules/admin/verbs/modifyvariables.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#21024 Holy futureproofing
  __DEFINES/_macros.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/legacy_cult/ritual.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
  code/datums/gamemode/factions/legacy_cult/talisman.dm
  code/game/gamemodes/wizard/artefact.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/spells/construct_spells.dm
Labels: File Cleanup

#20955 adds nt12 to summon guns
  code/game/gamemodes/wizard/rightandwrong.dm
Labels: Balance

#20985 Mushrom people now have higher darkvision
  code/modules/mob/living/carbon/species.dm
Labels: Balance

#21014 Fixes revs spawning on the wrong z-level
  code/datums/gamemode/role/rev.dm
  code/datums/mind.dm
Labels: Role Datums

#20997 Fixed annoying Atom ProcCall shit
  code/modules/admin/verbs/debug.dm
Labels: Bug / Fix

#20994 Allow crawling when knocked down
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
Labels: Balance

#20995 Flashes also stun in addition to knocking down
  code/game/machinery/flasher.dm
  code/game/objects/items/devices/flash.dm
Labels: Balance

#21012 Fixes a runtime on check antagonists
  code/datums/gamemode/role/vampire_role.dm
Labels: Bug / Fix

#21040 gives /datum/design/rad_cell its missing ID
  code/modules/research/designs/engineering.dm
Labels: 100% tested

#20970 Adds the Automag, a semi-automatic magazine-fed handcannon.
  code/game/gamemodes/wizard/rightandwrong.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Conflicts, Content

#21053 Replaces a Barsign Sprite
  icons/obj/barsigns.dmi
Labels: Sprites

#21058 Admin warns on thralling/dethralling
  code/datums/gamemode/role/vampire_role.dm
Labels: Logging / Administration

#21057 Fixes BritSky not deleting on Destruction II
  code/game/machinery/bots/secbot.dm
Labels: Bug / Fix

#21055 Rev fixes, 105% tested edition
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/role/rev.dm
Labels: Role Datums

#21050 Add a mushroom trader hardsuit
  __DEFINES/global.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/maps/spawners/spawners.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Content, Sprites

#21048 Spacepod occupant revamp
  code/WorkInProgress/pomf/spacepods/actions.dm
  code/WorkInProgress/pomf/spacepods/equipment.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
Labels: 100% tested, Tweak

#21041 Protected roles tweaks and refactor
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
Labels: Role Datums, System, Tweak

#21000 Trader Name Fix (SBO8)
  code/modules/mob/new_player/new_player.dm
Labels: Secret repo conflict.

#20977 Runtime hunting: Manifest prediction
  code/modules/mob/new_player/new_player.dm
Labels: Secret repo conflict.

#21054 You can now use any bottles, soda cans, drinking glass, etc in the making of chem grenades.
  code/game/objects/items/weapons/grenades/chem_grenade.dm
Labels: Gameplay / Gamemode, ❤️ Quality of Life ❤️

#20991 A helmet which hides your hair doesn't shave you off completely anymore.
  __DEFINES/setup.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Needs Fixing, Sprites

#21019 Nullrods now blocks vamp spells, unless vamp is young
  code/modules/spells/vampire_helpers.dm
Labels: Balance

#20998 Cult structures can be raised off-station after the sacrifice
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Balance

#21028 Disability Fixes (SBO9-12)
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
Labels: Bug / Fix

#21061 key_name() can now be passed a mind
  code/__HELPERS/unsorted.dm
Labels: System

#21062 fixes the messy thralling adminwarn that half works
  code/datums/gamemode/role/vampire_role.dm
Labels: Bug / Fix, Logging / Administration

#21080 Fixes a few strange haircuts
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/legacy_cult/cult_items.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/miscellaneous.dm
Labels: Sprites

#21077 Changes posibrain flavor text
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: Tweak

#21086 Fixes Vox helmets giving buggy hair
  code/modules/clothing/spacesuits/alien.dm
  icons/mob/human_face.dmi
Labels: 100% tested, Sprites

#21095 More things check for antag bans
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
Labels: Bug / Fix, Oversight

#21096 Add a few more checks for jobbans
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/game/gamemodes/blob/blobs/core.dm
Labels: Bug / Fix, Oversight

#21097 Fixes escape objectives failing if you were on a pod
  code/datums/gamemode/objectives/escape.dm
Labels: Bug / Fix, Role Datums

#21072 Update assistant jumpsuit to match their departments
  code/game/jobs/job/assistant.dm
Labels: Tweak

#20422 Logging for posibrain attack_ghost
  code/datums/recruiter.dm
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: Grammar / Formatting, Logging / Administration

#21098 Hostile ListTarget rewrite
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Balance, T-Thanks BYOND

#21105 Posibrain logging hotfix
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: Hotfix

#21104 there's a proc for that
  code/datums/religions.dm
Labels: File Cleanup, Grammar / Formatting

#21099 isantagbanned macro
  __DEFINES/_macros.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/machinery/syndicatebeacon.dm
  code/game/objects/items/changeling_vial.dm
  code/game/objects/items/weapons/explosives.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/client/preferences.dm
  code/modules/clothing/masks/stone.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/simple_animal/borer.dm
Labels: Grammar / Formatting, Ready to Merge, Role Datums

#21110 [OBS-2/51] Fixes lube on top of water lasting for way too long
  code/game/turfs/simulated/floor.dm
Labels: Bug / Fix

#20974 Essence printer
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  code/modules/research/xenoarchaeology/artifact/artifact_essenceprinter.dm
  icons/obj/xenoarchaeology.dmi
  vgstation13.dme
Labels: Content

#21106 renames can_fire()
  code/datums/religions.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/targeting.dm
  code/modules/reagents/dartgun.dm
  code/modules/reagents/syringe_gun.dm
Labels: Grammar / Formatting

#21123 Religion TLC
  code/datums/religions.dm
Labels: Content, Tweak

#21109 [OBS-1/51] Sanity for vampire spells
  code/modules/spells/aoe_turf/glare.dm
  code/modules/spells/aoe_turf/screech.dm
  code/modules/spells/targeted/hypnotise.dm
Labels: Bug / Fix

#21074 Emotes now check if there is actually somebody to hear it in earshot
  code/datums/emotes.dm
Labels: Tweak

#21115 Fixes zombies getting stuck on doors
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: Bug / Fix

#21143 Fixes minor typo on grinch bag
  code/modules/mob/living/simple_animal/hostile/grinch.dm
Labels: Grammar / Formatting

#19956 Adds a very basic weeaboo mini-antag
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/objectives/target/syndicate/skulls.dm
  code/datums/gamemode/role/weeaboo.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/client/preferences.dm
  code/modules/mob/inventory.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/gun.dm
  icons/logos.dmi
  icons/obj/storage/storage.dmi
  sound/effects/gong.ogg
  sound/weapons/shing.ogg
  vgstation13.dme
Labels: Content

#21144 Prevents borers from using hivemind while dead
  code/modules/mob/living/simple_animal/borer.dm
Labels: 100% tested, Bug / Fix

#21132 Cult tattoos tweaks
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Balance

#20837 Robot upgrade tweaks + Portable Smelter Upgrade(Adminbus only for now)
  code/game/objects/items/robot/robot_items/robot_furnace.dm
  code/game/objects/items/robot/robot_upgrades.dm
  icons/obj/mining.dmi
  vgstation13.dme
Labels: Content, Grammar / Formatting, Tweak, Unatomic

#21107 Fossilized egg
  __DEFINES/archaeo_defines.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/food/snacks/egg.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/xenoarchaeology/finds/digsites.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_fossils.dm
  icons/obj/food.dmi
  icons/obj/xenoarchaeology.dmi
Labels: Content

#21166 Bomberman Jump Fix (SBO24)
  code/modules/bomberman/bomberman.dm
Labels: Bug / Fix

#21164 Yet more mining turf tweaks for snowmap
  code/modules/mining/mine_turfs.dm
  code/modules/mining/minerals.dm
Labels: Consistency Issue, Content

#21171 Maturity minimum (SBO29)
  code/modules/hydroponics/hydroponics_mutations.dm
Labels: Bug / Fix

#21161 Map gen now checks for base turf rather than if the turf is space
  code/modules/html_interface/map/interactive_map.dm
  code/modules/html_interface/map/station_map.dm
Labels: System

#21167 Merchants Will Not Be Roundstart Cultists (SBO25)
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/legacy_cultist.dm
Labels: Bug / Fix

#21124 Adds Botany Chemicals
  __DEFINES/reagents.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Content

#21190 MR.V.A.L.I.D. now speaks his mind
  code/game/machinery/metaldetector.dm
Labels: Tweak

#21168 Fixes trader goof (SBO26)
  code/game/gamemodes/gameticker.dm
Labels: Bug / Fix

#21165 Better Layering (SBO22-23)
  code/game/machinery/vending.dm
  code/game/objects/effects/glowshroom.dm
Labels: Bug / Fix, Tweak
