Repository vgstation-coders/vgstation13, pull requests merged in 2018-09, with the labels that each got.

#19330 removes drag damage
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Feature Loss

#19545 Ling chat fix
  code/modules/mob/living/say.dm
Labels: Bug / Fix, Role Datums

#19544 Role datums player panel fix
  code/modules/admin/admin.dm
  code/modules/admin/player_panel.dm
Labels: Bug / Fix, Role Datums

#19543 More changeling fixes
  code/datums/gamemode/role/changeling.dm
  code/game/gamemodes/changeling/changeling_powers.dm
Labels: Bug / Fix, Role Datums

#19542 Yet more objective fixes.
  code/datums/gamemode/objectives/target/assassinate.dm
  code/datums/gamemode/objectives/target/debrain.dm
  code/datums/gamemode/objectives/target/harm.dm
  code/datums/gamemode/objectives/target/nanotrasen/brig.dm
  code/datums/gamemode/objectives/target/nanotrasen/demote.dm
  code/datums/gamemode/objectives/target/nanotrasen/execute.dm
  code/datums/gamemode/objectives/target/protection.dm
  code/datums/gamemode/objectives/target/sacrifice.dm
  code/datums/gamemode/objectives/target/syndicate/brig.dm
  code/datums/gamemode/objectives/target/syndicate/steal.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/role/role.dm
  code/datums/mind.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
  vgstation13.dme
Labels: Bug / Fix, File Cleanup, Role Datums

#19551 Woody Plants Need Sharp Object To Harvest (FFF4)
  code/modules/hydroponics/seed_datums.dm
Labels: Bug / Fix

#19530 [Cult 3.0] Astral Journey & Resurrect, Runes XIX & XX
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/modules/mob/dead/observer/observer.dm
  icons/effects/effects.dmi
Labels: Role Datums

#19572 Humans can no longer be martians
  code/game/machinery/lightswitch.dm
  icons/obj/power.dmi
Labels: ❤️ Quality of Life ❤️

#19480 Makes the supermatter crystal actually generate more power than shards
  code/modules/supermatter/supermatter.dm
Labels: Balance

#19593 Break cell lockers (FFF21)
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Bug / Fix

#19586 Fixes Animal Holder Inconsistencies (FFF15)
  code/modules/mob/living/holders.dm
  code/modules/mob/living/simple_animal/borer.dm
Labels: Bug / Fix

#19592 Electropacks Can't Be Quickswapped Off (FFF20)
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/electropack.dm
Labels: Bug / Fix

#19571 Haunted Arcades (FFF7)
  __DEFINES/lighting.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/machinery/computer/arcade/arcade_game.dm
  icons/obj/computer.dmi
Labels: Bug / Fix, Content

#19553 Ends Drone Love (FFF5)
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
Labels: Bug / Fix

#19554 Fixes SPS not beeping
  code/game/objects/items.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/assembly/bomb.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/mousetrap.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/telesci/gps.dm
Labels: Bug / Fix

#19591 Unlimited Clown Naming Time (FFF19)
  code/__HELPERS/unsorted.dm
Labels: ❤️ Quality of Life ❤️

#19528 Fixes bats attacking their master
  code/datums/gamemode/factions/vampire_faction.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/vampire_gamemode.dm
  code/modules/clothing/masks/stone.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
Labels: Role Datums

#19579 Role datums lingling fixes
  code/datums/gamemode/role/changeling.dm
  code/game/gamemodes/changeling/changeling_powers.dm
Labels: Bug / Fix, Role Datums, ❤️ Quality of Life ❤️

#19596 SPS Spam fix
  code/__HELPERS/unsorted.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/clothing/clothing.dm
  code/modules/telesci/gps.dm
Labels: 100% tested, Bug / Fix

#19581 Secure medical crates
  code/datums/supplypacks.dm
  code/game/objects/structures/crates_lockers/crates.dm
  icons/obj/storage/storage.dmi
Labels: Tweak

#19584 Diona Need Nonmonkey Blood to Evolve (FFF13)
  code/modules/mob/living/carbon/monkey/diona.dm
Labels: Bug / Fix, Tweak

#19570 Holoman Runtime w/ Shelter (FFF6)
  code/game/objects/structures/inflatable.dm
Labels: Bug / Fix

#19585 Seed Extractor No Longer Causes Dropping Items (FFF14)
  code/__HELPERS/unsorted.dm
Labels: Bug / Fix

#19559 Shelter fixes + QoL
  code/game/machinery/alarm.dm
  code/game/objects/structures/inflatable.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#19561 Fixes the message feedback when you place someone into a shelter, and adds click dragging
  code/game/objects/structures/inflatable.dm
Labels: Bug / Fix

#19595 Sacrifice Rune now works
  code/datums/gamemode/factions/legacy_cult/cult.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
Labels: Role Datums

#19594 Cargo Is NEVER Late (FFF22)
  code/controllers/subsystem/supply_shuttle.dm
Labels: Tweak

#19580 Malf fixes
  code/modules/power/apc.dm
Labels: Consistency Issue, Role Datums

#19614 Yet more objective tweaks and fixes
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/objectives/objective.dm
  code/datums/gamemode/role/role.dm
  code/datums/mind.dm
Labels: Role Datums

#19621 Clarkes Can Hack (FFF24)
  code/datums/wires/wires.dm
Labels: Bug / Fix

#19617 Haunted Arcade Spritefix
  icons/obj/computer.dmi
Labels: Bug / Fix

#19622 Welders Hot/Sharp Only While Active (FFF23)
  code/game/objects/items/weapons/tools.dm
Labels: Bug / Fix

#19599 Ports radial menu framework from AnturK's code with permission
  __DEFINES/planes+layers.dm
  code/__HELPERS/lists.dm
  code/_onclick/hud/radial.dm
  icons/mob/radial.dmi
  vgstation13.dme
Labels: Content, Port

#19623 Removes reversible bug handling + message because it doesn't describe a bug
  code/datums/helper_datums/construction_datum.dm
Labels: Logging / Administration

#19630 Chemistry Runtime Hunting (FFF26)
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#19632 stop breaking the database.
  code/modules/client/preferences_savefile.dm
Labels: Oversight

#19548 [Role Datums] Dynamic Mode
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_debug.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/role/syndicate.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  data/mode.txt
  vgstation13.dme
Labels: Role Datums

#19642 Fixes overlay on constructed lightswitches
  icons/obj/power.dmi
Labels: Bug / Fix

#19651 Fixes compile for 1447+
  code/datums/statistics/stat_helpers.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/lamarr_cage.dm
Labels: Bug / Fix

#19370 ghetto splint crafting
  code/game/objects/items/stacks/medical.dm
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
  icons/obj/items.dmi
Labels: Conflicts, Needs Spritework, Update WIKI, ❤️ Quality of Life ❤️

#19629 Unexploits Spessmart (FFF25)
  maps/randomvaults/spessmart.dm
Labels: Exploitable, Oversight

#19552 RPD Passing
  code/modules/RCD/RPD.dm
Labels: Bug / Fix, Tweak

#19647 [Role Datums] Adding some legacy rulesets for parity with the old game modes
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_debug.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/game/striketeams/striketeam_datums.dm
  code/modules/mob/new_player/new_player.dm
  icons/logos.dmi
Labels: Secret repo conflict.

#19608 Trader 2
  code/datums/wires/vending.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/doubleagent.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/vampire/vampire.dm
  code/game/jobs/job/whitelisted.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/mining/machine_processing.dm
  nano/templates/comm_console.tmpl
Labels: Balance, Content, Tweak, Unatomic

#19669 [Role Datums] Tweaks, Bugfixes and other stuff
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/role/legacy_cultist.dm
  code/datums/gamemode/role/role.dm
  code/datums/mind.dm
  code/modules/mob/new_player/new_player.dm
Labels: Role Datums, Secret repo conflict.

#19660 can now cut rags out of bedsheets with anything sharp
  code/game/objects/structures/bedsheet_bin.dm
Labels: ❤️ Quality of Life ❤️

#19609 T R A I N datums (fixes infinite loops with carts)
  code/game/objects/structures/vehicles/carts/cart.dm
  code/game/objects/structures/vehicles/carts/datum_cart_network.dm
  code/game/objects/structures/vehicles/vehicle.dm
  vgstation13.dme
Labels: Bug / Fix

#19675 fixes recipe for beepsky classic
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#19662 Fixes vampires not burning in the chapel (as well as other things.)
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/role/vampire_role.dm
Labels: Role Datums

#19538 Reverts stomach
  code/game/machinery/constructable_frame.dm
  code/game/machinery/dialysis.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/organs/internal/stomach/stomach.dm
  code/modules/organs/organ_objects.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagents/vg.dm
  code/modules/research/designs/boards/machine_medical.dm
  icons/obj/stationobjs.dmi
  icons/obj/surgery.dmi
  vgstation13.dme
Labels: Feature Loss, Unable To Reproduce

#19680 based and redpilled
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
Labels: Unable To Reproduce

#19671 re-adds the syndicate greytide implant
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/unsorted.dm
  code/datums/gamemode/factions/syndicate/traitor.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/role/role.dm
  code/datums/mind.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/mob/living/login.dm
  icons/logos.dmi
  vgstation13.dme
Labels: Role Datums

#19672 Adds slips to the scoreboard
  __DEFINES/global.dm
  code/game/gamemodes/scoreboard.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Honk

#19661 get_cell() helper
  code/ATMOSPHERICS/hvac/spaceheater.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  code/game/atoms.dm
  code/game/data_huds.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/floodlight.dm
  code/game/machinery/syndicatebeacon.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/vehicles/wheelchair.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/powernet.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/projectile/bow.dm
  code/modules/projectiles/guns/projectile/constructable/blinder.dm
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
  code/modules/telesci/rcs.dm
  code/modules/telesci/telesci_computer.dm
Labels: System

#19658 Paper Formatting
  code/WorkInProgress/kilakk/fax.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/photocopier.dm
Labels: Content

#19633 Fixes cyborgs getting stuck in limbo, part 2
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Bug / Fix, Runtime Log

#19624 Adds the card game Une.
  code/game/machinery/computer/store.dm
  code/game/machinery/vending.dm
  code/modules/RCD/RSF.dm
  code/modules/RCD/schematics/service.dm
  code/modules/games/cards/playing_cards.dm
  code/modules/games/cards/une/une_cards.dm
  code/modules/store/items.dm
  icons/obj/une_cards.dmi
  vgstation13.dme
Labels: Content

#19583 Network Alert: ALL SYSTEMS NOMINAL
  code/modules/mob/living/silicon/pai/software.dm
Labels: Feature Loss

#19366 What could possibly go wrong???
  __DEFINES/math_physics.dm
Labels: Needs Moar Testing, System, ✋ Do Not Merge ✋

#19329 Reverts Pillcreep
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/research/designs/borg_upgrades.dm
Labels: Feature Loss, Unatomic

#18834 Swap staff
  code/game/gamemodes/wizard/artifacts.dm
  code/game/objects/structures/safe.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/projectiles/targeting.dm
  icons/mob/in-hand/left/guns.dmi
  icons/mob/in-hand/right/guns.dmi
  icons/obj/wizard.dmi
Labels: Content

#19656 Constructing/deconstructing secure crates and lockers
  code/datums/supplypacks.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Content, Update WIKI

#19699 removes unused var in pai software
  code/modules/mob/living/silicon/pai/software.dm
Labels: 100% tested

#19701 Fixes Nano going nuclear if provided with infinite values
  code/modules/nano/JSON Writer.dm
Labels: Bug / Fix, System

#18844 Allows Players to See Readied High Job Prefs
  code/defines/obj.dm
  code/game/jobs/job_controller.dm
  code/modules/mob/new_player/new_player.dm
Labels: Needs Review, Secret repo conflict.

#19714 Fix nonsense
  code/modules/power/singularity/singularity.dm
Labels: File Cleanup, T-Thanks BYOND

#19713 #warning -> #warn
  __DEFINES/setup.dm
  code/__HELPERS/game.dm
  code/game/machinery/computer/slot_machine.dm
  code/game/objects/effects/beam.dm
  code/modules/media/mediamanager.dm
Labels: File Cleanup, T-Thanks BYOND

#19715 deduplicate a few defines
  __DEFINES/bots.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/secbot.dm
  vgstation13.dme
Labels: File Cleanup

#19716 Removed some more duplicate defines
  code/game/objects/items/devices/lightreplacer.dm
Labels: File Cleanup

#19717 Fixed conflicting defines
  code/game/objects/items/robot/robot_items/robot_hug.dm
Labels: File Cleanup

#19718 Removed #undef for macros that were never defined
  code/WorkInProgress/buildmode.dm
  code/game/objects/structures/curtains.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/admin/verbs/massmodvar.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: File Cleanup

#19711 Fixed issues with vehicle keys
  code/game/objects/structures/vehicles/secway.dm
  code/game/objects/structures/vehicles/vehicle.dm
Labels: Bug / Fix

#19708 Seemingly fix computer interfaces failing to load.
  nano/js/nano_template.js
Labels: System

#19720 Removed duplicated pipe defines
  code/ATMOSPHERICS/pipe_defines_for_mapping.dm
  maps/bagelstation.dm
  maps/defficiency.dm
  maps/roidstation.dm
  maps/tgstation.dm
  maps/tgstation/pipes.dm
  vgstation13.dme
Labels: File Cleanup

#19722 Removed duplicated pipe defines
  code/ATMOSPHERICS/utils.dm
Labels: File Cleanup

#19723 Fixed conflicting reagent state defines
  code/modules/mob/living/carbon/zombie/zombie.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagents/vg.dm
  code/modules/research/xenoarchaeology/chemistry.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
  code/modules/virus2/antibodies.dm
Labels: File Cleanup

#19721 Fixed lawgiver defines
  code/modules/projectiles/guns/lawgiver.dm
Labels: File Cleanup

#19724 Deduplicate xenoarch artifact defines
  __DEFINES/archaeo_defines.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_affect_cold.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_badfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cellcharge.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_celldrain.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cultify.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkness.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkrevive.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_dnaswitch.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_emp.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_forcefield.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasco2.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasnitro.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasoxy.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasplasma.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gassleeping.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_goodfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gravity.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_heal.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_heat.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_hurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_menagerie.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_plantkiller.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_projectiles.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_radiate.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_reagentblock.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_roboheal.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_robohurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_sleepy.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_stun.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_teleport.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_timestop.dm
  code/modules/research/xenoarchaeology/artifact/trigger.dm
  code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_touch.dm
  code/modules/research/xenoarchaeology/tools/ano_device_battery.dm
Labels: File Cleanup

#19725 Fixed spooky defines
  __DEFINES/setup.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/projectiles/guns/energy/special.dm
Labels: File Cleanup

#19726 Fixed chemmask defines
  code/modules/clothing/masks/chemmask.dm
Labels: File Cleanup

#19727 Fixed duplicated jukebox defines
  __DEFINES/jukebox.dm
  __DEFINES/setup.dm
  code/datums/wires/jukebox.dm
  code/modules/media/jukebox.dm
  code/modules/media/tapedeck.dm
  vgstation13.dme
Labels: File Cleanup

#19728 Unfuck several defines
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
Labels: File Cleanup

#19729 Fixed conflicting simple_animal defines
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/wolf.dm
Labels: File Cleanup

#19730 #warning -> #warn, episode 2, season finale
  code/datums/feedback.dm
  code/defines/procs/biohazard_alert.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/randomMaps/vaults.dm
Labels: File Cleanup

#19739 Fixed deathnettle being consumed on failed attacks
  code/modules/hydroponics/grown_inedible.dm
Labels: Bug / Fix

#19742 grille/broken/New() calls parent
  code/game/objects/structures/grille.dm
Labels: Bug / Fix

#19692 [Role Datums] Scoreboard
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/legacy_cult/cult.dm
  code/datums/gamemode/factions/syndicate/traitor.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/role/role.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/scoreboard.dm
  icons/effects/blood.dmi
  icons/logos.dmi
Labels: Role Datums

#19694 Cult 2.0 tweaks
  code/datums/gamemode/factions/legacy_cult/cult.dm
  code/datums/gamemode/role/legacy_cultist.dm
Labels: Role Datums

#19744 Brain Identities (FFF27)
  code/modules/mob/living/carbon/brain/brain_item.dm
Labels: Bug / Fix

#19747 Fixes AAC Import/Export (FFF30)
  code/modules/atmos_automation/implementation/scrubbers.dm
  code/modules/atmos_automation/implementation/vent_pump.dm
Labels: Bug / Fix

#19741 Added chat message when hitting grilles
  code/game/objects/structures/grille.dm
Labels: Tweak

#19743 aghost with matter synth
  code/game/machinery/antiquemattersynth.dm
Labels: Logging / Administration

#19710 Fixes things with papers on cameras
  code/game/machinery/camera/camera.dm
Labels: Bug / Fix, Tweak

#19737 Body scanner can now be (un)anchored with a wrench
  code/game/machinery/adv_med.dm
Labels: Tweak

#19667 Fixes Ion Laws being treated as emotes.
  code/__HELPERS/text.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#19752 Syringe injection refactor
  __DEFINES/syringes.dm
  code/game/atoms.dm
  code/game/objects/items/gum.dm
  code/game/objects/structures/lamarr_cage.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/power/lighting.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/syringes.dm
  vgstation13.dme
Labels: Bug / Fix, Tweak

#19659 Rags now work as bandages
  code/modules/detectivework/footprints_and_rag.dm
Labels: Content

#19753 Voice changer fixes
  __DEFINES/clothing.dm
  code/game/objects/items.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  vgstation13.dme
Labels: Bug / Fix, Unatomic

#19677 Readds Summon Guns, Swords, and Magic.
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/game/gamemodes/wizard/rightandwrong.dm
Labels: Role Datums

#19761 Fixes Plant Aging (FFF33)
  code/modules/hydroponics/hydro_tray.dm
Labels: Bug / Fix

#19760 Panel Sprite (FFF32)
  maps/defficiency/medbay.dmi
Labels: Bug / Fix

#19758 Fixed cargo computers hygiene
  code/game/machinery/computer/cargo.dm
Labels: Bug / Fix

#19764 Removes obscure changeling vore
  code/datums/gamemode/role/changeling.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/gamemodes/changeling/modularchangling.dm
  code/modules/mob/mob_grab.dm
Labels: Role Datums

#19763 [Role Datums] Antag HUD Icons are now properly removed when a role/faction is removed
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/role/role.dm
Labels: Role Datums

#19773 Role datums More Changeling Fixes
  code/game/gamemodes/changeling/changeling_powers.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: Role Datums

#19696 Role datums one click antag
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/factions/faction.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Role Datums

#19785 Safe debugging
  code/game/objects/structures/safe.dm
Labels: Logging / Administration

#19801 [Hotfix] Holy Fuck
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Hotfix

#19791 Re adds some lost sprites
  icons/obj/card.dmi
  icons/obj/storage/storage.dmi
Labels: Hotfix

#19804 Who Advanced fix (again)
  code/game/verbs/who.dm
Labels: 100% tested

#19778 Mr. Clean makes everything so clean that you can see your reflection in them
  code/game/gamemodes/cult/narsie.dm
  code/game/objects/effects/overlays.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/simulated/walls_reinforced.dm
  code/game/turfs/turf.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: File Cleanup

#19808 Changes some checks to actually return 0 on false, rather than null
  code/modules/mob/mob_helpers.dm
Labels: Bug / Fix

#19762 Virtual Wallet Needs Linked_DB (FFF34)
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Bug / Fix

#19754 Raises max lines for instruments from 100 to 300
  code/game/objects/structures/musician.dm
Labels: Tweak

#19733 Adds AI newLife and Death sounds
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  sound/machines/WXP_shutdown.ogg
  sound/machines/WXP_startup.ogg
Labels: Content

#19749 Religions 1.1: silly conversions
  code/datums/religions.dm
  code/modules/admin/topic.dm
Labels: Content

#19685 Can now set radio filter on buttons
  code/game/machinery/airlock_control.dm
Labels: Content

#19812 THAT AIN'T BINARY
  code/modules/mob/mob_helpers.dm
Labels: Bug / Fix

#19814 re-adds the cult structure parent
  code/datums/gamemode/factions/legacy_cult/cult_structures.dm
Labels: Bug / Fix

#19786 Improves check-self-for-injuries
  code/modules/mob/living/carbon/carbon.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#19827 GPS fixes
  code/modules/telesci/gps.dm
  nano/templates/gps.tmpl
Labels: Bug / Fix, File Cleanup, Tweak, Unatomic

#19830 Fixes speedbreathing
  code/game/objects/items/weapons/tanks/tanks.dm
Labels: Bug / Fix, Hotfix

#19835 Updates all (relevant) references to gases to the proper defines
  code/ZAS/Plasma.dm
  code/controllers/subsystem/plant.dm
  code/datums/gamemode/role/vampire_role.dm
  code/game/gamemodes/vampire/vampire_powers.dm
  code/game/machinery/cryo.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/structures/transit_tubes.dm
  code/modules/components/ai/atmos.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/borer/egg.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/organs/internal/lungs/filter.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasco2.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasnitro.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasoxy.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasplasma.dm
  code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_gas.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: Bug / Fix, File Cleanup, Hotfix

#19838 Fixes lockers, etc. (very slowly) suffocating you
  code/modules/organs/internal/lungs/lung.dm
Labels: Bug / Fix, Hotfix

#19757 Foam Can't Cause 0K Gas (FFF31)
  code/game/objects/effects/effect_system.dm
Labels: Legacy Bug

#19850 Removed old cult/wizard files
  code/game/gamemodes/cult/talisman.dm
  code/game/gamemodes/cult/trash_machinery.dm
  code/game/gamemodes/wizard/soulstone.dm
Labels: File Cleanup

#19851 Remove code/__DEFINES/role_defines.dm and move its contents to right file
  __DEFINES/role_datums_defines.dm
  code/__DEFINES/role_defines.dm
  vgstation13.dme
Labels: File Cleanup

#19856 Fixes hella runtimes
  code/ZAS/_gas_mixture.dm
Labels: Runtime Log

#19860 ACTUALLY make secret mode dynamic mode
  code/controllers/configuration.dm
Labels: 100% tested

#19824 Ports radial menu improvements, adds radial menu to the Bunsen Burner
  __DEFINES/global.dm
  code/_onclick/hud/radial.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
  icons/mob/radial.dmi
Labels: ❤️ Quality of Life ❤️

#19864 MoMMi will now report round end/threat level.
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/gamemode.dm
Labels: Bug / Fix, Role Datums Issue

#19832 Format units helper proc
  code/__HELPERS/text.dm
Labels: System

#18759 Fixes some issues between code and pre-existing sprites
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/chemical.dmi
  icons/obj/drinks.dmi
  icons/obj/surgery.dmi
Labels: Bug / Fix, Sprites

#19867 re-adds lost drink sprites.
  icons/obj/drinks.dmi
Labels: Sprites

#19878 fixes missing vampire check
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix, Hotfix

#19826 Fixes Vampire things
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/vampire_faction.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/mind.dm
  code/modules/clothing/masks/stone.dm
  code/modules/medical/cloning.dm
  data/mode.txt
Labels: Bug / Fix

#19887 Removes highly classified exploit
  code/_onclick/click.dm
Labels: Exploitable
