Repository vgstation-coders/vgstation13, pull requests merged in 2018-05, with the labels that each got.

#18199 Stops cloning pods putting inaprovaline in vox
  code/modules/medical/cloning.dm
Labels: Tweak

#18111 Removes boss monsters from gold core reactions
  __DEFINES/global.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Balance

#18191 Ai can ping
  code/modules/mob/living/silicon/ai/emote.dm
  vgstation13.dme
Labels: Content

#17888 Firelock frame manipulation (construction/deconstruction)
  code/game/machinery/doors/firedoor.dm
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Balance, Content

#18129 Adds a Dorf religion.
  code/datums/religions.dm
Labels: Content

#18138 Add effects for xenobotany machine upgrades.
  code/modules/hydroponics/seed_machines.dm
Labels: Content, Update WIKI

#18101 We can rebuild him, we have the technology.
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/human_races/o_robot.dmi
Labels: Sprites

#18047 Adds the security cyborg N.O.I.R. and warden upgrades as Jewvend-excusive rare loot.
  __DEFINES/_macros.dm
  code/__HELPERS/icons.dm
  code/datums/ai_laws.dm
  code/game/machinery/deployable.dm
  code/game/objects/items/cookie_synth.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/modules/detectivework/detective_work.dm
  code/modules/mob/living/silicon/mommi/update_icons.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  icons/mob/robots.dmi
  icons/obj/card.dmi
  icons/obj/device.dmi
Labels: Content, Unatomic

#18021 Lazymov lawset.
  code/datums/ai_laws.dm
  code/game/objects/items/weapons/ai_modules/core.dm
  code/modules/research/designs/AI_modules.dm
Labels: Content

#18225 adds species introductions, for species with strange gameplay mechanics
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
Labels: Grammar / Formatting, ❤️ Quality of Life ❤️

#18218 Re-adds holodudes
  code/game/machinery/computer/HolodeckControl.dm
Labels: Content

#18221 better buildmode type selector
  code/WorkInProgress/buildmode.dm
Labels: ❤️ Quality of Life ❤️

#18203 adds game datums
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/machinery/computer/arcade/arcade_game.dm
  vgstation13.dme
Labels: Tweak

#18232 simple_animal combat now checks for shields
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackanimal.dm
  vgstation13.dme
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#18231 fixes attacking simple animals not being consistent with just about anything
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/gun.dm
Labels: Bug / Fix

#18209 adds lactose intolerance
  __DEFINES/global.dm
  __DEFINES/setup.dm
  code/game/dna/genes/vg_disabilities.dm
  code/game/gamemodes/setupgame.dm
  code/modules/client/preferences.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Content

#18240 Adminordrazine will now set rad_tick to 0
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#18238 fixes deconstruct_item not passing a mob to to_chat to
  code/modules/research/rdconsole.dm
Labels: Bug / Fix

#18224 sporemind
  __DEFINES/_macros.dm
  __DEFINES/setup.dm
  __DEFINES/stylesheet.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/say.dm
  goon/browserassets/css/browserOutput.css
Labels: Content, ❤️ Quality of Life ❤️

#18257 Fixed slime tiles slowing down slimes
  __DEFINES/_macros.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
Labels: Bug / Fix

#18253 Fixed wooden walls having no floor underneath them when destroyed
  code/game/turfs/simulated/walls_mineral.dm
Labels: Bug / Fix

#18250 Fixed dough spawning inside humans
  code/modules/reagents/reagent_containers/food/snacks/egg.dm
Labels: Bug / Fix

#18249 Removes global variables helper
  code/__HELPERS/globalaccess.dm
  code/controllers/garbage.dm
  code/modules/admin/verbs/SDQL_2/SDQL_2.dm
  tools/gen_globals.py
  vgstation13.dme
Labels: System

#18256 Fixed R&D server turning invisible when screwdriver'd
  code/modules/research/server.dm
Labels: Bug / Fix

#18239 moves a parenthesis
  code/game/atoms.dm
Labels: Bug / Fix

#18255 Removed mob icon from the examine text
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature Loss, Tweak

#18242 Make GPS coord listing always display the activated GPS first.
  code/modules/telesci/gps.dm
  nano/templates/gps.tmpl
Labels: UI, ❤️ Quality of Life ❤️

#18150 Bluespace bananas.
  code/__HELPERS/unsorted.dm
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/hydroponics/seeds.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/obj/items.dmi
  icons/obj/seeds.dmi
Labels: Content, Honk

#18263 ACTUALLY makes mobs' examine text not show the icon
  code/game/atoms.dm
  code/modules/mob/living/living.dm
Labels: Feature Loss, Tweak

#18266 Gets rid of the awkward and unintended Fist targeting menu
  code/modules/spells/targeted/fist.dm
Labels: Bug / Fix

#17937 Ports Vampire to role_datums.
  __DEFINES/planes+layers.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/vampire_faction.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/objectives/acquire_blood.dm
  code/datums/gamemode/objectives/protect_master.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/vampire_gamemode.dm
  code/game/gamemodes/vampire/vampire.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/clothing/masks/stone.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/spells/aoe_turf/blink.dm
  code/modules/spells/aoe_turf/conjure/bats.dm
  code/modules/spells/aoe_turf/glare.dm
  code/modules/spells/aoe_turf/screech.dm
  code/modules/spells/general/cloak.dm
  code/modules/spells/general/menace.dm
  code/modules/spells/general/rejuvenate.dm
  code/modules/spells/general/shapeshift.dm
  code/modules/spells/general/undeath.dm
  code/modules/spells/targeted/disease.dm
  code/modules/spells/targeted/enthrall.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
  code/modules/spells/targeted/hypnotise.dm
  code/modules/spells/vampire_helpers.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: I'M FUCKING DONE, Role Datums

#18269 Re-add write/readglobal procs
  __DEFINES/global.dm
Labels: System

#18228 simple animals now break the seemingly unbreakable tape
  code/WorkInProgress/Ported/policetape.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix

#18273 Fixes vaporizer infinitely looping on full mixing chamber
  code/game/machinery/atmoalter/vaporizer.dm
Labels: Bug / Fix, Hotfix

#18211 Adds the third horsemen of the apocalypse
  code/modules/virus2/effect/effect.dm
Labels: Content

#18222 Fixes mulebot pAI overlay not sticking
  code/game/machinery/bots/mulebot.dm
Labels: Bug / Fix, Sprites

#18274 Fixes grammar for insufficient stack material messages
  code/game/objects/items/stacks/stack.dm
Labels: Grammar / Formatting

#18290 Fixes MMIs becoming permablind
  code/modules/mob/living/carbon/brain/life.dm
Labels: Bug / Fix

#18294 Fixed not being able to remove camera bugs from simple_animals
  code/modules/mob/language.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix

#18277 role datums fixes and tweaks
  code/__HELPERS/_macros.dm
  code/controllers/configuration.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/malf.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/vampire_faction.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/mixed.dm
  code/datums/gamemode/objectives/protect_master.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/vampire_gamemode.dm
  code/datums/gamemode/wizard.dm
  code/game/gamemodes/gameticker.dm
  code/modules/admin/topic.dm
  vgstation13.dme
Labels: Role Datums, WiP

#18300 Fixed merch computer runtimes
  code/modules/store/store.dm
Labels: Bug / Fix

#18299 Fixed spiritbreaker being invisible
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#18297 Fixed butterfly knife runtime
  code/game/objects/items/weapons/butterfly.dm
Labels: Bug / Fix

#18298 Fixed /datum/wires/UpdateCut runtimes
  code/datums/wires/alarm.dm
  code/datums/wires/apc.dm
  code/datums/wires/camera.dm
  code/datums/wires/explosive.dm
  code/datums/wires/jukebox.dm
  code/datums/wires/mommi.dm
  code/datums/wires/particle_accelerator.dm
  code/datums/wires/rnd_wires.dm
  code/datums/wires/robot.dm
  code/datums/wires/syndicatebomb.dm
  code/datums/wires/transmitter.dm
  code/game/machinery/alarm.dm
  code/game/objects/items/devices/radio/intercom.dm
Labels: Bug / Fix

#18272 Fixes gas and temperature defines order of operations
  __DEFINES/atmos.dm
  __DEFINES/math_physics.dm
Labels: Legacy Bug, Needs Moar Testing, Unatomic, ⚠️ OH GOD IT'S LOOSE ⚠️

#18301 Fixes asteroid "dug" icon
  code/modules/mining/mine_turfs.dm
Labels: Bug / Fix

#18289 Refactors hardcoded cyborg quirk checks to flags
  __DEFINES/game.dm
  __DEFINES/global.dm
  __DEFINES/silicon.dm
  code/game/dna/dna_modifier.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/cryo.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/vending.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/medical/cloning.dm
  code/modules/mob/living/silicon/mommi/mommi_modules.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  vgstation13.dme
Labels: Tweak, Unatomic

#18303 Fixes radiation trying to ruin missing eyes.
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
Labels: Bug / Fix, Runtime Log

#18304 Changes bluespace fruits when not thrown.
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Bug / Fix

#18302 Tweaked isspecies defines
  __DEFINES/_macros.dm
Labels: System

#18307 pAI signup verb for ghosts
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/pai/recruit.dm
Labels: Tweak

#18275 Gameplay hint for shades
  code/game/gamemodes/wizard/soulstone.dm
  code/modules/mob/living/simple_animal/shade.dm
Labels: Grammar / Formatting, Unatomic, ❤️ Quality of Life ❤️

#18287 50% discount on Ring of Fire
  code/modules/spells/general/ring_of_fire.dm
Labels: Balance, Tweak

#18320 Correctly use defines for the nutriment reagent
  code/modules/fish/fish_items.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#18321 Changed the right arm size class to small
  code/modules/organs/organ_external.dm
Labels: Consistency Issue, Tweak

#18270 Fixes mein lieben still appearing and golden core reactions tweaks
  __DEFINES/global.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Balance, Bug / Fix, Unatomic

#18280 Adds manual frequency setpoint for headsets, station bounced radios, and intercoms
  code/game/objects/items/devices/radio/radio.dm
Labels: Tweak, UI

#18326 Fixes simple animal zero emote stings runtime
  code/modules/mob/living/simple_animal/hostile/wolf.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix, Tweak

#18323 Fixes almost all the bugs that I should have fixed six months ago
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/thermal_plate.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/he_pipes.dm
  code/ATMOSPHERICS/hvac/chiller.dm
  code/ATMOSPHERICS/hvac/spaceheater.dm
  code/WorkInProgress/Cael_Aislinn/Rust/core_field.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  code/ZAS/Fire.dm
  code/ZAS/_gas_mixture.dm
  code/game/machinery/alarm.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/atmoalter/gas_mine.dm
  code/game/machinery/atmoalter/pump.dm
  code/game/machinery/atmoalter/scrubber.dm
  code/game/machinery/overview.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/components/ai/atmos.dm
  code/modules/media/broadcast/transmitters/broadcast.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/alien/humanoid/life.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/complex/life.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/borer/egg.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/thermoregulation.dm
  code/modules/power/turbine.dm
  code/modules/projectiles/guns/projectile/constructable/blastcannon.dm
  code/modules/recycling/disposal.dm
  code/modules/research/server.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_affect_cold.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasco2.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasnitro.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasoxy.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasplasma.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gassleeping.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_heat.dm
  code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_gas.dm
  code/modules/research/xenoarchaeology/machinery/analysis_base.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: Bug / Fix

#18333 Fixes all those bugs but with 100% fewer NEW bugs
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/thermal_plate.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/ATMOSPHERICS/he_pipes.dm
  code/ATMOSPHERICS/hvac/chiller.dm
  code/ATMOSPHERICS/hvac/spaceheater.dm
  code/WorkInProgress/Cael_Aislinn/Rust/core_field.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  code/ZAS/Fire.dm
  code/ZAS/_gas_mixture.dm
  code/game/machinery/alarm.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/atmoalter/gas_mine.dm
  code/game/machinery/atmoalter/pump.dm
  code/game/machinery/atmoalter/scrubber.dm
  code/game/machinery/overview.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/components/ai/atmos.dm
  code/modules/media/broadcast/transmitters/broadcast.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/alien/humanoid/life.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/complex/life.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/borer/egg.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/thermoregulation.dm
  code/modules/power/turbine.dm
  code/modules/projectiles/guns/projectile/constructable/blastcannon.dm
  code/modules/recycling/disposal.dm
  code/modules/research/server.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_affect_cold.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasco2.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasnitro.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasoxy.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasplasma.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gassleeping.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_heat.dm
  code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_gas.dm
  code/modules/research/xenoarchaeology/machinery/analysis_base.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: 100% tested, Bug / Fix

#18317 Deletes contents of movable atoms on Destroy()
  code/game/atoms_movable.dm
Labels: Bug / Fix, System, ⚠️ OH GOD IT'S LOOSE ⚠️

#18337 Makes all reactions independent from the order ingredients are added
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content, Tweak, Unatomic, Update WIKI, ❤️ Quality of Life ❤️

#18342 Readds water recipe, changes sodium polyacrylate recipe to use water
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Tweak, Update WIKI

#18343 Fixed a thing with the singularity maybe?
  code/modules/power/singularity/singularity.dm
Labels: Bug / Fix

#18344 Better logging for singularity runtimes
  code/modules/power/singularity/singularity.dm
Labels: Runtime Log

#18347 Fixes plant air somewhat
  code/modules/hydroponics/hydro_tray_process.dm
Labels: Bug / Fix

#18348 Fixes signaler importing
  code/modules/assembly/signaler.dm
Labels: Bug / Fix

#18340 Can now akimbo pistols to fire both at once
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/akimbo.dm
  code/modules/projectiles/guns/projectile.dm
  vgstation13.dme
Labels: Content

#18336 Adds a rad_tick readout to bodyscans
  code/game/machinery/adv_med.dm
  code/modules/mob/living/simple_animal/borer/verbs_attached_chest.dm
Labels: Content

#18361 More readable body scan rad_tick readout
  code/game/machinery/adv_med.dm
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
  code/modules/mob/living/simple_animal/borer/verbs_attached_chest.dm
Labels: Tweak

#18354 Does absolutely nothing
  code/modules/admin/verbs/debug.dm
  code/modules/client/client procs.dm
Labels: File Cleanup, Secret repo conflict.

#18252 Removed O hotkey
  interface/interface.dm
  interface/skin.dmf
Labels: Feature Loss, Tweak

#18360 fixes glock caliber
  code/modules/projectiles/guns/projectile/pistol.dm
Labels: Bug / Fix

#18365 Fixes invisible lattices planes problem
  code/game/objects/effects/effect_system.dm
  code/modules/mining/mine_turfs.dm
Labels: Bug / Fix

#18376 Emote runtime with hivelord broods
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Runtime Log

#18374 Fixed mech GC runtimes
  code/datums/helper_datums/events.dm
  code/game/mecha/mecha.dm
Labels: Bug / Fix, Runtime Log

#18378 Removed warning for null values passed to isSmoothableNeighbor
  code/game/smoothwall.dm
Labels: Logging / Administration

#18379 Fixed test_tiny minimap runtimes
  code/modules/html_interface/map/station_map.dm
Labels: Bug / Fix, Runtime Log

#18381 Fixed annoying shit
  code/modules/RCD/schematics/pipe.dm
Labels: Bug / Fix

#18390 Fixes the intercom icon not updating properly.
  code/game/objects/items/devices/radio/radio.dm
Labels: Bug / Fix

#18358 Made the centcomm order event actually have a chance to start
  code/modules/events/event_dynamic.dm
Labels: Content

#18362 Beretta action: Electric boogaloo
  code/game/gamemodes/wizard/rightandwrong.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/obj/beretta.dmi
Labels: Content

#18369 Restores PKA charge indicator
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/special.dm
  icons/obj/gun.dmi
Labels: Content

#18352 Player preferences can be edited during server start-up
  __DEFINES/global.dm
  __DEFINES/subsystem.dm
  code/controllers/subsystem/init/finishing.dm
  code/controllers/subsystem/init/genetics.dm
  code/controllers/subsystem/init/humans.dm
  code/game/gamemodes/setupgame.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
  vgstation13.dme
Labels: System

#18329 Unit testing
  .travis.yml
  code/controllers/mc/master.dm
  code/game/gamemodes/gameticker.dm
  code/modules/error_handler/error_handler.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
  code/modules/unit_tests/unit_test.dm
  code/world.dm
  tools/travis/build.py
  tools/travis/config/config.txt
  tools/travis/run_tests.py
  tools/travis/travis_utils.py
  vgstation13.dme
Labels: System

#18353 Doppelganger tweaks/nerfs
  code/modules/mob/living/simple_animal/hostile/human/wizard.dm
  code/modules/spells/aoe_turf/conjure/doppelganger.dm
Labels: Balance

#18395 Unbind the O key in hotkeymode so it can be used for macros
  interface/skin.dmf
Labels: System

#18367 Noreact spray bottle
  code/modules/reagents/reagent_containers/spray.dm
  icons/obj/janitor.dmi
Labels: Content
