Repository vgstation-coders/vgstation13, pull requests merged in 2018-11, with the labels that each got.

#20447 Doorcrushing No Longer Creates a Forcefield Around You
  code/game/machinery/doors/airlock.dm
Labels: Balance, Bug / Fix, Unatomic

#20527 fixes viruses constantly re-infecting people who should be immune
  code/modules/virus2/helpers.dm
Labels: Bug / Fix

#20528 Misc virology fixes
  code/modules/virus2/disease2.dm
  code/modules/virus2/effect/effect.dm
Labels: Bug / Fix

#20525 Hot pumpkin!
  code/modules/hydroponics/grown_inedible.dm
  code/modules/spells/targeted/pumpkinhead.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Content

#20536 🤔
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/pai/software.dm
  icons/obj/pda.dmi
Labels: Content, System, Unatomic

#20004 Blacksmithing 2
  __DEFINES/_macros.dm
  __DEFINES/math_physics.dm
  __DEFINES/reagents.dm
  code/WorkInProgress/MadmanMartian/blacksmithing/anvil.dm
  code/WorkInProgress/MadmanMartian/blacksmithing/blacksmithing.dm
  code/WorkInProgress/MadmanMartian/blacksmithing/forge.dm
  code/WorkInProgress/MadmanMartian/blacksmithing/misc_components.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/objs.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mining/materials.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/reagent_containers.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/blacksmithing.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/items.dmi
  icons/obj/misc_components.dmi
  icons/obj/weapons.dmi
  sound/items/hammer_strike.ogg
  vgstation13.dme
Labels: Content, Update WIKI

#20455 Fixed latespawning wheelchairs
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix, Secret repo conflict.

#19904 Can now examine while inside things
  code/modules/mob/mob.dm
Labels: Bug / Fix

#20552 Removed chain recipe
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Hotfix

#20548 Can now load an orebox onto the gigadrill
  code/game/objects/structures/vehicles/gigadrill.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#20472 Revert "Taser/Egun projectile nerf" as promised
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy.dm
Labels: Balance, Bleeding-Edge Experiment, ✋ Do Not Merge ✋

#20557 Removes the vicinity check from dorfify
  code/game/objects/objs.dm
Labels: Hotfix

#20546 Actually implements legacy bans this time
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Role Datums Issue

#20544 Removes the encouragement for admins to recall the shuttle.
  code/game/machinery/computer/communications.dm
Labels: Logging / Administration

#20542 Yet more hostile mob door opening fixes
  code/game/machinery/doors/airlock.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix, 🚓Fun Police🚓

#20532 Tasing and shooting borgs temporarily slows them down: episode 2
  __DEFINES/silicon.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
Labels: Balance

#20545 Fixes custom objectives for factions
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/objectives/objective.dm
  code/datums/gamemode/role/role.dm
  code/datums/mind.dm
Labels: Role Datums Issue

#20494 Freeform objectives, fifth time's the charm
  __DEFINES/setup.dm
  code/datums/gamemode/objectives/freeform.dm
  code/datums/gamemode/objectives/freeform/changeling.dm
  code/datums/gamemode/objectives/freeform/syndicate.dm
  code/datums/gamemode/objectives/freeform/vampire.dm
  code/datums/gamemode/objectives/freeform/wizard.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/role/vampire_role.dm
  vgstation13.dme
Labels: Bleeding-Edge Experiment, Role Datums, Tweak

#20580 Fixes stuff with vampire.
  code/datums/mind.dm
  code/modules/spells/general/rejuvenate.dm
  code/modules/spells/targeted/hypnotise.dm
Labels: Bug / Fix, Gameplay / Gamemode, Role Datums

#20564 Raises lasercannon damage (40->60)
  code/modules/projectiles/projectile/beams.dm
Labels: Balance

#20559 Makes drilling mechs automatically defuse gibtonite
  code/game/mecha/equipment/tools/tools.dm
  code/modules/mining/mine_turfs.dm
Labels: ❤️ Quality of Life ❤️

#20586 Fixes an href exploit with uplinks.
  code/game/objects/items/devices/uplinks.dm
Labels: Exploitable, T-Thanks BYOND

#20587 Properly fixes the fabricator problem
  code/datums/statistics/stat_helpers.dm
  code/game/jobs/job_objectives/science.dm
  code/modules/research/fabricators.dm
  code/modules/research/mechanic/reverse_engine.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
  code/modules/research/server.dm
Labels: 100% tested, Bug / Fix

#20471 Adds the (lesser) predicted potion bundles for wizards.
  code/game/gamemodes/wizard/artifacts.dm
  code/game/objects/items/weapons/storage/bags.dm
Labels: Balance, Content, Update WIKI

#20613 Turns out humans are bad at sorting
  vgstation13.dme
Labels: File Cleanup

#20605 Antag laz belt can no longer spawn blacklisted/boss mobs
  code/game/objects/items/weapons/storage/belt.dm
Labels: 🚓Fun Police🚓

#20589 Preferences subsection datums, new organ menu
  code/modules/client/preferences.dm
  code/modules/client/preferences/subsections.dm
  code/modules/client/preferences/subsections/limbs.dm
  code/modules/client/preferences/subsections/organs.dm
  vgstation13.dme
Labels: System, UI

#20588 Ointment, Plastic Solidification, Recycled nutrition cube fixed to work with plantchems
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#20627 Bruschetta fixes
  code/modules/food/recipes_microwave.dm
Labels: Bug / Fix, Update WIKI

#20584 Caramel Food
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/food_condiment.dmi
Labels: Content, Update WIKI

#20583 Fixes double thralls
  code/datums/gamemode/role/vampire_role.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Role Datums Issue

#20612 Fixes Soap Reaction
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#20631 Fixes double emotes
  code/datums/emotes.dm
  code/modules/mob/emote.dm
Labels: 100% tested, Bug / Fix

#20633 Fixed closets taking turf contents on non-roundstart creation
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Bug / Fix

#20616 Adds forge construction
  code/WorkInProgress/MadmanMartian/blacksmithing/forge.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Content

#20609 Organ poking, biocharger (cybernetic heart sidegrade)
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
  code/modules/organs/blood.dm
  code/modules/organs/internal/heart/heart.dm
  code/modules/organs/internal/kidney/filter.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_internal.dm
  code/modules/organs/organ_objects.dm
  icons/obj/surgery.dmi
  vgstation13.dme
Labels: Content

#20608 Adds two new levels of power cell
  code/game/objects/items/weapons/power_cells.dm
  code/modules/research/designs/engineering.dm
  icons/obj/power.dmi
Labels: Content

#20623 Lockboxes can now be opened with an alt-click or with a PDA swipe.
  code/game/objects/items/weapons/storage/lockbox.dm
Labels: ❤️ Quality of Life ❤️

#20641 Legacy cult runtimes
  code/datums/gamemode/factions/legacy_cult/cult.dm
Labels: Runtime Log

#20638 Clicking 'view available personalities' on the pAI card will close the window
  code/game/objects/items/devices/paicard.dm
Labels: Tweak

#20654 Fixes a typo with the autolathe
  code/game/machinery/autolathe.dm
Labels: Grammar / Formatting

#20656 Small vamp fixes
  code/modules/spells/general/rejuvenate.dm
  code/modules/spells/general/undeath.dm
Labels: Bug / Fix, Grammar / Formatting

#20558 All i wanted was to add brass windoors but i ended tweaking windoor code.
  code/__HELPERS/clockwork.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/structures/windoor_assembly.dm
  icons/effects/effects.dmi
  icons/obj/doors/door_clockwork.dmi
  icons/obj/doors/windoor.dmi
Labels: Content, Unatomic, Update WIKI

#20665 Re-implements stun nerf after poll succeeded
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy.dm
  html/changelogs/stun.yml
Labels: Ready to Merge

#20660 Adds logs and planks to the forge potential fuels
  code/WorkInProgress/MadmanMartian/blacksmithing/forge.dm
Labels: Content

#20650 Adds jackboots to the cursed dice nazi uniform
  code/game/objects/items/weapons/dice.dm
Labels: Tweak

#20653 MoMMI Spaghetti is now grey and has BIG FLASHING LIGHTS
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Sprites

#20672 These are (what I believe) to be causing server crashes
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/game/mecha/combat/marauder.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, 🚓Fun Police🚓

#20676 Un-removes Juggernaut/Marauder dash, and "properly" fixes server-crashing bug, and also several related minor bugs
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/mecha.dm
  code/game/objects/structures/grille.dm
Labels: Bug / Fix

#20667 Some outsider looks on bloodcult polishing
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_projectiles.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/faction.dm
Labels: Bug / Fix

#20679 Blood Cult (v.3.0.1) - Balance Update
  code/_onclick/hud/_defines.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/helper_datums/command_alerts.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/simple_animal/shade.dm
Labels: Balance, Tweak

#20680 Fixes typo in CentComm payroll update
  code/modules/Economy/Wages.dm
Labels: Bug / Fix, Grammar / Formatting

#20625 Buffs the pAI health reading.
  code/modules/mob/living/silicon/pai/software.dm
Labels: Balance, ❤️ Quality of Life ❤️

#20685 More Cult Fixes
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/cultist.dm
Labels: Bug / Fix, Hotfix

#20689 Blacksmithing recipe refactoring
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Tweak

#20686 Fixes cookie writing
  goon/browserassets/js/browserOutput.js
Labels: Bug / Fix, T-Thanks BYOND

#20629 Adds sprites and function for BSmatterbins when used with the SStunneler.
  code/modules/projectiles/guns/projectile/constructable/subspacetunneler.dm
  icons/obj/weaponsmithing.dmi
Labels: Balance, Sprites

#20697 Turns off skeleblob as the default look for blobs.
  code/game/gamemodes/blob/blobs/factory.dm
  code/game/gamemodes/blob/blobs/node.dm
  code/game/gamemodes/blob/blobs/resource.dm
  code/game/gamemodes/blob/blobs/shield.dm
  code/game/gamemodes/blob/theblob.dm
Labels: Tweak

#20699 Renames iron powder back to iron
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#20704 Cult counts warden as enemy, removed double chaplain entry
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix

#20695 Fixed roidstation being a special snowflake
  code/ATMOSPHERICS/pipe_defines_for_mapping.dm
  code/game/area/Space Station 13 areas.dm
  maps/roidstation.dm
  maps/roidstation/areas.dm
  maps/roidstation/pipes.dm
Labels: Bug / Fix, System

#20717 Comments out dorfify icon operations
  code/game/objects/objs.dm
Labels: Hotfix

#20700 Fixes the player panel
  code/modules/admin/admin.dm
Labels: Bug / Fix

#20696 Vending machines always display ads so the buttons don't jump and down
  code/game/machinery/vending.dm
Labels: ❤️ Quality of Life ❤️

#20714 Fixes stubborn windoors
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/windoor_assembly.dm
Labels: Bug / Fix, Runtime Log

#20722 Fixed nano UI windows not opening and more
  __DEFINES/setup.dm
  code/__HELPERS/unsorted.dm
  code/modules/nano/nanoui.dm
Labels: Bug / Fix

#20723 Removed debug message from preferences saving
  code/modules/client/preferences.dm
Labels: System

#20725 20181116 c ult f ixes
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix

#20727 Remove debug statement from onclose()
  code/__HELPERS/unsorted.dm
Labels: File Cleanup

#20688 More blacksmithing tweaks
  code/WorkInProgress/MadmanMartian/blacksmithing/blacksmithing.dm
  code/WorkInProgress/MadmanMartian/blacksmithing/misc_components.dm
  code/game/objects/objs.dm
Labels: Bug / Fix, Tweak

#20736 Fixes being stuck unconscious when sleeping&resting
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
Labels: Oversight

#20738 Fixed being able to use Cult 3.0 runes that you shouldn't already have access to
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/game/objects/items/weapons/null_rod.dm
  code/modules/library/lib_items.dm
  icons/effects/96x96.dmi
Labels: Bug / Fix

#20684 Fixed breaking any bones removing restraints.
  __DEFINES/limb_defines.dm
  code/modules/organs/organ_external.dm
Labels: Bug / Fix

#20730 Clockwork Airlocks, Brass/Ralloy recipe tweaks
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/structures/door_assembly.dm
  icons/obj/doors/door_assembly.dmi
  icons/obj/doors/door_clockwork.dmi
Labels: Content, Tweak

#20757 Body scanners show how much bones have been strengthened
  code/game/machinery/adv_med.dm
Labels: Content

#20761 Fixed emitters doing nothing to freezers
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
Labels: Bug / Fix

#20497 Dejunks the health analyzer display
  code/game/objects/items/devices/scanners.dm
Labels: Tweak

#20770 Should disable the die objective being rolled if you also have to steal something
  code/datums/gamemode/role/syndicate.dm
Labels: Bug / Fix, T-Thanks BYOND

#20647 Adds Officer Britsky
  code/game/machinery/bots/secbot.dm
  icons/obj/aibots.dmi
Labels: Content

#20615 Adds a basic chemistry supply pack
  code/datums/supplypacks.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Content, Update WIKI

#20779 change_base_turf uses CHECK_TICK
  maps/_map.dm
Labels: Performance

#20659 Adds Test_empty
  maps/test_empty.dm
  maps/test_empty.dmm
Labels: why

#20777 adds fat sprites for chainmail and in-hands for hammers.
  code/game/objects/items/weapons/weaponry.dm
  icons/mob/in-hand/left/newsprites_lefthand.dmi
  icons/mob/in-hand/right/newsprites_righthand.dmi
  icons/mob/suit_fat.dmi
Labels: Sprites

#20799 Fixes not being able to flip windoors when constructing them
  code/game/objects/structures/windoor_assembly.dm
Labels: Bug / Fix

#20798 potentially maybe perhaps possibly actually fix the nanoui bug
  code/modules/nano/nanoui.dm
Labels: Bug / Fix

#20769 adds leather aprons to anvil crates.
  code/datums/supplypacks.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Content

#20804 Fixed grille attack message
  code/game/objects/structures/grille.dm
Labels: Bug / Fix

#20780 Remove remnant of old multi-z in ChangeTurf
  code/game/turfs/turf.dm
Labels: File Cleanup

#20731 Unpowered smartfridges can be deconstructed
  code/game/machinery/kitchen/smartfridge.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#20745 Necromancy staff tweaks
  code/modules/projectiles/guns/energy/special.dm
Labels: Tweak

#20803 Smooth movement for spacepods
  code/WorkInProgress/pomf/spacepods/spacepods.dm
Labels: Tweak

#20762 Xenoarch digsite overhaul
  __DEFINES/archaeo_defines.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/research/xenoarchaeology/finds/digsites.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
  code/modules/research/xenoarchaeology/geosample.dm
  code/modules/research/xenoarchaeology/misc.dm
  code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
  vgstation13.dme
Labels: System

#20801 Possibly fix voting
  code/__HELPERS/files.dm
Labels: Bug / Fix

#20611 Glass recipe refactor
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/tiles/tiles.dm
  code/game/objects/structures/grille.dm
  icons/obj/items.dmi
Labels: File Cleanup, Update WIKI

#20366 Removes ling general stings, adds ling chemsting and chemspit
  code/__HELPERS/unsorted.dm
  code/datums/gamemode/objectives/sample.dm
  code/datums/gamemode/role/changeling.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/modules/mob/living/simple_animal/hostile/necromorph.dm
  code/modules/reagents/Chemistry-Reagents.dm
  vgstation13.dme
Labels: Balance, Gameplay / Gamemode, Tweak

#20771 When a borg is traitor removed, it removes the zeroth law
  code/datums/gamemode/role/syndicate.dm
Labels: Role Datums Issue

#20807 Plant, gadgets and mining bags show numbers in their inventory
  code/game/objects/items/weapons/storage/bags.dm
Labels: UI

#20758 Fixed degenerate calcium affecting robotic or peg limbs
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Muh Immulsions

#20812 transfer_fingerprints also transfers fibers
  code/__HELPERS/unsorted.dm
Labels: Bug / Fix

#20524 Refactors role interactions with reagents
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/legacy_cultist.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Role Datums, System

#20825 Ported ERP mechanics from vorestation
  code/game/dna/genes/goon_powers.dm
Labels: Grammar / Formatting

#20822 Fixed holodeck runtimes and nonsense
  __DEFINES/global.dm
  code/__HELPERS/unsorted.dm
Labels: Bug / Fix, Runtime Log

#20829 Admin teleportation of things is now logged.
  code/datums/datumvars.dm
Labels: Logging / Administration

#20827 Lawgiver refactor, added new mode for demolition variant
  __DEFINES/weapons.dm
  code/__HELPERS/angles_dirs.dm
  code/game/machinery/recharger.dm
  code/game/objects/items.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/lawgiver.dm
  code/modules/projectiles/projectile/energy.dm
  sound/weapons/alien_laser1.ogg
  sound/weapons/alien_laser2.ogg
Labels: Content, File Cleanup, Unatomic

#20796 Ammo pouch
  code/game/machinery/biogenerator.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/storage/bags.dm
  icons/obj/storage/storage.dmi
Labels: Content

#20805 Security cameras can be hit with tools to destroy them
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/camera_assembly.dm
Labels: Balance

#20824 hair/facial hair/eye color preferences input remembers your previous choice
  code/game/objects/items/weapons/cosmetics.dm
  code/modules/client/preferences.dm
Labels: ❤️ Quality of Life ❤️

#20694 Mythril
  __DEFINES/math_physics.dm
  __DEFINES/setup.dm
  code/WorkInProgress/MadmanMartian/blacksmithing/blacksmithing.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/mining/materials.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/minerals.dm
  code/modules/mining/ores_coins.dm
  maps/randomvaults/mining/angie_lair.dmm
Labels: Content

#20846 Fixes assassinate picking SoC mobs that now no longer exist
  code/datums/gamemode/objectives/target/assassinate.dm
Labels: Bug / Fix

#20853 Fixes everything being bullets
  code/__HELPERS/unsorted.dm
Labels: Bug / Fix, Hotfix

#20855 Minor XGM changes
  __DEFINES/gases.dm
  code/ZAS/XGM.dm
  code/ZAS/XGM_gases.dm
  code/ZAS/_gas_mixture.dm
  vgstation13.dme
Labels: Bug / Fix, File Cleanup, Runtime Log

#20821 Makes the bunsen burner hold more fuel
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: Tweak

#20831 Fixes viro incubator getting toxins incorrectly
  code/modules/virus2/dishincubator.dm
Labels: Bug / Fix

#20870 Probably fixes breaches not draining
  code/ZAS/Zone.dm
Labels: Bug / Fix

#20818 Fixes 'global' windows xp startup
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Bug / Fix, 🚓Fun Police🚓

#20562 Adds the projectile resistant quirk for Combat/Syndie Modules
  __DEFINES/silicon.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance

#20790 Fixes modules without CAN_HANDLE_CHEMS/FOOD being able to use chem dispensers
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Bug / Fix

#20817 Crafted windows now start unanchored again
  code/game/objects/items/stacks/sheets/glass.dm
Labels: Tweak

#20835 Shotgun speedloader
  code/game/machinery/autolathe.dm
  code/modules/projectiles/ammunition/speedloaders.dm
  icons/obj/ammo.dmi
Labels: Content
