Repository vgstation-coders/vgstation13, pull requests merged in 2019-01, with the labels that each got.

#21185 Blank talisman fix
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
Labels: Bug / Fix

#21181 Unatomic spell tweaks
  __DEFINES/spell_defines.dm
  code/datums/gamemode/role/role.dm
  code/modules/mob/spells.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/spells/aoe_turf/fall.dm
  code/modules/spells/spell_code.dm
  code/modules/spells/targeted/fist.dm
Labels: Gameplay / Gamemode, Tweak, Unatomic, 🚓Fun Police🚓

#21140 Chemmaster can slurp from nearby reagent dispensers and buckets
  code/__HELPERS/angles_dirs.dm
  code/modules/reagents/machinery/chem_master.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#21153 Credits use [audio] instead of world <<
  __DEFINES/global.dm
  code/game/gamemodes/scoreboard.dm
  code/game/machinery/bots/buttbot.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/credits/credit_disclaimers.dm
  code/modules/credits/credits.dm
  code/modules/credits/credits.html
  code/modules/credits/episode_name.dm
  code/modules/spells/targeted/buttbots_revenge.dm
  code/modules/spells/targeted/push.dm
  code/modules/spells/targeted/shoesnatch.dm
  code/modules/virus2/effect/effect.dm
Labels: Tweak

#21182 Fixed typos in the weeb katana description.
  code/game/objects/items/weapons/weaponry.dm
Labels: Grammar / Formatting, Hotfix

#21183 Adds extra important keywords to the Murdercube religions
  code/datums/religions.dm
Labels: Consistency Issue

#21187 Fix vendomat packs allowing nuke disks in containers
  code/game/machinery/vending_packs.dm
Labels: Bug / Fix, Tweak

#21189 Fix typo in stacks screen
  code/game/objects/items/stacks/stack.dm
Labels: Bug / Fix, Grammar / Formatting

#21208 Tweaks the Sokoban puzzle
  maps/randomvaults/sokoban.dm
Labels: Grammar / Formatting

#21192 Nothing heals mimes slightly.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance

#21209 Fixes laser cannons not having a fire delay
  code/modules/projectiles/guns/energy/laser.dm
Labels: 100% tested, Bug / Fix, Easy Fix

#21203 Custom shuttles fixes
  code/datums/shuttle.dm
  code/game/machinery/computer/shuttle_computers.dm
  code/game/objects/items/blueprints.dm
  code/game/shuttle_engines.dm
  code/game/shuttles/salvage.dm
Labels: Bug / Fix

#21128 Adds rule weighting
  code/datums/fuzzy_rules.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  vgstation13.dme
Labels: Tweak

#21156 Fixes a goof in the magnetic gripper upgrade
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Oversight

#21175 Holding a security knife actually makes you faster.
  code/game/objects/items/weapons/weaponry.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: 100% tested, Bug / Fix, Consistency Issue, ❤️ Quality of Life ❤️

#21211 Fixes the Honk Baton in-hands
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/swords_axes.dmi
Labels: Bug / Fix

#21201 Adds a suit for the Gumshoe alt-title
  code/game/jobs/job/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/species/grey/uniform.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
  icons/mob/uniform.dmi
Labels: Content

#21210 Lowers the Lawgiver's laser damage back to 40
  code/modules/projectiles/guns/lawgiver.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Balance

#21220 Fixes a runtimes in fuzzy rulings
  code/datums/fuzzy_rules.dm
Labels: Runtime Log

#21215 Fixes Time Stop's upgrade text
  code/modules/spells/aoe_turf/fall.dm
Labels: Grammar / Formatting

#21237 Mining dex check feedback fix
  code/modules/mining/mine_turfs.dm
Labels: Bug / Fix

#21219 Various Grinch tweaks and fixes
  code/modules/mob/living/simple_animal/hostile/grinch.dm
Labels: Balance, Bug / Fix

#21239 glowshroom / grass weeds
  code/modules/hydroponics/hydro_tray.dm
Labels: Tweak

#21234 Adjusts the E/W sprites for open labcoats
  icons/mob/custom/N3X15/suits.dmi
  icons/mob/suit.dmi
Labels: Sprites

#21228 Makes the MaMI's welcome message consistent
  code/modules/mob/living/carbon/brain/MaMI.dm
Labels: Grammar / Formatting

#21216 Whispering in crit makes you succumb again
  code/game/gamemodes/changeling/changeling_powers.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/alien/humanoid/death.dm
  code/modules/mob/living/carbon/alien/larva/death.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/monkey/death.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#21179 Weeb antag is now more likely to roll on higher populations.
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Discussion, Gameplay / Gamemode, Role Datums

#21233 Changes "Secondary Language" in character setup to "Tertiary Language"
  code/modules/client/preferences.dm
Labels: Grammar / Formatting

#21242 Did stuff! did other stuff! - The default changelog is no longer in a comment so collabs know to remove it if it's still there
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bug / Fix, Grammar / Formatting, Needs Changelog

#21244 Aaaah
  code/modules/mob/living/simple_animal/hostile/grinch.dm
Labels: Hotfix

#21248 Xenoarch gun desc
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Bug / Fix

#21246 Stops eye_blurry goind down while eye_blind is >0
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
Labels: Oversight

#21225 Adds an alt+click toggle to the Field Suspension Generator
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
Labels: ❤️ Quality of Life ❤️

#21270 Fixes a compile warning
  code/modules/spells/aoe_turf/fall.dm
Labels: Bug / Fix

#21277 Fixes this typo, was very hard to find.
  code/game/gamemodes/wizard/spellbook.dm
  code/game/machinery/vending.dm
Labels: Easy Fix

#21274 Fixes missing novaflower dead icon.
  code/modules/hydroponics/seeds.dm
  icons/obj/hydroponics2.dmi
Labels: Bug / Fix, Sprites

#21289 Fixes being able to make any reagent into ointment
  code/datums/recipe.dm
Labels: Bug / Fix

#21275 Ports grass clumps from /tg/
  code/modules/hydroponics/seeds.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/obj/harvest.dmi
Labels: Bug / Fix, Sprites

#21291 Eimplants didn't go off if you died without succumbing
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
Labels: Bug / Fix, Needs Changelog

#21286 Adds NO_LOBBY_MUSIC config
  code/controllers/configuration.dm
  code/game/sound.dm
  config-example/config.txt
Labels: ❤️ Quality of Life ❤️

#21292 Fixes seedify helper proc dropping items
  code/__HELPERS/unsorted.dm
Labels: Bug / Fix

#21293 fixes a few instances of showing antag on key_name() where it shouldn't
  code/ZAS/NewSettings.dm
  code/__HELPERS/unsorted.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/mob/logout.dm
Labels: Bug / Fix, Logging / Administration

#21184 Bacteria, Virii, and Parasites
  code/datums/supplypacks.dm
  code/game/machinery/computer/medical.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/virus2/analyser.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/diseasesplicer.dm
  code/modules/virus2/dishincubator.dm
  code/modules/virus2/helpers.dm
  code/modules/virus2/items_devices.dm
Labels: Content, Tweak, Update WIKI

#21256 Turns traitor job-exclusive items to job-discounted items (can buy tator items of any job by paying extra)
  code/datums/uplink_item.dm
  code/defines/obj/weapon.dm
  code/game/objects/items/devices/uplinks.dm
Labels: Balance, Bug / Fix, Tweak, Unatomic

#21250 Spiders unscrewed
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/hunter.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/nurse.dm
Labels: Bug / Fix, 🚓Fun Police🚓

#21252 Bloodcult sacrifice target can't be a cultist anymore
  code/datums/gamemode/objectives/bloodcult.dm
Labels: Balance, Tweak

#20617 Prestidigitation bundle
  code/game/gamemodes/wizard/artifacts.dm
  code/modules/spells/targeted/prestidigitation.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Content, Update WIKI

#21178 Grenade timer tweaking tweaking
  code/game/objects/items/weapons/grenades/grenade.dm
Labels: Balance, Bleeding-Edge Experiment, Tweak, 🚓Fun Police🚓

#21321 Black mouse inhands/onhead sprite (SBO34)
  code/modules/mob/living/holders.dm
  icons/mob/head.dmi
  icons/mob/in-hand/left/mob_holders.dmi
  icons/mob/in-hand/right/mob_holders.dmi
Labels: Bug / Fix, Sprites

#21322 Fixes a bad
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#21308 Adds mapping debug to check for disconnected wires
  code/modules/admin/verbs/mapping.dm
Labels: Mapping (General :world_map:), System

#21259 Mid round rulesets refactor
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/role/syndicate.dm
  code/modules/mob/mob.dm
Labels: Role Datums

#21326 Adds pre-warning to immovable rod event
  code/datums/helper_datums/command_alerts.dm
  code/modules/events/immovablerod.dm
Labels: Balance

#21320 Unsnowflake Assistants (SBO33)
  code/modules/client/preferences.dm
Labels: ❤️ Quality of Life ❤️

#21170 Allows Grilling in Space (SBO28)
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/structures/grille.dm
Labels: Bug / Fix

#21364 fixes WATCH ram (SBO36)
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/robot/robot_items/robot_implanter.dm
Labels: Bug / Fix, Unatomic

#21255 Make tomes improve rune-writing even while closed.
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
Labels: Balance

#21381 Adds target_rules to the resetVariables function
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix

#21382 Fixes rogue rulesets
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Bug / Fix, Role Datums

#21389 Can now set PDA ringtone while in a locker
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Balance, Bug / Fix

#21388 Ram Fixes
  code/defines/obj/weapon.dm
  code/game/machinery/doors/airlock.dm
  icons/obj/weapons.dmi
Labels: Bug / Fix, Sprites

#21356 department messenger bags
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
Labels: Content

#21332 Fixed Nar-Sie rising in nullspace if the anchor blood stone got destroyed during Act IV
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/objectives/bloodcult.dm
Labels: Bug / Fix, Gameplay / Gamemode

#21338 Gives paramedics full morgue access
  code/game/jobs/job/paramedic.dm
Labels: Tweak

#21411 Adds the door onopen signal wire
  code/datums/wires/airlock.dm
  code/datums/wires/wires.dm
  code/game/machinery/doors/airlock.dm
Labels: Content

#21358 Nerfs health of all types of Windoor
  code/game/machinery/doors/windowdoor.dm
Labels: Balance, Tweak, ❤️ Quality of Life ❤️

#21393 Adds inflatable floors
  code/game/objects/structures/inflatable.dm
  code/game/turfs/simulated/floor_inflatable.dm
  icons/obj/inflatable.dmi
  vgstation13.dme
Labels: Content

#21429 Fixes robot construction
  code/game/objects/items/robot/robot_parts.dm
Labels: Bug / Fix, Hotfix

#21344 Adds plantpot rustling sound
  code/game/objects/structures/flora/flora.dm
  sound/effects/plant_rustle.ogg
Labels: Balance, Content

#21283 Adds composting with plants
  code/modules/hydroponics/hydro_tray.dm
Labels: ❤️ Quality of Life ❤️

#21391 Syndicate Elite Squaddies's rifle now spawns in their backpack instead of in their active hand.
  code/game/striketeams/syndicate_elite_squad.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#21410 Door hacking additional feedback
  code/datums/wires/airlock.dm
Labels: Content

#21431 Grenades can now actually be primed at 3 seconds
  code/game/objects/items/weapons/grenades/grenade.dm
Labels: Bug / Fix, Muh Immulsions

#21432 Adds permanent portals
  code/game/objects/effects/portals.dm
Labels: Content

#21434 Plasmamen don't get damaged from slurping plasma anymore
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Muh Immulsions, ❤️ Quality of Life ❤️

#21408 Adds a new method of ejecting something from a mecha
  code/game/mecha/mecha.dm
Labels: Content

#21464 Fixes Midround Weeb (SBO43)
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: 100% tested

#21438 [not WIP] credits3 return of credits [finished] dawn of the night of the credits client preferences [media server updated] return of APC destroyed [does the things] [notice me]
  SQL/players2.sql
  __DEFINES/_macros.dm
  __DEFINES/global.dm
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  code/controllers/shuttle_controller.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
  code/game/machinery/computer/communications.dm
  code/game/objects/items/weapons/ai_modules/AI_modules.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/client/client defines.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/credits/credit_disclaimers.dm
  code/modules/credits/credits.dm
  code/modules/credits/credits.html
  code/modules/credits/credits_clientprocs.dm
  code/modules/credits/episode_name.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/migrations/SS13_Prefs/014-add-credits-pref.dm
  code/modules/migrations/SS13_Prefs/015-add-jingle_pref.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/spells/general/lightning.dm
  code/modules/spells/targeted/grease.dm
  code/modules/supermatter/supermatter.dm
  code/world.dm
  icons/credits/1zas.png
  icons/credits/2cluck.png
  icons/credits/3MPAOSA.png
  icons/credits/4_themed_NT.png
  icons/credits/4_themed_clown.png
  icons/credits/4_themed_cooks.png
  icons/credits/4_themed_syndie.png
  icons/credits/5BYOND.png
  sound/misc/RoundEndSounds/FTLvictory.ogg
  sound/misc/RoundEndSounds/apcdestroyed.ogg
  sound/misc/RoundEndSounds/bangindonk.ogg
  sound/misc/RoundEndSounds/bayojingle.ogg
  sound/misc/RoundEndSounds/calamitytrigger.ogg
  sound/misc/RoundEndSounds/castlevania.ogg
  sound/misc/RoundEndSounds/duckgame.ogg
  sound/misc/RoundEndSounds/gameoveryeah.ogg
  sound/misc/RoundEndSounds/marioworld.ogg
  sound/misc/RoundEndSounds/megamanX.ogg
  sound/misc/RoundEndSounds/rayman.ogg
  sound/misc/RoundEndSounds/slugmissioncomplete.ogg
  sound/misc/RoundEndSounds/soniclevelcomplete.ogg
  sound/misc/RoundEndSounds/sound help.txt
  sound/misc/RoundEndSounds/tfvictory.ogg
  sound/music/Frolic_Luciano_Michelini.ogg
  sound/music/Frolic_Luciano_Michelini_Short.ogg
  vgstation13.dme
Labels: Secret repo conflict.

#21369 Relax with the Chap
  code/modules/mob/living/carbon/human/human.dm
Labels: Muh Immulsions

#21324 Aghost Airlocks Made Silky Smooth (SBO35)
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/_onclick/observer.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/objects/objs.dm
Labels: Bug / Fix
