Repository vgstation-coders/vgstation13, pull requests merged in 2019-03, with the labels that each got.

#21886 Data Disk Inhand Sprites
  code/datums/uplink_item.dm
  code/defines/obj/weapon.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/medical/cloning.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  code/modules/virus2/diseasesplicer.dm
  code/modules/virus2/items_devices.dm
  icons/mob/in-hand/left/datadisks.dmi
  icons/mob/in-hand/right/datadisks.dmi
  icons/obj/cloning.dmi
  icons/obj/datadisks.dmi
  icons/obj/items.dmi
Labels: Sprites

#21898 Cult Balance of the Month - March 2019
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_tattoos.dm
  code/datums/gamemode/objectives/bloodcult.dm
  code/datums/gamemode/role/cultist.dm
  code/game/machinery/doors/mineral.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/simple_animal/shade.dm
  icons/mob/screen1_cult.dmi
  icons/mob/screen_spells.dmi
  icons/obj/cult.dmi
  icons/obj/cult_radial2.dmi
Labels: Balance, Gameplay / Gamemode

#21858 Fixes armor penetration and adds it to melee energy weapons
  code/game/objects/items.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/combat.dm
  code/modules/projectiles/projectile.dm
Labels: :up: Powercreep :up:, Update WIKI

#21562 Increases farsight range by one tile
  code/game/dna/genes/vg_powers.dm
Labels: Balance

#21803 Changes to the neo-soviet funk boots
  code/modules/clothing/shoes/magboots.dm
Labels: Tweak

#21742 Runtime hunting - Posters
  code/datums/gamemode/role/weeaboo.dm
  code/game/objects/items/mountable_frames/posters/poster.dm
Labels: Bug / Fix, Runtime Log

#21753 Local man makes firelocks 50% less annoying!
  code/game/machinery/doors/firedoor.dm
Labels: ❤️ Quality of Life ❤️

#21911 Improves Weeb QoL (SBO69-72)
  code/datums/gamemode/role/weeaboo.dm
  code/modules/client/preferences.dm
Labels: Bug / Fix, Content, Role Datums, Tweak, Unatomic Uncle

#21928 Fixes the fueltank rig overlay moving into the Nth dimension
  code/modules/reagents/reagent_dispenser.dm
Labels: Exploitable

#21931 adds an attack delay to blobs.
  code/game/gamemodes/blob/powers.dm
Labels: Bug / Fix

#21937 some small Cult fixes, QoL, and Sacrifice reroll rework
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/objectives/bloodcult.dm
  code/datums/gamemode/role/cultist.dm
Labels: Bug / Fix, Role Datums, Tweak, Unatomic Uncle

#21877 Moving all in-hand space suits and space helmets icons to a single dmi per hand
  code/modules/bomberman/bomberman.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig.dm
  icons/mob/in-hand/left/mining_suit.dmi
  icons/mob/in-hand/left/paramedic_eva.dmi
  icons/mob/in-hand/left/spacesuits.dmi
  icons/mob/in-hand/right/mining_suit.dmi
  icons/mob/in-hand/right/paramedic-eva.dmi
  icons/mob/in-hand/right/spacesuits.dmi
Labels: Sprites

#21909 Leafy Incense Clears Walk Command
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#21661 The Culling of ROLE_
  __DEFINES/setup.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/legacy_cult/cult.dm
  code/datums/gamemode/factions/legacy_cult/soulstone.dm
  code/datums/gamemode/factions/malf.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/factions/syndicate/traitor.dm
  code/datums/gamemode/factions/vampire_faction.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/grinch.dm
  code/datums/gamemode/role/legacy_cultist.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/role/weeaboo.dm
  code/datums/uplink_item.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items/changeling_vial.dm
  code/game/objects/items/robot/robot_items/robot_spawner.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/client/preferences.dm
  code/modules/events/meteors.dm
  code/modules/mob/living/carbon/brain/MMI.dm
Labels: File Cleanup

#21970 Fixing some long undetected blood issue
  code/game/objects/effects/decals/Cleanable/tracks.dm
  code/game/objects/effects/decals/cleanable.dm
Labels: Bug / Fix

#21885 changes a obscure interaction with cablecuffs and wirecutters
  code/game/objects/items/weapons/tools.dm
Labels: Needs Changelog, Tweak

#21856 Reduces attack delay on Bloodlust
  code/game/objects/items/weapons/twohanded.dm
Labels: :up: Powercreep :up:

#21855 Adds CUT_WALL and CUT_AIRLOCK flags, uses it in melee energy weapons
  __DEFINES/setup.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/walls.dm
Labels: :up: Powercreep :up:

#21782 Fixes ancient bugs with fire
  code/ZAS/Fire.dm
  code/ZAS/NewSettings.dm
  code/game/objects/effects/spawners/bombspawner.dm
  config-example/ZAS.txt
Labels: Bug / Fix, Legacy Bug, Needs Moar Testing, Secret repo conflict.

#21637 Adds rabbits and magic top hats.
  code/datums/helper_datums/butchering.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/game/machinery/vending.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/slime.dm
  code/modules/mob/living/simple_animal/hostile/slime.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/mob/clothing_accessories.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/accessory_overlays.dmi
Labels: Content, WiP

#21979 Re-adds the prisoner helmet to the suit storage unit
  code/game/machinery/suit_storage_unit.dm
Labels: Bug / Fix, Oversight

#21963 Cleaned Up Survivor Scoreboard
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/summonsurvivors.dm
  code/datums/gamemode/role/syndicate.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  vgstation13.dme
Labels: Bug / Fix

#21892 Adds a locking system for spacepods.
  code/WorkInProgress/pomf/spacepods/actions.dm
  code/WorkInProgress/pomf/spacepods/equipment.dm
  code/WorkInProgress/pomf/spacepods/pod_fabricator.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  code/__HELPERS/text.dm
  code/modules/research/designs/spacepod/weapons.dm
  icons/pods/ship.dmi
Labels: Content

#21955 Blob is less likely to roll at roundstart
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Balance, Gameplay / Gamemode, Tweak

#21965 Midround Blobstorm is now less likely to roll.
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Balance, Gameplay / Gamemode, Tweak

#21943 *TERMINATE* arrest setting.
  __DEFINES/security.dm
  code/game/data_huds.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/secbot.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/metaldetector.dm
  code/game/machinery/portable_turret.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_hud_list.dm
  icons/mob/hud.dmi
Labels: Tweak

#21896 Hulks and xenomorphs can unbuckle faster from being cuffed and buckled
  code/modules/mob/living/living.dm
Labels: Oversight

#21987 Allows you to set medical records to SSD from the console
  code/game/machinery/computer/medical.dm
Labels: Bug / Fix

#21974 ied-beartrap overlay and reference bugfix
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/grenades/ghettobomb.dm
  icons/obj/grenade.dmi
  icons/obj/items.dmi
Labels: Bug / Fix, Sprites, Unatomic Uncle

#21967 Adds tractor and carts to cargo
  code/datums/supplypacks.dm
Labels: :up: Powercreep :up:

#21962 MALF AIs now have a chance to roll midround with very low odds.
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Balance, Controversial, Gameplay / Gamemode, Tweak

#21980 Increases fire_fuel_energy_release again
  code/ZAS/NewSettings.dm
  code/game/objects/effects/spawners/bombspawner.dm
  config-example/ZAS.txt
Labels: Balance, Secret repo conflict.

#21938 Blob tweaks eternal.
  code/datums/gamemode/factions/blob.dm
  code/datums/gamemode/objectives/invade.dm
  code/datums/helper_datums/command_alerts.dm
  code/game/gamemodes/blob/blobs/core.dm
Labels: Bug / Fix, Content, Gameplay / Gamemode, Tweak, Unatomic Uncle

#21989 Fixed Dynamic Mode's combined starting ruleset costs sometimes exceeding its available threat
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Hotfix

#21961 Makes greys acid resistant more consistent, makes it into a define
  __DEFINES/setup.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: :up: Powercreep :up:, Consistency Issue, Controversial

#21960 Fixes chemistry recipe bug
  code/modules/reagents/Chemistry-Holder.dm
Labels: Bug / Fix

#21946 Cult actually requires enemies to fight
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Balance, Role Datums

#21665 Flavour lines for cultist conversion
  __DEFINES/game.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_flavourlines.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/game/jobs/jobs.dm
  vgstation13.dme
Labels: Content, Needs Review

#21687 Voice noises
  code/controllers/configuration.dm
  code/game/sound.dm
  code/modules/client/client procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/migrations/SS13_Prefs/016-add-voice.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/say.dm
  config-example/game_options.txt
  sound/misc/Vocal1.ogg
  sound/misc/Vocal2.ogg
  sound/misc/Vocal3.ogg
  sound/misc/Vocal4.ogg
  sound/misc/Vocal5.ogg
  vgstation13.dme
Labels: Content, why

#21998 The character preference window will now tell you what color your skin tone is instead of just a numerical value
  code/modules/client/preferences.dm
Labels: Tweak

#21852 Adds tier 4 stock parts
  code/game/objects/items/weapons/stock_parts.dm
  code/modules/mining/surprises/tg.dm
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  icons/obj/stock_parts.dmi
  icons/obj/weaponsmithing.dmi
Labels: :up: Powercreep :up:, Content

#21942 Cult reminders
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Tweak

#21986 Weeb to Ninja
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/weeaboo.dm
  code/game/objects/items/mountable_frames/posters/poster.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/client/preferences.dm
  code/modules/credits/episode_name.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/gun.dm
  icons/logos.dmi
  icons/mob/AI.dmi
  icons/obj/posters.dmi
  icons/obj/weapons.dmi
  icons/role_HUD_icons.dmi
  vgstation13.dme
Labels: Consistency Issue

#22028 Fixes Play Global Sound
  code/modules/admin/verbs/playsound.dm
Labels: Bug / Fix, Sound, T-Thanks BYOND

#22022 Improvements to Check Antags Panel
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/factions/faction.dm
  code/modules/admin/check_antagonists.dm
  code/modules/admin/topic.dm
Labels: ❤️ Quality of Life ❤️

#22034 Runtime hunting; barricade destroy
  code/game/objects/structures/barricade.dm
Labels: Bug / Fix, Runtime Log

#22040 Fixes Shuttle Disk Icons
  code/game/machinery/computer/shuttle_computers.dm
  icons/mob/in-hand/left/datadisks.dmi
  icons/mob/in-hand/right/datadisks.dmi
  icons/obj/datadisks.dmi
Labels: Hotfix, Sprites

#22012 Makes the life of powergame genetics harder.
  code/game/dna/dna2.dm
Labels: Legacy Bug

#22046 Bleb good end fixes
  code/datums/gamemode/factions/blob.dm
  code/datums/helper_datums/command_alerts.dm
Labels: Bug / Fix

#22045 Moves the destroy faction button to the admin panel entry
  code/datums/gamemode/factions/faction.dm
Labels: Bug / Fix

#21916 Body bag changes
  code/game/objects/items/bodybag.dm
  code/game/objects/structures/crates_lockers/closets.dm
  icons/obj/bodybag.dmi
Labels: Tweak

#22049 Species has icon checks and more
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug / Fix, Consistency Issue, Sprites, Unatomic Uncle

#22044 Makes the method of repairing a broken vending machine more obvious
  code/game/machinery/vending.dm
Labels: Tweak

#22065 Optimize set_glide_size
  code/game/atoms_movable.dm
Labels: System

#22067 Adds a slow down lighting button
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: System

#22056 Adds a toggle instrument preference
  code/game/objects/structures/musician.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/migrations/SS13_Prefs/017-add-instrument.dm
  vgstation13.dme
Labels: Sound, ❤️ Quality of Life ❤️

#22072 Rev Stage HF
  code/datums/gamemode/factions/syndicate/rev.dm
Labels: Hotfix

#22073 Fixes a LJ Wiz Cost Oversight
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
Labels: Hotfix

#22084 The Ammolathe can no longer print NT12 and Automag magazines.
  code/game/machinery/ammolathe.dm
Labels: Balance, Tweak

#22087 Target stake overlay sanity
  code/game/objects/items/shooting_range.dm
Labels: Bug / Fix, Exploitable

#21968 Blob Improvements
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/blob.dm
  code/datums/gamemode/role/blob.dm
  code/datums/gamemode/role/role.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/blob/blobs/node.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/blob/powers.dm
  code/game/gamemodes/blob/theblob.dm
  icons/role_HUD_icons.dmi
  vgstation13.dme
Labels: Bug / Fix, Content

#22038 Various Ninja Buffs (More glove targets, untrackability, grille smashin', wire slashin')
  code/datums/gamemode/role/ninja.dm
  code/game/machinery/camera/tracking.dm
  code/game/objects/items.dm
  code/game/objects/structures/grille.dm
  code/modules/power/cable.dm
  icons/obj/weapons.dmi
Labels: Bug / Fix, Content, Unatomic Uncle, ❤️ Quality of Life ❤️

#22059 Latejoin Gun Roles Generate 2-7 Less Threat
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Balance, Role Datums, Update WIKI

#22088 Revert "The Ammolathe can no longer print NT12 and Automag magazines."
  code/game/machinery/ammolathe.dm
Labels: Balance

#22058 free e20s were a mistake
  code/datums/uplink_item.dm
Labels: Balance

#22130 Mystery of the LJ Antag Solved
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
Labels: Role Datums

#22127 Nuke Op Scoreboard Formatting
  code/datums/gamemode/factions/syndicate/nukeops.dm
Labels: Easy Fix

#22125 Runtime Hunting for Posters
  code/game/objects/items/mountable_frames/posters/poster.dm
Labels: Bug / Fix, Runtime Log

#22117 Stops the teleporter from committing infinite loopduku
  code/game/machinery/teleporter.dm
Labels: Bug / Fix

#22126 Kill or Exile Objective for Revs
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/objectives/target/killorexile.dm
  vgstation13.dme
Labels: Role Datums

#22140 Fixes being able to ignore the requirement of degenerative calcium by punching your robotic limbs
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix, Consistency Issue, Exploitable

#22123 Summon Guns to All
  code/game/gamemodes/wizard/rightandwrong.dm
Labels: Bug / Fix

#22124 Donutgiver Fix
  code/game/objects/items/trader.dm
Labels: Bug / Fix

#22074 AntagHUD Fixup
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_hud_list.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/constructs.dm
  icons/role_HUD_icons.dmi
Labels: Bug / Fix

#21865 Refactors Religion Choice
  code/datums/religions.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/library/computers/checkout.dm
  code/modules/mob/new_player/new_player.dm
Labels: Secret repo conflict.

#22129 Admins View Prefs Info
  code/datums/mind.dm
  code/modules/client/client procs.dm
Labels: Logging / Administration

#21800 Added Emperor's new clothes
  code/game/objects/items/trader.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Content, Needs Spritework

#22075 Changes ice pepper to chilly pepper
  code/modules/hydroponics/seeds.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Content, Tweak

#22109 Evidence bag consistency fixes
  code/modules/detectivework/evidence.dm
Labels: Bug / Fix

#22137 Blacksmithing hammer quality matters
  code/WorkInProgress/MadmanMartian/blacksmithing/blacksmithing.dm
Labels: Content

#22156 Literally just sets the default alternate option to RETURN TO LOBBY
  code/modules/client/preferences.dm
Labels: Tweak

#22159 reaks -> reeks
  code/modules/mob/living/simple_animal/hostile/necromorph.dm
Labels: Grammar / Formatting

#22079 Adds a damage threshold for robolimbs to count as malfunctioning
  code/modules/organs/organ_external.dm
Labels: Balance, ❤️ Quality of Life ❤️

#22155 Fixes a Bunch of Broken Religion Keys
  code/datums/religions.dm
Labels: Hotfix

#22168 oh god oh fuck
  code/modules/migrations/SS13_Prefs/017-add-instrument.dm
Labels: 100% tested, Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️

#22076 Should properly disable blob on roid
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Gameplay / Gamemode, Mapping (Roidstation :pick:)

#22153 Delay Assassinate
  code/datums/gamemode/objectives/target/assassinate.dm
  code/datums/gamemode/objectives/target/delayedassassinate.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/role/wizard.dm
  vgstation13.dme
Labels: Role Datums

#22100 Grants janitors the amazing ability to converse with mice speech.
  code/game/jobs/job/civilian.dm
Labels: Content

#22116 Makes phazon change your lungs required gas at the same time as the species breath type
  code/modules/mob/living/carbon/human/human.dm
Labels: ❤️ Quality of Life ❤️

#22173 [Dynamic Mode] High Population Override
  code/controllers/configuration.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Role Datums

#22175 Fixes ghetto rig helmets not showing
  code/modules/clothing/spacesuits/rig.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Bug / Fix, Oversight, Sprites

#22131 Catbeast Black
  __DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
  code/datums/gamemode/role/catbeast.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/effects/species.dmi
  icons/mob/human_face.dmi
  icons/mob/human_races/r_def_tajaranblack.dmi
  icons/mob/human_races/r_tajaranblack.dmi
Labels: Sprites

#21465 Soul Rambler Mini-Antag
  __DEFINES/_macros.dm
  __DEFINES/game.dm
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  code/__HELPERS/lists.dm
  code/controllers/shuttle_controller.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/objectives/freeform/rambler.dm
  code/datums/gamemode/objectives/investigate.dm
  code/datums/gamemode/objectives/ramble.dm
  code/datums/gamemode/objectives/uphold_vows.dm
  code/datums/gamemode/role/rambler.dm
  code/datums/gamemode/role/role.dm
  code/game/objects/items/devices/instruments.dm
  code/game/objects/structures/musician.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/necklaces.dm
  icons/logos.dmi
  icons/mob/screen_spells.dmi
  icons/role_HUD_icons.dmi
  vgstation13.dme
Labels: Content, Role Datums

#22128 Easy Bwoink Overminds
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Logging / Administration

#22214 Fixes action buttons persisting after the object has been unequipped
  code/game/objects/items.dm
Labels: Bug / Fix

#22212 Delay Improvements
  code/datums/gamemode/objectives/objective.dm
  code/datums/gamemode/objectives/target/delayedassassinate.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/role/role.dm
Labels: Tweak

#22149 Brian Damag and the prisoners of Shoutstakistan
  code/modules/spells/targeted/retard.dm
Labels: Tweak

#22182 adds minimal player age to borgs
  code/game/jobs/job/silicon.dm
Labels: Logging / Administration

#22163 Removes need for harm intent when cutting walls with CUT_WALL flag weapons
  code/game/turfs/simulated/walls.dm
Labels: ❤️ Quality of Life ❤️

#22009 uncomments sovietvend/nazivend/boda recharge packs from cargo console (requires emag anyway)
  code/datums/supplypacks.dm
Labels: :up: Powercreep :up:, Balance, Content, 🚓Fun Police🚓

#22054 Adds three circuits to the board printer
  code/modules/research/designs/boards/machine_misc.dm
Labels: 100% tested

#22098 adds in-hand sprites for butcher knife (not the traitor item, the chef vendor thing)
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/swords_axes.dmi
Labels: Sprites

#22111 Mulebot atom locking
  code/game/machinery/bots/mulebot.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix, Consistency Issue

#22179 null rod revamp qB^)
  code/game/objects/items/weapons/null_rod.dm
Labels: :up: Powercreep :up:

#22162 Wizard gloves from the hardsuit bundle are now shockproof (and has very low permeability coefficient)
  code/game/gamemodes/wizard/artifacts.dm
  code/modules/clothing/gloves/color.dm
Labels: :up: Powercreep :up:

#22139 Quality now modifies force, throwforce, sharpness, and physical armors
  code/game/objects/items.dm
  code/game/objects/objs.dm
Labels: Content, WiP

#22132 [WIP] Cockroach update
  code/modules/mob/living/simple_animal/roach.dm
Labels: Tweak

#22246 Hair styles
  code/modules/clothing/suits/wintercoat.dm
Labels: Bug / Fix

#22144 makes shuriken less fuckhueg
  icons/obj/weapons.dmi
Labels: Sprites
