Repository vgstation-coders/vgstation13, pull requests merged in 2019-10, with the labels that each got.

#24201 GC Fixes
  code/controllers/garbage.dm
  code/game/atoms_movable.dm
Labels: Bug / Fix, Performance

#24310 Pick up verb sanity
  code/game/objects/items.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix

#24294 Adds a normal, non-firebird Snowmobile, renames wizard one to magic snowmobile
  code/game/objects/structures/vehicles/firebird.dm
  code/game/objects/structures/vehicles/snowmobile.dm
  vgstation13.dme
Labels: Mapping (Snowmap ❄)

#24188 Energy sword and dual sword QoL
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/clothing/suits/miscellaneous.dm
  maps/randomvaults/spessmart.dm
Labels: Consistency Issue, Update WIKI

#24257 Gives exca. suits a make over and brings them into the hard suit age.
  __DEFINES/archaeo_defines.dm
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/finds/digsites.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
  icons/mob/head.dmi
  icons/mob/in-hand/left/spacesuits.dmi
  icons/mob/in-hand/left/xenoarch.dmi
  icons/mob/in-hand/right/spacesuits.dmi
  icons/mob/in-hand/right/xenoarch.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Balance, Sprites

#24196 Atmos machines now actually use power
  code/controllers/subsystem/pipenet.dm
Labels: Oversight

#24322 Washing machine code cleanup
  code/game/machinery/washing_machine.dm
Labels: File Cleanup

#24197 Microwaves can now be examined to check out the contents.
  code/game/machinery/kitchen/microwave.dm
Labels: ❤️ Quality of Life ❤️

#24315 Knife Holsters can now hold banana guns.
  code/modules/clothing/accessories/holster.dm
Labels: 100% tested, Oversight

#24328 Adds Halloween Vinyl to the bar juke during halloween.
  code/modules/media/jukebox.dm
Labels: Sound

#24342 Fixes a material dupe with R&D
  code/modules/mining/materials.dm
  code/modules/research/rdconsole.dm
Labels: Bug / Fix

#24340 Properly pathing holsters on a spawner list to their subtype rather than parent holder object that should not be spawned.
  code/modules/maps/spawners/spawners.dm
Labels: 0% tested, Bug / Fix

#23464 Revert "Possible workaround for scrollbar bug that only randomly affects admins"
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/mob/mob.dm
Labels: Secret repo conflict., T-Thanks BYOND

#24304 Really good diy shuttle ideas
  code/game/objects/items/blueprints.dm
Labels: ❤️ Quality of Life ❤️

#24348 Adds Lil' Slugger Vinyl (for real this time)
  code/modules/media/jukebox.dm
Labels: Hotfix

#24336 Two new lobby screens submitted by players for serb.
  icons/splashworks/title19.png
  icons/splashworks/title20.gif
Labels: Content

#24353 Emagged defib and electric chairs no longer harms slime people
  code/game/objects/items/weapons/defib.dm
  code/game/objects/structures/electricchair.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix, WiP

#24364 fixes missing hair
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Bug / Fix

#24368 Fixes pill eating restriction logic
  code/modules/reagents/reagent_containers/pill.dm
Labels: Bug / Fix

#24371 Fixes unbuckling while unconscious
  code/modules/mob/living/living.dm
Labels: Bug / Fix

#24378 Fixes biosuits in CMO and RD lockers.
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
Labels: Bug / Fix

#24162 My take on balancing scp-294
  code/game/machinery/scp_294.dm
Labels: Balance

#24388 Adds a new clown outfit to the Autorobe
  code/game/machinery/vending.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#24390 Fixes a goof with the bartender winter coat
  icons/mob/suit.dmi
Labels: Bug / Fix

#24384 Fixes hair going through some masks (and some head objects too)
  __DEFINES/setup.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug / Fix

#24399 More things fit on coat racks
  code/game/objects/structures/coatrack.dm
  icons/obj/coatrack.dmi
Labels: Content, Tweak

#24403 Cocoa powder condiment bottle icon.
  code/modules/reagents/reagent_containers/food/condiment.dm
  icons/obj/food_condiment.dmi
Labels: Sprites

#24373 Each job now knows which frequency they are tuned to
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/paramedic.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
Labels: Emoji This :+1: :-1:, Oversight

#24410 Fixes a Jukebox Runtime
  code/modules/media/jukebox.dm
Labels: Bug / Fix

#24404 new pharaoh suit sprite
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#24414 Fixes click dragging clothes on the ground
  code/modules/clothing/clothing.dm
Labels: Bug / Fix

#24416 Remove need for carrier fluid from Fourier and Hyperspectral
  code/modules/research/xenoarchaeology/machinery/analysis_fourier_transform.dm
  code/modules/research/xenoarchaeology/machinery/analysis_hyperspectral.dm
Labels: ❤️ Quality of Life ❤️

#24424 Changes the viro googles click sound
  code/modules/clothing/glasses/glasses.dm
Labels: Sound

#24439 Wolves no longer spam the console when near a campfire
  code/modules/mob/living/simple_animal/hostile/wolf.dm
Labels: Bug / Fix

#24421 Energy Dome
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  sound/misc/devo_crack_that_whip.ogg
  sound/misc/devo_whip_it_good.ogg
  sound/misc/devo_you_must_whip_it.ogg
Labels: Content

#24435 Make the posibrain directive more visible.
  code/modules/mob/living/carbon/brain/posibrain.dm
Labels: Tweak

#24423 Say logs QoL
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
Labels: Logging / Administration

#24422 Hot coco recipe
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content, WiP

#24452 Cold resistant mobs no longer get affected by snowballs
  code/game/gamemodes/endgame/xmas/snowman.dm
Labels: Bug / Fix

#24460 Biomass no longer has a fetish
  code/game/gamemodes/events/biomass.dm
Labels: Bug / Fix

#24444 Fixed roundstart skeles using human's movement speed modifier
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
Labels: Bug / Fix

#24455 Fixes human runtimes
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix

#24469 Rigging votes is now logged
  code/controllers/mc/admin.dm
Labels: Logging / Administration

#24472 fixes a runtime I found while testing gibself
  goon/code/datums/browserOutput.dm
Labels: Runtime Log

#24438 Spawned and roundstart slime people start with electric protection
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#24437 Adds a new lobby screen.
  icons/splashworks/title21.png
Labels: Sprites

#24476 prevents dedchet singulo 0 of doom
  code/modules/power/singularity/singularity.dm
Labels: Hotfix

#24463 Two New Asteroid Vaults
  maps/randomvaults/mining/AbandonedForge.dmm
  maps/randomvaults/mining/cultbase.dmm
Labels: Mapping (Vault :question:)

#24428 An attempt at trying to fix or at least debug #24418 by preloading.
  code/modules/client/client procs.dm
  code/modules/mob/living/silicon/ai/say.dm
Labels: Secret repo conflict.

#24488 Fixes for the VOX Announcements UI
  code/modules/mob/living/silicon/ai/say.dm
Labels: System, ❤️ Quality of Life ❤️

#24485 Jumping to a mob (not coords) via admin links now follows them instead of just jumping.
  code/modules/admin/topic.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#24482 removes compile warning
  code/modules/client/client procs.dm
Labels: Oversight

#24471 re-implements gibself as a ghost spawning gibs
  code/modules/admin/verbs/randomverbs.dm
Labels: Feature Loss, IT'S A FEAAAATUUUUREEEEEEEEE, Logging / Administration

#24454 Fullscreen overlays now resize
  code/_onclick/hud/fullscreen.dm
Labels: Bug / Fix

#24493 Partially reverts #24428: Removes preloader
  code/modules/client/client procs.dm
Labels: Bug / Fix, Hotfix, Secret repo conflict.

#24487 Adds some VOX soundfiles to the toggling of the trader port.
  code/game/machinery/computer/communications.dm
  sound/AI/trading_port_closed.ogg
  sound/AI/trading_port_open.ogg
Labels: Sound

#24450 Allows admins to delete notes they made under all circumstances
  code/modules/admin/admin.dm
  code/modules/admin/player_notes.dm
Labels: Bug / Fix

#24502 fixes a bug with vv dropdown gib not working right
  code/modules/admin/verbs/randomverbs.dm
Labels: Bug / Fix, Logging / Administration

#24375 Adds universal key snow mobiles and key fabricator for snaxi use.
  code/game/machinery/constructable_frame.dm
  code/game/machinery/keyfab.dm
  code/game/objects/structures/vehicles/snowmobile.dm
  code/game/objects/structures/vehicles/vehicle.dm
  icons/obj/stationobjs.dmi
  vgstation13.dme
Labels: Content, Needs Changelog

#24449 AI now actually get the station's frequencies
  code/game/jobs/job/silicon.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Tweak

#24496 Add when kick shoes they equip if you have no shoes on.
  code/modules/clothing/clothing.dm
Labels: 100% tested, Feature Request

#24486 create-command-report now cancels correctly, overall less ass
  code/modules/admin/verbs/randomverbs.dm
Labels: Bug / Fix, Logging / Administration

#24489 Changes pillbottle color change shortcut to ctrl click
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Tweak

#24516 Ping IAA and HOP on Fax
  code/WorkInProgress/kilakk/fax.dm
  code/game/objects/items/devices/PDA/cart.dm
Labels: Content, ❤️ Quality of Life ❤️

#24511 Sports Makes You Strong
  code/modules/mob/living/helper_procs.dm
  code/modules/mob/living/living.dm
Labels: Tweak

#24524 Fixes RA Trader Lockdown
  code/game/machinery/computer/communications.dm
Labels: Bug / Fix

#24509 Maybe fix VOX.
  code/modules/mob/living/silicon/ai/say.dm
Labels: Bug / Fix

#24526 Sterile CMO
  code/game/objects/items/devices/radio/headset.dm
Labels: :up: Powercreep :up:

#24521 Inflatable shelters now fit in the inflatable box
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Tweak

#24528 Ping Labor Console
  code/WorkInProgress/kilakk/fax.dm
  code/modules/mob/new_player/new_player.dm
Labels: Secret repo conflict.

#24549 Fix dog gender being incorrect in new master message.
  code/modules/mob/living/simple_animal/friendly/corgi.dm
Labels: Easy Fix, Grammar / Formatting

#24538 Snowmobiles On Snow
  code/game/objects/structures/vehicles/snowmobile.dm
  code/game/turfs/unsimulated/snow.dm
  icons/turf/floors.dmi
  sound/misc/metal_drag1.ogg
  sound/misc/metal_drag2.ogg
  sound/misc/metal_drag3.ogg
  vgstation13.dme
Labels: Content, Tweak

#24552 Outfit datums : nuke ops, vox raiders
  __DEFINES/mobs.dm
  __DEFINES/setup.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/vox_shoal.dm
  code/datums/inventory/slot.dm
  code/datums/outfit/civilian.dm
  code/datums/outfit/outfit.dm
  code/datums/outfit/striketeams/death_commando.dm
  code/datums/outfit/striketeams/nukeop.dm
  code/datums/outfit/striketeams/vox_raider.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/striketeams/nanotrasen_deathsquad.dm
  code/game/striketeams/striketeam_datums.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/species.dm
  vgstation13.dme
Labels: System

#24546 cappuccino and passione now do things
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Oversight

#24462 Dorfstation Map Initial Commit
  maps/Dorfstation.dmm
  maps/dorfstation.dm
Labels: Mapping (General :world_map:), ❤️ Quality of Life ❤️

#24523 Clowning Guns
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/left/guns.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
  icons/mob/in-hand/right/guns.dmi
  icons/obj/biggun.dmi
  icons/obj/gun.dmi
Labels: Content

#24550 Winter Wizard Robes
  code/game/machinery/vending.dm
  code/modules/clothing/suits/wintercoat.dm
  code/modules/clothing/suits/wiz_robe.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Gameplay / Gamemode, Sprites

#24566 Makes code compile on 513
  code/__HELPERS/lists.dm
  code/__HELPERS/maths.dm
  code/modules/mob/living/simple_animal/shade_powers.dm
  code/modules/organs/organ_external.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/surgery/butt.dm
  code/modules/surgery/generic.dm
Labels: T-Thanks BYOND

#24352 Map popups
  code/_onclick/hud/map_popups.dm
  icons/mob/map_backgrounds.dmi
  interface/skin.dmf
  vgstation13.dme
Labels: Needs Spritework, System

#24572 Fixes glass tables giving plasma sheets
  code/game/objects/items/weapons/table_rack_parts.dm
Labels: Bug / Fix

#24577 Ports some AI sprites.
  code/modules/mob/living/silicon/ai/ai.dm
  icons/mob/AI.dmi
Labels: 100% tested, Sprites

#24547 adds 2 new door commands, fixes 2 old ones
  code/game/machinery/airlock_control.dm
Labels: 100% tested, Content

#24576 Broken tube light subtype and minor icon bugfixes for mapping
  code/modules/power/lighting.dm
Labels: Content, Mapping (General :world_map:)

#24475 Robo cryo rework revival
  code/game/machinery/cryo.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  html/changelogs/madmanmartian.yml
  nano/templates/cryo.tmpl
Labels: 100% tested, Balance

#24541 Adds Gondola Cultist/Shade subtypes
  code/modules/mob/living/carbon/complex/gondola.dm
  code/modules/mob/living/simple_animal/shade.dm
  icons/mob/gondola.dmi
Labels: Content

#24527 Restores Syndie Chair
  code/game/objects/structures/vehicles/wheelchair.dm
Labels: Balance

#24555 unathi soghun gear update
  code/modules/clothing/spacesuits/alien.dm
  icons/mob/species/unathi/head.dmi
  icons/mob/species/unathi/suit.dmi
Labels: Content

#24586 Adds Code for Derelict R&D Server and Derelict R&D Console
  code/game/machinery/computer/buildandrepair.dm
  code/modules/research/designs/boards/computer_science.dm
  code/modules/research/rdconsole.dm
  code/modules/research/server.dm
Labels: Balance, Bug / Fix, System, ❤️ Quality of Life ❤️

#24598 Are cargo carts finally fixed?
  code/game/objects/structures/vehicles/carts/cargo.dm
  code/game/objects/structures/vehicles/carts/cart.dm
  code/game/objects/structures/vehicles/vehicle.dm
Labels: 100% tested, Bug / Fix

#24614 Moving on a cargo cart now gets you off
  code/game/objects/structures/vehicles/carts/cargo.dm
Labels: Hotfix

#24613 bananium coins now have their proper name
  code/modules/mining/ores_coins.dm
Labels: Grammar / Formatting

#24578 AI Ambience Changes
  code/controllers/subsystem/ambient_sound.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/ambience_datums.dm
  code/game/area/areas.dm
  sound/ambience/ambimalf1.ogg
  sound/ambience/ambimalf2.ogg
  sound/ambience/ambimalf3.ogg
  sound/ambience/ambimalf4.ogg
Labels: Sound, Tweak

#24618 Fixes simple_animals not deleting properly
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#24624 Fix Boxes Again
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Bug / Fix

#24636 Cell timer layer fix
  code/game/machinery/doors/brigdoors.dm
Labels: Bug / Fix

#24647 Minihoe has an attack message
  code/modules/hydroponics/hydro_tools.dm
Labels: Bug / Fix

#24615 pAI cleanup and tweaks
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: Content, File Cleanup, Tweak

#24589 Adds Satellite of Love to lobby music.
  code/game/gamemodes/gameticker.dm
  sound/music/Lou_Reed_-_Satellite_of_Love.ogg
Labels: Sound

#24623 Alarm Clock
  __DEFINES/setup.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/apps.dm
Labels: Content

#24621 Lets SDQL work on clients and datums
  code/modules/admin/verbs/SDQL_2/SDQL_2.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#24620 Fixes #24619
  nano/templates/cryo.tmpl
Labels: 0% tested, Bug / Fix

#24626 Allows wearing belts without requiring a uniform
  __DEFINES/_macros.dm
  code/game/objects/items.dm
  code/game/objects/items/misc_items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Tweak

#24506 Buff condensedcapsaicin (pepperspray) and fix ghost peppers not being spicy at all.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak, WiP

#24616 Adds the color-smoke symptom (Stage 3)
  code/modules/virus2/effect/stage_3.dm
Labels: Content, Honk

#24679 Renames isatommovable() to ismovable()
  __DEFINES/_macros.dm
  code/game/objects/effects/beam.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/camera_bug.dm
  code/game/objects/items/potions.dm
  code/game/turfs/turf_flick_animations.dm
  code/modules/projectiles/projectile/force.dm
Labels: T-Thanks BYOND

#24668 Supermatter warning signs
  code/game/objects/structures/signs.dm
  icons/obj/decals.dmi
Labels: Sprites
