Repository vgstation-coders/vgstation13, pull requests merged in 2019-05, with the labels that each got.

#22716 Mushmen pressure suits were called mushmen helmets
  code/modules/clothing/spacesuits/alien.dm
Labels: Bug / Fix

#22717 paul should really test his hotfixes
  code/modules/cmc/crew.dm
Labels: 100% tested

#22721 Haha whoops I accidentaly broke upgrading protolathes I'm such a Leo sometimes :)
  code/game/machinery/constructable_frame.dm
Labels: Bug / Fix

#22725 Gives Vox sprites for telekinesis, heat/cold resistance and their combined counterpart.
  code/game/dna/genes/powers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/effects/genetics.dmi
Labels: Sprites

#22571 Give the ninja gloves action buttons.
  code/datums/gamemode/role/ninja.dm
Labels: Content

#22494 New rune effect - Unholy Threshold
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: :up: Powercreep :up:, Gameplay / Gamemode

#22515 Broken Bottle
  code/game/objects/items/robot/robot_items/robot_gripper.dm
Labels: :up: Powercreep :up:, Content

#22645 you can now pull the pilot out of a spacepod
  code/WorkInProgress/pomf/spacepods/spacepods.dm
Labels: ❤️ Quality of Life ❤️

#22730 puts teleport prefs under +FUN instead of +DEBUG
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
Labels: Logging / Administration

#22736 typo
  code/modules/admin/verbs/debug.dm
Labels: Grammar / Formatting

#22638 Tator codewords now appear in red when seen by other tators/nukeops
  code/__HELPERS/names.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/saycode/speech.dm
  code/modules/mob/living/say.dm
Labels: ❤️ Quality of Life ❤️

#22738 Attack logs transfered on ghosting/mind transfer
  code/datums/mind.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Logging / Administration

#22737 Logged Guillotines
  code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
Labels: Logging / Administration

#22728 flash meteors now use global flashbang proc
  code/game/gamemodes/meteor/meteors.dm
Labels: File Cleanup

#22669 Phenol properly reacts with plasticide for making plastic.
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Tweak

#22734 Lazily increases rollerbed wheelie hitbox
  icons/obj/rollerbed.dmi
Labels: Tweak

#22740 Fixes Nano with infinities/NaN again
  code/modules/nano/nanoui.dm
  nano/js/JSON_parseMore.js
  nano/js/nano_state_manager.js
  nano/js/nano_update.js
Labels: Bug / Fix, File Cleanup, System

#22679 Dynamic mode : no stacking by default
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Gameplay / Gamemode, Role Datums

#22695 Pills fit in IV drips once again
  code/modules/reagents/reagent_containers/pill.dm
Labels: Content, IT'S A FEAAAATUUUUREEEEEEEEE

#22689 Glass floors QoL + powercreep
  code/game/turfs/simulated/floor_glass.dm
Labels: ❤️ Quality of Life ❤️

#22755 Empty pills delete themselves in IVs
  code/game/machinery/iv_drip.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: ❤️ Quality of Life ❤️

#22581 Giving silicons the option to plausibly lie about their laws
  code/_onclick/hud/screen_objects.dm
  code/datums/ai_laws.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/laws.dm
  code/modules/mob/living/silicon/mommi/laws.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/silicon/state_laws.dm
  nano/css/shared.css
  nano/js/nano_base_callbacks.js
  nano/js/nano_base_helpers.js
  nano/templates/state_laws.tmpl
  vgstation13.dme
Labels: :up: Powercreep :up:

#22790 Fixes the empty laws in State Laws
  code/modules/mob/living/silicon/state_laws.dm
Labels: Bug / Fix

#22777 Reset selected laws in State Laws when laws change
  code/modules/mob/living/silicon/state_laws.dm
Labels: Bug / Fix

#22311 IDs with the right access can be thrown against doors to open them
  code/game/machinery/doors/door.dm
Labels: Balance, Tweak

#22747 Adds regular and security biosuit crates.
  code/datums/supplypacks.dm
Labels: Content

#22742 Check antag menu fixes
  code/__HELPERS/unsorted.dm
  code/datums/gamemode/objectives/custom.dm
  code/datums/gamemode/objectives/objective.dm
  code/datums/mind.dm
  code/modules/admin/topic.dm
Labels: Bug / Fix, Feature Request, Logging / Administration, ❤️ Quality of Life ❤️

#22698 Borers abandon host faster
  code/modules/mob/living/simple_animal/borer.dm
Labels: Tweak

#22690 glass tiles now cost 1 sheet and are faster to make
  code/game/objects/items/stacks/sheets/glass.dm
Labels: ❤️ Quality of Life ❤️

#22651 Firefighting equipment crate
  code/datums/supplypacks.dm
Labels: Balance, Content

#22785 Signaler sanity
  code/modules/assembly/signaler.dm
Labels: Needs Changelog

#22772 Makes catbeast sandals leave catbeast footprints
  code/datums/gamemode/role/catbeast.dm
Labels: Discussion

#22786 AIs and cyborgs show up on the OOC crew manifest
  code/defines/obj.dm
  code/modules/mob/living/silicon/robot/robot_subtypes/syndicate.dm
Labels: ❤️ Quality of Life ❤️

#22798 Fixed active/inactive for silicons on the crew manifest
  code/defines/obj.dm
Labels: Bug / Fix

#22733 Can attach IV drips to rollerbeds
  code/datums/locking_category.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/structures/flaps.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
  code/game/objects/structures/stool_bed_chair_nest/rollerbed.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/game/turfs/turf.dm
  vgstation13.dme
Labels: Update WIKI, ❤️ Quality of Life ❤️

#22801 Fixed targeted mind_affecting spells not checking for tinfoil hats
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/mob.dm
  code/modules/spells/targeted/targeted.dm
Labels: Bug / Fix

#21520 Midround bomberman
  code/game/objects/effects/landmarks.dm
  code/modules/bomberman/bomberman.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Gameplay / Gamemode, Mapping (Roidstation :pick:)

#22768 Bunsen burner overlay is consistent with different size container sprites
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: Bug / Fix

#22762 really nasty bug
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix, Feature Loss, Oversight

#22640 Fabricators will now produce items immediately if they are next in queue
  code/modules/research/fabricators.dm
Labels: :up: Powercreep :up:

#22811 Revert "Fabricators will now produce items immediately if they are next in queue"
  code/modules/research/fabricators.dm
Labels: Feature Loss, Hotfix

#22817 cmc-hotfix - adds holomap_offset where needed
  code/modules/cmc/crew.dm
Labels: 100% tested, Hotfix

#22816 Bomberman sanity
  code/modules/mob/dead/observer/observer.dm
Labels: Hotfix

#22660 you can now pull out the pilot of a mecha
  code/game/mecha/mecha.dm
Labels: :up: Powercreep :up:, ❤️ Quality of Life ❤️

#22779 Spamming throwing items fix
  __DEFINES/setup.dm
  code/modules/mob/delays.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: 100% tested, Exploitable, Tweak

#22759 Give namepick upon monkey transformation
  code/modules/mob/transform_procs.dm
Labels: Gameplay / Gamemode

#22694 Jar QoL, Chemistry starts with 2 reskinned jars
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/jar.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Content, ❤️ Quality of Life ❤️

#22666 Removing clone damage from vampire succ
  code/datums/gamemode/role/vampire_role.dm
  code/modules/organs/organ_external.dm
Labels: Balance, Tweak

#22599 Let MoMMIs use microwaves and bartending machines
  code/modules/mob/living/silicon/mommi/mommi_modules.dm
  html/changelogs/FudgePucker.yml
Labels: :up: Powercreep :up:, Tweak, ✋ Do Not Merge ✋

#22653 small edit to the PKA projectile
  code/modules/projectiles/projectile/special.dm
Labels: Tweak

#22680 Buff TEG
  code/modules/power/generator.dm
Labels: Tweak

#22685 Mushmen fixes
  code/modules/clothing/spacesuits/alien.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix, Needs Changelog, ❤️ Quality of Life ❤️

#22255 Adds luminol.
  __DEFINES/reagents.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items.dm
  code/game/turfs/simulated.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content

#22835 meant to go along with #22666
  code/datums/gamemode/role/vampire_role.dm
Labels: Hotfix

#22834 Adds Z-6 back to CMC
  __DEFINES/setup.dm
  code/modules/cmc/crew.dm
Labels: Oversight

#22843 fixed slip on tele
  code/modules/mob/living/carbon/carbon.dm
  code/modules/spells/aoe_turf/blink.dm
Labels: Hotfix

#22803 Tweaked starting requirements and cost for revs
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Gameplay / Gamemode

#22807 Surgery patients scream if they're not anaesthetized
  code/modules/organs/pain.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/butt.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
Labels: Honk

#22805 Converting 40% of the crew to revs triggers the 'subversive elements' announcement
  code/datums/gamemode/factions/syndicate/rev.dm
Labels: Balance

#22855 Slip changes
  code/modules/mob/living/carbon/carbon.dm
Labels: Hotfix

#22863 added !occupant sanitycheck
  code/game/mecha/combat/combat.dm
  code/game/mecha/mecha.dm
  code/modules/research/xenoarchaeology/artifact/artifact_hoverpod.dm
Labels: Sanity / Ghosthands

#22847 VSCode fixes
  __DEFINES/accessories.dm
  code/__HELPERS/unsorted.dm
  code/datums/shuttle.dm
  code/game/machinery/computer/shuttle_computers.dm
  code/game/machinery/newscaster.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/docking_port.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/vehicles/clowncart.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/onlyone.dm
  code/modules/assembly/assembly_frame.dm
  code/modules/assembly/speaker.dm
  code/modules/clothing/accessories/tactical_light.dm
  code/modules/fish/fish_tank.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/organs/blood.dm
  code/modules/projectiles/targeting.dm
  code/modules/research/rdmachines.dm
  goon/code/obj/machinery/bot/chefbot.dm
Labels: File Cleanup

#22849 fixed runtime when logging pills being put in containers
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Hotfix

#22848 ROGANbot
  code/__HELPERS/global_lists.dm
  code/game/machinery/computer/store.dm
  code/modules/reagents/reagent_containers/roganbot.dm
  code/modules/store/items.dm
  code/modules/store/store.dm
  sound/effects/aoe2/01 yes.ogg
  sound/effects/aoe2/02 no.ogg
  sound/effects/aoe2/03 food, please.ogg
  sound/effects/aoe2/04 wood, please.ogg
  sound/effects/aoe2/05 gold, please.ogg
  sound/effects/aoe2/06 stone, please.ogg
  sound/effects/aoe2/07 ahh.ogg
  sound/effects/aoe2/08 all hail.ogg
  sound/effects/aoe2/09 oooh.ogg
  sound/effects/aoe2/10 back to age 1.ogg
  sound/effects/aoe2/11 herb laugh.ogg
  sound/effects/aoe2/12 being rushed.ogg
  sound/effects/aoe2/13 blame your isp.ogg
  sound/effects/aoe2/14 start the game.ogg
  sound/effects/aoe2/15 dont point that thing.ogg
  sound/effects/aoe2/16 enemy sighted.ogg
  sound/effects/aoe2/17 it is good.ogg
  sound/effects/aoe2/18 i need a monk.ogg
  sound/effects/aoe2/19 long time no siege.ogg
  sound/effects/aoe2/20 my granny.ogg
  sound/effects/aoe2/21 nice town ill take it.ogg
  sound/effects/aoe2/22 quit touchin.ogg
  sound/effects/aoe2/23 raiding party.ogg
  sound/effects/aoe2/24 dadgum.ogg
  sound/effects/aoe2/25 smite me.ogg
  sound/effects/aoe2/26 the wonder.ogg
  sound/effects/aoe2/27 you play 2 hours.ogg
  sound/effects/aoe2/28 you should see the other guy.ogg
  sound/effects/aoe2/29 rogan.ogg
  sound/effects/aoe2/30 wololo.ogg
  sound/effects/aoe2/31 attack an enemy now.ogg
  sound/effects/aoe2/32 cease creating extra villagers.ogg
  sound/effects/aoe2/33 create extra villagers.ogg
  sound/effects/aoe2/34 build a navy.ogg
  sound/effects/aoe2/35 stop building a navy.ogg
  sound/effects/aoe2/36 wait for my signal to attack.ogg
  sound/effects/aoe2/37 build a wonder.ogg
  sound/effects/aoe2/38 give me your extra resources.ogg
  vgstation13.dme
Labels: Content

#22820 New xcom laser icons
  icons/obj/gun.dmi
Labels: Sprites

#22868 Fixes a couple of logging things
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantcase.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/modules/reagents/machinery/chem_master.dm
Labels: Logging / Administration

#22881 Paramedic access can now open alarming firelocks
  code/game/machinery/doors/firedoor.dm
Labels: Tweak

#22893 fixes wiki link for ninja
  __DEFINES/role_datums_defines.dm
Labels: Hotfix

#22187 Flash powder flashbang
  code/modules/reagents/Chemistry-Recipes.dm
Labels: :up: Powercreep :up:

#22850 Attacking cult structures plays attack animations and hit sounds
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
Labels: ❤️ Quality of Life ❤️

#22876 Fixes secure briefcase HUD not updating
  code/game/objects/items/weapons/storage/secure.dm
Labels: Bug / Fix, Thanks old coders

#22443 Cult will no longer yank the shuttle if it's on the way to centcomm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/faction.dm
Labels: Gameplay / Gamemode

#22871 Ninja energy katanas can't be hooked into eachother to make dual energy swords anymore
  code/datums/gamemode/role/ninja.dm
Labels: Bug / Fix

#22859 Secure briefcase big
  code/game/objects/items/weapons/storage/secure.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#22846 Small percentage of roundstart cameras deactivated
  code/game/machinery/camera/camera.dm
Labels: Balance, Tweak

#22837 Ups a bit the 'max blood per victim' number.
  code/datums/gamemode/role/vampire_role.dm
Labels: Tweak

#22832 Reduces cost of some of the least popular tator uplink items
  code/datums/uplink_item.dm
Labels: Balance

#22861 Cowboy Boots
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/clothing/shoes/miscellaneous.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Content

#22889 Adds gunka-cola and Dr. Pecker's DIY Soda
  __DEFINES/reagents.dm
  code/game/machinery/kitchen/snackbarmachine.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/paperwork/paper.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/chemical.dmi
  icons/obj/drinks.dmi
  icons/obj/storage/smallboxes.dmi
Labels: Content

#22661 Not-Obvious No-Slip Shoes + other syndigaloshes changes
  code/datums/uplink_item.dm
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Bug / Fix, Consistency Issue, ❤️ Quality of Life ❤️

#22767 Cult EMP rune buff
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Balance

#22760 Borers can infest through armour/hardsuits
  code/modules/mob/living/simple_animal/borer.dm
Labels: Tweak

#22869 Air alarm & central atmos computer & vents & scrubbers unatomic featurecreep bug-a-palooza
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/WorkInProgress/Mini/atmos_control.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  code/game/machinery/alarm.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/doors/firedoor.dm
  code/modules/atmos_automation/implementation/vent_pump.dm
  code/modules/research/designs/boards/computer_engie.dm
  nano/css/shared.css
  nano/templates/air_alarm.tmpl
  nano/templates/atmos_control.tmpl
  nano/templates/atmos_control_map_header.tmpl
  vgstation13.dme
Labels: Bug / Fix, Gameplay / Gamemode, Tweak, ❤️ Quality of Life ❤️

#22866 converts the cmc textview to nanoui
  code/modules/cmc/crew.dm
  code/modules/nano/nanomanager.dm
  code/modules/nano/nanoui.dm
  nano/css/cmc.css
  nano/css/shared.css
  nano/templates/cmc.tmpl
  nano/templates/crew_monitor.tmpl
  nano/templates/crew_monitor_map_content.tmpl
  nano/templates/crew_monitor_map_header.tmpl
Labels: ❤️ Quality of Life ❤️

#22758 Security RPGs
  code/game/machinery/ammolathe.dm
  code/modules/projectiles/ammunition/rocket.dm
  code/modules/projectiles/guns/projectile/rocketlauncher.dm
  code/modules/projectiles/projectile/rocket.dm
  code/modules/research/designs/weapons.dm
  icons/mob/in-hand/left/guns.dmi
  icons/mob/in-hand/right/guns.dmi
  icons/obj/gun.dmi
Labels: :up: Powercreep :up:, Content

#22931 fixes air alarms for silicons
  code/game/machinery/alarm.dm
Labels: Bug / Fix

#22932 Borgs can now use air alarms from the CAC again
  code/game/machinery/computer/atmos_control.dm
Labels: Bug / Fix

#22867 added functionality to buckle to coffin
  code/game/objects/structures/crates_lockers/closets/coffin.dm
Labels: Feature Request

#22870 Non-ninjas can no longer use energy katanas
  code/datums/gamemode/role/ninja.dm
Labels: Balance

#22872 Make Bolas great again
  __DEFINES/obj_defines.dm
  code/datums/gamemode/role/ninja.dm
  code/defines/obj/weapon.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance

#22880 Scrubber pressure check consistency
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
Labels: Bug / Fix, Consistency Issue

#22894 Manual and digital valve bugfixes and code cleanup
  code/ATMOSPHERICS/components/binary_devices/valve.dm
Labels: Bug / Fix

#22916 only monkeys get the monkey namepick prompt
  code/modules/mob/transform_procs.dm
Labels: Bug / Fix

#22911 red suit and hat
  code/game/machinery/vending.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#22618 plasma cutter rework 1
  code/game/objects/items/devices/modkit.dm
  code/modules/mining/mine_items.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/research/designs/mining.dm
  code/modules/research/research.dm
Labels: Tweak

#22883 Static air tank improvements (plus some atmos machine bugfixes)
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
  code/ATMOSPHERICS/components/unary/tank.dm
  code/ATMOSPHERICS/components/unary/unary_base.dm
  code/game/machinery/Freezer.dm
  code/game/objects/items/stacks/stack_recipes.dm
  icons/obj/atmospherics/pipe_tank.dmi
Labels: Bug / Fix, Tweak

#22948 MoMMI blueprints and construction permits can now delete blueprint-defined areas
  code/game/objects/items/blueprints.dm
Labels: ❤️ Quality of Life ❤️

#22944 double click to ventcrawl
  code/_onclick/ventcrawl.dm
Labels: ❤️ Quality of Life ❤️

#22969 Make all tator fix
  code/modules/admin/topic.dm
Labels: Bug / Fix, Easy Fix

#22972 Removes dead code (species darksight var)
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/species.dm
Labels: File Cleanup

#22985 Probably fixes mind transfers without bodies
  code/datums/mind.dm
Labels: Bug / Fix

#22984 Scrubber siphoning fix
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
Labels: Consistency Issue

#22963 Updates gas mixers and filters to use the new gas pump functionality
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/trinary_devices/mixer.dm
Labels: Tweak

#22952 make_zombie now can produce zombies controlled by players.
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix

#22856 added brighter slip zone
  icons/effects/water.dmi
Labels: Tweak, ❤️ Quality of Life ❤️

#22970 Increases passive gate throughput
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
Labels: Tweak

#22967 Buffs portable air pumps
  code/game/machinery/atmoalter/pump.dm
Labels: Tweak

#22954 Glutton zombies can now create player zombies.
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: Gameplay / Gamemode, Tweak

#22945 Radiation artifact tweaks
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_radiate.dm
Labels: Balance, Tweak, Unatomic Uncle

#22927 Makes HE pipe radiation capacity equal to thermal plates
  code/ATMOSPHERICS/components/unary/thermal_plate.dm
  code/ATMOSPHERICS/he_pipes.dm
Labels: Consistency Issue

#22917 Space ninja suit + spawn in space + misc
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/ninja.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Content, Gameplay / Gamemode, Unatomic Uncle

#22994 Mecha Mousedrop HF
  code/game/mecha/mecha.dm
Labels: Hotfix

#22764 Disorient spell now has an empowered variant
  code/modules/spells/targeted/disorient.dm
Labels: 100% tested

#23002 fix ninja throw and species runtime
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/ninja.dm
Labels: Hotfix

#22980 Emag not emagging living human limbs fix
  code/_onclick/hud/human.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bug / Fix, Oversight

#22971 vox suits hold all air tanks
  code/modules/clothing/spacesuits/alien.dm
Labels: Tweak

#22986 Openning and flicking cult tome pages now does somes low volume short-range noise
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/library/lib_items.dm
Labels: Sound

#23018 revives #22010 - Supply Consoles no longer require cargo access to use 2: SOLDERING EDITION.
  code/game/machinery/computer/cargo.dm
  nano/templates/supply_console.tmpl
Labels: Balance, Tweak

#21992 Add the full Inquisitor set to the Chap's vending machine
  code/game/machinery/vending.dm
Labels: Content

#23029 Fixes an oopsie in the bottlesmash attack text.
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Bug / Fix

#23017 Updates stylesheets a bit
  goon/browserassets/css/browserOutput.css
  goon/browserassets/css/browserOutput_dark.css
Labels: Tweak

#23023 THE JUKENING OF OUR TIME
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/malf.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/game/machinery/vending.dm
  code/modules/media/jukebox.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Labels: Sound, help wanted

#23022 MAGPULSE clothing flag instead of hard magboot checks
  __DEFINES/clothing.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/unit_tests/slipping.dm
Labels: 100% tested, Tweak

#23040 ROGANbot has a 0.6 second cooldown
  code/game/objects/items/devices/roganbot.dm
  vgstation13.dme
Labels: Tweak, 🚓Fun Police🚓

#23057 Fixed emagged Doctor Acula succing blood from dry bodies
  code/game/machinery/bots/draculabot.dm
Labels: Bug / Fix

#23007 added option to throw admin made ninjas into station from space
  code/datums/mind.dm
Labels: 100% tested, Tweak

#23061 Flatpacks and bartending machines can be moved over tables
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/research/mechanic/flatpack.dm
Labels: ❤️ Quality of Life ❤️

#23020 Maybe fix the volume setting for VLC
  code/modules/media/mediamanager.dm
Labels: Bug / Fix

#22574 Longer delays for dynamic injections
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/maths.dm
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Role Datums, System

#22808 Vampires and holy weapons : a mini rework
  __DEFINES/setup.dm
  code/datums/gamemode/role/vampire_role.dm
  code/game/atoms.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/weapons/mop.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/spells/aoe_turf/glare.dm
  code/modules/spells/aoe_turf/screech.dm
  code/modules/spells/targeted/disease.dm
  code/modules/spells/targeted/enthrall.dm
  code/modules/spells/targeted/hypnotise.dm
  code/modules/spells/vampire_helpers.dm
Labels: Balance, Role Datums, Tweak

#23084 I accidentaly made dynamic cooldowns 10 times bigger than what they should be
  __DEFINES/role_datums_defines.dm
Labels: Hotfix
