Repository vgstation-coders/vgstation13, pull requests merged in 2019-04, with the labels that each got.

#22227 Chem Grenades can be made with any reagent container.
  code/game/objects/items/weapons/grenades/chem_grenade.dm
Labels: Honk, Tweak, why, ✋ Do Not Merge ✋, ❤️ Quality of Life ❤️

#22290 Fixes a religion runtime
  code/datums/religions.dm
Labels: Bug / Fix, Runtime Log

#22289 Fixes the crayon decal runtime
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/game/objects/structures/vehicles/clowncart.dm
Labels: Bug / Fix, Runtime Log

#22287 Reopens the span in soreness, removes excess spaces
  code/modules/virus2/effect/stage_1.dm
Labels: Bug / Fix

#22288 Fixes april fools cargo mimics from making mustard gas and eating all of your cargo
  code/controllers/subsystem/supply_shuttle.dm
Labels: Bug / Fix, Hotfix

#22256 Fixes a runtime with APCs and malf that involve an AI that has jaunted
  code/modules/power/apc.dm
Labels: Bug / Fix

#22291 fixes female scientists not screaming at all on april fools
  code/modules/mob/living/carbon/emote.dm
Labels: Bug / Fix

#22207 Refactors Throw Impact
  code/datums/gamemode/role/ninja.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/lance.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/objs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/complex/combat.dm
  code/modules/mob/living/carbon/human/human_attackalien.dm
  code/modules/mob/living/carbon/human/human_attackanimal.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Tweak

#22304 Economy 2019 Part A
  __DEFINES/_macros.dm
  __DEFINES/global.dm
  code/datums/supplypacks.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/slot_machine.dm
  code/game/machinery/vending.dm
  code/modules/Economy/Accounts.dm
  code/modules/Economy/utils.dm
Labels: Bug / Fix, System, Tweak

#22277 Makes knockdowns great again
  code/game/dna/genes/vg_powers.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/computer/HolodeckControl.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/mines.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/electropack.dm
  code/game/objects/items/robot/robot_items/robot_harm_alarm.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/dice.dm
  code/game/objects/items/weapons/grenades/clowngrenade.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/lance.dm
  code/game/objects/items/weapons/shard.dm
  code/game/objects/items/weapons/storage/bluespace.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/vehicles/clowncart.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/floor_glass.dm
  code/modules/assembly/mousetrap.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/genetics/side_effects.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/balloon.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/frog.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/mob/living/simple_animal/hostile/necromorph.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/mob_grab.dm
  code/modules/projectiles/guns/energy/gravitywell.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/gravitywell.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
  maps/randomvaults/dance_revolution.dm
Labels: Balance

#22335 Adds an ambience volume preference
  code/controllers/subsystem/ambient_sound.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/migrations/SS13_Prefs/018-add-ambience_vol.dm
  vgstation13.dme
Labels: Sound, ❤️ Quality of Life ❤️

#22315 Some Bible tweaks
  code/datums/religions.dm
Labels: Bug / Fix, Tweak

#22341 Actually fixes gun button for real
  icons/obj/fakegun.dmi
Labels: 100% tested, Bug / Fix

#22348 Better sqlite error logging
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Logging / Administration

#22352 Changes the Vampire Mature state to properly reflect that it makes you more vulnerable to holy things.
  code/datums/gamemode/vampire_gamemode.dm
Labels: Easy Fix, Oversight, Role Datums

#22353 Preference bugs eternal
  code/modules/client/preferences.dm
Labels: Hotfix

#22345 OOC will now automatically turn back on at the end of rounds
  code/game/gamemodes/gameticker.dm
Labels: Logging / Administration, Tweak, ❤️ Quality of Life ❤️

#22370 Revert #21204
  code/modules/mob/living/carbon/human/human.dm
Labels: File Cleanup

#22296 Fixing some unintended Holy Water/Incense behaviours
  code/datums/gamemode/role/cultist.dm
  code/game/objects/items/incense.dm
Labels: Bug / Fix

#22274 People who punch the soul rambler now say things
  code/modules/mob/living/carbon/human/combat.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: :thinking:, Content

#22273 Restricts the use of 12ga and .357 mags in the vector. Also adds an unrestricted one.
  code/modules/projectiles/guns/projectile/automatic.dm
Labels: Balance

#22372 Should stop spider queens from making mass trails of web in space
  code/modules/mob/living/simple_animal/hostile/giant_spider/nurse.dm
Labels: Bug / Fix

#22391 Spider sanity eternal
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/nurse.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix

#22399 highlander is now only defined once
  __DEFINES/setup.dm
Labels: System

#22310 Jungle Fever
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/datums/diseases/jungle_fever.dm
  code/datums/gamemode/factions/junglefever.dm
  code/datums/gamemode/objectives/infect.dm
  code/datums/gamemode/role/blob.dm
  code/datums/gamemode/role/madmonkey.dm
  code/datums/gamemode/role/role.dm
  code/datums/helper_datums/command_alerts.dm
  icons/role_HUD_icons.dmi
  vgstation13.dme
Labels: :thinking:, Role Datums

#22400 beepsky now ignores invisible perps
  code/game/machinery/bots/secbot.dm
Labels: Bug / Fix, IT'S A FEAAAATUUUUREEEEEEEEE

#22397 /obj/item/delivery will now drop all contents
  code/game/objects/items/stacks/packagewrap.dm
Labels: Bug / Fix

#22403 Removes the 'create Nuke Ops' option from the secret panel.
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
Labels: Logging / Administration

#22313 You can bite-intent attack drinks to drink them
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Tweak

#22321 Borg Smashing
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Content

#22407 Update sql page
  SQL/players2.sql
Labels: System

#22405 Revert "beepsky now ignores invisible perps"
  code/game/machinery/bots/secbot.dm
Labels: IT'S A FEAAAATUUUUREEEEEEEEE

#22401 secure safes are now actually secure, go figure
  code/game/objects/items/weapons/storage/secure.dm
Labels: Bug / Fix, Exploitable, Oversight

#22428 Fixes Ghost Pepper Typo
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Grammar / Formatting

#22396 fixes typo
  code/game/objects/structures/fullwindow.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/window.dm
Labels: Grammar / Formatting

#22392 Ore machinery optimization
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/materials.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/minerals.dm
Labels: Bug / Fix, Consistency Issue

#22389 Very Minor Grammar Fix
  code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
Labels: Grammar / Formatting

#22365 Add credits volume client preference. Credits are 25% quieter by default.
  SQL/players2.sql
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/credits/credits.html
  code/modules/credits/credits_clientprocs.dm
  code/modules/credits/episode_name.dm
  code/modules/migrations/SS13_Prefs/019-add-credits_vol.dm
  vgstation13.dme
Labels: System

#22234 Reduces Midround Blob weight and ups threat cost & threshold.
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Balance, Gameplay / Gamemode, Role Datums, Tweak

#22439 Make delayed ruleset cost threat
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Bug / Fix

#22423 Potassium Hydroxide Tune Up draft
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Tweak

#22420 Waterpotass
  code/modules/reagents/Chemistry-Recipes.dm
Labels: :up: Powercreep :up:

#22447 Fixes tractor glide_size
  code/game/objects/structures/vehicles/carts/cart.dm
  code/game/objects/structures/vehicles/vehicle.dm
Labels: Bug / Fix

#22440 Alien nest fix
  code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
Labels: Bug / Fix

#22445 rotationverbs were rotating the wrong direction. literally unplayable
  code/ATMOSPHERICS/components/binary_devices/MSGS.dm
  code/ATMOSPHERICS/components/binary_devices/circulator.dm
  code/game/machinery/Freezer.dm
  code/modules/power/generator.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
Labels: Bug / Fix

#22460 added a supercall to Destroy() of the holomap (the device one)
  code/game/objects/items/devices/holomap.dm
Labels: Bug / Fix, Easy Fix

#22355 Adds unit test for reject_bad_name
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/names.dm
Labels: System

#21737 runtime hunting: client
  code/modules/client/client procs.dm
Labels: Bug / Fix, Runtime Log, Sanity / Ghosthands

#22035 You can now shoot narsie
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/legacy_cult/narsie.dm
  code/modules/projectiles/guns/projectile/constructable/railgun.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Content, Honk

#22422 numbers i like better: part five
  code/game/objects/items/weapons/table_rack_parts.dm
Labels: Bug / Fix

#22421 numbers i like better: part four
  code/game/objects/structures/girders.dm
Labels: Bug / Fix

#22441 added margin of error in the objective-fulfilled check
  code/datums/gamemode/objectives/invade.dm
Labels: Bug / Fix, Tweak

#22470 Washing machines wouldn't dye jumpsuits without inhand sprites
  code/game/machinery/washing_machine.dm
Labels: Bug / Fix

#22496 Fixes glass tile creation
  code/game/objects/items/stacks/tiles/tiles.dm
Labels: Bug / Fix, Runtime Log

#22495 Fixes blood track runtime
  code/game/objects/effects/decals/Cleanable/tracks.dm
Labels: Bug / Fix, Runtime Log

#22367 Refactors appearance randomisation.
  code/datums/datacore.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_tattoos.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/religions.dm
  code/game/area/Space Station 13 areas.dm
  code/game/dna/dna2.dm
  code/game/dna/dna2_helpers.dm
  code/game/dna/genes/monkey.dm
  code/game/gamemodes/changeling/horror.dm
  code/game/gamemodes/endgame/xmas/krampus.dm
  code/game/machinery/Sleeper.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/structures/mirror.dm
  code/game/striketeams/emergency_response_team.dm
  code/game/striketeams/nanotrasen_deathsquad.dm
  code/game/striketeams/striketeam_datums.dm
  code/game/striketeams/syndicate_elite_squad.dm
  code/game/turfs/simulated.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/admin/verbs/onlyone.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/preferences.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/credits/episode_name.dm
  code/modules/events/heist.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/living/carbon/human/catbeast/catbeast.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life/handle_random_events.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/transform_procs.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_objects.dm
  code/modules/spells/general/shapeshift.dm
  code/modules/virus2/effect/stage_2.dm
  code/modules/virus2/effect/stage_3.dm
  vgstation13.dme
Labels: Performance, System

#22409 Solarboards
  code/modules/research/designs/boards/machine_engie.dm
Labels: Content, Unatomic Uncle

#22444 added rotate verbs for the treadmill
  code/modules/power/treadmill.dm
Labels: Easy Fix, ❤️ Quality of Life ❤️

#22424 Acutely Adjust Acids Again
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#22398 makes the weldingmask start opened
  code/modules/clothing/head/misc_special.dm
Labels: Tweak

#22404 Re-adds magboots verb.
  code/modules/clothing/shoes/magboots.dm
Labels: ❤️ Quality of Life ❤️

#22410 New equation for threat
  code/__HELPERS/maths.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: System

#22434 removes audio clipping on lighter1.ogg
  sound/items/lighter1.ogg
Labels: Sound

#22415 numbers i like better: part one
  code/game/objects/items/weapons/storage/boxes.dm
Labels: :up: Powercreep :up:

#22416 numbers i like better: part two
  code/game/objects/items/weapons/shard.dm
Labels: :up: Powercreep :up:

#22417 numbers i like better: part three
  code/modules/projectiles/projectile/bullets.dm
Labels: :up: Powercreep :up:

#22253 Burn damage can cause ashing in high amounts
  code/controllers/configuration.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: why

#22063 Security cyborg H.O.S. upgrade, W.A.T.C.H. upgrade tweak and more.
  __DEFINES/silicon.dm
  code/game/machinery/flasher.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/objs.dm
  code/modules/mob/living/silicon/robot/robot_subtypes/hug.dm
  icons/mob/robots.dmi
Labels: :up: Powercreep :up:, Balance, Content, Tweak, Unatomic Uncle

#22451 Reduce DNA modifier injector creation cooldown by half
  code/game/dna/dna_modifier.dm
Labels: :up: Powercreep :up:, Gameplay / Gamemode

#22465 Smartglass revision
  code/game/machinery/door_control.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/smartglass.dm
  code/game/objects/structures/window.dm
Labels: Tweak

#22468 Adding sake sprites and a new cocktail for it
  __DEFINES/reagents.dm
  code/game/machinery/vending.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  icons/obj/drinks.dmi
Labels: Gameplay / Gamemode, Sprites, Update WIKI

#22478 Pale Beings no longer scream or jitter when hit by electrode and a custom message is displayed.
  __DEFINES/_macros.dm
  code/datums/gamemode/factions/legacy_cult/soulstone.dm
  code/game/dna/dna_modifier.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/medical/computer/cloning.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#22492 Alphabetized the AI spritepick lists
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Tweak

#22493 rewords mommi lawset because people still complain about it
  code/datums/ai_laws.dm
  code/game/objects/items/weapons/ai_modules/AI_modules.dm
Labels: Discussion, Gameplay / Gamemode

#22513 Eswords can now slice open firelocks
  code/game/machinery/doors/firedoor.dm
Labels: :up: Powercreep :up:, Content

#22518 Fixes secure safe UI not updating
  code/game/objects/items/weapons/storage/secure.dm
Labels: Bug / Fix

#22479 Androids -> Droids
  code/game/objects/items/robot/robot_items/robot_mobility.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Tweak, Update WIKI

#22450 Fixing clean_stepxy.py
  maptools/clean_stepxy.py
Labels: Mapping (General :world_map:)

#22475 Drinks grammar pass
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: 100% tested, Tweak

#22520 Fixes an oopsie in chem dispenser overlays
  code/game/machinery/scp_294.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Bug / Fix

#22185 global flashbang procs
  code/game/objects/items/weapons/grenades/flashbang.dm
Labels: System

#22536 Watermelon potency is back to before a nerf that happened ages ago.
  code/modules/hydroponics/seeds.dm
Labels: Consistency Issue, Tweak, ❤️ Quality of Life ❤️

#22523 Adds Solar Assemblies to Metal recipes
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Content

#22522 fixes brigdoor timers
  code/game/machinery/doors/brigdoors.dm
Labels: 100% tested, Bug / Fix, Easy Fix, UI

#22545 Fixes runtime preventing firedoors from opening with empty hand
  code/game/machinery/doors/firedoor.dm
Labels: Hotfix, Runtime Log

#22425 Reduces time it takes to unbuckle from bucklecuff to 1 minute from 2 minutes
  code/modules/mob/living/living.dm
Labels: Balance

#22558 Fixes mommis being able to reset their modules
  code/modules/mob/living/silicon/mommi/mommi_modules.dm
Labels: Hotfix

#22562 Fixes a goof in enthrall message
  code/datums/gamemode/role/vampire_role.dm
Labels: Grammar / Formatting

#22565 Holy fuck how the fuck did it take THIS FUCKING LONG for somebody (inc me) to finally make these fucking piece of shit ass block doors even REMOTELY not suck?
  code/game/machinery/doors/firedoor.dm
Labels: ❤️ Quality of Life ❤️

#22483 Ports Dreamseeker window flashing from TG
  code/__HELPERS/unsorted.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/migrations/SS13_Prefs/020-window_flashing.dm
  vgstation13.dme
Labels: Content

#22474 Fixing a potential exploit of the sacrifice target re-roll mechanic
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
Labels: Bug / Fix

#22303 I fucking swear this better fix it
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Bug / Fix

#22532 Faxing Tomes Fix
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
Labels: Tweak

#22592 Bluespace RPEDs now display machine parts when they can't upgrade.
  code/game/machinery/machinery.dm
Labels: Tweak

#22584 A path to fixing Nano loading issues.
  nano/js/nano_base_callbacks.js
  nano/js/nano_base_helpers.js
  nano/js/nano_state.js
  nano/js/nano_state_default.js
  nano/js/nano_state_manager.js
  nano/js/nano_template.js
  nano/js/nano_update.js
  nano/js/nano_utility.js
Labels: System, UI

#22603 q
  nano/templates/portscrubber.tmpl
Labels: Bug / Fix, UI

#22601 Fixes Clown Latejoining
  code/game/jobs/job/civilian.dm
Labels: Bug / Fix

#22602 Make Nano use json_encode.
  code/modules/nano/nanoui.dm
Labels: Performance, System, UI

#22351 Simple mob sounds
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  sound/voice/cathiss.ogg
  sound/voice/catmeow.ogg
  sound/voice/catpurr.ogg
  sound/voice/corgibark.ogg
  sound/voice/corgigrowl.ogg
Labels: Sound

#22621 Vampire bugfix: Screech properly consumes blood
  code/modules/spells/aoe_turf/screech.dm
Labels: 100% tested, Bug / Fix

#22627 Fixes being unable to spawn catbeasts
  code/game/gamemodes/endgame/xmas/krampus.dm
  code/modules/mob/living/carbon/human/catbeast/catbeast.dm
Labels: Bug / Fix

#22521 Ninja - Sake interactions
  code/datums/gamemode/objectives/ninja/stealsake.dm
  code/datums/gamemode/role/ninja.dm
  code/modules/reagents/Chemistry-Reagents.dm
  vgstation13.dme
Labels: Content

#22608 Decreases the delay for saving preferences
  code/modules/client/preferences.dm
Labels: Tweak

#22650 Adding libvg.so to gitignore
  .gitignore
Labels: Oversight

#22634 Cheap bugfixes
  code/datums/mind.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/telesci/telesci_computer.dm
Labels: Bug / Fix

#22622 Make R-UST gyrotrons 5x as effective.
  code/WorkInProgress/Cael_Aislinn/Rust/core_field.dm
  code/WorkInProgress/Cael_Aislinn/Rust/virtual_particle_catcher.dm
Labels: :up: Powercreep :up:, ❤️ Quality of Life ❤️

#22605 IV Drips now give/succ 12 units of blood.
  code/game/machinery/iv_drip.dm
Labels: Balance, Tweak

#22594 Poly now yells about the scrungulartiy
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Content

#22589 Nanoui check_interactive() rework
  code/modules/nano/nanoui.dm
Labels: Tweak, UI

#22560 Vampire dread will no longer terrify Thralls.
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/role/vampire_role.dm
Labels: Balance

#22575 Ions projectiles will now ALWAYS hit mechs
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
Labels: Balance

#22570 Arcane Golems now have 200 HP.
  code/modules/mob/living/simple_animal/friendly/arcane_golem.dm
Labels: Balance, Tweak

#22600 Fucking remove mindswap book recoil
  code/game/gamemodes/wizard/spellbook.dm
Labels: Bug / Fix, Feature Loss

#22563 Shadowstep removes restrains
  code/modules/spells/aoe_turf/blink.dm
Labels: Balance

#22559 Changes the shapeshift spell to be more flexible.
  code/datums/gamemode/role/vampire_role.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/spells/general/shapeshift.dm
Labels: Balance

#22561 Chaplains are ALWAYS resistant to vampire powers
  code/modules/spells/vampire_helpers.dm
Labels: Balance

#22564 Mist form removes restraints
  code/modules/spells/targeted/ethereal_jaunt.dm
Labels: Balance

#22606 More roundstart bloodbags
  code/game/machinery/kitchen/smartfridge.dm
Labels: :up: Powercreep :up:

#22279 Walking on the clown PDA slips you (not april fools)
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/unit_tests/slipping.dm
Labels: :up: Powercreep :up:

#22639 fixes it
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Gameplay / Gamemode, ❤️ Quality of Life ❤️

#22326 adds bone gel and fixovein to the surgery switchtool
  code/game/objects/items/weapons/switchtool.dm
  icons/obj/switchtool.dmi
Labels: Content

#22485 Improved combat text readability
  code/game/objects/items.dm
  code/game/objects/items/weapons/lance.dm
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/human/human_attackalien.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/combat.dm
  code/modules/mob/living/living_defense.dm
  goon/browserassets/css/browserOutput.css
Labels: Grammar / Formatting

#22646 Dynamic mode options
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/maths.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_maths.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  vgstation13.dme
Labels: Logging / Administration, System

#22675 Adds the changelog prefixes from example.yml to the New PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ❤️ Quality of Life ❤️

#22657 holy shitpost
  code/__HELPERS/text.dm
  code/datums/religions.dm
  code/game/machinery/bots/buttbot.dm
  code/modules/admin/verbs/pray.dm
Labels: Content, Honk

#22678 Self click-dragging onto operating tables
  code/game/machinery/OpTable.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#22555 A little space pod love
  code/WorkInProgress/pomf/spacepods/actions.dm
  code/WorkInProgress/pomf/spacepods/equipment.dm
  code/WorkInProgress/pomf/spacepods/parts.dm
  code/WorkInProgress/pomf/spacepods/pod_fabricator.dm
  code/WorkInProgress/pomf/spacepods/spacepods.dm
  icons/pods/button_icons.dmi
Labels: Balance, Bug / Fix, Unatomic Uncle

#22630 changes the cost of the revolver from 13 tc to 12 tc
  code/datums/uplink_item.dm
Labels: Balance

#22655 Buffs socket wrench
  code/game/objects/items/weapons/tools.dm
Labels: Balance

#22647 delay assassination jectie now shows name in chat after delay
  code/datums/gamemode/objectives/target/delayedassassinate.dm
Labels: Role Datums

#22636 Adds two micro-lasers to protolathe required components
  code/datums/supplypacks.dm
  code/modules/research/protolathe.dm
Labels: Tweak

#22625 we /wwe/ here
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Balance

#22551 Pocketsand extinguish
  code/modules/mining/ores_coins.dm
Labels: Tweak

#22662 Adding police/engineering/atmospherics tape to vendors
  code/game/machinery/vending.dm
Labels: Content

#22682 The crusade against relative pathing took one tab too many.
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: Hotfix

#22677 Strike teams now get and display jecties
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/objectives/custom.dm
  code/game/striketeams/emergency_response_team.dm
  code/game/striketeams/nanotrasen_deathsquad.dm
  code/game/striketeams/striketeam_datums.dm
  code/game/striketeams/syndicate_elite_squad.dm
Labels: Content, ❤️ Quality of Life ❤️

#22674 striketeams now show mission when polling
  code/game/striketeams/striketeam_datums.dm
Labels: ❤️ Quality of Life ❤️

#22686 Fixes the oopsie with the holomap cmc
  code/modules/cmc/crew.dm
Labels: Bug / Fix

#22624 Tac light accessory
  __DEFINES/accessories.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/tactical_light.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/tactical.dm
  icons/mob/clothing_accessories.dmi
  icons/obj/clothing/accessory_overlays.dmi
  vgstation13.dme
Labels: Content

#22671 custom striketeams now spawn naked
  code/game/striketeams/striketeam_datums.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#22673 Custom Strike Teams get renamed upon creation
  code/game/striketeams/striketeam_datums.dm
Labels: Conflicts, ❤️ Quality of Life ❤️

#22670 Cafe and Bartending equipment crates now come with flatpacks
  code/datums/supplypacks.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/research/mechanic/flatpack.dm
Labels: :up: Powercreep :up:
