Repository vgstation-coders/vgstation13, pull requests merged in 2019-09, with the labels that each got.

#24039 Adds monkey soup.
  code/game/objects/items/trash.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/trash.dmi
Labels: 100% tested, Update WIKI

#24041 Simon's Jacket can now hold drills
  code/modules/clothing/suits/miscellaneous.dm
Labels: Oversight

#24025 Fax machine bug fixes and QoL
  code/WorkInProgress/kilakk/fax.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#24047 Fixes evidence bags not resetting their weight class or description
  code/modules/detectivework/evidence.dm
Labels: Bug / Fix

#24052 Easy Rig
  code/controllers/mc/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
Labels: Logging / Administration

#23848 Adds tower shields, craftable via blacksmithing
  code/WorkInProgress/MadmanMartian/blacksmithing/misc_components.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/shields.dm
  icons/mob/in-hand/left/shields.dmi
  icons/mob/in-hand/right/shields.dmi
  icons/obj/butchering_products.dmi
  icons/obj/misc_components.dmi
  icons/obj/weapons.dmi
Labels: Content, Needs Review

#23973 Add single greytide implant item to uplink
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
Labels: Content

#24042 Finally fucking removes all explicit calls to Destroy() (except the necessary ones of course)
  code/WorkInProgress/Cael_Aislinn/scp_173.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/doors/airlock.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/spells/aoe_turf/screech.dm
Labels: File Cleanup

#24032 Changes event chance population
  code/game/turfs/unsimulated/snow.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/blizzard.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/carp_migration.dm
  code/modules/events/centcomm_order.dm
  code/modules/events/comms_blackout.dm
  code/modules/events/communications_blackout.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/event.dm
  code/modules/events/event_dynamic.dm
  code/modules/events/grid_check.dm
  code/modules/events/hostile_infestation.dm
  code/modules/events/immovablerod.dm
  code/modules/events/infestation.dm
  code/modules/events/ion_storm.dm
  code/modules/events/link_with_centcomm.dm
  code/modules/events/meteors.dm
  code/modules/events/money_hacker.dm
  code/modules/events/money_lotto.dm
  code/modules/events/money_spam.dm
  code/modules/events/organ_failure.dm
  code/modules/events/powercreeper.dm
  code/modules/events/prison_break.dm
  code/modules/events/radiation_storm.dm
  code/modules/events/rogue_drones.dm
  code/modules/events/spacevine.dm
  code/modules/events/spider_infestation.dm
  code/modules/events/spontaneous_appendicitis.dm
  code/modules/events/viral_infection.dm
  code/modules/events/viral_outbreak.dm
  code/modules/events/wallrot.dm
  maps/_map.dm
  maps/snaxi.dm
  vgstation13.dme
Labels: Bug / Fix, Legacy Bug, Mapping (General :world_map:)

#24059 SCP 294 balance
  code/game/machinery/scp_294.dm
Labels: Balance, 🚓Fun Police🚓

#24082 better proc call results
  code/datums/datumvars.dm
  code/modules/admin/verbs/debug.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#24046 R&D QoL - Material costs preview
  code/modules/research/fabricators.dm
  code/modules/research/rdconsole.dm
Labels: Content, Update WIKI, ❤️ Quality of Life ❤️

#24077 Mice colour fix+ hunger tweaks
  code/modules/maps/spawners/spawners.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#24092 friggin ZAS
  code/ZAS/Airflow.dm
Labels: Bug / Fix

#24095 Appearance bans now also forbid you from changing your name as a silicon.
  code/modules/mob/living/silicon/robot/robot_verbs.dm
Labels: Logging / Administration

#24097 Fixes a typo for appearance banned shitborgs.
  code/modules/mob/living/silicon/robot/robot_verbs.dm
Labels: Grammar / Formatting

#24043 stupid lootbox no longer kills you
  code/game/objects/items/weapons/gift_wrappaper.dm
Labels: Unable To Reproduce, ❤️ Quality of Life ❤️

#24125 Fixes xeno meat pie recipe
  code/modules/food/recipes_microwave.dm
Labels: Bug / Fix

#24110 Powercreep scything fix
  code/game/mecha/equipment/tools/tools.dm
  code/modules/hydroponics/hydro_tools.dm
Labels: Bug / Fix

#24157 Reverts nu-keeper
  code/datums/ai_laws.dm
  code/game/objects/items/weapons/ai_modules/AI_modules.dm
Labels: Gameplay / Gamemode, Logging / Administration

#24115 Adds a readme file to cult
  code/datums/gamemode/factions/bloodcult/_README_.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/objectives/target/sacrifice.dm
  vgstation13.dme
Labels: ❤️ Quality of Life ❤️

#24013 Telescience machines can now be linked via multitool, should fix the bug where the game would crash if there were multiple telepads.
  code/modules/telesci/telepad.dm
  code/modules/telesci/telesci_computer.dm
Labels: Update WIKI

#24169 fixed pointing at invisible things you can't see
  code/modules/mob/mob.dm
Labels: Bug / Fix, Exploitable, Logging / Administration

#24172 clown goblins no longer drop free meat
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
Labels: Hotfix

#24051 New Disease and Spread Types
  __DEFINES/setup.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/mob.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/helpers.dm
  code/modules/virus2/items_devices.dm
Labels: Content

#24181 fixes broken winter coat icons
  icons/mob/suit.dmi
Labels: Hotfix

#24036 GC Tuneup
  code/controllers/garbage.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
Labels: Bug / Fix, Runtime Log, System

#24180 Fixes blocked Check
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bug / Fix

#24139 Increases Rev Reveal Threshold to 50% of the Crew
  code/datums/gamemode/factions/syndicate/rev.dm
Labels: Discussion, Emoji This :+1: :-1:

#24133 Human health now only takes into account the vital external organs.
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Balance, 🚓Fun Police🚓

#24123 added animated still and cereal maker on state
  code/modules/food/cooking_machines.dm
  icons/obj/cooking_machines.dmi
Labels: Bug / Fix, Sprites

#24129 New SCP-294 wrenchable subtype
  code/game/machinery/scp_294.dm
Labels: Content, Logging / Administration

#23991 Makes diona immune to hypothermia
  code/modules/mob/living/carbon/species.dm
Labels: :up: Powercreep :up:

#23987 Can slide drinks across tables
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Content

#23794 Changes snow tiles to standard atmospheric pressure
  __DEFINES/atmos.dm
Labels: Needs Moar Testing, Tweak

#24182 humans are now naked by default + randombodies can roll no underwear
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Tweak, Unable To Reproduce

#24168 Fixes odysseus sleepers being impossible to escape from
  code/game/mecha/equipment/tools/medical_tools.dm
Labels: Bug / Fix

#24094 If you rush the spare today you're in for a surprise
  __DEFINES/global.dm
  code/datums/helper_datums/butchering.dm
  code/modules/clothing/head/misc.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  icons/mob/animal.dmi
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Content

#24191 Event dynamic fixes
  code/modules/events/event_dynamic.dm
Labels: Bug / Fix

#23918 do_delay now checks if you are holding the item with any hand instead of active hand
  code/__HELPERS/unsorted.dm
  code/modules/mob/living/carbon/complex/martian/martian.dm
  code/modules/mob/living/carbon/stripping.dm
Labels: Balance, Emoji This :+1: :-1:

#24113 Ghost minds
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix, Secret repo conflict.

#24070 buffs tricord and doctor's delight
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Controversial

#23876 Makes comm frequencies randomized at roundstart.
  __DEFINES/communications.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/init/more_init_stuff.dm
  code/game/communications.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/presets.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/say.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/paperwork/paper.dm
  code/modules/scripting/IDE.dm
  code/modules/scripting/Implementations/Telecomms.dm
  code/modules/supermatter/supermatter.dm
  code/world.dm
  vgstation13.dme
Labels: Emoji This :+1: :-1:

#24215 Fixes ghosts being unable to re-enter their old bodies
  code/modules/mob/dead/observer/observer.dm
Labels: Hotfix, ⚠️ OH GOD IT'S LOOSE ⚠️

#24216 Fixes silicons and MoMMIs not being able to do anything time consuming
  code/modules/mob/living/silicon/mommi/inventory.dm
  code/modules/mob/living/silicon/robot/inventory.dm
Labels: Bug / Fix

#24219 adds missing changelogs for a bunch of robo PRs
  html/changelogs/martian.yml
Labels: Hotfix

#24199 fixes some fingerprint shitcode
  code/game/atoms.dm
Labels: Bug / Fix, Logging / Administration

#24026 ATM QoL and bug fixes
  code/WorkInProgress/Mini/ATM.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/cash.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#24224 Hotfix to asphault empty snowsound list causing runtimes
  code/game/turfs/unsimulated/snow.dm
Labels: Hotfix

#24239 leather fix for black market
  code/datums/black_market_item.dm
Labels: Bug / Fix

#24228 Fix powersink Destroy() failing due to bad assumption
  code/game/objects/items/devices/powersink.dm
Labels: Hotfix

#24227 Fix ejected engine having windoors with invalid req_access values (num instead of list)
  maps/randomvaults/ejectedengine.dmm
Labels: Hotfix, Mapping (Vault :question:)

#24225 Hotfix changed snow tiles staying in global snow list, blizzard holders acting on non-snowtiles
  code/game/turfs/unsimulated/snow.dm
Labels: Hotfix

#24244 Yet more do after fixes
  code/__HELPERS/unsorted.dm
Labels: Bug / Fix

#24252 Fixes Packed Telecoms
  maps/packedstation/telecomms.dm
Labels: 100% tested, Bug / Fix, Mapping (Packed :package:)

#24220 Re-adds recursive cereal
  code/modules/food/cooking_machines.dm
Labels: :thinking:, why

#24198 Stamps Improved
  code/game/machinery/vending.dm
  code/modules/admin/topic.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/stamps.dm
  icons/obj/bureaucracy.dmi
Labels: Content, Tweak

#24167 Xenoarch digsite scanner finishing up
  code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
  icons/obj/device.dmi
Labels: Content

#24256 Xenoarch exploit fixes
  code/modules/mining/mine_turfs.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Bug / Fix, 🚓Fun Police🚓

#24258 Adds an in-hand for snakes (and also picking them up)
  code/modules/mob/living/holders.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  icons/mob/in-hand/left/mob_holders.dmi
  icons/mob/in-hand/right/mob_holders.dmi
Labels: Sprites

#24254 Sleek Combat Borg Sprite
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: Sprites

#24253 Fixes Some Listening Stuff
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#24241 adds holiday-specific items to vending machines
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: Content, WiP

#24278 Holiday vending
  code/game/machinery/vending.dm
Labels: Hotfix

#24276 Ironrot reagent
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content, Update WIKI

#24261 Revert "Limb Health"
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Bleeding-Edge Experiment

#24287 Remove Clownwarn
  code/modules/paperwork/stamps.dm
Labels: Hotfix

#24286 Viro Dispenser Nondense
  code/modules/reagents/reagent_dispenser.dm
Labels: Bug / Fix

#24302 Fixes my mistake of not making find items actually spawn somewhere properly
  code/modules/mining/mine_turfs.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Bug / Fix

#24314 Fixes service comms not working
  code/game/machinery/telecomms/presets.dm
Labels: Bug / Fix, Honk

#24309 Yet more xenoarch fixes
  code/modules/mining/mine_turfs.dm
Labels: Bug / Fix

#24255 Enhanced April Fools' Mancrowave + subtype
  code/game/machinery/Sleeper.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/transform_procs.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/cryogenics3.dmi
Labels: Sprites

#24321 Fix shuttle timer overflow
  code/controllers/shuttle_controller.dm
Labels: Bug / Fix
