Repository vgstation-coders/vgstation13, pull requests merged in 2019-08, with the labels that each got.

#23746 Fixes Bear Meat
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
Labels: Bug / Fix

#23727 ERT finally get their USP
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/striketeams/emergency_response_team.dm
  code/modules/clothing/accessories/holster.dm
Labels: :up: Powercreep :up:, Tweak

#23733 Mech id upload buttons
  code/game/mecha/mecha.dm
Labels: ❤️ Quality of Life ❤️

#23756 MoMMIs can no longer be blobs
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Hotfix

#23744 Fixed Dynamic ruleset injection cooldowns still using the original delays after the first injection
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Bug / Fix, Role Datums

#23737 Portable air scrubbers volume fix
  code/game/machinery/atmoalter/scrubber.dm
Labels: Bug / Fix

#23721 Nagant revolver
  __DEFINES/weapons.dm
  code/datums/supplypacks.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/game/objects/items/weapons/null_rod.dm
  code/modules/mob/living/simple_animal/hostile/human/russian.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile/mosin.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  sound/weapons/mosin.ogg
  sound/weapons/mosinreload.ogg
  sound/weapons/nagant.ogg
  vgstation13.dme
Labels: Content

#23765 Should prevent traders abusing the RCS to steal from spacemart
  code/modules/telesci/rcs.dm
Labels: Oversight

#23763 Fixed the asteroid lair showing up on holomaps
  __DEFINES/setup.dm
  code/game/area/Space Station 13 areas.dm
  code/game/atoms.dm
  code/modules/html_interface/map/station_map.dm
  maps/randomvaults/objects.dm
Labels: Bug / Fix

#23745 Immunity Scanner tweaks and more in-hand icons
  code/game/objects/items/devices/scanners.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/virus2/items_devices.dm
  icons/mob/belt.dmi
  icons/mob/in-hand/left/misc_tools.dmi
  icons/mob/in-hand/right/misc_tools.dmi
Labels: Sprites, Tweak

#23706 [RFR] Powercreeper 2 electric boogaloo
  code/__HELPERS/unsorted.dm
  code/game/atoms.dm
  code/game/gamemodes/events/powercreeper.dm
  code/game/machinery/doors/door.dm
  code/game/objects/effects/beam.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix, System

#23772 Adds an admin-only projectile variant of Buckshot.
  code/modules/projectiles/projectile/bullets.dm
Labels: Logging / Administration

#23450 Vampires will now repair their external limbs when resting in coffins
  code/datums/gamemode/role/vampire_role.dm
Labels: Balance, Needs Fixing

#23778 More blacksmithing fixes
  code/WorkInProgress/MadmanMartian/blacksmithing/blacksmithing.dm
  code/WorkInProgress/MadmanMartian/blacksmithing/forge.dm
Labels: Bug / Fix

#23782 Fixes #23779
  code/game/dna/genes/monkey.dm
Labels: Bug / Fix

#23799 fixes invisible mosin nagant sprites
  icons/obj/gun.dmi
Labels: Hotfix

#23619 Vampire ruleset tweaks
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Emoji This :+1: :-1:, Gameplay / Gamemode

#23750 "Credits/Jingle Volume" now actually works with jingles
  code/modules/credits/credits_clientprocs.dm
Labels: Bug / Fix

#23784 Adds an extinguisher that starts empty, autolathe prints it.
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/extinguisher.dm
Labels: Emoji This :+1: :-1:, Feature Loss

#23773 Spessmart Inventory Tweaks
  maps/randomvaults/spessmart.dm
Labels: Mapping (General :world_map:)

#23796 Sombreros
  code/game/machinery/vending.dm
  code/modules/clothing/head/misc.dm
  icons/obj/clothing/hats.dmi
Labels: Content

#23752 This twisted game needs to be reset
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Feature Loss, Thanks old coders, ❤️ Quality of Life ❤️

#23770 Bearnades and spawn grenade descriptions
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  icons/obj/grenade.dmi
Labels: Content

#23791 Nolight snow tiles
  code/game/turfs/simulated/snow.dm
  code/game/turfs/unsimulated/snow.dm
Labels: Tweak

#23806 Fixing a runtime
  code/modules/virus2/effect/stage_3.dm
Labels: Bug / Fix, Runtime Log

#23144 Stats rewrite yet again
  __DEFINES/_macros.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_stats.dm
  code/datums/gamemode/factions/blob.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/legacy_cult/narsie.dm
  code/datums/gamemode/factions/legacy_cult/ritual.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
  code/datums/gamemode/factions/malf.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/legacy_cultist.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/role/wizard.dm
  code/datums/statistics/json_helpers.dm
  code/datums/statistics/stat_blob.dm
  code/datums/statistics/stat_helpers.dm
  code/datums/statistics/statcollection.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/blob/blobs/factory.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/blob/powers.dm
  code/game/gamemodes/blob/theblob.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/malfunction/Malf_Modules.dm
  code/game/gamemodes/scoreboard.dm
  code/game/gamemodes/wizard/spellbook.dm
  code/game/objects/items/devices/flash.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/power/apc.dm
  vgstation13.dme
Labels: System

#23732 adds a new magazine type exclusive to vector (take 2)
  code/game/machinery/ammolathe.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/research/designs/weapons.dm
  icons/obj/ammo.dmi
Labels: Content, Emoji This :+1: :-1:

#23838 should fix vaults (including angie's lair) from overlapping existing structures.
  code/modules/randomMaps/vaults.dm
Labels: Bug / Fix

#23881 Fix runtime on nullspaced brains on CMC
  code/modules/cmc/crew.dm
Labels: Hotfix

#23890 Removes SCP-173 from the menagerie artifact effect
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_menagerie.dm
Labels: Exploitable

#23912 Fixed Plasmamen being able to use their own blood for cult rituals, when they're supposed to be a NO_BLOOD race
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
Labels: Bug / Fix, Consistency Issue

#23901 Lattices now smooth properly
  code/game/objects/structures/lattice.dm
Labels: Bug / Fix

#23894 Lighter icon mapper fix
  code/game/objects/items/weapons/cigs_lighters.dm
  icons/obj/items.dmi
Labels: Bug / Fix

#23905 Games vendor from tgstation
  code/datums/supplypacks.dm
  code/game/machinery/vending.dm
  code/game/machinery/vending_packs.dm
  code/game/objects/items/weapons/dice.dm
  icons/obj/vending.dmi
  icons/obj/vending_pack.dmi
Labels: Content

#23834 Welding speed tweaks
  code/game/objects/items/weapons/tools.dm
Labels: Balance, Content

#23875 Recursive cyber horror works
  code/modules/mob/living/simple_animal/hostile/monster.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix, 🚓Fun Police🚓

#23833 Adds Lola's Set to the autovend
  code/game/machinery/vending.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/feet.dmi
  icons/mob/mask.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#23923 Fixes lings creeping out of snowfort
  maps/_map.dm
  maps/roidstation.dm
  maps/snaxi.dm
Labels: 100% tested, Hotfix, Mapping (Snowmap ❄)

#23859 Adds a new mapping tool for finding if supply and waste cross at any point
  code/modules/admin/verbs/mapping.dm
Labels: Mapping (General :world_map:)

#23836 Drinking Glass Examine Nerf
  code/modules/reagents/Chemistry-Holder.dm
Labels: Content, Feature Loss

#23793 Reverts the ability to get in chairs/beds without being on the same tile as them.
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Hotfix, ❤️ Quality of Life ❤️

#23924 Adds the wirecutting and booping sounds to everything with wires
  code/datums/wires/airlock.dm
  code/datums/wires/alarm.dm
  code/datums/wires/apc.dm
  code/datums/wires/camera.dm
  code/datums/wires/jukebox.dm
  code/datums/wires/mommi.dm
  code/datums/wires/mulebot.dm
  code/datums/wires/particle_accelerator.dm
  code/datums/wires/radio.dm
  code/datums/wires/rnd_wires.dm
  code/datums/wires/robot.dm
  code/datums/wires/transmitter.dm
  code/datums/wires/vending.dm
  code/datums/wires/wires.dm
  code/game/machinery/bots/mulebot.dm
  code/modules/power/apc.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
Labels: 100% tested, Emoji This :+1: :-1:, Sound

#23926 Fixes a typo with cluwnes and faguetttes
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/faguette.dm
Labels: Grammar / Formatting

#23931 Fixes sprite error with Greys
  icons/mob/human_races/r_grey.dmi
Labels: Bug / Fix, Sprites

#23930 Renames the old laser rifle to xcomlaserrifle-old
  icons/obj/gun.dmi
Labels: Oversight, Sprites

#23938 Fixes vehicles and everything
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Hotfix

#23957 ling b gone
  maps/roidstation.dm
Labels: Hotfix

#23489 Rewrite isolation centrifuge. In Nano.
  __DEFINES/machinery.dm
  code/modules/nano/nanoui.dm
  code/modules/virus2/analyser.dm
  code/modules/virus2/centrifuge.dm
  code/modules/virus2/dishincubator.dm
  nano/css/shared.css
  nano/templates/disease_isolation_centrifuge.tmpl
  nano/templates/dish_incubator.tmpl
  vgstation13.dme
Labels: ❤️ Quality of Life ❤️

#23895 Extinguisher cabinets can be closed with alt-click
  code/game/objects/structures/extinguisher.dm
Labels: Update WIKI

#23947 Adds Grey species specific sprites for all eye slot items
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/scanners.dm
  icons/mob/species/grey/eyes.dmi
Labels: 100% tested, Sprites, ❤️ Quality of Life ❤️

#23921 RC now makes three sounds when a message is sent to it
  code/game/machinery/requests_console.dm
Labels: Sound

#23941 Simon Glasses Fix
  icons/mob/eyes.dmi
Labels: Consistency Issue

#23877 Make slime tiles make slimes go faster and everyone else slower
  code/game/objects/items/stacks/tiles/tile_types.dm
Labels: Balance, Emoji This :+1: :-1:

#23885 Removes implant/embed removal surgery RNG
  code/modules/surgery/implant.dm
Labels: Emoji This :+1: :-1:, ❤️ Quality of Life ❤️

#23889 Adds xenoarch digsite locators
  code/modules/research/designs/anomaly.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
  code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
  icons/turf/mine_overlays.dmi
Labels: Balance, Content, Emoji This :+1: :-1:, Needs Spritework

#23476 Remove solo antag objectives part 55: electric boogaloo
  __DEFINES/setup.dm
Labels: Muh Immulsions

#23942 Removes the default 7-item limit in a storage such as backpacks
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bleeding-Edge Experiment

#23983 Revert "Removes the default 7-item limit in a storage such as backpacks"
  code/game/objects/items/weapons/storage/storage.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#23984 Larger backpack storage (for real this time)
  code/game/objects/items/weapons/storage/storage.dm
Labels: 0% tested

#23932 Starman DX
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_subtypes/starman.dm
  icons/mob/screen_spells.dmi
  sound/effects/psi/enemy_attack.ogg
  sound/effects/psi/other/boss_intro.ogg
  sound/effects/psi/other/enterbattle_ambush.ogg
  sound/effects/psi/other/enterbattle_normal.ogg
  sound/effects/psi/other/possession.ogg
  sound/effects/psi/other/spooky.ogg
  sound/effects/psi/other/surprise.ogg
  sound/effects/psi/other/text_bleep.ogg
  sound/effects/psi/other/warning.ogg
  sound/effects/psi/psi_beam.ogg
  sound/effects/psi/psi_lifeup_alpha.ogg
  sound/effects/psi/psi_lifeup_beta.ogg
  sound/effects/psi/psi_precast.ogg
  sound/effects/psi/psi_reflect_alpha.ogg
  sound/effects/psi/psi_reflect_beta.ogg
  sound/effects/psi/psi_shield_alpha.ogg
  sound/effects/psi/psi_teleport.ogg
Labels: :thinking:, Content

#23997 fixes grey spacesuits being invisible
  code/modules/clothing/spacesuits/alien.dm
Labels: Hotfix

#24003 fixes supply_console.tmpl
  nano/templates/supply_console.tmpl
Labels: Hotfix, UI

#24024 fixes backpacks not being properly filled
  code/game/objects/items.dm
  code/modules/mob/mob.dm
Labels: Hotfix

#24021 Fixes responsive reagent for stock parts
  code/modules/mining/mine_turfs.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_defines.dm
  code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
Labels: Bug / Fix

#24004 Malf Fix
  code/game/machinery/computer/robot.dm
Labels: Bug / Fix

#23919 fixes some delays
  code/modules/mob/living/living.dm
Labels: Emoji This :+1: :-1:

#24030 R&D QoL - Destructive Analyzer
  code/modules/research/rdconsole.dm
Labels: Content, ❤️ Quality of Life ❤️

#24028 Fixes being able to givebomb somebody
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/give.dm
Labels: Exploitable, 🚓Fun Police🚓

#23946 Adds a rigsuit module for making your rigsuit plasmaproof
  code/modules/clothing/spacesuits/rig_modules/rig_modules.dm
  code/modules/research/designs/boards/misc.dm
Labels: :up: Powercreep :up:

#23742 [RFR] Ninja TLC
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/role/ninja.dm
  code/game/atoms_movable.dm
  code/game/objects/items/airbag.dm
  code/game/turfs/simulated/walls.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/power/cell.dm
  data/mode.txt
Labels: Tweak

#23906 Fixes a redefine
  __DEFINES/obj_defines.dm
  code/datums/black_market_item.dm
  code/game/objects/objs.dm
Labels: Bug / Fix

#23880 Adds Winter coats to cargo orders
  code/datums/supplypacks.dm
Labels: Content
