Repository vgstation-coders/vgstation13, pull requests merged in 2019-02, with the labels that each got.

#21495 Random Item uplink deal gives 50% discount (plus doesn't give nukeop items anymore lol)
  code/datums/uplink_item.dm
  code/game/objects/items/devices/uplinks.dm
Labels: Bug / Fix

#21488 Fixes sand just deleting the entire stack of itself rather when making bricks
  code/modules/mining/ores_coins.dm
Labels: Bug / Fix

#21468 Fixes empty snacks not dropping properly
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#21485 Trophy mount exploit fixes
  code/game/objects/items/mountable_frames/trophy_mount.dm
Labels: Bug / Fix

#21457 Datum Refactor Revengeance (SBO37-41)
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/malf.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/mind.dm
  code/datums/uplink_item.dm
  code/game/gamemodes/wizard/artifacts.dm
Labels: Bug / Fix, Content, Role Datums, Unatomic Uncle

#21467 Sanitizes some parts of storage item
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug / Fix, Sanity / Ghosthands

#21490 Updates the discord invite link info since it got deleted
  README.md
Labels: Oversight

#21503 Fixes mapped DNA injectors. Apparently.
  code/game/objects/items/weapons/dna_injector.dm
Labels: Bug / Fix

#21453 Cult Balance of the Month - February
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_tattoos.dm
  code/datums/gamemode/objectives/bloodcult.dm
  code/modules/mob/living/carbon/species.dm
Labels: Balance, Gameplay / Gamemode

#21466 Yet more cells
  code/game/objects/items/weapons/power_cells.dm
  code/modules/research/designs/engineering.dm
  icons/obj/power.dmi
Labels: Content

#21461 Makes examination only work for objects in view
  code/modules/mob/mob.dm
Labels: Bug / Fix

#21513 Fixes posibrains of dead crew being able to hear xenos
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#21525 [OBS-6/51] Fixes teleporting fruits leaving you buckled when thrown.
  code/datums/helper_datums/teleport.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Bug / Fix

#21523 Adds brass floors
  code/game/objects/items/stacks/tiles/mineral.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/mineral.dm
  icons/obj/items.dmi
  icons/turf/floors.dmi
Labels: Content

#21471 See Jobs For Other Races
  code/modules/mob/new_player/new_player.dm
Labels: Secret repo conflict.

#21509 Faction Antag Candidate Adjustment
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Role Datums, Tweak

#21494 Makes Bananannon, Banana Sword, Advanced Mime Gloves and Living Balloons job-exclusive rather than job-discounted, since only mimes and clowns can use them anyways
  code/datums/uplink_item.dm
  code/game/objects/items/devices/uplinks.dm
Labels: Tweak

#21473 Fixing roundstart clowns having their slot name on the manifest instead of their chosen name
  code/game/jobs/job/civilian.dm
Labels: Bug / Fix

#21486 Fixes being able to brush-spam to get a polar star/spur
  code/modules/mining/mine_turfs.dm
Labels: Unatomic Uncle

#21510 Fixes a typo in the Toxins Special drink
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Grammar / Formatting

#21316 Adds the Bangerboi bundle.
  code/game/objects/items/weapons/storage/uplink_kits.dm
Labels: Balance

#21537 Makes Candied Pear only require 1 pear instead of 2
  code/modules/food/recipes_microwave.dm
Labels: Hotfix

#21546 More pear typos
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Grammar / Formatting

#21526 Advanced Clown Shoes now require the user to be clumsy instead of requiring to be a clown.
  code/modules/clothing/shoes/miscellaneous.dm
Labels: 100% tested, Needs Fixing

#21542 removes stub file: ghoul
  code/modules/mob/living/simple_animal/hostile/ghoul.dm
Labels: File Cleanup

#21483 The thing can not cast fist if it has no hands
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/organs/organ_external.dm
  code/modules/spells/targeted/fist.dm
Labels: Balance

#21370 Adds flavoured sweets
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Content

#21555 Fix sleepy talk
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#21558 Fixes Brian not being a worthy prophet
  code/datums/religions.dm
Labels: Bug / Fix

#21566 Fixes being unable to grind ice in the reagentgrinder
  code/modules/reagents/machinery/reagentgrinder.dm
Labels: Consistency Issue

#21548 Avocado burgers now accept any type of meat, not just meat/animal
  code/modules/food/recipes_microwave.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#21198 Traitors are now more likely to spawn at roundstart on lower population.
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Gameplay / Gamemode

#21238 Adds EMP flashlight to syndie uplink
  code/datums/uplink_item.dm
  code/game/objects/items/devices/flashlight.dm
Labels: 100% tested

#21276 Latejoin roles may now increase the threat.
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Conflicts, Role Datums

#21448 Shoot candles with lasers to light them.
  code/game/objects/items/candle.dm
Labels: Content

#21280 Fixes stun revolvers not going on security belts
  code/game/objects/items/weapons/storage/belt.dm
Labels: Balance, Tweak

#21281 [OBS-3/51] Fixes shelter icon not updating on jaunt
  code/game/atoms_movable.dm
  code/game/objects/structures/inflatable.dm
Labels: Bug / Fix

#21420 Adds wearable, craftable warning cones
  code/defines/obj/weapon.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  icons/mob/head.dmi
  icons/mob/monkey_head.dmi
  icons/mob/species/vox/head.dmi
  icons/obj/janitor.dmi
Labels: Content

#21297 Gives Unathi claws
  code/modules/mob/living/carbon/species.dm
Labels: Consistency Issue

#21545 Dish Incubator QOL
  code/modules/virus2/disease2.dm
  code/modules/virus2/dishincubator.dm
  code/modules/virus2/effect/effect.dm
Labels: ❤️ Quality of Life ❤️

#21527 Dispense_prize function
  code/game/machinery/computer/arcade/arcade_game.dm
Labels: File Cleanup

#21577 Fixes ghost items on mass removal
  code/game/objects/items/weapons/storage/storage.dm
Labels: Hotfix

#21553 Adds a simple 'persistence' subsystem
  .gitignore
  __DEFINES/subsystem.dm
  code/controllers/subsystem/init/persistence.dm
  code/modules/credits/credits.dm
  data/persistence/round_counts_per_year.json
  vgstation13.dme
Labels: System

#21556 Makes Watchdog call a few world shutdown thingies it wasn't calling before
  code/modules/ext_scripts/watchdog.dm
  code/world.dm
Labels: 100% tested

#21368 Space Christianity Converts Everyone
  code/datums/religions.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/modules/mob/new_player/new_player.dm
Labels: Content

#21366 further dab fixes
  code/modules/mob/living/carbon/human/emote.dm
Labels: why

#21229 Adds the brain damage spell for Wizards.
  code/modules/spells/targeted/retard.dm
  code/modules/spells/targeted/targeted.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Content

#21573 Removes blinded from glare
  code/modules/spells/aoe_turf/glare.dm
Labels: Tweak

#21598 Changes dex cart description from five to four.
  code/datums/uplink_item.dm
Labels: Grammar / Formatting

#21582 Examine, guns, and campfire typo fixes
  code/ATMOSPHERICS/hvac/spaceheater.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
Labels: Grammar / Formatting

#21543 Angie lair tweaks
  code/modules/mining/mine_turfs.dm
  maps/randomvaults/mining/angie_lair.dmm
Labels: Mapping (Vault :question:)

#21576 You can now shoot OVER candles to light them
  __DEFINES/_macros.dm
  code/game/objects/items/candle.dm
Labels: Tweak

#21579 Adds aminocyprinidol
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content

#21606 Removes round ending should all revolutionaries be dead.
  code/datums/gamemode/factions/syndicate/rev.dm
Labels: Consistency Issue, Role Datums

#21600 Nerf Blink's smoke to not act like a free smoke bomb spam spell
  code/modules/spells/aoe_turf/blink.dm
Labels: Balance

#21616 Re-adds eject sanity, makes the href eject work properly.
  code/game/mecha/mecha.dm
Labels: Bug / Fix

#21611 All types of clothing items may now have SLOWDOWN
  code/game/machinery/computer/labor.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: System

#21604 Fixes Dynamic Mode "Checking the state of the round" every second during the shuttle trip to centcom
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Logging / Administration

#21572 Allows regular spacesuits to hold larger tanks in their suit slot.
  code/modules/clothing/clothing.dm
Labels: Balance, ❤️ Quality of Life ❤️

#21599 Makes vampire less likely to fire at roundstart (especially on lower populations).
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Balance, Role Datums

#21557 Fixes HasProximity() extreme fuckiness
  code/game/objects/structures/mannequin.dm
  code/game/turfs/turf.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Legacy Bug

#21449 Adds welding mask toggles to plasmaman engineer and atmos tech helmets
  code/modules/clothing/spacesuits/plasmamen.dm
Labels: Balance, Consistency Issue

#21601 Teleport cooldown changed to 45 sec, minus 10 per upgrade, 5 sec min
  code/modules/spells/general/area_teleport.dm
Labels: Balance

#21630 This PR's name was edited by the cult gang
  code/datums/gamemode/role/cultist.dm
Labels: Bug / Fix

#21631 Cult gang fixes part II: Security rises
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix

#21563 Fixes mesons and night vision not changing vision when combined with x-rays.
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
Labels: 100% tested

#20856 Ambience subsystem v2 - less shitty and gritty edition
  __DEFINES/subsystem.dm
  code/controllers/subsystem/ambient_sound.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/ambience_datums.dm
  code/game/area/areas.dm
  code/modules/client/client defines.dm
  vgstation13.dme
Labels: Sound, System

#21633 Janitrashbag revival
  code/game/objects/items/weapons/storage/bags.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#21651 You may NOT have my attention
  code/game/area/ambience_datums.dm
Labels: Sound

#21640 Midround Ops Forge Objectives (SBO45)
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Role Datums

#21627 The Chaplain Update, Part 1: The "Incense Update"
  __DEFINES/reagents.dm
  code/_onclick/hud/fullscreen.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/religions.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/machinery/vending.dm
  code/game/objects/items/incense.dm
  code/game/objects/items/weapons/null_rod.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/reagents/Chemistry-Reagents.dm
  icons/effects/160x160.dmi
  icons/mob/in-hand/left/incense.dmi
  icons/mob/in-hand/right/incense.dmi
  icons/obj/incense.dmi
  vgstation13.dme
Labels: Content

#21550 Blob Rebalance
  code/game/gamemodes/blob/_blob_defines.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/blob/blobs/resource.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/blob/powers.dm
  code/game/gamemodes/blob/theblob.dm
  code/game/objects/items/devices/transfer_valve.dm
Labels: Balance, Update WIKI

#21639 Uplinks Get Dropped (SBO44)
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/syndicate.dm
Labels: Bug / Fix

#21662 MoMMIs can now use the forge
  code/WorkInProgress/MadmanMartian/blacksmithing/forge.dm
Labels: Bug / Fix

#21560 fix midround / latejoin injection
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Role Datums

#21296 [OBS-5/51] Brings back THE PAPER :tm:
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/misc_gamemode_procs.dm
Labels: Bug / Fix, Role Datums

#21496 Syndie Bundles cost 14 TC, down from 20
  code/datums/uplink_item.dm
Labels: Balance, Tweak

#21497 Wizard spell bundles cost 80 spellpoints, down from 100
  code/game/gamemodes/wizard/artifacts.dm
  code/game/objects/items/weapons/storage/bags.dm
Labels: Balance, Gameplay / Gamemode, Tweak

#21508 Wines and grape juice
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  icons/obj/drinks.dmi
Labels: 100% tested

#20298 Slip refactor
  __DEFINES/clothing.dm
  __DEFINES/turfs.dm
  code/ZAS/Airflow.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/weapons/grenades/clowngrenade.dm
  code/game/turfs/turf.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/simple_animal/friendly/slime.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/mob.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/slipping.dm
Labels: Needs Changelog, System

#21506 Now you can ctrl-click fire alarms to toggle them on or off.
  code/game/machinery/alarm.dm
Labels: 100% tested, ❤️ Quality of Life ❤️

#21554 Loose Catbeast Miniantag
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/objectives/catbeast.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/syndicate.dm
  code/modules/client/preferences.dm
  icons/logos.dmi
  vgstation13.dme
Labels: Role Datums

#21641 Removes credits debugging
  code/modules/credits/credits.dm
  code/modules/credits/episode_name.dm
Labels: System, Unatomic Uncle

#21644 Sync Borgs At Roundstart (SBO46)
  code/game/gamemodes/gameticker.dm
  code/modules/mob/living/silicon/robot/laws.dm
Labels: Bug / Fix

#21667 Fixes cultist brains put in MMI being able to hear cult chat messages.
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix

#21634 Introducing the NINJAMOP
  code/game/objects/items/weapons/mop.dm
  code/game/objects/structures/mop_bucket.dm
  code/game/sound.dm
  sound/effects/mop1.ogg
  sound/effects/mop2.ogg
  sound/effects/mop3.ogg
  sound/effects/mop4.ogg
  sound/effects/mop5.ogg
  sound/effects/mopbucket.ogg
Labels: Tweak, ❤️ Quality of Life ❤️

#21679 Fixes lonely robots BRICKING THE ENTIRE GAMESTART
  code/datums/wires/robot.dm
  code/game/gamemodes/gameticker.dm
  code/modules/mob/living/silicon/mommi/life.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Hotfix, ⚠️ OH GOD IT'S LOOSE ⚠️

#21666 Can now smelt mythril and telecrystal
  __DEFINES/setup.dm
  code/modules/mining/materials.dm
  code/modules/mining/minerals.dm
  code/modules/mining/ores_coins.dm
  code/modules/mining/smelting.dm
Labels: Content

#21649 Janitor PDA also tracks janicarts
  code/__HELPERS/global_lists.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/structures/vehicles/janicart.dm
Labels: Content

#21605 Adds spare trader IDs
  code/game/machinery/vending.dm
  code/game/objects/items/trader.dm
Labels: ❤️ Quality of Life ❤️

#21594 Adds a fake SPS noise to the sound synth
  code/game/objects/items/devices/sound_synth.dm
  sound/items/fake_SPS.ogg
Labels: Content

#21608 Analysis now appends the type of pathogen as its name, rather than stamm
  code/modules/virus2/disease2.dm
Labels: Content

#21590 Refactors assistant job limit for labor console compatibility
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job_controller.dm
  code/game/machinery/computer/labor.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix

#21565 You shouldn't mess with the anime club..... they have grown in power..........
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/weeaboo.dm
  code/game/objects/items/mountable_frames/posters/poster.dm
  code/game/objects/items/weapons/weaponry.dm
  icons/obj/posters.dmi
  icons/obj/weapons.dmi
Labels: Content

#21669 Fixes glass tiles
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/tiles/tiles.dm
Labels: Bug / Fix

#21619 Add the first purely Chaplain traitor item
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/projectiles/guns/projectile/pistol.dm
Labels: Content

#21678 Threat Log (SBO47-48)
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/role.dm
  code/modules/admin/topic.dm
Labels: Bug / Fix, Logging / Administration

#21685 Forgot something crucial about altar holomaps
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
Labels: Bug / Fix, Hotfix

#21480 super singularity god super singularity
  __DEFINES/setup.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/modules/power/singularity/singularity.dm
  code/modules/supermatter/supermatter.dm
  icons/effects/384x384.dmi
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#21697 Fixes the name of some designs.
  code/modules/research/designs/robotics.dm
  code/modules/research/designs/weapons.dm
Labels: Grammar / Formatting

#21686 Catbeast Tweaks
  code/datums/gamemode/role/catbeast.dm
Labels: Balance, Role Datums

#21709 Sweets spelling mistake
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix, Grammar / Formatting

#21714 MODE Takes No Job (SBO55)
  code/datums/gamemode/role/role.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix

#21716 fixes ghetto splints not consuming cablecuffs
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
Labels: Easy Fix

#21712 More bibles and books in-hand sprites
  code/datums/gamemode/factions/legacy_cult/ritual.dm
  code/game/gamemodes/wizard/spellbook.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/weapons/manuals.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/library/computers/checkout.dm
  code/modules/library/lib_machines.dm
  icons/mob/in-hand/left/books.dmi
  icons/mob/in-hand/left/drinkingglass.dmi
  icons/mob/in-hand/right/books.dmi
  icons/mob/in-hand/right/drinkingglass.dmi
  icons/obj/library.dmi
  icons/obj/storage/bibles.dmi
  icons/obj/storage/storage.dmi
Labels: Sprites

#21726 Runtime hunting: Boulders
  code/modules/mining/mine_turfs.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
Labels: Bug / Fix, Runtime Log

#21727 runtime hunting: ores
  code/modules/mining/ores_coins.dm
Labels: Bug / Fix, Runtime Log

#21724 Fixes being able to spam out bunches of overlays as an artificer
  code/modules/spells/aoe_turf/conjure/construct.dm
Labels: Bug / Fix, Oversight

#21722 Fixes being able to see if a crate is a mimic through an oversight
  code/modules/mob/living/simple_animal/hostile/mimic.dm
Labels: Bug / Fix, Oversight

#21721 Fixes bananium not showing
  icons/turf/mine_overlays.dmi
Labels: Bug / Fix

#21725 Removes interactive map debug
  code/modules/html_interface/map/interactive_map.dm
Labels: File Cleanup

#21713 Tome radials on AltClick
  code/_onclick/hud/radial.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
Labels: Content

#21710 Adds burning swirlies and BURN/BRUTE damage corrections for greys
  code/game/objects/structures/watercloset.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Content, Unatomic Uncle

#21708 adds canned coffee as premium soda machine item
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  icons/obj/drinks.dmi
Labels: Content

#21602 Breaks up the virus2/effect file into stages
  code/modules/virus2/effect/effect.dm
  code/modules/virus2/effect/stage_1.dm
  code/modules/virus2/effect/stage_2.dm
  code/modules/virus2/effect/stage_3.dm
  code/modules/virus2/effect/stage_4.dm
  code/modules/virus2/effect/stage_special.dm
  vgstation13.dme
Labels: File Cleanup

#21544 Changes slime split results.
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/carbon/slime/subtypes.dm
Labels: Feature Request, Tweak, Update WIKI

#21728 Runtime hunting: Storage
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug / Fix, Runtime Log

#21731 Runtime hunting - beaker update_icon()
  code/modules/reagents/reagent_containers/glass.dm
Labels: Bug / Fix, Runtime Log

#21699 No TTVs for Midround Nuke Ops
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/game/objects/effects/spawners/bombspawner.dm
Labels: Balance

#21736 Runtime hunting: labor console
  code/game/machinery/computer/labor.dm
Labels: Bug / Fix, Runtime Log

#21732 Runtime hunting: soulstones
  code/datums/gamemode/factions/legacy_cult/soulstone.dm
Labels: Bug / Fix, Runtime Log

#21735 Runtime hunting: storage 2
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug / Fix, Runtime Log

#21734 Exploit fix: Safe
  code/game/objects/structures/safe.dm
Labels: Bug / Fix, Exploitable, Sanity / Ghosthands

#21729 Runtime hunting: Metal detector
  code/game/machinery/metaldetector.dm
Labels: Bug / Fix, Runtime Log

#21739 Runtime hunting - storage 3
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/paperwork/clipboard.dm
Labels: Bug / Fix, Runtime Log

#21738 Runtime hunting: cameras
  code/game/machinery/camera/camera.dm
Labels: Bug / Fix, Runtime Log

#21740 more inhand sprites
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/in-hand/left/food.dmi
  icons/mob/in-hand/right/food.dmi
Labels: Sprites

#21706 Mug overlays
  code/modules/reagents/Chemistry-Colours.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  icons/obj/reagentfillings.dmi
Labels: Sprites

#21564 Repeatable Gamemodes
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Role Datums

#21743 Runtime hunting - Ambience
  code/controllers/subsystem/ambient_sound.dm
Labels: Bug / Fix, Runtime Log

#20915 Re-adds blob to the rotation
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/blob.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/objectives/invade.dm
  code/datums/gamemode/role/role.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/meteor/meteors.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/events/meteors.dm
  maps/bagelstation.dm
  maps/roidstation.dm
  vgstation13.dme
Labels: Role Datums

#21620 Actually delayed revs this time
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/role/rev.dm
  code/modules/credits/episode_name.dm
Labels: 100% tested, Bug / Fix, Gameplay / Gamemode, Role Datums

#21755 Fixing Syndicate "Screwed" Bundle
  code/game/objects/items/weapons/storage/uplink_kits.dm
Labels: Bug / Fix, Hotfix

#21744 Runtime hunting - DragnDrop
  code/_onclick/drag_drop.dm
Labels: T-Thanks BYOND

#21759 Preventing borged cultist brains from hearing the voice of narsie
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
Labels: Bug / Fix

#21610 New Rev Modes: RevSquad and Provocateur
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/role/rev.dm
  code/game/communications.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/projectiles/ammunition/speedloaders.dm
Labels: Content, Gameplay / Gamemode

#21745 Runtime hunting: IEDs
  code/game/objects/items/weapons/grenades/ghettobomb.dm
Labels: Bug / Fix, Runtime Log

#21746 Runtime hunting - Mortem farting
  code/modules/mob/living/carbon/human/emote.dm
Labels: Bug / Fix, Runtime Log

#21681 Increases maximum queue limit for Protolathe and Circuit Imprinter to 50
  code/modules/research/rdconsole.dm
Labels: Tweak

#21748 Runtime hunting - Casing drop sound
  code/modules/projectiles/guns/projectile.dm
  sound/weapons/casing_drop.ogg
Labels: Content, Runtime Log, Sound

#21751 Feint blade fix
  code/game/objects/items/weapons/weaponry.dm
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/swords_axes.dmi
  icons/mob/screen_spells.dmi
  icons/obj/weapons.dmi
Labels: Bug / Fix, Tweak, Unatomic Uncle

#21595 Upon travelling through a window, a lasers damage is affected by the window itself
  code/game/objects/structures/window.dm
Labels: Balance, Controversial

#21704 tomato soup premium item for coffee machines
  __DEFINES/reagents.dm
  code/game/machinery/vending.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/drinks.dmi
Labels: Conflicts, Content

#21783 Merchant Report Mugshot Fixed (SBO58)
  code/modules/paperwork/paper.dm
Labels: Bug / Fix

#21784 tomato soup is now red
  code/modules/reagents/Chemistry-Reagents.dm
Labels: 100% tested

#21692 Adds scientist screams
  code/modules/mob/living/carbon/emote.dm
  sound/misc/science_scream1.ogg
  sound/misc/science_scream2.ogg
  sound/misc/science_scream3.ogg
  sound/misc/science_scream4.ogg
  sound/misc/science_scream5.ogg
  sound/misc/science_scream6.ogg
Labels: Honk, Sound, why

#21701 Datums Readme (SBO47-54)
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_readme.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/role/weeaboo.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/mob/living/living.dm
  vgstation13.dme
Labels: Bug / Fix, Conflicts, Role Datums, Tweak, Unatomic Uncle

#21788 Latejoin Threat Logging Hotfix
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Hotfix

#21682 Adds the Prototype Bluespace RPED
  code/game/machinery/machinery.dm
  code/game/objects/items/weapons/storage/RPED.dm
  code/modules/research/designs/engineering.dm
  icons/mob/in-hand/left/misc_tools.dmi
  icons/mob/in-hand/right/misc_tools.dmi
  icons/obj/storage/storage.dmi
Labels: Conflicts, Content

#21781 Chisel the Cistern
  code/game/objects/structures/watercloset.dm
Labels: IT'S A FEAAAATUUUUREEEEEEEEE
