Repository vgstation-coders/vgstation13, pull requests merged in 2020-04, with the labels that each got.

#26088 Adds Avali as a playable race
  __DEFINES/global.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/job.dm
  code/modules/client/preferences.dm
  code/modules/clothing/under/color.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_environment.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/r_avali.dmi
  icons/mob/species/avali/back.dmi
  icons/mob/species/avali/belt.dmi
  icons/mob/species/avali/ears.dmi
  icons/mob/species/avali/eyes.dmi
  icons/mob/species/avali/feet.dmi
  icons/mob/species/avali/gloves.dmi
  icons/mob/species/avali/head.dmi
  icons/mob/species/avali/id.dmi
  icons/mob/species/avali/mask.dmi
  icons/mob/species/avali/suit.dmi
  icons/mob/species/avali/uniform.dmi
Labels: Content, Honk

#26087 Gamer fixes
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/streamer.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/camera.dm
  code/modules/clothing/accessories/spesstv.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/research/mechanic/flatpacker.dm
Labels: Bug / Fix, Tweak, Unatomic Uncle

#26089 Flatpacks are now layered above machinery
  code/modules/research/mechanic/flatpack.dm
Labels: Bug / Fix

#26080 Head positions set to Low or Medium no longer take precedence over other roles
  code/game/jobs/job_controller.dm
Labels: Tweak

#26040 Fixes(?) a bug where the soulstone would not trigger the SPS even if it killed the victim
  code/datums/gamemode/factions/legacy_cult/soulstone.dm
Labels: Bug / Fix

#26095 New Mortar Icon
  code/modules/reagents/machinery/mortar.dm
  icons/obj/chemical.dmi
Labels: Sprites

#26073 Fix traitor reaganomics
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: 100% tested, Bug / Fix

#26064 Makes NTD less terrible (by removing Evaluate)
  code/datums/ai_laws.dm
  code/game/objects/items/weapons/ai_modules/core.dm
Labels: Tweak, Update WIKI

#26074 An attempt at fixing autotraitor inflation
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Balance

#25981 Randomize shrapnel damage
  code/modules/projectiles/projectile/bullets.dm
Labels: Tweak

#26102 Fixes a few hair-clipping-through-helmets bugs
  code/modules/clothing/head/misc.dm
Labels: Bug / Fix

#26098 Lowpop rounds will no longer use the setting 'classic secret'
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Emoji This :+1: :-1:, Gameplay / Gamemode

#26042 Xenomorphs should no longer hulk-scream when trying to break out of restraints
  code/modules/mob/living/living.dm
Labels: Muh Immulsions

#26094 Raises the amount of roundstart cultists back to 4
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Balance

#26045 Syndicate robot module changes
  code/game/objects/items/robot/robot_items/robot_rack.dm
  code/game/objects/structures/stool_bed_chair_nest/rollerbed.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance

#26081 Fixes lockbox variants of automatic projectile weapons conjuring ammo from thin air.
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
Labels: Bug / Fix

#26118 Adds some new insectoid customization, fixes two (2) missing pixels
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: 100% tested, Bug / Fix, Sprites

#26110 Nerf (almost) all stun bullets
  code/modules/projectiles/projectile/bullets.dm
Labels: Balance

#26105 No more plant gene decay
  code/modules/hydroponics/seed_machines.dm
  nano/templates/botany_editor.tmpl
  nano/templates/botany_isolator.tmpl
Labels: Feature Loss

#26123 Med-HUDs can now identify zombies.
  code/game/data_huds.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
  icons/mob/hud.dmi
Labels: ❤️ Quality of Life ❤️

#26000 buff stoxin2 and make sleeper use it
  code/game/machinery/Sleeper.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#26103 Zombies created by the Stubborn Brain virus syndrome are now player-controlled.
  code/modules/virus2/effect/stage_4.dm
Labels: Balance, Tweak

#26119 Allows voice changers to properly mimick robotic voices
  __DEFINES/clothing.dm
  code/game/say.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#26136 fixes supermatter singulo interaction log messages
  code/modules/supermatter/supermatter.dm
Labels: Bug / Fix, Logging / Administration

#26135 Fixed microwave failing for no reason
  code/datums/recipe.dm
Labels: Bug / Fix

#26107 Ensure bodies created for rulesets are not mindless
  code/modules/admin/verbs/one_click_antag.dm
Labels: Bug / Fix, Runtime Log

#26117 Removes fuck-up boots from spellbook
  code/game/gamemodes/wizard/artifacts.dm
Labels: Feature Loss

#26122 buffs traitor tape a lot
  code/WorkInProgress/Ported/policetape.dm
Labels: :up: Powercreep :up:

#26137 Fixed unbuckling while handcuffed not working
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Bug / Fix

#26125 Dynamic has been unleashed
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Balance, Gameplay / Gamemode

#26033 Outfit datums: captain, science, trader
  code/datums/outfit/captain.dm
  code/datums/outfit/science.dm
  code/datums/outfit/trader.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job/whitelisted.dm
  code/game/jobs/job_controller.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/species.dm
  vgstation13.dme
Labels: Needs Fixing, System

#26138 Two meaningless fixes related to esports
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/streamer.dm
Labels: Bug / Fix

#26143 Fixes spacepod locking system
  code/WorkInProgress/pomf/spacepods/spacepods.dm
Labels: Bug / Fix

#26106 Fixes a few runtimes related to hitmarkers
  code/game/atoms_movable.dm
  code/game/machinery/computer/camera.dm
Labels: Runtime Log

#26120 Putrid zombies will no longer attack zombies that they create.
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: Oversight, Tweak

#26146 RDs now have ties
  code/datums/outfit/science.dm
Labels: Oversight

#26150 makes dynamic work for roundstart
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Hotfix

#26151 Pills can be crushed into cauldrons
  code/modules/reagents/reagent_containers/pill.dm
Labels: Tweak

#26133 Added maps/backup to .gitignore
  .gitignore
Labels: Bad Faith :latin_cross:

#26140 Fixed EMP'd AI shuttle call and more
  code/game/machinery/computer/communications.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Bug / Fix

#26160 Dynamic mode will display the correct numbers in the logs
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Bug / Fix

#26164 makes dionae the supreme race like we always wanted!
  code/modules/mob/living/carbon/species.dm
Labels: Unable To Reproduce

#26165 Revert "makes dionae the supreme race like we always wanted!"
  code/modules/mob/living/carbon/species.dm
Labels: 🚓Fun Police🚓

#26178 Fixes sec record preview
  code/datums/datacore.dm
Labels: Bug / Fix

#26139 Game Master gets a dice bag with a digital dice
  code/game/jobs/job/civilian.dm
Labels: Tweak

#26121 Unfuckups the fuck-up boots
  code/game/gamemodes/wizard/artefact.dm
  code/modules/mob/mob.dm
  code/modules/spells/aoe_turf/blink.dm
  code/modules/spells/aoe_turf/fall.dm
  code/modules/spells/spell_code.dm
  icons/mob/screen_spells.dmi
Labels: Balance, Tweak

#26180 Fixes a few things with pointing
  code/__HELPERS/unsorted.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix

#26184 Bot bugfixes
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/mulebot.dm
Labels: Bug / Fix

#26176 Add Snails!
  code/datums/helper_datums/butchering.dm
  code/datums/supplypacks.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/clothing/head/helmet.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/holders.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/snail.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/egg.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  icons/mob/animal.dmi
  icons/mob/head.dmi
  icons/mob/in-hand/left/food.dmi
  icons/mob/in-hand/left/hats.dmi
  icons/mob/in-hand/left/mob_holders.dmi
  icons/mob/in-hand/right/altsuits.dmi
  icons/mob/in-hand/right/food.dmi
  icons/mob/in-hand/right/hats.dmi
  icons/mob/in-hand/right/mob_holders.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/food.dmi
  vgstation13.dme
Labels: Content

#26188 Fixes broken sprites, and fixes ghetto hardsuits and yellow hardhats …
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/spacesuits/rig.dm
  icons/mob/species/insectoid/ears.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/suit.dmi
Labels: Bug / Fix, Sprites

#26198 Fixes Janky Beepers
  code/game/machinery/bots/bots.dm
Labels: Bug / Fix

#26201 Fixes some runtimes with bots.
  code/defines/procs/AStar.dm
  code/game/machinery/bots/bots.dm
  code/modules/components/ai/controllers/movement.dm
  code/modules/spells/aoe_turf/conjure/pitbulls.dm
Labels: Bug / Fix, Runtime Log

#26204 Deleting smartglass electronics or supermatter shards/crystals no longer bricks all radio connections on the same frequency
  code/game/machinery/smartglass.dm
  code/modules/supermatter/supermatter.dm
Labels: Bug / Fix, Runtime Log

#26179 Shields now properly block stun batons and syringes
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Bug / Fix, Legacy Bug

#26206 Fixes being able to harmbaton people with an inactive baton
  code/game/objects/items/weapons/stunbaton.dm
Labels: 100% tested, ⚠️ OH GOD IT'S LOOSE ⚠️

#26212 Make regular dynamic roll if forced rulesets have failed.
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Bug / Fix

#26189 Makes beanbag shells not retarded again.
  code/modules/projectiles/projectile/bullets.dm
Labels: Tweak

#26207 Fixes a few runtimes with AStar
  code/controllers/subsystem/pathing.dm
  code/defines/procs/AStar.dm
Labels: Runtime Log

#26217 Fixes stutter for a few actions
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/game/mecha/equipment/tools/sec_tools.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/vehicles/adminbus.dm
  code/modules/clothing/gloves/miscellaneous.dm
  maps/RandomZLevels/hive.dm
Labels: Bug / Fix

#26210 Fixes a pair of runtimes
  code/game/machinery/bees_apiary.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Bug / Fix

#26185 Fix IEDs breaking the fabric of space and time
  code/defines/obj/weapon.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/living.dm
Labels: Bug / Fix

#26227 Makes the plasma cutter generate logs
  code/__HELPERS/unsorted.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/projectiles/projectile.dm
Labels: Logging / Administration

#26225 The station time will now be exported with a status() call
  code/world.dm
Labels: ❤️ Quality of Life ❤️

#26224 Fixes some issues with midround malf
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Bug / Fix

#26230 Midround rulesets poll ghosts with preferences set to No
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Tweak

#26158 Removes autoborger cooldown
  code/game/machinery/autoborger.dm
Labels: Balance, Tweak

#26234 fixes layering issues with pre-mapped tape
  code/WorkInProgress/Ported/policetape.dm
Labels: Bug / Fix

#26130 Adds the plasmaman sith suit and changes a little how bundles work
  code/datums/uplink_item.dm
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  icons/mob/species/plasmaman/head.dmi
  icons/mob/species/plasmaman/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Conflicts, Content

#26216 Fixes dionae player request logic
  code/modules/hydroponics/seed_mobs.dm
Labels: Bug / Fix

#26233 The search for AStar runtimes part 2
  code/controllers/subsystem/pathing.dm
  code/defines/procs/AStar.dm
  code/game/machinery/bots/cleanbot.dm
Labels: Runtime Log

#26253 hotfix for rev flash runtime, which did not prevent execution of any related code
  code/game/objects/items/devices/flash.dm
Labels: Hotfix

#26231 Hazard vest suit storage accepts several cargo-related items
  code/modules/clothing/suits/jobs.dm
  code/modules/paperwork/envelope.dm
  code/modules/paperwork/stamps.dm
Labels: Needs Fixing

#26255 Revert "The search for AStar runtimes part 2"
  code/controllers/subsystem/pathing.dm
  code/defines/procs/AStar.dm
  code/game/machinery/bots/cleanbot.dm
Labels: Hotfix, Runtime Log

#26256 Forgot this for #26231
  code/modules/paperwork/envelope.dm
Labels: Hotfix

#26220 Food processor now transfers reagents and can be filled with a plant bag
  code/game/machinery/kitchen/processor.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Consistency Issue, Tweak

#26264 Actually fixes AStar runtimes
  code/controllers/subsystem/pathing.dm
  code/datums/disease.dm
  code/defines/procs/AStar.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/modules/spells/aoe_turf/conjure/bats.dm
  code/modules/spells/aoe_turf/conjure/pitbulls.dm
Labels: Runtime Log, ⚠️ OH GOD IT'S LOOSE ⚠️

#26275 Makes Random Items Not Give Free Bundles
  code/datums/uplink_item.dm
Labels: Hotfix

#26276 HFHF
  code/datums/uplink_item.dm
Labels: Hotfix

#26280 Fixes turret controllers
  code/game/machinery/turrets.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/turretid.dm
Labels: Bug / Fix

#26283 Possibly fixed the bug that caused locker contents to spawn twice
  __DEFINES/setup.dm
  code/controllers/subsystem/objects.dm
  code/game/atoms.dm
Labels: Bug / Fix

#26269 Makes the GC into an actual subsystem
  code/controllers/garbage.dm
  code/controllers/mc/admin.dm
  code/controllers/subsystem/garbage.dm
  vgstation13.dme
Labels: System

#26247 ai hologram beachball
  code/modules/mob/living/silicon/ai/ai.dm
  icons/mob/AI.dmi
Labels: Content

#26281 Added fluoride stare
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Content

#26236 Simpolinol
  __DEFINES/reagents.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content

#26267 Aghost Toggle Windoor
  code/game/machinery/doors/windowdoor.dm
Labels: Logging / Administration

#26277 Better Pheromones
  code/modules/reagents/Chemistry-Reagents.dm
Labels: ❤️ Quality of Life ❤️

#26235 An experiment on making higher threat rulesets more common.
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Gameplay / Gamemode

#26301 Add gibbing funcion for plasamemes
  code/modules/mob/living/carbon/human/plasmaman/species.dm
Labels: Bug / Fix

#26279 Bomb Armor Is Better
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance

#26241 Adds the Jazz & Swing vinyl
  code/modules/media/jukebox.dm
Labels: Sound, ✋ Do Not Merge ✋

#26248 Spesschan
  code/game/machinery/newscaster.dm
Labels: Content

#26303 More Chaplain Religions And Clothing
  code/datums/religions.dm
Labels: Content, Tweak, Update WIKI

#26289 Add a funny effect to ring of fire
  code/modules/spells/general/ring_of_fire.dm
  sound/weapons/fireball.ogg
Labels: Content

#26282 adds harm baton to uplink
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/stunbaton.dm
  icons/obj/weapons.dmi
Labels: Content

#26186 Primetime
  __DEFINES/dates.dm
  code/__HELPERS/time.dm
  code/controllers/mc/admin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/new_player/new_player.dm
Labels: Gameplay / Gamemode, Secret repo conflict.

#26325 Fixed agent ID cards getting bricked when reset
  code/game/objects/items/weapons/cards_ids.dm
Labels: Bug / Fix

#26274 Fixes Security Rockets
  code/modules/projectiles/ammunition/rocket.dm
  code/modules/projectiles/projectile/rocket.dm
Labels: :thinking:, Bug / Fix, Needs Fixing, Tweak

#26290 Improved travis
  .travis.yml
  __DEFINES/__spaceman_dmm.dm
  tools/travis/install_spaceman_dmm.sh
  vgstation13.dme
Labels: System

#26305 Fixes golden extract mimic reaction
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix, Feature Loss

#26261 Added option for admins to deadmin on login
  __DEFINES/setup.dm
  code/modules/client/client procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Logging / Administration, Secret repo conflict.

#26318 Reduces cult endgame from 3 minutes and 20 seconds to 2 minutes
  code/datums/gamemode/objectives/bloodcult.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/monkey/death.dm
  code/modules/mob/living/carbon/slime/death.dm
Labels: 0% tested, Tweak

#26330 Fixed thrown pies not immediately going SPLAT
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#26316 New Mecha Stuff
  code/_onclick/hud/screen_objects.dm
  code/game/machinery/vending.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/passive/passive.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/trader.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/mob/inventory.dm
  code/modules/research/designs/mecha/tools.dm
  icons/mecha/mecha_equipment.dmi
  sound/effects/rustle-metal.ogg
  vgstation13.dme
Labels: Content, Update WIKI

#26319 Upgrade Injectors
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/RPED.dm
  icons/obj/syringe.dmi
Labels: Conflicts, Content

#26327 Wet/Dry Vac
  code/game/machinery/vending.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/trader.dm
  icons/mob/in-hand/left/misc_tools.dmi
  icons/mob/in-hand/right/misc_tools.dmi
  icons/obj/objects.dmi
  sound/effects/vacuum.ogg
Labels: Conflicts, Content
