Repository vgstation-coders/vgstation13, pull requests merged in 2020-06, with the labels that each got.

#26658 Celldoor hotfixes
  code/game/machinery/doors/brigdoors.dm
  code/game/objects/items/sec_lawplanner.dm
Labels: Hotfix

#26641 simplifies colt
  code/modules/projectiles/guns/projectile/revolver.dm
Labels: Tweak

#26629 Adds Penguins
  code/modules/mob/living/simple_animal/friendly/penguin.dm
  icons/mob/animal.dmi
  sound/voice/penguin.ogg
  vgstation13.dme
Labels: Content

#26630 a better way to fix guns not shooting
  code/modules/projectiles/guns/projectile.dm
Labels: Bug / Fix

#26657 Afflictus Emittus and more
  code/_onclick/click.dm
  code/game/objects/effects/beam.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/maracas.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/organs/organ_objects.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/projectile.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/effect/effect.dm
  code/modules/virus2/effect/stage_4.dm
  icons/effects/beam.dmi
  icons/mob/eyes.dmi
  icons/mob/monkey_eyes.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/surgery.dmi
Labels: Content, Performance

#26467 Parachad/Medivend changes
  code/game/jobs/job/paramedic.dm
  code/game/machinery/vending.dm
Labels: Controversial

#26680 Why can't you be normal code?
  code/game/mecha/mecha.dm
  code/game/mecha/medical/odysseus.dm
  code/game/mecha/working/working.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix

#26675 BUGFIXES: Fixed a bunch of emitter issues
  code/game/atoms.dm
  code/game/objects/effects/beam.dm
  code/game/objects/effects/step_triggers.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix

#26678 Fixes various Super Soaker issues
  code/modules/projectiles/guns/projectile/siren.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/reagents/reagent_dispenser.dm
  icons/mob/in-hand/left/guns.dmi
  icons/mob/in-hand/right/guns.dmi
Labels: Bug / Fix, Runtime Log, Sprites

#26681 AAC Importing
  code/modules/atmos_automation/console.dm
Labels: ❤️ Quality of Life ❤️

#26656 Reduces overall vending machine prices
  code/game/machinery/vending.dm
Labels: Balance

#26614 Mushroom Nourishment
  __DEFINES/_macros.dm
  __DEFINES/setup.dm
  code/__HELPERS/lists.dm
  code/game/objects/items/devices/inhaler.dm
  code/game/objects/items/devices/instruments.dm
  code/game/objects/items/gum.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/kitchen.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/combat.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
  code/modules/mob/living/carbon/human/life/handle_stomach.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Emoji This :+1: :-1:

#26659 Better Scan
  code/game/machinery/adv_med.dm
Labels: ❤️ Quality of Life ❤️

#26686 removes fun
  code/modules/recycling/disposal.dm
Labels: 🚓Fun Police🚓

#26687 [HOTFIX] Fixes Mirrors and Prisms' interactions with beams being utterly broken
  code/modules/assembly/infrared.dm
  code/modules/optics/mirrors/mirror.dm
  code/modules/optics/prism.dm
  code/modules/power/singularity/emitter.dm
  code/modules/virus2/effect/stage_4.dm
Labels: Hotfix

#26691 Fix Afflictus Emittus on death
  code/modules/virus2/effect/stage_4.dm
Labels: Bug / Fix, Hotfix

#26683 nia (short) hairstyle + new ponytail hairstyle
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#26661 The Phantom Pain
  code/modules/organs/organ_internal.dm
Labels: Bug / Fix

#26692 Makes the typing indicator animated
  code/modules/mob/typing_indicator.dm
  icons/mob/talk.dmi
Labels: Bug / Fix

#26664 No Flask
  code/game/machinery/vending.dm
Labels: Feature Loss

#26650 Tweaks Colorful Syndrome so it cannot activate in Mice, and lowers its danger level
  code/modules/virus2/effect/stage_3.dm
Labels: Emoji This :+1: :-1:, Tweak

#26704 New Rows on FBS
  code/game/machinery/adv_med.dm
Labels: Bug / Fix

#26698 Infrared Emitters: THE COMEBACK! ("Five Years Later" edition)
  __DEFINES/setup.dm
  code/datums/supplypacks.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/beam.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/modules/assembly/assembly.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/timer.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/reagents/reagent_dispenser.dm
  icons/effects/beam.dmi
  icons/obj/assemblies/new_assemblies.dmi
Labels: Content

#26705 Fixed interactions between Infrared beams and portals
  code/game/objects/effects/portals.dm
Labels: Bug / Fix, Hotfix

#26716 fixes SPSes showing up on the GPS list and vice versa
  code/modules/telesci/gps.dm
Labels: Hotfix

#26712 Another shot at fixing broken persistent broken growth dishes
  code/game/objects/effects/decals/Cleanable/misc.dm
Labels: Bug / Fix, Hotfix

#26720 fixes windoors not using their passed electronics
  code/game/objects/structures/windoor_assembly.dm
Labels: Bug / Fix

#26690 Pops economic inflation like a balloon
  code/modules/store/items.dm
Labels: Tweak

#26688 Emitter Re-Sprite
  code/modules/power/singularity/emitter.dm
  icons/obj/singularity.dmi
  maps/RandomZLevels/challenge.dm
Labels: Sprites

#26696 Fixes cargo carts being able to load anchored atoms
  code/game/objects/structures/vehicles/carts/cargo.dm
Labels: Bug / Fix, 🚓Fun Police🚓

#26734 Fixes Nuke Ops Grenade Launcher (and the regular one as well) firing when getting put in a backpack
  code/modules/reagents/grenade_launcher.dm
Labels: Bug / Fix, Hotfix

#26728 Fix floorbots
  __DEFINES/machinery.dm
  code/defines/procs/AStar.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/floorbot.dm
Labels: Bug / Fix

#26724 Adds [date] & [time] tags for paperwork and ports tables from Bay
  code/modules/paperwork/pen.dm
Labels: Content, Port

#26723 bucket now has armor values
  code/game/objects/items/trash.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Tweak

#26695 Fixes radio transmitters not overheating due shitcode.
  code/modules/media/broadcast/transmitters/broadcast.dm
Labels: Bug / Fix

#26721 Ports goon large artifact sprites
  __DEFINES/archaeo_defines.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_affect_cold.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_badfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cellcharge.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_celldrain.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_clockworkify.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cultify.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkness.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkrevive.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_dnaswitch.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_emp.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_forcefield.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasco2.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasnitro.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasoxy.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gasplasma.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gassleeping.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_goodfeeling.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gravity.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_heal.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_heat.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_hurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_menagerie.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_pathogen.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_plantkiller.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_projectiles.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_radiate.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_reagentblock.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_roboheal.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_robohurt.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_sleepy.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_stun.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_teleport.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_timestop.dm
  goon/icons/obj/artifacts.dmi
  icons/obj/xenoarchaeology.dmi
Labels: Port, Sprites

#26727 Allows transparent clothing such as helmets to display "some" of the item slots they are covering
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/legacy_cult/cult_items.dm
  code/game/objects/items.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/tactical.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/void.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
Labels: Sprites, System

#26729 Converting a gondola to the cult now updates their sprite, and they can respawn as a gondola shade
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/complex/gondola.dm
Labels: Tweak

#26731 Click!
  code/game/machinery/airlock_control.dm
  code/game/machinery/lightswitch.dm
Labels: Sound

#26593 Wind-Up Boxes
  code/datums/uplink_item.dm
  code/game/objects/items/misc_items.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/projectiles/guns/hookshot.dm
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
  code/modules/projectiles/projectile/hookshot.dm
  icons/mob/in-hand/left/guns_experimental.dmi
  icons/mob/in-hand/right/guns_experimental.dmi
  icons/obj/projectiles_experimental.dmi
  icons/obj/weaponsmithing.dmi
  icons/obj/wind_up.dmi
Labels: Content

#26732 Newscaster/Newspaper update
  code/game/machinery/newscaster.dm
  icons/mob/in-hand/left/books.dmi
  icons/mob/in-hand/right/books.dmi
  icons/obj/terminals.dmi
Labels: Sprites

#26738 New Cigarettes for Vending Machines
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/mask.dmi
  icons/mob/species/grey/masks.dmi
  icons/mob/species/insectoid/mask.dmi
  icons/obj/cigarettes.dmi
  icons/obj/clothing/masks.dmi
Labels: 100% tested, Sprites, ❤️ Quality of Life ❤️

#26741 Fixes #26737
  __DEFINES/setup.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug / Fix

#26754 [HOTFIX] Fixes Masks being invisible
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Hotfix

#26772 fixes white pixel on Starlights sprite.
  icons/obj/cigarettes.dmi
Labels: Bug / Fix

#26766 Instrument fix
  code/game/objects/structures/musician.dm
Labels: Bug / Fix

#26759 Punchline/gingerbread bug fix
  code/game/objects/structures/false_walls.dm
  code/modules/projectiles/projectile/hookshot.dm
Labels: Bug / Fix

#26796 Rigsuit modification stations can only be activated once while operating
  code/game/machinery/suit_modifier.dm
Labels: Bug / Fix

#26756 Shrinks the inhaler sprite
  icons/obj/inhaler.dmi
Labels: Sprites

#26798 No more half-measures : completely rewrite PDA-bot code
  code/controllers/subsystem/pathing.dm
  code/defines/procs/AStar.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/floorbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/bots/secbot.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/radio.dm
Labels: 100% tested, Bug / Fix, Content, Easy Fix

#26730 You can now fit mesons, science, thermal and material scanners over prescription glasses
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/scanners.dm
  code/modules/clothing/shoes/magboots.dm
Labels: Tweak

#26801 Retardproofs rig modules
  code/game/machinery/suit_modifier.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/rig_modules/rig_modules.dm
Labels: Runtime Log, Tweak

#26797 ATMs now print cash directly in your hands
  code/game/machinery/ATM.dm
Labels: Bug / Fix

#26791 Fixes immortal borgs because i was bullied into doing so
  code/modules/mob/living/silicon/robot/robot_damage.dm
Labels: Bug / Fix

#26803 Beeper is too slow
  code/game/machinery/bots/bots.dm
Labels: Bug / Fix

#26813 *scream
  code/game/machinery/bots/bots.dm
Labels: Bug / Fix

#26816 Make monkeisation less laggy
  code/modules/mob/transform_procs.dm
Labels: Performance

#26818 BSQL connection closure
  code/controllers/subsystem/dbcore.dm
Labels: Performance

#26814 Stops the snail menace
  code/modules/mob/living/simple_animal/snail.dm
Labels: Bug / Fix

#26793 Fix cone helmet sprite coverage
  code/defines/obj/weapon.dm
Labels: Tweak

#26815 Adds a new animation for plasmaman monkeyisation
  code/game/dna/genes/monkey.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/monkey/skeleton.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/transform_procs.dm
  icons/mob/mob.dmi
Labels: Sprites

#26802 Fix doublejuke songs
  code/modules/media/broadcast/receiver.dm
  code/modules/media/broadcast/transmitter.dm
  code/modules/media/machinery.dm
  code/modules/media/mediamanager.dm
Labels: 100% tested

#26762 Crank charger charges things faster if you're strong.
  code/game/machinery/cell_charger.dm
Labels: Balance

#26761 Ports beanies from Hippiestation
  __DEFINES/clothing.dm
  code/game/machinery/vending.dm
  code/modules/clothing/head/beanies.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  vgstation13.dme
Labels: Port

#26824 !
  code/game/machinery/computer/security_alert.dm
Labels: Hotfix

#26830 fixes grenade launchers
  code/modules/reagents/grenade_launcher.dm
Labels: 100% tested, Hotfix

#26822 Actually close BSQL connections the hard way but only when needed this time
  code/controllers/subsystem/dbcore.dm
  code/world.dm
Labels: 100% tested

#26832 Beanies should no longer recolor subsequent hats you wear
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: 100% tested

#26825 Removes shitcode
  code/game/machinery/bots/bots.dm
Labels: Bug / Fix

#26828 Fixes airlock stuff
  code/game/machinery/door_control.dm
  code/game/machinery/doors/airlock.dm
Labels: Bug / Fix

#26763 Disposal units have a bit more sanity.
  code/modules/recycling/disposal.dm
Labels: Bug / Fix

#26827 Fixes rigs missing emp_act and initial modules having no rig set
  code/modules/clothing/spacesuits/rig.dm
Labels: Bug / Fix, Oversight

#26843 Soap should no longer attack people
  code/defines/obj/weapon.dm
Labels: 100% tested, ❤️ Quality of Life ❤️

#26829 Nuke ops: combat shorty
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
  icons/obj/gun.dmi
Labels: :up: Powercreep :up:

#26833 Selectable Background in Character Creation
  code/modules/client/preferences.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/previewbg.dmi
Labels: ❤️ Quality of Life ❤️

#26831 mask of the goat
  code/modules/clothing/masks/transmog.dm
  icons/obj/clothing/masks.dmi
Labels: Content

#26817 DNA injectors should now disappear after injecting someone with a monkey-to-human or human-to-monkey SE
  code/game/objects/items/weapons/dna_injector.dm
Labels: Bug / Fix

#26652 Runescape-y chat on the game world
  __DEFINES/game.dm
  __DEFINES/planes+layers.dm
  code/datums/chat_message.dm
  code/datums/saycode/speech.dm
  code/game/atoms.dm
  code/modules/client/client defines.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/migrations/SS13_Prefs/023-runechat.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
  code/world.dm
  icons/chat_icons.dmi
  interface/skin.dmf
  interface/skin_azerty.dmf
  vgstation13.dme
Labels: Content, UI

#26849 Fixing broken/wonky sprites on aliens
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/clothing/suits/bio.dm
  icons/mob/species/grey/head.dmi
  icons/mob/species/grey/suit.dmi
  icons/mob/species/vox/masks.dmi
Labels: Bug / Fix, Sprites, ❤️ Quality of Life ❤️

#26856 Speeds up pipe initialization
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
  code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
  code/ATMOSPHERICS/components/unary/unary_base.dm
  code/ATMOSPHERICS/he_pipes.dm
  code/ATMOSPHERICS/pipes.dm
Labels: Performance

#26854 Fixes datumpool runtimes
  code/__HELPERS/datumpool.dm
Labels: Runtime Log

#26860 Fixes SQLite error in saving prefs
  code/modules/client/preferences_savefile.dm
Labels: Bug / Fix

#26859 Removes the runechat grey background
  code/datums/chat_message.dm
Labels: Tweak

#26853 Fixes rig modules trying to scream with no mouth
  code/modules/clothing/spacesuits/rig_modules/rig_modules.dm
Labels: Oversight, Runtime Log

#26845 Fixes oldcoder stuff with radio controllers
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/magnet.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/PDA/radio.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: File Cleanup, Runtime Log

#26868 Revert "Fixes oldcoder stuff with radio controllers"
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/magnet.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/PDA/radio.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Bug / Fix

#26872 Fixes wrong default value in sanitation or whatev on sqlite load for max chat length
  code/modules/client/preferences_savefile.dm
Labels: Oversight

#26876 Fixes #26864
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Bug / Fix

#26888 Added a safety timeout to BSQL connect operations
  code/controllers/subsystem/dbcore.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#26887 asteroid turfs don't set their name to their name on New()
  code/modules/mining/mine_turfs.dm
Labels: File Cleanup

#26877 Removes some unnecessary code
  __DEFINES/_macros.dm
  __DEFINES/setup.dm
  code/ZAS/Atom.dm
  code/__HELPERS/lists.dm
  code/__HELPERS/maths.dm
Labels: File Cleanup

#26886 Fixes a monkeyise runetime
  code/modules/mob/transform_procs.dm
Labels: Bug / Fix

#26885 Make runechat saved prefs load properly
  code/modules/client/preferences_savefile.dm
Labels: Bug / Fix

#26874 More dynamic logging
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Logging / Administration

#26851 Add light emission to bunsen burner
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: Bug / Fix, good first issue

#26863 Clearer and more saturated colours for runechat
  code/datums/chat_message.dm
Labels: Tweak

#26889 Fixes runechat messages 'hard-deleteing'
  code/datums/chat_message.dm
Labels: Bug / Fix

#26894 Fixes #26892
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Bug / Fix

#26897 Chat messages are now pooled
  code/datums/chat_message.dm
Labels: Performance

#26871 Rigsuit Fix and Tweak (Formely R0B0's)
  code/modules/clothing/spacesuits/rig.dm
Labels: Bug / Fix, Tweak

#26901 Make ghosts properly see runechat
  code/modules/mob/dead/observer/say.dm
Labels: Bug / Fix

#26782 Lesser chems
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/spells/spell_code.dm
  code/modules/spells/targeted/equip/robesummon.dm
  icons/obj/drinks.dmi
Labels: Content, Update WIKI

#26631 adds some melee damage logging
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/living_defense.dm
Labels: Logging / Administration

#26841 ninja latejoin with prompt
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/role/ninja.dm
Labels: Content

#26912 Fix lonely midround nukies
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Bug / Fix

#26922 Possibly speed up runechat
  code/datums/chat_message.dm
Labels: Performance

#26915 Fix Prism Runtime
  code/modules/optics/prism.dm
Labels: Bug / Fix

#26917 Some small cult fixes
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix

#26899 Removes the nonfunctional move to top verb
  code/game/objects/items.dm
Labels: Feature Loss

#26923 Fixes clarke's scrubber loose screws
  code/game/mecha/working/clarke.dm
Labels: Bug / Fix

#26902 Fixes runechat layering issues
  __DEFINES/planes+layers.dm
  code/datums/chat_message.dm
Labels: Bug / Fix

#26914 Working version of radio controller fixes
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/magnet.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/PDA/radio.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/structures/crates_lockers/closets.dm
Labels: File Cleanup, System

#26893 Mouse Ops explode (IED sized) on death
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Tweak

#26932 Fixes Observers Having Preview Backgrounds
  code/modules/mob/new_player/preferences_setup.dm
Labels: Bug / Fix

#26804 Exile Implant Revamp: Borders are Closed
  code/datums/supplypacks.dm
  code/game/objects/items/weapons/implants/exile2.dm
  code/game/objects/items/weapons/storage/lockbox.dm
Labels: Needs Review, Tweak

#26694 silicon unit link established notification
  code/datums/wires/robot.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Content, Emoji This :+1: :-1:

#26937 Bunnybot was meant to be cute. Instead, it erased a man.
  __DEFINES/global.dm
Labels: Bug / Fix, Oversight

#26938 weird borgs no longer AI link in the first place
  code/modules/mob/living/silicon/robot/robot_subtypes/hug.dm
  code/modules/mob/living/silicon/robot/robot_subtypes/syndicate.dm
Labels: Hotfix

#26931 Adds a couple more hairstyles for bugs.
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#26949 Fixes most recent insect hair, makes bugs unable to be shaven.
  code/modules/mob/living/carbon/species.dm
  icons/mob/human_face.dmi
Labels: Bug / Fix, Sprites

#26930 Even more dynamic logging
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Logging / Administration

#26900 Added reference tracking
  __DEFINES/__compile_options.dm
  byond-extools.dll
  code/datums/datumvars.dm
  code/datums/reference_tracking.dm
  code/world.dm
  vgstation13.dme
Labels: Port, System

#26942 Small RPED QoL change
  code/game/objects/items/weapons/stock_parts.dm
  code/game/objects/items/weapons/storage/bags.dm
Labels: Oversight

#26926 Headset microphones can be turned off
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Balance

#26954 hunting rifle scope action button fix
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Bug / Fix

#26952 Fixed Potted Plants
  code/modules/hydroponics/hydro_tray.dm
Labels: Bug / Fix

#26839 Wizard Spell: Street Alchemy - Now with less chemist suicide
  code/modules/spells/targeted/street_alchemy.dm
  icons/mob/screen_spells.dmi
  icons/obj/potions.dmi
  vgstation13.dme
Labels: :up: Powercreep :up:, Content

#26944 Fix bison runtime
  code/modules/projectiles/projectile/beams.dm
Labels: Bug / Fix

#26846 Expunges hasvar()
  __DEFINES/_macros.dm
  code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
  code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm
  code/ATMOSPHERICS/components/binary_devices/heat_pump.dm
  code/ATMOSPHERICS/components/binary_devices/passive_gate.dm
  code/ATMOSPHERICS/components/binary_devices/pump.dm
  code/ATMOSPHERICS/components/binary_devices/valve.dm
  code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
  code/ATMOSPHERICS/components/trinary_devices/t_valve.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/__HELPERS/unsorted.dm
  code/datums/datumvars.dm
  code/datums/disease.dm
  code/datums/helper_datums/construction_datum.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/atmoalter/meter.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/buttons.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/embedded_controller/embedded_controller_base.dm
  code/game/machinery/flasher.dm
  code/game/machinery/holosign.dm
  code/game/machinery/igniter.dm
  code/game/machinery/machinery.dm
  code/game/machinery/mass_driver.dm
  code/game/machinery/metaldetector.dm
  code/game/machinery/smartglass.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/remote/remote_buttons.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/docking_port.dm
  code/game/objects/structures/window.dm
  code/modules/components/ai/controller.dm
  code/modules/context_click/context_click.dm
  code/modules/media/machinery.dm
  code/modules/medical/cloning.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/materials.dm
  code/modules/power/rust/core_gen.dm
  code/modules/power/rust/fuel_injector.dm
  code/modules/power/rust/gyrotron.dm
  code/modules/power/rust/gyrotron_controller.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/solars/control.dm
  code/modules/power/solars/panel.dm
  code/modules/power/turbine.dm
  code/modules/recycling/conveyor2.dm
  code/modules/supermatter/supermatter.dm
  code/modules/telesci/telepad.dm
  code/modules/telesci/telesci_computer.dm
Labels: Performance

#26907 wrapping messages & boxes
  code/game/objects/items/stacks/packagewrap.dm
Labels: Content

#26939 announce name changes for silicons + name change confirmation
  code/__HELPERS/unsorted.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: ❤️ Quality of Life ❤️

#26943 adds security formalwear crate (+ dmi adjusts)
  code/controllers/subsystem/supply_shuttle.dm
  code/datums/supplypacks.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Content

#26670 Removes Unicode stuff
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/datums/browser.dm
  code/datums/datumvars.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/game/communications.dm
  code/game/machinery/newscaster.dm
  code/game/objects/items/cookie_synth.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/verbs/ooc.dm
  code/modules/Economy/debit_card.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/assembly/assembly.dm
  code/modules/libvg/utf8.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
  code/modules/nano/nanoui.dm
  code/modules/scripting/Implementations/Telecomms.dm
  code/modules/scripting/Implementations/_Logic.dm
  code/modules/scripting/Scanner/Scanner.dm
  code/modules/telesci/gps.dm
  goon/browserassets/js/browserOutput.js
  goon/code/datums/browserOutput.dm
  libvg.dll
  libvg/benches/utf8.rs
  libvg/src/lib.rs
  libvg/src/utf8.rs
  vgstation13.dme
Labels: System, T-Thanks BYOND, libvg

#26975 Fixes internalOutput()
  goon/browserassets/js/browserOutput.js
Labels: Bug / Fix, Goonchat

#26986 Fixes RCD crash and character weirdness
  code/__HELPERS/text.dm
  code/modules/RCD/schematics/engi.dm
Labels: Bug / Fix

#26977 Fixed several linter warnings
  __DEFINES/global.dm
  __DEFINES/profile.dm
  code/__HELPERS/text.dm
  code/libs/BSQL/core/library.dm
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/media/jukebox.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/scripting/Parser/Expressions.dm
  code/modules/scripting/Parser/Keywords.dm
  code/modules/scripting/Parser/Parser.dm
Labels: File Cleanup, System

#26910 makes apocalyptic meteors apocalyptic
  code/game/gamemodes/meteor/meteors.dm
Labels: Tweak
