Repository vgstation-coders/vgstation13, pull requests merged in 2020-03, with the labels that each got.

#25953 Fixes botany some more
  code/modules/hydroponics/grown_inedible.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Bug / Fix

#25944 Fixes gibs hard deleting
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/objects/effects/gibs.dm
Labels: 100% tested

#25947 TEC power tweaks
  code/ATMOSPHERICS/components/binary_devices/heat_pump.dm
Labels: Balance, Tweak

#25941 Makes Honk Serum overdose break miming.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance

#25958 Meme disease type is now admin-only. Fungii can only appear in random dishes (take 2)
  __DEFINES/disease2.dm
  code/modules/events/viral_infection.dm
  code/modules/events/viral_outbreak.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/helpers.dm
Labels: Tweak

#25962 Xenoarch Core Sampler fixes
  code/modules/research/xenoarchaeology/tools/tools_coresampler.dm
Labels: Bug / Fix

#25971 Fixes cameras keeping a ref on tracked mobs that were deleted
  code/game/machinery/camera/motion.dm
Labels: Bug / Fix

#25883 Summon Pitbulls
  code/modules/mob/living/simple_animal/hostile/pitbull.dm
  code/modules/spells/aoe_turf/conjure/pitbulls.dm
  icons/mob/animal.dmi
  sound/voice/pitbullbark.ogg
Labels: Content, Needs Fixing

#25980 Species without blood no longer gib when they dissolve
  code/game/dna/genes/goon_disabilities.dm
Labels: Muh Immulsions

#25985 Adds a file which allows VSCode to recommend essential extensions on opening the project.
  .vscode/extensions.json
Labels: System

#25970 Civilian outfit datums
  code/datums/outfit/civilian.dm
  code/datums/outfit/outfit.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/species.dm
  vgstation13.dme
Labels: System

#25996 Pitbull quickfix
  vgstation13.dme
Labels: Bug / Fix

#26012 Danger, danger, high voltage
  code/game/objects/items/devices/radio/electropack.dm
Labels: Bug / Fix

#26004 Adds a lollipop synthesizer to mediborgs
  code/game/objects/items/cookie_synth.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Content

#25978 Fixes Bloodbank powering problems
  code/game/machinery/kitchen/smartfridge.dm
Labels: Bug / Fix

#25994 Renames all instances of the autoborger in the code to autoborger
  code/game/gamemodes/malfunction/Malf_Modules.dm
  code/game/machinery/autoborger.dm
  vgstation13.dme
Labels: Tweak

#26027 Fix strange rocks spawning so damn much.
  code/modules/mining/mine_turfs.dm
Labels: Bug / Fix

#25945 Revert "Make the blast cannon a bit better"
  code/modules/projectiles/guns/projectile/constructable/blastcannon.dm
Labels: Bleeding-Edge Experiment

#26030 Fix some incorrect xenoarch distance values.
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  code/modules/research/xenoarchaeology/tools/tools_excdrill.dm
Labels: Grammar / Formatting

#25983 Adds extools maptick functionality for maximum not-lag.
  __DEFINES/tick.dm
  byond-extools.dll
  code/modules/mob/mob.dm
  code/world.dm
Labels: System

#26026 Tracker for projectiles, and a new badmin tool
  code/datums/datumvars.dm
  code/game/atoms_movable.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/events/immovablerod.dm
  code/modules/projectiles/projectile.dm
Labels: Logging / Administration, System

#26044 Fix landmark hard-deleting
  code/game/objects/effects/landmarks.dm
Labels: Performance

#26038 Insectoids Rework: The spritening
  __DEFINES/global.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/head/tactical.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/under/chameleon.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/mob/living/carbon/species.dm
  icons/mob/human_face.dmi
  icons/mob/human_races/r_def_insectoid.dmi
  icons/mob/human_races/r_def_insectoidold.dmi
  icons/mob/human_races/r_insectoid.dmi
  icons/mob/human_races/r_insectoidold.dmi
  icons/mob/species/insectoid/ears.dmi
  icons/mob/species/insectoid/eyes.dmi
  icons/mob/species/insectoid/feet.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/mask.dmi
  icons/mob/species/insectoid/suit.dmi
  icons/mob/species/insectoid/uniform.dmi
Labels: 100% tested, Sprites

#26053 Sec Uniform Alt Sprites Fixed
  code/modules/clothing/under/jobs/security.dm
  icons/mob/species/grey/uniform.dmi
  icons/mob/species/insectoid/uniform.dmi
  icons/mob/species/vox/uniform.dmi
  icons/mob/uniform.dmi
Labels: 100% tested, Bug / Fix, Sprites

#26055 fixes broken sprites
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/under/jobs/engineering.dm
  icons/mob/species/insectoid/eyes.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/suit.dmi
Labels: Sprites

#26057 MORE FIXES BATMAN
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/scanners.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/species/insectoid/eyes.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/suit.dmi
  icons/mob/species/insectoid/uniform.dmi
  icons/mob/species/vox/gloves.dmi
Labels: Sprites

#26062 Fixed the fucky-wucky with job preview and fat sec sprites
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/uniform_fat.dmi
Labels: Sprites

#26063 Big EMPS will no longer slow the server to a crawl
  code/game/objects/empulse.dm
Labels: Performance

#26056 Fix issue 26013 (age restriction for borging)
  code/game/machinery/autoborger.dm
  code/game/objects/items/robot/robot_parts.dm
  code/modules/mob/transform_procs.dm
Labels: Bug / Fix

#26024 Un-greytided dudes will now appear on the round end report
  code/datums/gamemode/role/role.dm
Labels: Bug / Fix

#26025 Fix non-vox raider return
  code/datums/gamemode/factions/vox_shoal.dm
  code/game/shuttles/vox.dm
Labels: Bug / Fix, Muh Immulsions

#26021 Fixes mime curses 4real this time
  code/modules/reagents/Chemistry-Reagents.dm
Labels: 100% tested, Bug / Fix

#26070 Insectoid Screams: the chittering
  __DEFINES/_macros.dm
  code/datums/emotes.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/emote.dm
  sound/misc/hiss1.ogg
  sound/misc/hiss2.ogg
  sound/misc/hiss3.ogg
Labels: 100% tested, Sound

#26023 Klendathu Arachnids
  code/modules/mob/living/simple_animal/hostile/warriorbug.dm
  icons/mob/arachnid.dmi
Labels: Content

#26077 Throwing a rod at people is no between the teleport links
  code/datums/datumvars.dm
Labels: Tweak

#26075 Chaplain PDA and manifest updated with alt title
  code/datums/religions.dm
Labels: Bug / Fix

#26082 Fixing broken sprites.
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/clothing/head/misc.dm
  icons/mob/human_face.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/uniform.dmi
Labels: Bug / Fix, Sprites

#26083 Blood Cult Season 1
  __DEFINES/cameranet.dm
  __DEFINES/reagents.dm
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/objectives/spesstv.dm
  code/datums/gamemode/role/streamer.dm
  code/datums/religions.dm
  code/datums/supplypacks.dm
  code/game/atoms_movable.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/vending.dm
  code/game/machinery/vending_packs.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/modules/clothing/accessories/spesstv.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/research/mechanic/flatpack.dm
  code/modules/research/mechanic/flatpacker.dm
  icons/effects/effects.dmi
  icons/logos.dmi
  icons/mob/head.dmi
  icons/mob/in-hand/left/clothing.dmi
  icons/mob/in-hand/right/clothing.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/mob/uniform_overlays.dmi
  icons/obj/camera_buttons.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/device.dmi
  icons/obj/drinks.dmi
  icons/obj/food.dmi
  icons/obj/spesstv.dmi
  icons/obj/status_display.dmi
  icons/obj/trash.dmi
  icons/obj/vending.dmi
  icons/obj/vending_pack.dmi
  sound/effects/hitmarker.ogg
  sound/effects/intervention.ogg
  sound/effects/noisemaker1.ogg
  sound/effects/noisemaker2.ogg
  sound/effects/noisemaker3.ogg
  vgstation13.dme
Labels: Content
