Repository vgstation-coders/vgstation13, pull requests merged in 2020-10, with the labels that each got.

#27942 Fixed description for alcoholic drinks
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/spells/targeted/watertowine.dm
Labels: 100% tested, Bug / Fix

#27928 fixes AI mentions
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#27845 Malfunctioning AI Module: Explosive Hardware
  code/game/gamemodes/malfunction/Malf_Modules.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/robot/death.dm
  sound/machines/Alarm_short.ogg
Labels: Content

#27949 Fixes blood dripping from human wounds no longer carrying DNA properly in most cases
  code/modules/organs/blood.dm
Labels: Bug / Fix

#27952 Fixes janicart's repairment
  code/game/objects/structures/vehicles/vehicle.dm
Labels: Bug / Fix

#27927 Cargo SS properly deletes items, fixed hard dels
  code/datums/supplypacks.dm
  code/game/communications.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/computer/shuttle_computers.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/modules/clothing/suits/wintercoat.dm
  code/modules/games/cards/playing_cards.dm
  code/modules/games/cards/wizard_cards.dm
  code/world.dm
Labels: Bug / Fix, Performance, System

#27951 One runtime
  code/game/objects/items/devices/PDA/cart.dm
Labels: Bug / Fix

#27848 Malfunctioning AIs: Fix Overload Machine not working on some machines
  code/ATMOSPHERICS/atmospherics.dm
  code/game/gamemodes/malfunction/Malf_Modules.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/bees_apiary.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/machinery.dm
  code/game/machinery/shieldgen.dm
  code/modules/power/apc.dm
  code/modules/power/lighting/lighting.dm
  code/modules/power/power.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
Labels: Bug / Fix, Tweak

#27961 Adds the Gingerbread Mother to the Boss Mob List
  __DEFINES/global.dm
Labels: Exploitable, 🚓Fun Police🚓

#27911 *teleports behind u*
  code/modules/spells/targeted/feint.dm
  sound/misc/teleport_behind.ogg
Labels: Sound

#27959 Prevent the map loader from messing with gliding
  code/modules/awaymissions/maploader/reader.dm
Labels: 0% tested

#27955 Fixes a mistake with dmi sprites
  icons/mob/mob.dmi
Labels: Bug / Fix

#27954 Antag HUD icons are now properly updated when getting in/out of a mecha
  __DEFINES/planes+layers.dm
  code/datums/gamemode/factions/faction.dm
  code/game/mecha/mecha.dm
Labels: Bug / Fix

#27960 Fat Ninja Fix
  code/datums/gamemode/role/ninja.dm
Labels: Bug / Fix

#27958 You can pat/punch AIs
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Balance, Content

#27946 Moves oldviro symptoms and transformation viruses to current virus system
  __DEFINES/disease2.dm
  __DEFINES/setup.dm
  code/ZAS/Plasma.dm
  code/controllers/subsystem/init/more_init_stuff.dm
  code/datums/diseases/beesease.dm
  code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/cockatrice.dm
  code/modules/organs/internal/lungs/lung_gasses.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/virus2/effect/stage_1.dm
  code/modules/virus2/effect/stage_2.dm
  code/modules/virus2/effect/stage_3.dm
  code/modules/virus2/effect/stage_4.dm
  code/modules/virus2/effect/stage_special.dm
  code/modules/virus2/helpers.dm
  code/modules/virus2/predefined.dm
  icons/mob/mommi.dmi
  vgstation13.dme
Labels: Bug / Fix, Content

#27948 adds civil protection uniform/helmet/armor to the secvend
  code/game/machinery/vending.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Content, Sprites

#27957 Using a screwdriver on undeployed switchtool dumps out all modules, clicking on tools with an undeployed switchtool adds all tools on the tile into the switchtool
  code/game/objects/items/weapons/switchtool.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#27969 Hitting someone with a gun plays a sound
  code/modules/projectiles/gun.dm
Labels: Sound

#27983 foam extinguishers now good
  code/game/objects/effects/effect_system.dm
Labels: Unable To Reproduce

#27980 Fixed the bug that briefly woke people up if they were injected with a second dose of chloral hydrate
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#27839 Update AI Upload sprite to show inserted AIs
  code/game/machinery/computer/law.dm
  icons/obj/computer.dmi
Labels: Sprites

#27663 middle shift click to enable/disable door safeties as silicons
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/game/machinery/doors/airlock.dm
Labels: Emoji This :+1: :-1:, ❤️ Quality of Life ❤️

#27715 Shift/Alt/Ctrl clicking the turf below an airlock Shift/Alt/Ctrl clicks the airlock. AI camera will not jump on double shift/alt/ctrl click (only regular double click)
  code/_onclick/ai.dm
  code/game/machinery/doors/airlock.dm
Labels: Conflicts, Tweak, ❤️ Quality of Life ❤️

#27844 Malfunctioning AI Blackout + RCD Disable Ability Tweaks
  __DEFINES/global.dm
  code/__HELPERS/global_lists.dm
  code/game/gamemodes/malfunction/Malf_Modules.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/say.dm
  code/modules/RCD/engie.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/power/apc.dm
Labels: Balance, Tweak

#27953 Fixes re-admining not restoring the AntagHUD verb
  code/modules/admin/admin_verbs.dm
Labels: Bug / Fix

#28003 improved a qdel warning message
  code/controllers/subsystem/garbage.dm
Labels: System

#27995 Fixing some Seer issues and other cult runtimes
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/role/cultist.dm
Labels: Bug / Fix

#27998 fix xeno/cyborg/mommi/wendigo diseases appearing from random events and loose catbeats
  code/datums/gamemode/role/catbeast.dm
  code/modules/virus2/predefined.dm
Labels: Bug / Fix

#28006 Areas without APCs can no longer have overlays
  code/game/area/areas.dm
Labels: Tweak

#28002 Gas overlays no longer capture clicks
  code/ZAS/XGM_gases.dm
Labels: Bug / Fix

#27992 DNA modifiers and injectors properly transfer unique enzymes
  code/game/dna/dna_modifier.dm
  code/game/objects/items/weapons/dna_injector.dm
Labels: 100% tested, Bug / Fix

#28001 fix ai upload overlay not disappearing when it gets depowered/destroyed
  code/game/machinery/computer/law.dm
  icons/obj/computer.dmi
Labels: Bug / Fix

#28011 Battering rams can ram firelocks
  code/__HELPERS/unsorted.dm
  code/defines/obj/weapon.dm
  code/game/atoms.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
Labels: Balance, Tweak, Unatomic Uncle

#28016 Makes the Lamprey thing work for real maybe perhaps I guess I'm not sure but I think so
  code/__HELPERS/files.dm
Labels: Bug / Fix, Unable To Reproduce

#27993 Bagel Voting Requirement
  code/__HELPERS/files.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Content, Mapping (Bagel :o:)

#27997 Added setting to change client fps
  SQL/players2.sql
  __DEFINES/setup.dm
  code/modules/client/client procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/migrations/SS13_Prefs/026-add-fps.dm
  vgstation13.dme
Labels: Secret repo conflict., Tweak

#28031 Maybe fix bagel voting requirement
  code/__HELPERS/files.dm
Labels: 0% tested, Bug / Fix

#28036 fix double-diseases (again)
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_pathogen.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/helpers.dm
  code/modules/virus2/predefined.dm
Labels: Bug / Fix

#28039 gatormix /heart/ into /kidney/
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Hotfix

#27977 Switchtool inhands
  code/game/objects/items/weapons/switchtool.dm
  icons/mob/in-hand/left/switchtool.dmi
  icons/mob/in-hand/right/switchtool.dmi
Labels: Conflicts, Sprites

#28023 Adds some new in-hand sprites for bar drinks
  icons/mob/in-hand/left/drinkingglass.dmi
  icons/mob/in-hand/right/drinkingglass.dmi
Labels: Sprites

#28046 fix dojo cyborg and sushi
  code/modules/mob/living/silicon/robot/robot_subtypes/dummy.dm
  maps/misc/dojo.dmm
  vgstation13.dme
Labels: Hotfix

#28000 Security sprites: the compromisening
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
Labels: Consistency Issue, Sprites, Tweak

#28008 fix silencer-related errors
  code/modules/mob/living/simple_animal/borer/fleshshot.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/lawgiver.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/constructable/blastcannon.dm
  code/modules/projectiles/guns/projectile/pistol.dm
Labels: Bug / Fix

#28068 fix AI seeing "Unable to track [realname]" when someone uses a voice changer
  code/modules/mob/living/silicon/ai/say.dm
Labels: Bug / Fix

#28014 fix stoves/fireplaces being turned into campfire decals
  code/ATMOSPHERICS/hvac/spaceheater.dm
Labels: Bug / Fix, Easy Fix

#28070 Visible emotes are no longer displayed in runechat if the player is invisible
  __DEFINES/_macros.dm
  code/datums/emotes.dm
Labels: Bug / Fix

#27988 robots console self-destruct sequence access tweaks and more
  __DEFINES/global.dm
  code/game/machinery/computer/robot.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  icons/obj/computer.dmi
Labels: Tweak

#28024 The Batlinggun
  code/datums/uplink_item.dm
  code/modules/projectiles/guns/projectile/minigun.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/in-hand/left/guns_experimental.dmi
  icons/mob/in-hand/right/guns_experimental.dmi
  icons/obj/ammo.dmi
  icons/obj/gun_experimental.dmi
  icons/obj/projectiles_experimental.dmi
Labels: Content

#27975 Slime Extract/Product Bag
  code/datums/outfit/science.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/research/designs/misc.dm
  icons/obj/storage/storage.dmi
Labels: Content

#28078 robotics console self-destruct sequence wont blow up mommis anymore
  code/__HELPERS/global_lists.dm
  code/game/machinery/computer/robot.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Bug / Fix

#28082 fixes commie barsign
  code/game/objects/structures/barsigns/vg.dm
Labels: Bug / Fix

#28081 Added synergy to compile options
  __DEFINES/__compile_options.dm
  maps/_map_override.dm
Labels: System

#28052 Fixed a bug in an item that doesn't exist yet
  code/modules/reagents/Chemistry-Holder.dm
Labels: Bug / Fix

#28018 Update dreamchecker to version 1.6
  .travis.yml
  code/modules/assembly/assembly.dm
  code/modules/awaymissions/maploader/swapmaps.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/organs/internal/eyes/eyes.dm
  code/modules/projectiles/targeting.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/surgery/organs_internal.dm
Labels: Bug / Fix, System

#28069 Insectoid Fashion Month 1 - Masks
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/masks/chemmask.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/masks/mystic.dm
  code/modules/clothing/masks/necklaces.dm
  icons/mob/species/insectoid/mask.dmi
Labels: 100% tested, ❤️ Quality of Life ❤️

#28074 Changed maximum name length from 26 to 52
  __DEFINES/setup.dm
Labels: Tweak

#28097 Fixes visor helmet runtime
  code/game/objects/items.dm
  code/modules/clothing/head/helmet.dm
Labels: Bug / Fix

#28108 SMG Briefcase Examination Fix
  code/game/objects/items/weapons/storage/briefcase.dm
Labels: Bug / Fix

#28113 Stop the message monitor console going invisible when emagged.
  icons/obj/machines/telecomms.dmi
Labels: Bug / Fix

#28115 You should no longer be able to roll malf AI on Castle, an AI-less map
  maps/tgstation-sec.dm
Labels: Bug / Fix

#28114 Make :h speak over departmental instead of common channel again.
  code/game/objects/items/devices/radio/radio.dm
Labels: Bug / Fix

#28120 Improved typing indicator episode 2 the revenge
  code/controllers/subsystem/init/more_init_stuff.dm
  code/modules/mob/typing_indicator.dm
Labels: Bug / Fix
