Repository vgstation-coders/vgstation13, pull requests merged in 2020-11, with the labels that each got.

#28131 Fixes Soymilk Being Invisible in a Drinking Glass
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#28136 Fixes tableflipping of plastic and plasmaglass tables
  code/game/objects/structures/tables_racks.dm
  icons/obj/structures.dmi
Labels: Bug / Fix

#28140 Fixed off by one error in check_enemy_jobs maybe
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Bug / Fix

#28106 Changed nuke ops roundstart ruleset requirements to those of cult
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#28142 Insectoid Fashion Month 2 - Suits
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
  code/modules/clothing/spacesuits/void.dm
  code/modules/clothing/suits/alien.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/plate_carrier.dm
  code/modules/clothing/suits/slimecoat.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wintercoat.dm
  code/modules/clothing/suits/wiz_robe.dm
  icons/mob/species/insectoid/suit.dmi
Labels: 100% tested, Sprites, ❤️ Quality of Life ❤️

#28154 Insectoid Fashion Month 3 - Hats!
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/legacy_cult/cult_items.dm
  code/defines/obj/weapon.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/trader.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/clothing/head/beanies.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/leather.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/head/tactical.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
  code/modules/clothing/spacesuits/void.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/paperwork/paper_folded.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/mob/species/insectoid/head.dmi
Labels: 100% tested, Sprites, ❤️ Quality of Life ❤️

#28122 Adds beer box
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/storage/fancy.dm
  icons/mob/in-hand/left/boxes_and_storage.dmi
  icons/mob/in-hand/right/boxes_and_storage.dmi
  icons/obj/food_container.dmi
Labels: Content, Sprites

#28132 Re-adds the Autoborger Cooldown. (Reverts #26158)
  code/game/machinery/autoborger.dm
Labels: Balance, Tweak

#28155 IsAdvancedToolUser() removal / You can't fire guns anymore with warping claws or knuckles equipped as dexterity checks are now consistent.
  code/game/machinery/doors/firedoor.dm
  code/game/objects/items/weapons/barricade_kit.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/musician.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/complex/martian/martian.dm
  code/modules/mob/living/carbon/human/catbeast/catbeast.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/hostile/gremlin.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun.dm
Labels: Bug / Fix, Tweak

#28174 Adds missing changelog line
  html/changelogs/.all_changelog.yml
Labels: Bug / Fix, Grammar / Formatting

#28040 Butcher Code Revision
  code/datums/helper_datums/butchering.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: 100% tested, Oversight, Tweak

#28099 Runechat is invisible if you're invisible.
  code/modules/mob/living/say.dm
Labels: Oversight

#28117 triples nukeops weight on castle station
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  maps/_map.dm
  maps/tgstation-sec.dm
Labels: Tweak

#28123 Adds swiss army knives to the merch store. Yes, the merch store still exists.
  code/game/machinery/computer/store.dm
  code/modules/store/items.dm
Labels: Content

#28139 fixes headcrab wierdness
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/living.dm
Labels: Bug / Fix

#28157 Performing surgery with no dexterity gives you a chance to fail
  code/modules/surgery/generic.dm
  code/modules/surgery/surgery.dm
Labels: Balance

#28175 Add the starting runes to cultists' notes.
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/role/cultist.dm
Labels: Bug / Fix

#28176 Data HUD range increase
  __DEFINES/setup.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/game/data_huds.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Tweak

#28158 Monkey/Diona Nymphs can now use their own "blood" as cultists, and some Shade/Constructs buffs
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/role/cultist.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/organs/blood.dm
Labels: Content, Tweak

#28189 Podbuilding "Fix" Revert
  code/modules/spacepods/construction.dm
  code/modules/spacepods/spacepods.dm
Labels: Feature Loss, IT'S A FEAAAATUUUUREEEEEEEEE

#28188 saw-shortening a doublebarrel shotgun now turns it into a subtype
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: Bug / Fix

#28191 Pod fix
  code/modules/spacepods/construction.dm
Labels: 100% tested, Bug / Fix

#28198 Pod fix 2
  code/modules/spacepods/construction.dm
Labels: Bug / Fix

#28201 batling gun invisible hotfix
  code/modules/projectiles/guns/projectile/minigun.dm
Labels: Hotfix

#28017 Changeling Spells + power datums rework
  __DEFINES/global.dm
  __DEFINES/setup.dm
  __DEFINES/spell_defines.dm
  code/_onclick/hud/spell_screen_objects.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/dynamic/dynamic_stats.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/powers/changeling.dm
  code/datums/gamemode/powers/powers.dm
  code/datums/gamemode/powers/vampire.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/vampire_gamemode.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/gamemodes/changeling/changeling_procs.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items/changeling_vial.dm
  code/game/objects/items/incense.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/null_rod.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/structures/mirror.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/transform_procs.dm
  code/modules/spells/aoe_turf/glare.dm
  code/modules/spells/changeling/absorb_dna.dm
  code/modules/spells/changeling/armblade.dm
  code/modules/spells/changeling/changeling_spell.dm
  code/modules/spells/changeling/changespecies.dm
  code/modules/spells/changeling/evolutionmenu.dm
  code/modules/spells/changeling/hivedownload.dm
  code/modules/spells/changeling/hiveupload.dm
  code/modules/spells/changeling/horrorform.dm
  code/modules/spells/changeling/lesser_form.dm
  code/modules/spells/changeling/rapidregen.dm
  code/modules/spells/changeling/regenerative_stasis.dm
  code/modules/spells/changeling/stings/blind.dm
  code/modules/spells/changeling/stings/deaf.dm
  code/modules/spells/changeling/stings/dnaextract.dm
  code/modules/spells/changeling/stings/fat.dm
  code/modules/spells/changeling/stings/hallucinate.dm
  code/modules/spells/changeling/stings/mute.dm
  code/modules/spells/changeling/stings/paralyse.dm
  code/modules/spells/changeling/stings/sting.dm
  code/modules/spells/changeling/stings/transformation.dm
  code/modules/spells/changeling/transform.dm
  code/modules/spells/changeling/unstun.dm
  code/modules/spells/changeling/voicechange.dm
  code/modules/spells/spell_code.dm
  code/modules/spells/targeted/absorb.dm
  code/modules/spells/targeted/enthrall.dm
  code/modules/spells/vampire_helpers.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Tweak

#28192 Fixes borers in slimes
  code/modules/mob/living/carbon/species.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/borer.dm
Labels: Bug / Fix

#28190 IAA Headset
  code/datums/outfit/civilian.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  icons/mob/ears.dmi
Labels: Emoji This :+1: :-1:

#28217 Fixes Beneficial and Harmful Disease Centcomm Orders
  __DEFINES/setup.dm
  code/game/gamemodes/scoreboard.dm
  code/modules/virus2/disease2.dm
Labels: Bug / Fix

#28213 We purposely trained him wrong as a joke.
  code/datums/gamemode/role/ninja.dm
Labels: Bug / Fix

#28221 Fix & tweak Toxic Compensation
  code/modules/virus2/effect/stage_3.dm
Labels: Bug / Fix

#28219 Space Helmets/Hardsuit Helmets that should hide eyes (and thus gender) now properly do
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/ninja.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/ert.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/time.dm
Labels: Bug / Fix

#28225 [HOTFIX] RE-ADDS VIROLOGY TO THE GAME
  __DEFINES/setup.dm
  code/game/centcomm_orders/orders_medical.dm
  code/game/gamemodes/scoreboard.dm
  code/modules/virus2/disease2.dm
Labels: Bug / Fix, Hotfix

#28222 Fixed windoors being open at round start sometimes
  maps/randomvaults/gingerbread_house.dmm
Labels: Bug / Fix

#28229 Fixed being able to still identify gender of people wearing Vox helmets
  code/modules/clothing/spacesuits/alien.dm
Labels: Bug / Fix, Hotfix

#28224 Energy Swords and Energy Katanas Now Properly Cut Open Firelocks
  code/game/machinery/doors/firedoor.dm
Labels: Bug / Fix

#28230 Re-Adds Fun
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/mob/living/living.dm
Labels: Hotfix

#28232 Fixes the description of guac
  code/modules/reagents/reagent_containers/food.dm
Labels: Tweak

#28206 Some Dynamic Logging QoL and Fix'd Forced Rulesets
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Bug / Fix, Logging / Administration

#28234 Fixes intercoms and hand radio modification
  code/game/objects/items/devices/radio/radio.dm
Labels: Bug / Fix

#28244 Fixes the Security Alerts board
  code/game/machinery/computer/buildandrepair.dm
Labels: Bug / Fix

#28243 Fixes an ace reporter paper typo
  code/modules/paperwork/paper.dm
Labels: Tweak

#28257 Ian is Once Again a Boy Dog
  code/modules/mob/living/simple_animal/friendly/corgi.dm
Labels: Bug / Fix, Grammar / Formatting

#28254 Fixes Mad Scientist Megaphone users being trackable
  code/game/machinery/camera/tracking.dm
Labels: Bug / Fix

#28256 Fashion Report - Hoodies
  code/game/machinery/vending.dm
  code/modules/clothing/suits/wintercoat.dm
  icons/mob/in-hand/left/clothing.dmi
  icons/mob/in-hand/right/clothing.dmi
  icons/mob/species/insectoid/suit.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: 100% tested, Sprites

#28250 Insectoid Fashion Month 4 - Uniforms!
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/species/insectoid/uniform.dmi
Labels: 100% tested, Sprites, ❤️ Quality of Life ❤️

#28245 Gives the ghosts of corpses enthralled by a vampire a notification
  code/modules/spells/targeted/enthrall.dm
Labels: ❤️ Quality of Life ❤️

#28268 Fixed vox and plasmaman bartenders not starting with service headset
  code/datums/outfit/civilian.dm
Labels: Bug / Fix

#28259 Adds admin logging for Silicon/Trader characters joining the round
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job/whitelisted.dm
Labels: 100% tested, Logging / Administration

#28267 Makes SDQL understand typepaths
  code/modules/admin/verbs/SDQL_2/SDQL_2.dm
  code/modules/admin/verbs/SDQL_2/SDQL_2_parser.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#28270 plasmaman mechanics will no longer burn alive roundstart
  code/datums/outfit/engineering.dm
Labels: Bug / Fix

#28105 Change the law 4 of Corporate
  code/datums/ai_laws.dm
Labels: Emoji This :+1: :-1:, Needs Changelog
