Repository vgstation-coders/vgstation13, pull requests merged in 2020-01, with the labels that each got.

#25525 What took you so long?
  code/game/machinery/kitchen/monkeyrecycler.dm
Labels: Runtime Log

#25392 Nu Cryo: Feedbackcreep
  __DEFINES/_macros.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/scanners.dm
  nano/templates/cryo.tmpl
Labels: :up: Powercreep :up:, Content, Controversial

#25393 Nu Cryo: Clonex' an Cryox Redux
  code/modules/reagents/Chemistry-Reagents.dm
Labels: :up: Powercreep :up:, Controversial, Tweak

#25542 Snaxi Areas
  code/datums/shuttle.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/structures/docking_port.dm
  maps/_map.dm
  maps/snaxi.dmm
Labels: Mapping (Snaxi ❄)

#25519 Some Cult Experiment
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Balance, Role Datums

#25544 Adds framework for clothing changing screams, adds half-life scientist screams to science labcoat
  __DEFINES/clothing.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/mob/living/carbon/emote.dm
Labels: Content, Sound

#25566 Fixed a Climate Goof
  code/game/machinery/computer/climate.dm
Labels: Bug / Fix

#25571 Chaos Blade shades now have universal understand/speak
  code/game/objects/items/weapons/null_rod.dm
Labels: Tweak

#25570 Changes firelocks to change density earlier/later when opening/closing.
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
Labels: ❤️ Quality of Life ❤️

#25577 Fix airlocks not changing density until closing animation finishes.
  code/game/machinery/doors/door.dm
Labels: Bug / Fix

#25578 Fix ryetalyn not updating sprite for horns gene.
  __DEFINES/setup.dm
  code/game/dna/genes/goon_disabilities.dm
Labels: Bug / Fix

#25565 AI Jump Buttons for Snaxi
  code/_onclick/hud/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  icons/mob/screen_ai.dmi
  maps/_map.dm
  maps/snaxi.dm
Labels: ❤️ Quality of Life ❤️

#25562 Snaxi Mine
  code/game/turfs/unsimulated/snow.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/materials.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/minerals.dm
  code/modules/mining/ores_coins.dm
  code/modules/mining/smelting.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  icons/mob/animal.dmi
  icons/obj/mining.dmi
  icons/turf/mine_overlays.dmi
  maps/snaxi.dmm
Labels: Content, Mapping (Snaxi ❄)

#25568 Shows whether a human can be revived inside the health analyzer.
  code/game/objects/items/devices/scanners.dm
Labels: ❤️ Quality of Life ❤️

#25586 Fix ore handling.
  __DEFINES/materials.dm
  __DEFINES/setup.dm
  code/game/atoms_movable.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/robot/robot_items/robot_furnace.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/sheets/sheets.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/structures/vehicles/gigadrill.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/materials.dm
  code/modules/mining/ore_box.dm
  code/modules/mining/ore_redemption.dm
  code/modules/mining/ores_coins.dm
  code/modules/mining/smelting.dm
Labels: Bug / Fix

#25595 UI Fix
  code/_onclick/hud/screen_objects.dm
  maps/_map.dm
  maps/snaxi.dm
Labels: Hotfix

#25601 fixes VV not being able to delete vars
  code/datums/datumvars.dm
Labels: Hotfix

#25610 Little Fix
  maps/snaxi.dmm
Labels: Mapping (Snaxi ❄)

#25591 Sanitizes adminhelp
  code/modules/admin/verbs/adminhelp.dm
Labels: Sanity / Ghosthands

#25619 Teleporter Fix
  code/game/machinery/teleporter.dm
Labels: Bug / Fix

#25617 Update the entire Traitor Uplink listing to tidy it up
  code/datums/uplink_item.dm
Labels: File Cleanup, Grammar / Formatting

#25608 Changes the types of mobs that you can turn into with the Transformation potion
  code/game/objects/items/potions.dm
Labels: Balance, Tweak

#25622 Cowboy hats now have a (very slight) bullet resistance
  code/modules/clothing/head/misc.dm
Labels: Tweak

#25630 Adds a non-pacifying subtype of pillowbug
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/mob/mob.dm
Labels: Content

#25554 Adds some stunprod feedback
  code/game/objects/items/weapons/stunbaton.dm
Labels: Oversight

#25647 Fixes some genetic damage nonsense
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Bug / Fix

#25649 Failsafe for tcomms server
  code/game/machinery/telecomms/logbrowser.dm
Labels: Hotfix

#25646 Slime friendship ended with monkey
  code/modules/mob/living/carbon/slime/powers.dm
Labels: Tweak

#25606 Reduces the cost of the Transformation to 10 points (Formerly 15 points)
  code/game/gamemodes/wizard/spellbook.dm
Labels: Balance, Tweak

#25597 chem dispensers accept any reagent amount
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Tweak

#25569 dragon's breath and HE shells
  code/game/machinery/ammolathe.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/research/designs/weapons.dm
  icons/obj/ammo.dmi
  icons/obj/storage/smallboxes.dmi
Labels: Content

#25514 ninja stuff
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/factions/spider_clan.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/role.dm
  code/datums/mind.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/swords_axes.dmi
  icons/obj/decals.dmi
  icons/obj/stools-chairs-beds.dmi
  icons/obj/weapons.dmi
  icons/turf/areas.dmi
  maps/misc/dojo.dmm
  sound/effects/yooooooooooo.ogg
  vgstation13.dme
Labels: Content, Gameplay / Gamemode, Mapping (Vault :question:), Needs Review, Role Datums, Tweak, Unatomic Uncle, Update WIKI, WiP

#25642 Self-recharging batteries now recharge 10x faster
  code/game/objects/items/weapons/power_cells.dm
Labels: :up: Powercreep :up:

#25674 Doing this on a bus
  .travis.yml
Labels: System

#25637 adds 6 hairs for diona
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#25635 suppermatter
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Content, Update WIKI

#25645 Bleach & Space Cleaner now cleans tiles & mobs that have been colored via the colorful reagent.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Gameplay / Gamemode, Tweak, ❤️ Quality of Life ❤️

#25673 Changes graphics for weeds
  icons/obj/hydroponics/weeds.dmi
Labels: Sprites

#25633 Some work on hands
  code/_onclick/other_mobs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
Labels: Content

#25704 Adds White Cap + Balaclava to Hatlord 9000
  code/game/machinery/vending.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#25696 Sleepers upgraded with xenoarch tier 4 components let you use it on people in crit
  code/game/machinery/Sleeper.dm
Labels: Content

#25687 Shower tweaks: Ghetto Cryo Edition
  code/game/objects/structures/watercloset.dm
Labels: Tweak

#25715 Fixes Vox Skin-Color Preview
  code/modules/mob/new_player/preferences_setup.dm
Labels: Bug / Fix

#25685 Reduces Laser tag stun times from 10 seconds to 4
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/energy.dm
Labels: Tweak

#25621 mind transfer file maintenace i guess okay
  code/datums/gamemode/role/cultist.dm
  code/datums/mind.dm
Labels: File Cleanup

#25701 Adds new peanut based foods, hopefuly without conflicts
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food2.dmi
Labels: 100% tested, Sprites, Update WIKI

#25516 Robot Life() is the Life() for me
  __DEFINES/silicon.dm
  code/modules/mob/living/silicon/mommi/cogspider.dm
  code/modules/mob/living/silicon/mommi/death.dm
  code/modules/mob/living/silicon/mommi/life.dm
  code/modules/mob/living/silicon/mommi/mommi_hud.dm
  code/modules/mob/living/silicon/mommi/mommi_inventory.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_hud.dm
  code/modules/mob/living/silicon/robot/robot_inventory.dm
  vgstation13.dme
Labels: Bug / Fix, File Cleanup, Needs Review, Tweak

#25587 Pyrite slimes produce 5x as much cash
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Tweak

#25626 Adds 3x/4x & Zoom Options, Renames Icons to Display, Moves Swap Sides to Display on skin file.
  interface/skin.dmf
Labels: UI, ❤️ Quality of Life ❤️

#25628 Making fabricator delay between items shorter: Revenge of the Scientist
  code/modules/research/fabricators.dm
  code/modules/research/rdconsole.dm
Labels: :thinking:, Tweak

#25644 Ups the danger level of the "Colorsmoke" virus symptom.
  code/modules/virus2/effect/stage_3.dm
Labels: Gameplay / Gamemode, Tweak

#25656 Abandoned crates can now be emagged properly
  code/modules/mining/abandonedcrates.dm
Labels: Bug / Fix, Legacy Bug

#25695 Monkey recycler fixes
  code/game/machinery/kitchen/monkeyrecycler.dm
Labels: Bug / Fix, Needs Changelog

#25723 More Vox Hairs + Extra Special Appearance of A New Beard, Oh My!
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#25714 Small scream changes
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Content, Update WIKI

#25733 Cryo improvements:
  code/game/machinery/cryo.dm
  icons/obj/cryogenics.dmi
  nano/templates/cryo.tmpl
Labels: UI, ❤️ Quality of Life ❤️

#25697 Upgrading the cloning pod with T4 components makes it able to make perfect clones
  code/modules/medical/cloning.dm
Labels: :up: Powercreep :up:, Content

#25746 Fixed Three Mile Island not having the kick it should
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#25740 Revert "Spessmart destination disk now spawns in the black market uplink"
  __DEFINES/global.dm
  code/datums/black_market_item.dm
  maps/randomvaults/spessmart.dm
Labels: Emoji This :+1: :-1:, 🚓Fun Police🚓

#25738 Xenos from the staff of change can only be Hunters and Sentinels
  code/modules/projectiles/projectile/change.dm
Labels: Balance

#25748 Bloodlust now drops 2 detached machetes when detatched instead of the completed bloodlust.
  code/game/objects/items/weapons/twohanded.dm
Labels: Tweak

#25719 Traitors can share telecrystals
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/uplinks.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: 100% tested, Content

#25764 Removes infinite TC where you could gain infinite TC by extracting 0 telecrystals from the uplink while having telecrystals, giving you one telecrystal and consuming none[balance] [ohgoditsloose] [controversial]
  code/game/objects/items/devices/uplinks.dm
Labels: Balance, ❤️ Quality of Life ❤️

#25768 Minor fixes to telecrystal sharing
  code/game/objects/items/devices/mat_synth.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/uplinks.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Exploitable, 🚓Fun Police🚓

#25772 Fixes some exploits with telecrystals
  code/game/objects/items/devices/mat_synth.dm
  code/game/objects/items/devices/uplinks.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Bug / Fix

#25763 Makes medborgs able to pickup plasma sheets for chemistry
  code/game/objects/items/robot/robot_items/robot_gripper.dm
Labels: Tweak

#25761 Fixes black slimecore reaction
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#25780 Fixes a few formatting errors in a previously merged PR
  code/defines/obj/weapon.dm
Labels: Grammar / Formatting

#25782 Fixes meteor blob spawning empty cores
  code/modules/events/meteors.dm
Labels: Bug / Fix
