Repository vgstation-coders/vgstation13, pull requests merged in 2020-07, with the labels that each got.

#26947 Better tracking implant locator
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implanttracking.dm
  code/game/objects/items/weapons/storage/boxes.dm
  icons/holomap_markers.dmi
  icons/obj/device.dmi
  vgstation13.dme
Labels: Balance, ❤️ Quality of Life ❤️

#26976 insectoid added to emagged cloner
  code/modules/medical/computer/cloning.dm
Labels: Tweak

#26993 Fixed a bunch of warnings and errors
  __DEFINES/global.dm
  __DEFINES/implants.dm
  code/__HELPERS/game.dm
  code/_onclick/click.dm
  code/game/atoms_movable.dm
  code/game/dna/dna2_domutcheck.dm
  code/game/jobs/job_controller.dm
  code/game/jobs/whitelist.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implanttracking.dm
  code/libs/BSQL/core/connection.dm
  code/libs/BSQL/core/library.dm
  code/libs/BSQL/core/operation.dm
  code/modules/admin/admin_memo.dm
  code/modules/assembly/infrared.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/wolf.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/organs/organ_external.dm
  vgstation13.dme
Labels: Bug / Fix, Unatomic Uncle

#26995 Very urgent hotfix please merge
  __DEFINES/global.dm
Labels: Hotfix

#26996 Fixes disappearing cards
  code/modules/games/cards/playing_cards.dm
Labels: Bug / Fix

#26997 Fixes beams just breaking constantly
  code/game/objects/effects/beam.dm
Labels: Bug / Fix

#26953 gygax sprites now respect overload status or lack thereof
  code/game/mecha/combat/gygax.dm
Labels: Bug / Fix

#26982 Gentlemen
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Bug / Fix

#26964 Husbando
  __DEFINES/reagents.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  icons/effects/96x96.dmi
  icons/obj/drinks.dmi
Labels: Content

#26985 added a thing that spawns windows and grilles for mappers
  code/game/objects/effects/spawners/grille_window_spawner.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/weapons/barricade_kit.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/fullwindow.dm
  code/game/objects/structures/window.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/liquid/splash_simulation.dm
  icons/obj/window_grille_spawner.dmi
  vgstation13.dme
Labels: Mapping (General :world_map:), System

#26911 two new posters + posters from merch computer
  code/game/machinery/computer/store.dm
  code/game/objects/effects/decals/posters/vgposters.dm
  code/modules/store/items.dm
  icons/obj/posters.dmi
Labels: Content

#26706 Mind Machine
  code/game/machinery/constructable_frame.dm
  code/game/machinery/mind_machine.dm
  code/modules/research/designs/boards/machine_medical.dm
  icons/obj/mind_machine.dmi
  nano/templates/mind_machine.tmpl
  vgstation13.dme
Labels: Content, Update WIKI

#27009 Mind Machine Bugs Part One
  code/game/machinery/mind_machine.dm
  code/modules/telesci/bscrystal.dm
Labels: Bug / Fix

#26879 Put Hypospray in medical belt
  code/game/objects/items/weapons/storage/belt.dm
Labels: Tweak

#27015 Fixes NaNs/infinities with Nano yet again
  code/modules/nano/nanoui.dm
  nano/js/JSON_parseMore.js
  nano/js/nano_state_manager.js
Labels: Bug / Fix, File Cleanup

#27022 Damian asked me to clean mommi inventory code
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/mommi/mommi_inventory.dm
  code/modules/mob/living/silicon/mommi/mommi_modules.dm
  code/modules/mob/living/silicon/robot/robot_inventory.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/destructive_analyzer.dm
Labels: File Cleanup, Tweak

#27004 Fixed warnings and stuff
  code/defines/procs/AStar.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/organs/blood.dm
  code/modules/projectiles/guns/hookshot.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: File Cleanup

#27002 Hunting for Cult bugs
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/role/cultist.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/shade_powers.dm
Labels: Bug / Fix

#27003 Fixed Pathogenic Clouds "visibly" slamming into windows and grilles when getting ZAS'd, or dealing damage when thrown in general
  code/game/objects/structures/grille.dm
  code/game/objects/structures/window.dm
  code/modules/virus2/pathogen_cloud.dm
Labels: Bug / Fix

#27031 Fix cultists not being able to just fucking use runes
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
Labels: Bug / Fix

#27036 Xenomorphs can no longer spam screams by deathgasping
  code/modules/mob/living/emote.dm
Labels: Bug / Fix

#27045 fuck you Humphry Davy
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#27039 The last batch of linter fixes
  code/ZAS/Fire.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_data.dm
  code/game/objects/effects/decals/slag.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/modules/admin/topic.dm
  code/modules/cmc/crew.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/alien/death.dm
  code/modules/mob/living/carbon/brain/death.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/monkey/death.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/death.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/organs/organ.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: File Cleanup

#27043 Prevent casting more than one spell at a time
  code/modules/mob/mob_defines.dm
  code/modules/spells/aoe_turf/aoe_turf.dm
  code/modules/spells/aoe_turf/fall.dm
  code/modules/spells/spell_code.dm
Labels: Bug / Fix

#27027 The vials in an Isolation Centrifuge now stop spinning if it breaks/runs out of power.
  code/modules/virus2/centrifuge.dm
Labels: Bug / Fix

#27016 Fixes a bug with seer rune
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix

#27038 Fixed Toggle-AI verb not working
  code/game/jobs/job/job.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job_controller.dm
Labels: Bug / Fix

#26826 Improves phylactery
  code/game/gamemodes/wizard/artefact.dm
  code/game/gamemodes/wizard/artifacts.dm
Labels: Tweak

#27005 Gives CMO locker a surgeons switchtool
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Tweak

#27008 Lets upgraded service borgs pick up botany disks
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Tweak

#27023 fixes ghetto spacesuit species tagging
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
  icons/mob/head.dmi
  icons/mob/species/grey/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Bug / Fix, Easy Fix

#27051 Added missing fields to players2.sql
  SQL/players2.sql
Labels: System

#27055 maybe fix shuttle lag
  code/modules/media/mediamanager.dm
Labels: Bug / Fix

#27047 allows most atmos stuff to be colored again
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
  code/ATMOSPHERICS/components/unary/unary_base.dm
Labels: Tweak

#26990 Recalculate channels when a headset's frequency is changed.
  code/game/objects/items/devices/radio/headset.dm
Labels: Bug / Fix

#27033 Hello it's us! Your old friends "Spacevine infestation" and "Biomass infestation", we've missed you, why didn't you call?
  code/game/gamemodes/events/spacevines.dm
  code/modules/events/spacevine.dm
  code/modules/hydroponics/spreading/spreading.dm
  icons/effects/spacevines.dmi
Labels: Bug / Fix, Tweak

#27029 Allows stripping belt and ID over exosuit
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#27066 Fixed cows, humans and virtualhearers hard-dels
  code/game/atoms_movable.dm
  code/modules/mob/hearing/virtualhearer.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Bug / Fix

#26951 Rigsuits Fix, Tweaks & New Modules
  code/game/machinery/suit_modifier.dm
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/rig_modules/rig_modules.dm
Labels: Bug / Fix, Content, Tweak, Unatomic Uncle

#27053 Reverted GPS to nanoui
  code/modules/telesci/gps.dm
Labels: :thinking:

#27071 Hotfix for cultists drawing runes
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
Labels: Hotfix

#27068 Fixed implementations of Destroy() not calling parent
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/ATMOSPHERICS/datum_pipeline.dm
  code/ATMOSPHERICS/pipes.dm
  code/__HELPERS/unsorted.dm
  code/controllers/mc/subsystem.dm
  code/controllers/subsystem/garbage.dm
  code/datums/locking_category.dm
  code/datums/wires/wires.dm
  code/game/communications.dm
  code/game/machinery/computer/shuttle_computers.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/objects/structures/vehicles/carts/datum_cart_network.dm
  code/game/turfs/unsimulated/snow.dm
  code/modules/RCD/schematic.dm
  code/modules/maps/map_objects.dm
  code/modules/maps/spawners/spawners.dm
  code/modules/mining/mine_turfs.dm
  code/modules/power/powernet.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/artifact/trigger.dm
Labels: Bug / Fix

#27072 Fixed chrono grenades not working and stuff
  code/modules/spells/aoe_turf/fall.dm
Labels: Bug / Fix

#27067 Remove references to mob/new_player after roundstart
  code/datums/gamemode/dynamic/dynamic.dm
Labels: T-Thanks BYOND

#27046 makes meters readable from as far away as you can see them
  code/game/machinery/atmoalter/meter.dm
Labels: Tweak

#27059 Fixes #27058
  code/modules/virus2/analyser.dm
Labels: Bug / Fix

#27062 Vampires turning to dust from burning will now drop all their items.
  code/modules/mob/living/carbon/human/life/handle_fire.dm
Labels: Tweak

#26758 Strange wheelchair now allows you to buckle other people to it
  code/game/objects/structures/vehicles/wheelchair.dm
Labels: Emoji This :+1: :-1:

#27089 Fixes extra html_encode() in pray and rambler vows
  code/__HELPERS/text.dm
  code/datums/gamemode/role/rambler.dm
  code/modules/admin/verbs/pray.dm
Labels: Bug / Fix

#27095 Possibly fix runechat lag
  code/datums/chat_message.dm
Labels: Performance

#27099 Fix typo
  code/modules/clothing/accessories/storage.dm
Labels: Bug / Fix, Grammar / Formatting

#27088 Re-tgui-ified GPS, added potential bug workaround
  code/modules/admin/verbs/SDQL_2/SDQL_2_std.dm
  code/modules/nano/nanoui.dm
  code/modules/telesci/gps.dm
  code/modules/tgui/tgui.dm
Labels: T-Thanks BYOND, UI

#27098 Fixed deaf people hearing instruments
  code/game/objects/structures/musician.dm
Labels: Bug / Fix

#27057 Fixed glass floors having the wrong icon sometimes
  code/game/turfs/simulated/floor_glass.dm
Labels: Bug / Fix

#27091 Added lazy events
  __DEFINES/global.dm
  code/_hooks/events.dm
  code/_onclick/mutual_cuff.dm
  code/datums/helper_datums/teleport.dm
  code/datums/shuttle.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/objects/items/weapons/scrolls.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/lazy_events.dm
Labels: System

#27080 Adds insectoid cult alts, fixes broken gloves on vox and insectoids, tweaks bug sec armor.
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/modules/clothing/gloves/boxing.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/miscellaneous.dm
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/suit.dmi
  icons/mob/species/vox/gloves.dmi
Labels: 100% tested, Sprites, ❤️ Quality of Life ❤️

#27069 GC_FINDREF logs the refs
  code/controllers/subsystem/garbage.dm
Labels: System

#27061 Some Cult shading tweaks
  code/modules/mob/dead/observer/observer.dm
  code/modules/organs/organ_external.dm
Labels: Bug / Fix, Tweak

#27078 Fix confusion runes not affecting mobs and cameras in the dark
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix

#27104 Reverted spell spam workaround
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/modules/mob/mob_defines.dm
  code/modules/spells/aoe_turf/aoe_turf.dm
  code/modules/spells/aoe_turf/fall.dm
  code/modules/spells/spell_code.dm
Labels: System

#27112 Mosin Resprite II (the fixening)
  code/modules/projectiles/guns/projectile/mosin.dm
  icons/obj/biggun.dmi
Labels: 100% tested, Sprites, ❤️ Quality of Life ❤️

#27121 Fixed human screen object hard dels
  code/modules/mob/mob.dm
Labels: Bug / Fix

#27122 Fixed mob transformation hard dels
  code/datums/gamemode/factions/wizard.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/objectives/die.dm
  code/datums/mind.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/robot.dm
  code/game/striketeams/emergency_response_team.dm
  code/game/striketeams/striketeam_datums.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/transform_procs.dm
Labels: Bug / Fix

#27124 Fixed two minor fuck ups
  code/datums/mind.dm
  code/modules/mob/living/carbon/species.dm
Labels: File Cleanup

#27125 Fixed Farmbot doing nothing.
  code/game/machinery/bots/farmbot.dm
Labels: Bug / Fix

#27131 Fixes Roundstart Assistants
  code/game/jobs/job_controller.dm
Labels: Bug / Fix

#27107 Plasma Cutter Safeties (for hitting rocks)
  code/modules/mining/mine_items.dm
Labels: ❤️ Quality of Life ❤️

#27106 Adds More Mugs to Boozevender
  code/game/machinery/vending.dm
Labels: Tweak

#27065 removed SVN stuff
  code/datums/gamemode/gamemode.dm
  code/datums/helper_datums/getrev.dm
  code/world.dm
  config/svndir.txt
Labels: File Cleanup, Secret repo conflict.

#27135 Corgis no longer break emulsions
  code/modules/mob/living/simple_animal/friendly/corgi.dm
Labels: Muh Immulsions

#27142 removed hard del from add_fingerprint
  code/game/atoms.dm
Labels: 0% tested

#27130 allows firedoor frame deconstruction
  code/game/machinery/doors/firedoor.dm
Labels: Consistency Issue

#26960 AI holopad overlays verb
  code/game/machinery/hologram.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
Labels: Emoji This :+1: :-1:

#27162 FUCK
  code/modules/admin/IsBanned.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#27134 Clickdrag someone into a mirror to change their appearance
  code/game/objects/structures/mirror.dm
Labels: Content

#27158 Forgotten Clicks
  code/game/machinery/door_control.dm
  code/game/machinery/flasher.dm
  code/game/machinery/igniter.dm
  code/game/objects/structures/morgue.dm
Labels: Sound

#27157 Added a bunch more in-hand book icons
  code/game/gamemodes/wizard/spellbook.dm
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/mob/living/simple_animal/bees/bees_items.dm
  code/modules/research/xenoarchaeology/manuals.dm
  icons/mob/in-hand/left/books.dmi
  icons/mob/in-hand/right/books.dmi
  icons/obj/library.dmi
Labels: Sprites

#27149 Surgeons can examine patients with open body parts to see what's inside
  code/modules/mob/living/carbon/human/examine.dm
Labels: ❤️ Quality of Life ❤️

#27147 AI can no longer track people who changed identity
  code/game/machinery/camera/camera.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/say.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/say_readme.dm
  code/modules/scripting/Implementations/Telecomms.dm
Labels: Bug / Fix

#27144 removed atom del profiler
  __DEFINES/global.dm
  code/game/atoms.dm
  code/game/machinery/computer/HolodeckControl.dm
  code/game/objects/effects/effect_system.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/awaymissions/corpse.dm
  code/modules/mob/hearing/virtualhearer.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Performance

#27123 Vampire chapel blink tweak.
  code/modules/spells/aoe_turf/blink.dm
Labels: Tweak

#27103 Make MindSwap not crash people
  code/modules/mob/spells.dm
  code/modules/spells/targeted/mind_transfer.dm
Labels: Bug / Fix

#27077 dreamchecker errors now cause travis to fail
  .travis.yml
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/media/jukebox.dm
  code/modules/surgery/butt.dm
  code/modules/surgery/tooth.dm
  maps/RandomZLevels/stationCollision.dm
Labels: System

#27118 Ruleset chance to fire is halved if it fired last or current round
  code/controllers/subsystem/init/persistence_misc.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Tweak

#27119 Mining Scanner Activation via Alt-Click
  code/modules/mining/mine_items.dm
Labels: Emoji This :+1: :-1:

#26760 Telepads are now upgradeable among other things
  code/game/machinery/computer/buildandrepair.dm
  code/modules/telesci/telepad.dm
  code/modules/telesci/telesci_computer.dm
  nano/templates/telescience_console.tmpl
Labels: :up: Powercreep :up:

#27154 Increases Playing Card Hand Size from 5 to 7
  code/modules/games/cards/playing_cards.dm
Labels: Emoji This :+1: :-1:, ❤️ Quality of Life ❤️

#27169 tiny bugfixes
  code/game/mecha/mecha.dm
Labels: Bug / Fix, Needs Fixing

#27177 Fixed PDA and RCD hard dels
  code/game/machinery/telecomms/multicaster.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/RCD/schematic.dm
  code/modules/RCD/schematics/engi.dm
  code/modules/html_interface/html_interface.dm
Labels: Bug / Fix, Performance

#27148 Implant removal surgery is faster, inverted order
  code/modules/surgery/implant.dm
Labels: Balance, ❤️ Quality of Life ❤️

#27145 Removed unused events
  __DEFINES/global.dm
  code/controllers/subsystem/pipenet.dm
  code/datums/inventory/inventory.dm
  code/datums/inventory/slot.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/client/client procs.dm
  code/modules/power/generator.dm
  code/world.dm
  vgstation13.dme
Labels: File Cleanup, Secret repo conflict.

#27151 makes secbelt fit more small things
  code/game/objects/items/weapons/storage/belt.dm
Labels: :up: Powercreep :up:, Emoji This :+1: :-1:

#27153 another glock resizing
  code/modules/projectiles/guns/projectile/pistol.dm
Labels: Balance, Emoji This :+1: :-1:

#27126 Adds a new (currently unobtainable) wizard spell: Absorb
  .gitignore
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/modules/spells/targeted/absorb.dm
  vgstation13.dme
Labels: Content

#27165 Fishtank boards can now be soldered to make them larger/smaller
  code/game/machinery/computer/buildandrepair.dm
Labels: Emoji This :+1: :-1:, Tweak

#27161 Allows carded AI's to be inserted into an AI upload
  code/game/machinery/computer/ai_core.dm
  code/game/machinery/computer/aifixer.dm
  code/game/machinery/computer/law.dm
Labels: Tweak

#27179 Fixed requests console hard dels
  code/game/machinery/requests_console.dm
  code/modules/admin/verbs/debug.dm
  code/modules/events/money_hacker.dm
Labels: Bug / Fix, Performance

#27181 Fixed ghost holomap hard del
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/verbs.dm
Labels: Bug / Fix, Performance

#27178 Fixed buildmode hard dels and memory leak
  code/modules/admin/buildmode.dm
  code/modules/client/client defines.dm
Labels: Bug / Fix, Performance, Secret repo conflict.

#27164 Halves the cost for wizard cooldown upgrades
  code/modules/spells/aoe_turf/blink.dm
  code/modules/spells/aoe_turf/conjure/pitbulls.dm
  code/modules/spells/spell_code.dm
Labels: Emoji This :+1: :-1:

#27170 Xenoarcheology Matter Replicator can now print some more interesting stuff.
  code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
Labels: Emoji This :+1: :-1:, Tweak

#27174 Added smashing noises when hulked out characters punch a wall.
  code/game/turfs/simulated/walls.dm
Labels: Tweak

#27175 Tinfoil hats prevent AI tracking
  code/game/machinery/camera/tracking.dm
Labels: Balance, Tweak

#27215 pAIs can use their GPS again
  code/__HELPERS/game.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/tgui/states/adjacent.dm
Labels: Bug / Fix

#27213 Improved snaxi's holomap
  __DEFINES/setup.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/floor.dm
  code/game/turfs/unsimulated/snow.dm
  code/game/turfs/unsimulated/walls.dm
  code/modules/html_interface/map/station_map.dm
  code/modules/mining/mine_areas.dm
  code/modules/mining/mine_turfs.dm
  maps/RandomZLevels/stationCollision.dm
  maps/randomvaults/objects.dm
Labels: System, ❤️ Quality of Life ❤️

#27212 Disposals Recycler fix
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
Labels: Bug / Fix

#27187 Fix admin vermin infestation
  code/modules/events/infestation.dm
Labels: Bug / Fix

#27070 THE "GORY" UPDATE
  __DEFINES/setup.dm
  code/controllers/subsystem/init/more_init_stuff.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/game/atoms.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/objects/effects/decals/Cleanable/aliens.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/objects/effects/decals/Cleanable/tracks.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/gibs.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/structures/mop_bucket.dm
  code/game/turfs/simulated.dm
  code/modules/detectivework/detective_work.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_equipment.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/blood.dm
  code/modules/organs/organ_objects.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  code/modules/virus2/curer.dm
  icons/mob/dam_human.dmi
  icons/mob/human_races/r_plasmaman_pb.dmi
  icons/mob/human_races/r_plasmaman_sb.dmi
  icons/mob/human_races/vox/r_def_vox.dmi
  icons/mob/human_races/vox/r_def_voxazu.dmi
  icons/mob/human_races/vox/r_def_voxbrn.dmi
  icons/mob/human_races/vox/r_def_voxemrl.dmi
  icons/mob/human_races/vox/r_def_voxgry.dmi
  icons/mob/human_races/vox/r_def_voxlgrn.dmi
  icons/mob/human_races/vox/r_vox.dmi
  icons/mob/human_races/vox/r_voxazu.dmi
  icons/mob/human_races/vox/r_voxboney.dmi
  icons/mob/human_races/vox/r_voxbrn.dmi
  icons/mob/human_races/vox/r_voxemrl.dmi
  icons/mob/human_races/vox/r_voxgry.dmi
  icons/mob/human_races/vox/r_voxlgrn.dmi
  icons/obj/janitor.dmi
  vgstation13.dme
Labels: Bug / Fix, Sprites, Tweak

#27186 Adds a brain damage line
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
Labels: Tweak

#27236 Revert "Make MindSwap not crash people"
  code/modules/mob/spells.dm
  code/modules/spells/targeted/mind_transfer.dm
Labels: File Cleanup

#27205 Some Horizon holomap and cult fixes
  maps/nrvhorizon.dm
Labels: Bug / Fix, Conflicts

#27240 Fixed dreamchecker warnings
  code/game/objects/items.dm
  code/modules/organs/blood.dm
Labels: File Cleanup

#27220 Fixed roundstart rulesets not being affected by weight modifiers
  code/datums/gamemode/dynamic/dynamic.dm
Labels: 0% tested, Bug / Fix

#27241 converted on_irradiate to lazy events
  __DEFINES/global.dm
  code/_hooks/events.dm
  code/game/objects/items/devices/geiger.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/spacesuits/rig_modules/rig_modules.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: 100% tested, System

#27239 converted on_moved to lazy events
  __DEFINES/global.dm
  code/_hooks/events.dm
  code/_onclick/mutual_cuff.dm
  code/datums/tether.dm
  code/defines/obj/weapon.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/effects/beam.dm
  code/game/objects/items/misc_items.dm
  code/game/objects/items/robot/robot_items/robot_binoculars.dm
  code/game/objects/items/trader.dm
  code/game/objects/items/weapons/RCL.dm
  code/game/objects/items/weapons/implants/exile2.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/components.dm
  code/modules/spells/general/lightning.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
  maps/randomvaults/sokoban.dm
Labels: System

#27243 Fixes do_after bars drawing weird on horizontal mobs
  code/__HELPERS/unsorted.dm
Labels: 100% tested, Bug / Fix

#27244 Carbons lying down or standing up no longer reset transform matrix
  code/modules/mob/living/carbon/update_icons.dm
Labels: 100% tested

#27254 Fixed bed/chairs/vehicles hard dels and persistent screen alarms
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/vehicles/clowncart.dm
  code/game/objects/structures/vehicles/vehicle.dm
Labels: Bug / Fix

#27257 Automatic ore loader no longer needs to be turned off and on after being dropped
  code/game/objects/items/weapons/storage/bags.dm
Labels: ❤️ Quality of Life ❤️

#27256 Fixed bots hard dels
  code/game/machinery/bots/bots.dm
Labels: Bug / Fix, Performance

#27255 Fixed cleanables hard dels, removed manual New() calls
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/pipe/construction.dm
  code/ATMOSPHERICS/pipe/pipe_dispenser.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/bots/secbot.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/turfs/simulated.dm
  code/modules/mob/dead/observer/verbs.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/blood.dm
  code/modules/paperwork/photocopier.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/virus2/effect/stage_2.dm
  code/modules/virus2/effect/stage_4.dm
Labels: Bug / Fix, Performance

#27260 converted on_destroyed to lazy events
  __DEFINES/global.dm
  code/_hooks/events.dm
  code/datums/chat_message.dm
  code/datums/map_elements.dm
  code/game/atoms_movable.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/camera/motion.dm
  code/game/objects/effects/beam.dm
  code/modules/projectiles/guns/projectile/constructable/tomahawk.dm
  maps/randomvaults/sokoban.dm
  maps/randomvaults/spessmart.dm
Labels: System

#27261 The delete verb no longer hard dels
  code/datums/datumvars.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Performance, T-Thanks BYOND

#27278 Fixes accessing a destroyed object
  code/_onclick/hud/spell_screen_objects.dm
Labels: Bug / Fix

#27281 Fixes wizard sneks runtiming when they die
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Bug / Fix

#27282 Fixed grammar on code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/ai/examine.dm
Labels: Grammar / Formatting

#27275 fixes skeletons having asthma attacks
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix

#27266 Adds the Cyrillic block to the allowed characters in chat
  code/__HELPERS/text.dm
Labels: Tweak

#27250 Fix description for spellbook of lightning and buttbots revenge.
  code/game/gamemodes/wizard/spellbook_oneuse.dm
Labels: Grammar / Formatting

#27190 Ammolathe recycling
  code/game/machinery/ammolathe.dm
  code/game/machinery/autolathe.dm
  code/modules/mining/materials.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rocket.dm
  code/modules/projectiles/ammunition/speedloaders.dm
  code/modules/projectiles/guns/gun_parts.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/rocketlauncher.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: Tweak

#27232 Runechat images containing your name will now be highlighted
  code/__HELPERS/text.dm
  code/datums/chat_message.dm
  interface/skin.dmf
Labels: Tweak

#27234 Makes stacked runechat messages fade out slightly slower.
  code/datums/chat_message.dm
Labels: Tweak

#27116 Fixed droppers consistently saying 'You can't do that, the dropper is not open."
  code/game/jobs/job/security.dm
  code/modules/reagents/reagent_containers/dropper.dm
Labels: Bug / Fix

#27279 Fixes spacepods runtiming every time they shoot
  code/modules/projectiles/projectile.dm
Labels: Bug / Fix

#27253 Wizard contracts of apprenticeship never recruit automatically
  code/game/gamemodes/wizard/apprentice_contract.dm
Labels: Tweak

#27270 converted on_density_change to lazy events
  __DEFINES/global.dm
  code/_hooks/events.dm
  code/game/atoms.dm
  code/game/gamemodes/events/powercreeper.dm
  code/game/objects/effects/beam.dm
Labels: Bug / Fix, Performance, System

#27176 Cyborgs are now hackable again by Malf AIs
  code/game/machinery/computer/robot.dm
  code/modules/power/apc.dm
Labels: Bug / Fix

#27233 Emotes made by players are now visible on runechat
  code/datums/chat_message.dm
  code/datums/emotes.dm
  interface/skin.dmf
  interface/skin_azerty.dmf
Labels: Conflicts, Tweak

#27294 Bugfix for autolathes
  code/game/machinery/autolathe.dm
Labels: Bug / Fix

#27289 More runtimes
  code/game/machinery/autolathe.dm
  code/modules/credits/credits.dm
  code/modules/telesci/telesci_computer.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/autolathe.dm
  maps/randomvaults/gingerbread_house.dmm
Labels: Bug / Fix

#27299 capitalizes O2/N2 on emergency lockers
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Labels: Grammar / Formatting

#27296 fixed typo on personal lockers
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
Labels: Grammar / Formatting

#27297 It's either this or anchoring them all
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
Labels: Grammar / Formatting

#27204 old glocks + suppressor overlays + other changes
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/gun_parts.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/obj/biggun.dmi
  icons/obj/gun.dmi
  icons/obj/gun_part.dmi
Labels: Bug / Fix, Sprites, Unatomic Uncle

#27273 Vampires will no longer shadowstep onto asteroid tiles.
  code/modules/spells/aoe_turf/blink.dm
Labels: Tweak

#27285 disable AI use of camera computers
  code/game/machinery/computer/camera.dm
Labels: Tweak

#27274 Telesci telepad fixes
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
Labels: Bug / Fix

#27309 Maybe fix nano/tgui runtime
  code/modules/mob/logout.dm
Labels: Bug / Fix

#27302 Adds 11 new hair sprites.
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#27320 Fixed hf machete runtime
  code/game/objects/items/weapons/melee/energy.dm
Labels: Bug / Fix
