Repository vgstation-coders/vgstation13, pull requests merged in 2021-03, with the labels that each got.

#28895 Totally Radical Radiation Collectors
  code/datums/wires/jukebox.dm
  code/game/machinery/doors/airlock.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/walls_mineral.dm
  code/modules/media/broadcast/transmitters/broadcast.dm
  code/modules/media/jukebox.dm
Labels: Tweak

#28957 Ghosts no longer change icon state of security alerts computer
  code/game/machinery/computer/security_alert.dm
Labels: Bug / Fix

#28948 Adds sound to priority announcements
  code/defines/procs/captain_announce.dm
Labels: Sound, Tweak

#28941 Lossetta stone can teach Clown language.
  code/modules/research/xenoarchaeology/artifact/artifact_losetta.dm
Labels: Tweak

#28919 Adds three new bar drinks and a new hot beverage.
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/drinks.dmi
Labels: Content

#28915 Hyperzine increases blood loss
  code/modules/organs/blood.dm
  code/modules/organs/organ_external.dm
Labels: Balance

#28905 Adds the "Impostor" character from the 2018 hit video game "Among Us"
  code/modules/mob/living/simple_animal/hostile/scp_173.dm
  icons/mob/scp.dmi
Labels: Content, Unable To Reproduce

#28904 Holy water now explodes in contact with potassium, just like regular water.
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  sound/misc/holyhandgrenade.ogg
Labels: Balance, Content, Emoji This :+1: :-1:

#28958 Bag of Holding now checks for another in nested items to baguloose (including dionas)
  code/game/objects/items/weapons/storage/bluespace.dm
Labels: Bug / Fix, Consistency Issue

#28858 Add some more information on the canister NanoUI interface
  nano/templates/canister.tmpl
Labels: Controversial, Tweak, i ded, ❤️ Quality of Life ❤️

#28918 Turns lightswitches off by default.
  code/__HELPERS/game.dm
  code/__HELPERS/typeof.dm
  code/game/gamemodes/gameticker.dm
  code/game/machinery/lightswitch.dm
Labels: Needs Review, Tweak

#28971 Revert "Adds the "Impostor" character from the 2018 hit video game "Among Us""
  code/modules/mob/living/simple_animal/hostile/scp_173.dm
  icons/mob/scp.dmi
Labels: Bug / Fix, Feature Loss

#29011 Fixes Syndicate code words not being highlighted in red for challengers.
  code/modules/mob/living/say.dm
Labels: Bug / Fix

#28981 A PR to remove the Snow Taxi map from the rotation except for certain months
  code/__HELPERS/files.dm
Labels: Mapping (Snaxi ❄)

#28973 Trader (and other) radio uplinks can now be loaded with telecrystals
  code/game/objects/items/devices/radio/radio.dm
Labels: Bug / Fix

#28979 Fix voting frauds in map selection
  code/modules/html_interface/voting/voting.dm
Labels: Logging / Administration, 🚓Fun Police🚓

#28873 Insecticide reagent, replacement for Pest Spray.
  __DEFINES/reagents.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/vending.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/mob/living/simple_animal/hostile/bigroach.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
  code/modules/mob/living/simple_animal/roach.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Consistency Issue, Content

#29037 Gourmonger tweaks
  code/modules/power/gourmonger.dm
Labels: Bug / Fix, Tweak

#29028 Makes some wooden objects flammable that previously were not
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/mannequin.dm
Labels: Consistency Issue, Muh Immulsions

#29030 Makes object burning slightly less bad
  code/ZAS/Fire.dm
Labels: Bug / Fix, System

#29041 Should fix deconversion-shade spam
  code/game/objects/items/weapons/storage/bible.dm
Labels: Bug / Fix

#29036 Rainbow Gun Fix: Color Edition
  code/__HELPERS/math/ray/ray.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Bug / Fix

#28969 Lists of contents as viewed by ghost now looks a lot nicer
  code/__HELPERS/lists.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/clothing/accessories/accessory.dm
Labels: Grammar / Formatting, Tweak

#29046 Gourmonger Tweaks: The Second Course
  code/modules/power/gourmonger.dm
Labels: Tweak

#28780 New Alcatraz Gear
  code/game/machinery/autolathe.dm
  code/game/machinery/mind_machine.dm
  code/game/machinery/recharger.dm
  code/game/machinery/vending.dm
  code/game/mecha/mech_bay.dm
  code/game/objects/items.dm
  code/game/objects/items/trader.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/vehicles/secway.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/mob/mob.dm
  code/modules/reagents/reagent_containers/glass/jar.dm
  code/modules/spells/targeted/targeted.dm
  icons/mob/head.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/flora/big_pots.dmi
  icons/obj/vehicles.dmi
Labels: Content

#28943 Allows portable turrets to actually be deconstructed
  code/game/machinery/portable_turret.dm
Labels: Tweak

#29075 Fixed a Bug With Monkey Madness
  code/datums/gamemode/factions/junglefever.dm
Labels: Bug / Fix

#29085 A Wrench in the Engine
  code/game/objects/structures/vehicles/vehicle.dm
Labels: Hotfix, ⚠️ OH GOD IT'S LOOSE ⚠️

#29076 Gourmonger Meal Priority Fix
  code/modules/power/gourmonger.dm
Labels: Hotfix

#29107 Donutgiver fix, take 2
  code/game/objects/items/trader.dm
  icons/mob/head.dmi
Labels: Bug / Fix, Sprites

#29120 Teleports stop accepting sparks from nearby ones
  code/datums/helper_datums/teleport.dm
Labels: Bug / Fix
