Repository vgstation-coders/vgstation13, pull requests merged in 2021-10, with the labels that each got.

#30880 tgui power monitor
  code/modules/power/monitor.dm
  code/modules/power/power.dm
  tgui/packages/tgui/interfaces/PowerMonitor.js
  tgui/public/tgui.bundle.js
Labels: UI

#30959 Less infuriating buildmode
  code/modules/admin/buildmode.dm
Labels: Bug / Fix

#30881 Hat stacking
  code/game/gamemodes/events/holidays/Holidays.dm
  code/game/objects/structures/mannequin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/clothing.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/examine.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/silicon/mommi/examine.dm
  code/modules/mob/living/silicon/mommi/update_icons.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/hologram/hologram_inventory.dm
Labels: Content

#30906 Timer subsystem
  __DEFINES/subsystem.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/datum.dm
  code/__HELPERS/priority_queue.dm
  code/_onclick/hud/screen_alarms.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/pathing.dm
  code/controllers/subsystem/timer.dm
  code/defines/procs/AStar.dm
  vgstation13.dme
Labels: Bug / Fix, System

#30927 Lightning can now be fired at bots and mechas.
  code/modules/spells/general/lightning.dm
Labels: Balance

#30930 Allow most vehicles to spin once again
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/vehicles/adminbus.dm
  code/game/objects/structures/vehicles/clowncart.dm
  code/game/objects/structures/vehicles/firebird.dm
  code/game/objects/structures/vehicles/gokart.dm
  code/game/objects/structures/vehicles/janicart.dm
  code/game/objects/structures/vehicles/vehicle.dm
Labels: Tweak

#30935 Better multi-Z layer connection system
  code/controllers/configuration.dm
  code/modules/multiz/_HELPERS.dm
  code/modules/multiz/basic.dm
  code/modules/multiz/turfs.dm
  config-example/config.txt
  maps/_map.dm
  maps/test_multiz.dm
  maps/tgstation-snow.dm
Labels: System, 100% tested, Tweak

#30947 Orderly Tweaks & Nurse Orderlies
  code/datums/outfit/medical.dm
  code/game/jobs/job/medical.dm
  code/game/objects/items/cookie_synth.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Tweak

#30951 Brute damage now only disfigures faces if the weapon used wasn't sharp.
  code/modules/organs/organ_external.dm
  code/modules/surgery/face.dm
Labels: Bug / Fix, Tweak

#30953 Makes some machines ping/buzz/beep more audibly
  code/game/machinery/iv_drip.dm
  code/modules/hydroponics/seed_machines.dm
Labels: Sound

#30954 Places surgery extracted items in hands on removal
  code/modules/mob/living/carbon/human/human.dm
  code/modules/surgery/implant.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#30817 Fungal Telepathy
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/carbon/species_powers.dm
Labels: Balance, Content, ❤️ Quality of Life ❤️

#30765 Makes random bought uplink item show true name and cost
  code/datums/uplink_item.dm
Labels: Bug / Fix, 100% tested

#30639 Mob shrinking standardisation
  code/game/dna/genes/powers.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/mob_defines.dm
  code/modules/virus2/effect/stage_2.dm
Labels: Consistency Issue, Tweak

#30962 test_tiny creates bank accounts for crew members
  code/modules/Economy/Accounts.dm
  maps/test_tiny.dm
Labels: System

#30956 Reduces paramedic limit to 2
  code/game/jobs/job/medical.dm
Labels: Balance

#30957 Map element (vault etc) updates: Item overwriting option, rotation on loading
  code/controllers/configuration.dm
  code/datums/map_elements.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/awaymissions/maploader/reader.dm
  code/modules/randomMaps/dungeons.dm
  code/modules/randomMaps/vault_definitions.dm
  code/modules/randomMaps/vaults.dm
  config-example/config.txt
  maps/randomvaults/sokoban.dm
Labels: Mapping (Vault :question:), 100% tested

#30971 Multi-Z fix #3 ish
  code/modules/multiz/basic.dm
Labels: Bug / Fix

#30921 Old Vendotron Events
  __DEFINES/global.dm
  code/datums/helper_datums/command_alerts.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/events/old_vendotron_event/old_vendotron.dm
  code/modules/events/old_vendotron_event/vendor_crash_event.dm
  code/modules/events/old_vendotron_event/vendor_teleport_event.dm
  icons/mob/old_vendotron.dmi
  icons/obj/vending.dmi
  vgstation13.dme
Labels: Content

#30984 tgui TEG
  code/modules/power/generator.dm
  tgui/packages/tgui/interfaces/TEG.js
  tgui/public/tgui.bundle.js
Labels: UI

#30993 Fixed examining worn items as a ghost showing the examined item twice
  code/modules/mob/dead/observer/observer.dm
Labels: Bug / Fix

#30992 Fixed dojo and time agent's place being dark
  code/game/area/Space Station 13 areas.dm
Labels: Bug / Fix

#30948 Buffs clowns
  code/game/objects/items/weapons/clown_items.dm
  sound/items/bikehorn_curaracha.ogg
Labels: Content

#30965 Human leather color now depends on the color of their species' skin color
  code/datums/helper_datums/butchering.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/mob/living/carbon/species.dm
  icons/obj/butchering_products.dmi
Labels: Sprites, Tweak

#30996 Multi-z infinite loop fixes
  code/controllers/configuration.dm
  code/modules/multiz/basic.dm
  code/modules/multiz/falling.dm
  config-example/config.txt
Labels: Bug / Fix

#30775 Allows anything of type /obj/structure to bump things away in front of them
  code/game/objects/structures.dm
  code/game/objects/structures/vehicles/vehicle.dm
  maps/randomvaults/sokoban.dm
Labels: Controversial, Content, ❤️ Quality of Life ❤️, Tweak, Emoji This :+1: :-1:

#30982 Re-enables rotation/spin on shuttle chairs and couches.
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Tweak

#31093 Wrecked RTGs become Broken Cells.
  code/game/objects/items/weapons/power_cells.dm
Labels: Bug / Fix, Oversight

#31166 Vending machines can now offer month-specific items
  code/game/machinery/vending.dm
Labels: Tweak

#31172 Lazy-init pAImove_delayer
  code/game/objects/objs.dm
Labels: System

#31161 Fixes Abstract Giving
  code/game/objects/items.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/give.dm
  code/modules/mob/mob_grab.dm
Labels: Bug / Fix

#31174 Pitbulls will no longer attack their dearest mommy
  code/datums/gamemode/role/wizard.dm
  code/datums/mind.dm
Labels: Bug / Fix, i ded
