Repository vgstation-coders/vgstation13, pull requests merged in 2021-07, with the labels that each got.

#29939 Mech Beacon Fix
  code/game/mecha/mecha_control_console.dm
Labels: Bug / Fix

#29940 "Unblurries" pictures of moving people & Fixed AI Hologram
  code/datums/datacore.dm
  code/game/gamemodes/gameticker.dm
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
Labels: Bug / Fix

#29943 Fixes eye ghetto surgery when using a fork
  code/game/objects/items/weapons/kitchen.dm
Labels: Bug / Fix

#29938 Refactored go-kart code
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items/stacks/tiles/mineral.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/vehicles/firebird.dm
  code/game/objects/structures/vehicles/gokart.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/modules/mob/emote.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: System

#29935 Better spider eyes and more perception goodness
  __DEFINES/planes+layers.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/plague_mice.dm
  code/modules/client/client defines.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species_powers.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/organs/internal/eyes/eyes.dm
  code/modules/power/lighting/lighting.dm
Labels: Content

#29941 Added a thing for adminbus
  code/game/objects/items/bodybag.dm
Labels: Content

#29930 Fixes certain types of glasses such as mesons or science goggles not fitting inside pockets.
  code/modules/clothing/glasses/glasses.dm
Labels: Bug / Fix

#29927 More hobo tweaks
  code/datums/outfit/special_outfits/special.dm
  code/modules/mob/dead/observer/verbs.dm
  maps/misc/hoboshack.dmm
Labels: Bug / Fix

#29905 Syndie Shipping
  code/game/objects/items/stacks/packagewrap.dm
  code/modules/recycling/disposal.dm
Labels: Bug / Fix

#29933 Energy shotgun loaded chamber light + alt-click sound
  code/modules/projectiles/guns/energy/stun.dm
  icons/obj/gun.dmi
Labels: Sound, Sprites

#29915 simple_animal flap and aflap
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/emote.dm
Labels: Content

#29949 corgi immersions unshattered
  code/modules/mob/living/simple_animal/friendly/corgi.dm
Labels: Grammar / Formatting

#29958 Fixes a bunch of non-lighting_overlay atoms still being on LIGHTING_PLANE
  __DEFINES/planes+layers.dm
  code/ATMOSPHERICS/hvac/spaceheater.dm
  code/_onclick/ventcrawl.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_projectiles.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/holosign.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/station_map.dm
  code/game/machinery/vending.dm
  code/game/mecha/combat/marauder.dm
  code/game/objects/effects/beam.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/items/weapons/null_rod.dm
  code/game/objects/structures/dorfpod.dm
  code/game/objects/structures/vehicles/adminbus_powers.dm
  code/modules/assembly/infrared.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mining/mine_structures.dm
  code/modules/mob/living/silicon/mommi/update_icons.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/hostile/glow_orb.dm
  code/modules/mob/living/simple_animal/hostile/human/jackal.dm
  code/modules/mob/mob.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/xenoarchaeology/tools/anomaly_container.dm
  code/modules/runescape/runescape_pvp.dm
  code/modules/virus2/analyser.dm
  code/modules/virus2/centrifuge.dm
  code/modules/virus2/diseasesplicer.dm
  code/modules/virus2/dishincubator.dm
Labels: Bug / Fix, Hotfix

#29959 Reverts my dreaming.dm changes from #29915
  code/modules/flufftext/Dreaming.dm
Labels: Fluff :teddy_bear:

#29960 Revert "Sets world.movement_mode to TILE_MOVEMENT_MODE"
  code/world.dm
Labels: Bug / Fix, T-Thanks BYOND

#29945 unique vox voices
  code/game/sound.dm
  code/modules/client/client procs.dm
  sound/misc/voxvocal1.ogg
  sound/misc/voxvocal2.ogg
  sound/misc/voxvocal3.ogg
  sound/misc/voxvocal4.ogg
  sound/misc/voxvocal5.ogg
Labels: Secret repo conflict.

#29966 Fixed a bunch of hard-dels
  code/controllers/subsystem/init/more_init_stuff.dm
  code/datums/supplypacks.dm
  code/modules/food/icecreamvat.dm
Labels: Bug / Fix, Performance

#29967 Refactored holodeck
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/computer/HolodeckControl.dm
  maps/misc/holodeck_olympics.dmm
  maps/olympics.dmm
  maps/olympics_z2.dmm
Labels: Tweak

#29898 Inactive gene fix for bartenders and detectives
  code/datums/outfit/civilian.dm
  code/datums/outfit/security.dm
Labels: Bug / Fix

#29909 No Mechfab Access Requirement
  code/game/mecha/mech_fabricator.dm
Labels: Consistency Issue

#29907 Robotics for the Robos
  code/game/jobs/job/science.dm
Labels: Balance, Controversial

#29926 Allows forges to smelt ores
  code/game/objects/items/robot/robot_items/robot_furnace.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/ores_coins.dm
  code/modules/mining/smelting.dm
Labels: Content

#29937 (Revival) Bikehorn goes off if you step on it
  code/game/objects/items/weapons/clown_items.dm
Labels: Honk

#29944 Adds some Game Panel admin toggles
  __DEFINES/global.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/events/event_dynamic.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#29954 Hides hobo shacks from the holomap
  code/game/area/Space Station 13 areas.dm
Labels: Bug / Fix

#29955 Allows mass pipe painting to work with pipe end caps
  code/ATMOSPHERICS/components/unary/cap.dm
  code/modules/RCD/schematics/pipe.dm
Labels: Bug / Fix, Consistency Issue

#29962 Fixes Security/Medical Record Pictures of non-humans having them look like humans
  code/datums/datacore.dm
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
Labels: Bug / Fix, Hotfix, why

#29968 Fixes splashing full containers on dispensers
  code/modules/reagents/reagent_containers.dm
Labels: Bug / Fix

#29978 Allows Ghosts to click Portals and engaged teleporter HUBs to use them
  code/datums/helper_datums/teleport.dm
  code/game/objects/effects/portals.dm
Labels: Bug / Fix

#29969 missingtexture
  code/modules/RCD/schematics/tile.dm
  code/modules/RCD/tile painter.dm
  icons/turf/floors.dmi
Labels: Fluff :teddy_bear:, Sprites

#29971 Logs and sends prayers/centcomm/syndicate/fax messages to admin channels
  code/modules/admin/verbs/pray.dm
  code/modules/paperwork/fax.dm
Labels: Consistency Issue, Logging / Administration

#29974 Forces a few specific areas' lightswitches on at roundstart
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/lightswitch.dm
Labels: Tweak

#29982 Some Strike team logging
  code/game/striketeams/striketeam_datums.dm
Labels: Logging / Administration, ❤️ Quality of Life ❤️

#29977 Fixes the Master Trainer Belt's mobs attacking the agent who bought the belt
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/uplink_item.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#29976 Blood Diseases transmission through biting, and a some contact transmission consistency
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/combat.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/living_defense.dm
Labels: Bug / Fix, Consistency Issue, Content

#29965 Photo Booth, ID Photos, and Scissors (the Database Update Update)
  code/game/machinery/autolathe.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/paperwork/photography.dm
  code/modules/research/designs/boards/machine_misc.dm
  icons/effects/32x32.dmi
  icons/effects/70x70.dmi
  icons/obj/items.dmi
  icons/obj/stationobjs.dmi
Labels: Content

#29961 Wristwatches
  __DEFINES/accessories.dm
  __DEFINES/archaeo_defines.dm
  code/datums/action.dm
  code/datums/outfit/captain.dm
  code/datums/outfit/special_outfits/special.dm
  code/datums/outfit/striketeams/nukeop.dm
  code/game/machinery/computer/store.dm
  code/modules/clothing/accessories/wristwatch.dm
  code/modules/clothing/clothing.dm
  code/modules/maps/spawners/spawners.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/research/xenoarchaeology/finds/digsites.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/store/items.dm
  icons/mob/clothing_accessories.dmi
  icons/mob/in-hand/left/clothing_accessories.dmi
  icons/mob/in-hand/right/clothing_accessories.dmi
  icons/obj/clothing/accessory_overlays.dmi
  icons/obj/watches/goldwatch.dmi
  icons/obj/watches/pocketwatch.dmi
  icons/obj/watches/wristwatch.dmi
  icons/obj/watches/wristwatch_black.dmi
  vgstation13.dme
Labels: Content

#29972 Fixes CWC's multi powered wizards
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️

#29963 Plant-B-Gone stops dionae healing from light.
  code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
Labels: Consistency Issue

#29936 (Revival) Allows slime extracts to act as upgrades for stuff around the station
  __DEFINES/reagents.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/game/atoms.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/objs.dm
  code/modules/RCD/RPD.dm
  code/modules/RCD/schematics/pipe.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: 100% tested, Content

#29979 Makes manifest predictions sort by department and look much nicer
  code/defines/obj.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix, Tweak, UI, ❤️ Quality of Life ❤️

#29983 New Stage 3 Disease Effect: Piratitis Syndrome, aka Tooth Decay
  code/__HELPERS/text.dm
  code/modules/virus2/effect/stage_3.dm
Labels: Content

#29987 More hobo shack updates
  maps/misc/hoboshack.dmm
Labels: Mapping (General :world_map:), Tweak

#29996 Fix photobooth board
  code/modules/research/designs/boards/machine_misc.dm
Labels: Bug / Fix, Hotfix

#29997 Fixes disfiguring consistency
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/organ_external.dm
Labels: Consistency Issue

#29999 Fixes Stackable Porokeratosis Acanthus and other bumpable symptoms
  code/modules/mob/living/carbon/carbon.dm
Labels: Bug / Fix

#29914 The traitor uplink encryption key now grants access to the syndicate radio channel
  code/datums/uplink_item.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
Labels: Content

#30004 Fixes admin PM mute bypass
  code/modules/admin/verbs/adminhelp.dm
Labels: Bug / Fix, Sanity / Ghosthands

#30008 Fixes newscasters deleting photos when made into frame
  code/game/machinery/newscaster.dm
Labels: Bug / Fix

#29877 Makes attack logs carry over via cloning
  code/game/dna/dna_modifier.dm
  code/game/objects/structures/dorfpod.dm
  code/modules/medical/cloning.dm
  code/modules/medical/computer/cloning.dm
  code/modules/mob/mob_defines.dm
Labels: Bug / Fix, Logging / Administration, Needs Moar Testing

#30006 Xenoarchaeology Nerf
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Honk

#29998 Radstorm harvesting
  code/modules/events/radiation_storm.dm
Labels: Consistency Issue

#30001 Removesspacesfromspeechwhileonhyperzines
  code/modules/mob/living/say.dm
Labels: Tweak

#30005 Fixes various coffins issues and changes how buckling in one works
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, ❤️ Quality of Life ❤️

#29994 Adds baby carp cubes and carp pheromone bottles. Not mapped anywhere currently.
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/reagents/reagent_containers/food/mobcube.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  icons/obj/food.dmi
Labels: Content

#30013 Drop dat cardboard
  code/game/machinery/kitchen/microwave.dm
Labels: Bug / Fix

#30026 Fixed a bug that prevented using a premade barsign after a custom one
  code/game/objects/structures/barsign.dm
Labels: Bug / Fix

#30030 Fixes bison projectile alpha
  code/modules/projectiles/projectile/beams.dm
Labels: Bug / Fix

#30029 Coffin unbuckle alarm button
  code/_onclick/hud/screen_alarms.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
Labels: ❤️ Quality of Life ❤️

#30020 Fixes Traitors not having access to their role exclusive uplink items
  code/game/objects/items/devices/uplinks.dm
Labels: Bug / Fix

#29908 Adds an important (read: completely and utterly unnecessary) holiday from the clown religion.
  __DEFINES/dates.dm
  code/game/gamemodes/events/holidays/Holidays.dm
Labels: Content, Emoji This :+1: :-1:

#29992 Reworks various speech replacements into wordfilters
  code/game/dna/genes/gene.dm
  code/game/dna/genes/goon_disabilities.dm
  code/game/dna/genes/speech.dm
  code/game/objects/items.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/mob/living/carbon/human/plasmaman/species.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
  code/modules/mob/mob_defines.dm
Labels: Content, Tweak

#30010 Better crit logging
  code/__HELPERS/logging.dm
  code/modules/mob/living/damage_procs.dm
Labels: Logging / Administration

#30011 adminspawncookie REdux
  code/modules/admin/topic.dm
Labels: Fluff :teddy_bear:

#30014 Adds extra modes to some assemblies
  code/modules/assembly/proximity.dm
  code/modules/assembly/timer.dm
Labels: Content

#30017 Available maps are determined by code
  code/__HELPERS/files.dm
  code/controllers/mc/admin.dm
  code/datums/next_map.dm
  code/game/gamemodes/gameticker.dm
  code/modules/html_interface/voting/voting.dm
  vgstation13.dme
Labels: System

#30033 Prevents cultists from making items disappear through Blood Tesseract magic
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix

#30038 Xenoarch Outfit Fix
  code/datums/outfit/science.dm
Labels: Hotfix

#30048 fix voting maybe
  code/modules/html_interface/voting/voting.dm
Labels: Bug / Fix

#30050 Fixes the game thinking you have no hands if you tried swapping hands while handcuffed, after getting un-handcuffed
  code/modules/organs/organ.dm
Labels: Bug / Fix

#30051 Only maps that exist on the server can be voted for
  code/datums/next_map.dm
Labels: Bug / Fix

#30067 It's a feature haha
  code/game/objects/items/devices/uplinks.dm
Labels: 🚓Fun Police🚓

#30027 Magnitis buff
  code/modules/virus2/effect/stage_4.dm
Labels: Balance

#30028 Wizarditis buff
  code/modules/virus2/effect/stage_4.dm
Labels: Balance

#30034 Refactored job preferences
  SQL/players2.sql
  __DEFINES/preferences.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/defines/obj.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job/whitelisted.dm
  code/game/jobs/job_controller.dm
  code/game/jobs/jobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/migrations/SS13_Prefs/027-refactor-jobs.dm
  code/modules/mob/new_player/preferences_setup.dm
  vgstation13.dme
Labels: Bug / Fix, System

#30036 AME Polishing and QoL
  code/modules/power/antimatter/containment_jar.dm
  code/modules/power/antimatter/control.dm
  code/modules/power/antimatter/shielding.dm
  icons/am_engine.dmi
  icons/mob/in-hand/left/misc_tools.dmi
  icons/mob/in-hand/right/misc_tools.dmi
  icons/obj/machines/am_engine.dmi
  icons/obj/machines/antimatter-old.dmi
  icons/obj/machines/antimatter.dmi
  icons/obj/machines/new_ame.dmi
  nano/templates/ame.tmpl
Labels: Bug / Fix, Sprites, ❤️ Quality of Life ❤️

#30044 [New Vault] Nanotrasen Experimental AME Lab
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/blob/blobs/node.dm
  code/game/gamemodes/blob/theblob.dm
  code/game/machinery/suit_storage_unit.dm
  maps/randomvaults/amelab.dmm
  maps/randomvaults/objects.dm
Labels: Content, Mapping (Vault :question:)

#30046 various mining vault fixes
  maps/randomvaults/mining/abandoned_digsite.dmm
  maps/randomvaults/mining/crashed_pod.dmm
  maps/randomvaults/mining/crashed_tradeship.dmm
  maps/randomvaults/mining/geode.dmm
Labels: Bug / Fix, Mapping (Vault :question:)

#30054 Fixes some Blob Meteor sanity
  code/game/gamemodes/meteor/meteors.dm
Labels: Bug / Fix

#30058 Xenobiologists can finally contribute to the crew score
  __DEFINES/global.dm
  code/game/gamemodes/scoreboard.dm
  code/game/machinery/kitchen/processor.dm
Labels: Content, Tweak

#30059 Custom cyanide pill suicide
  code/modules/reagents/reagent_containers/pill.dm
Labels: Fluff :teddy_bear:

#30063 Fixes examining people wearing accessories indicating "it has nothing" when there are in fact accessories
  code/modules/clothing/accessories/accessory.dm
Labels: Bug / Fix

#30068 Fixes a manual's title var
  code/game/objects/items/weapons/manuals.dm
Labels: Bug / Fix

#30055 Tweaks to make ghoulification possible.
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
Labels: Balance

#30073 Hotfix for character slots not loading
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Bug / Fix, Hotfix

#30078 Hotfix for job preferences carrying over to other slots sometimes
  code/modules/client/preferences_savefile.dm
Labels: Bug / Fix, Hotfix

#30047 Update Alien Nest Mining Surprise
  code/modules/mining/surprises/vg.dm
  maps/randomvaults/mining/huggernest.dmm
Labels: Mapping (Vault :question:)

#30080 Oops, forgot the AME Lab's vault definition
  code/modules/randomMaps/vault_definitions.dm
Labels: Hotfix, Mapping (Vault :question:)

#30071 Added black wristwatches to the Shoal junk crate and the Wonderful Wardrobe
  code/game/objects/items/trader.dm
Labels: Content

#30095 Nicer join game menu
  code/modules/mob/new_player/new_player.dm
Labels: Tweak, UI

#30045 Swap some dense (indestructable) rock for normal rock in angies lair
  maps/randomvaults/mining/angie_lair.dmm
Labels: Emoji This :+1: :-1:, Mapping (Vault :question:)

#30056 Awakens Packed
  code/datums/next_map.dm
Labels: Tweak

#30057 Data Disk Duplicator
  code/defines/obj/weapon.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/disk_duplicator.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/modules/research/designs/boards/machine_misc.dm
  icons/obj/datadisks.dmi
  vgstation13.dme
Labels: Content

#30069 Fix update_canmove() firing during TimeStop
  code/modules/mob/mob.dm
  code/modules/spells/aoe_turf/fall.dm
Labels: Bug / Fix

#30064 The suit modification thingy can now repaint plasmaman and vox suits
  code/game/machinery/suit_modifier.dm
  icons/obj/stationobjs.dmi
Labels: Content

#30075 biobuilin-whatever symptom danger 0 -> 1
  code/modules/virus2/effect/stage_4.dm
Labels: Tweak

#30079 Tweaks to Zam Nitro Freeze
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Tweak

#30082 *mind UI*
  __DEFINES/planes+layers.dm
  __DEFINES/setup.dm
  code/_onclick/hud/adminbus.dm
  code/_onclick/mindUI/adminbus.dm
  code/_onclick/mindUI/example.dm
  code/_onclick/mindUI/mindUI.dm
  code/datums/mind.dm
  code/datums/ui_icons.dm
  code/game/gamemodes/gameticker.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/structures/vehicles/adminbus.dm
  code/game/objects/structures/vehicles/adminbus_powers.dm
  code/modules/client/client procs.dm
  code/modules/media/jukebox.dm
  code/modules/mob/living/login.dm
  code/modules/mob/logout.dm
  icons/ui/192x192.dmi
  icons/ui/32x32.dmi
  icons/ui/480x480.dmi
  icons/ui/adminbus/bottom_panel/background.dmi
  icons/ui/adminbus/bottom_panel/buttons.dmi
  icons/ui/adminbus/left_panel/background.dmi
  icons/ui/adminbus/left_panel/buttons.dmi
  icons/ui/adminbus/top_panel/background.dmi
  icons/ui/adminbus/top_panel/buttons.dmi
  vgstation13.dme
Labels: Bug / Fix, Secret repo conflict., System, UI

#30083 Prettier job selection window
  code/modules/client/preferences.dm
Labels: UI

#30085 Tweak to the Sacid ghetto chem recipe.
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Tweak

#30097 Fixes enemy job check runtimes and threat checking
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Bug / Fix, Consistency Issue, Gameplay / Gamemode

#30110 Fixes Implant Pinpointer
  code/game/gamemodes/nuclear/pinpointer.dm
Labels: Bug / Fix

#30109 Fixes some Adminbus-related oversights
  code/game/objects/structures/vehicles/adminbus.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug / Fix

#30115 My autism
  code/game/objects/effects/decals/cleanable.dm
Labels: Runtime Log
