Repository vgstation-coders/vgstation13, pull requests merged in 2021-08, with the labels that each got.

#30116 lol dorf
  code/datums/next_map.dm
Labels: Fun Police

#30117 dorfstation - makes mining suits actually dispense properly
  code/game/machinery/suit_dispenser.dm
Labels: Bug / Fix

#30126 Fixes Vox Medical Doctors spawning with a duplicate uniform in their backpack instead of their job-specific labcoat.
  code/datums/outfit/medical.dm
Labels: Bug / Fix

#30124 Adjust growth dish offset when coming out of a centrifuge
  code/modules/virus2/centrifuge.dm
Labels: Tweak, ❤️ Quality of Life ❤️

#30122 Telecomms Traffic Console Explicitation on Scan Failure
  code/game/machinery/telecomms/traffic_control.dm
Labels: ❤️ Quality of Life ❤️

#30120 Fixes Timestop turning VirtualHearers dense, and making their associated mobs unable to pull dense objects
  code/modules/mob/hearing/virtualhearer.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️

#30107 Blob Meteor Penetration
  code/game/gamemodes/blob/blobs/shield.dm
  code/game/gamemodes/meteor/meteors.dm
  code/modules/power/solars/panel.dm
Labels: Balance, Tweak

#30102 [mindUI] Blob HUD refresh
  __DEFINES/blob.dm
  __DEFINES/planes+layers.dm
  code/_onclick/hud/blob.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/mindUI/_example.dm
  code/_onclick/mindUI/_mindUI.dm
  code/_onclick/mindUI/blob.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/blob/blobs/factory.dm
  code/game/gamemodes/blob/blobs/node.dm
  code/game/gamemodes/blob/blobs/resource.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/gamemodes/blob/powers.dm
  code/game/gamemodes/blob/theblob.dm
  icons/mob/screen1_blob.dmi
  icons/mob/screen1_blob_bars.dmi
  icons/mob/screen1_blob_fullscreen.dmi
  icons/ui/16x16.dmi
  icons/ui/192x192.dmi
  icons/ui/blob/18x200.dmi
  icons/ui/blob/21x242.dmi
  icons/ui/blob/32x32.dmi
  sound/effects/ping_warning.ogg
  vgstation13.dme
Labels: Bug / Fix, Content, UI, ❤️ Quality of Life ❤️

#30121 Glasses with ghoul blood are now "piccolyn" instead of "tomato juice".
  __DEFINES/setup.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Consistency Issue

#30129 Changes camera network on taxi engineering vault
  maps/randomvaults/taxi_engineering.dmm
Labels: Bug / Fix, Tweak

#30131 Fixes reagent check saycode runtime
  code/modules/mob/living/say.dm
Labels: Runtime Log

#30092 Weather Control Device Animation
  code/game/machinery/weathercontrol.dm
  icons/effects/224x224.dmi
Labels: Sprites

#30104 Small Blob Attack Buff (mostly just reducing frustration)
  code/game/gamemodes/blob/powers.dm
  code/game/gamemodes/blob/theblob.dm
Labels: Balance

#30144 Adds a period to the vending machines' "You hear a whirr" and "The [src.name] whirrs as it vends" messages.
  code/game/machinery/vending.dm
Labels: Grammar / Formatting

#30146 Lowers TC Cost of Syndicate Pocket Satellite
  code/datums/uplink_item.dm
Labels: Tweak

#30148 Clicking an unpowered Washing Machine now empties it
  code/game/machinery/washing_machine.dm
Labels: ❤️ Quality of Life ❤️

#30149 Radio Transmitter tweaks and QoL
  code/modules/media/broadcast/transmitters/broadcast.dm
  icons/obj/machines/broadcast.dmi
Labels: Sprites, ❤️ Quality of Life ❤️, Tweak

#30140 makes the advanced rigsuit rad absorber printable
  code/modules/research/designs/boards/misc.dm
Labels: Content, Oversight

#30139 Re-factor butchering drops code
  code/datums/helper_datums/butchering.dm
  code/modules/clothing/head/misc.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/complex/gondola.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/deer.dm
  code/modules/mob/living/simple_animal/hostile/frog.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
  code/modules/mob/living/simple_animal/hostile/wolf.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/snail.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Bug / Fix, System

#30135 Adds a filled water bucket to hobo shack blacksmithing
  maps/misc/hoboshack.dmm
Labels: Mapping (General :world_map:)

#30145 Deadminning updates
  code/modules/admin/admin_verbs.dm
  code/modules/mob/logout.dm
Labels: Bug / Fix, Logging / Administration

#30132 [mind UI] Soulblades HUD. Goodbye gui_icons
  code/_hooks/events.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/mindUI/_mindUI.dm
  code/_onclick/mindUI/soulblade.dm
  code/datums/alt_control.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/cultist.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/objects/structures/vehicles/adminbus.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/shade_powers.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  icons/mob/screen1_shade_fullscreen.dmi
  icons/ui/soulblade/18x200.dmi
  icons/ui/soulblade/21x246.dmi
  icons/ui/soulblade/32x32.dmi
  vgstation13.dme
Labels: System, UI

#30134 Fixes enemy job check fix typo
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Bug / Fix, Oversight

#30157 187 times faster direct_subtypesof
  code/__HELPERS/text.dm
  code/__HELPERS/typeof.dm
Labels: Performance

#30170 Fixes alien thermals
  code/modules/mob/hearing/virtualhearer.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
Labels: Bug / Fix

#30173 Fixes Shades being blind
  code/datums/gamemode/role/cultist.dm
  code/datums/ui_icons.dm
  vgstation13.dme
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Hotfix

#30162 Adds MoMMI flavoured adminbus autoborger
  code/game/machinery/autoborger.dm
  code/modules/mob/transform_procs.dm
Labels: Content

#30158 Scientists (also Xenobio/arch) get Robotics access back. Roboticists get RnD access.
  code/game/jobs/job/science.dm
Labels: Balance, ❤️ Quality of Life ❤️

#30156 gives rig mod stations the ability to remove a user's rig modules when empty
  code/game/machinery/suit_modifier.dm
Labels: Tweak

#30164 Fixes some Vox and Insectoid scanner glasses sprites
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/scanners.dm
  icons/mob/species/insectoid/eyes.dmi
  icons/mob/species/vox/eyes.dmi
Labels: Sprites

#30177 Renouncing your religion is now a button in your IC tab
  code/datums/religions.dm
  code/modules/admin/topic.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#30180 The Manifest Prediction button now appears to new players right away
  code/controllers/subsystem/init/job.dm
Labels: ❤️ Quality of Life ❤️

#30160 Removed one useless line of code
  code/game/jobs/job_controller.dm
Labels: 100% tested

#30182 Fixed toxins being 10 times more effective than intended(?)
  code/modules/organs/internal/liver/liver.dm
Labels: Bug / Fix

#30191 Added a confirmation request before kicking people as admin
  code/modules/admin/topic.dm
Labels: Logging / Administration

#30196 Fixes build mode checking space turfs instead of base turf type
  code/modules/admin/buildmode.dm
Labels: Bug / Fix, Logging / Administration

#30176 fix the number 6 actually being the number 8 (mindUI)
  icons/ui/16x16.dmi
Labels: Sprites

#30193 Fixed Tajaran saying \list instead of god
  code/game/dna/genes/speech.dm
Labels: Bug / Fix

#30190 Fixes being unable to place customizable food on a plate
  code/game/objects/items/trash.dm
  code/modules/food/customizables.dm
Labels: Bug / Fix

#30187 Fixes Mulebots not unloading crates on the tile in front of them at destination
  code/game/machinery/bots/mulebot.dm
Labels: Bug / Fix

#30186 Fixed some missing PDA interface icons
  code/game/objects/items/devices/PDA/cart.dm
Labels: Bug / Fix

#30090 Adds a video game playlist.
  code/modules/media/jukebox.dm
Labels: Content, Sound

#30171 Resin (Alien) and Cult doors now require proper access from Mechas, Bots, and Vehicles
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/mineral.dm
Labels: Bug / Fix

#30165 Space Vietnam Grass Coat
  code/datums/uplink_item.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/hydroponics/spreading/spreading_response.dm
Labels: Content

#30201 Fixed the Ithaqua bible facing the wrong way when held left handed.
  icons/mob/in-hand/left/books.dmi
Labels: Bug / Fix, Sprites

#30202 Fixed getting bloodied when doing surgery on bloodless species
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bug / Fix, Consistency Issue

#30203 Fixed mounted extinguisher cabinets getting built on the floor
  code/game/objects/structures/extinguisher.dm
Labels: Bug / Fix

#30205 You can no longer aim guns at people using a cloak of cloaking
  code/modules/projectiles/targeting.dm
Labels: Bug / Fix

#30207 North facing chairs are now built on the right plane right away.
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Bug / Fix

#30200 Clicking the Unbuckle button on a shuttle chair while holding an item no longer makes you hit yourself
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Bug / Fix, Oversight

#30210 Photobooth fixes and activation from outside
  code/game/objects/items.dm
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/paperwork/photography.dm
  icons/effects/genetics.dmi
Labels: Bug / Fix, Content

#30215 Re-Adds Mouse Opacity to a bunch of effects
  code/game/gamemodes/blob/theblob.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/effects/glowshroom.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/effects/portals.dm
  code/modules/hydroponics/spreading/spreading.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Hotfix

#30179 Wizard Pitbulls, Arcane Golems, and Constructs no longer attack each others
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/arcane_golem.dm
  code/modules/mob/living/simple_animal/hostile/pitbull.dm
  code/modules/spells/aoe_turf/conjure/arcane_golem.dm
  code/modules/spells/aoe_turf/conjure/pitbulls.dm
  vgstation13.dme
Labels: Bug / Fix

#30199 Hitting a broken APC's cover now gives feedback if you failed to knock it down
  code/modules/power/apc.dm
Labels: ❤️ Quality of Life ❤️

#30198 Added Prisoner HUD icon for AntagHUD
  icons/role_HUD_icons.dmi
Labels: Bug / Fix, Sprites, Logging / Administration

#30152 Adds candy machine and cereal maker circuits.
  code/game/machinery/constructable_frame.dm
  code/modules/food/cooking_machines.dm
Labels: Content

#30218 Fixes glass floors making a space turf instead of base when destroyed
  code/game/turfs/simulated/floor_glass.dm
Labels: Bug / Fix, Consistency Issue

#30223 Tunes up zone rebuilding again
  code/controllers/subsystem/air.dm
Labels: Bug / Fix, System

#30225 Fixed Teleport Scrolls, Ghost Teleports, and Adminbus Teleports missing most if not all destination areas.
  code/controllers/subsystem/init/more_init_stuff.dm
  code/game/area/Space Station 13 areas.dm
  code/game/turfs/simulated/floor.dm
  code/world.dm
Labels: Bug / Fix, Hotfix

#30232 Fixes the RCD saying "Building wall" instead of "Building wall...".
  code/modules/RCD/schematics/engi.dm
Labels: Consistency Issue, Grammar / Formatting

#28728 Time agent
  __DEFINES/_macros.dm
  __DEFINES/global.dm
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/global_lists.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/factions/time_agency.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/objectives/freeform/aid.dm
  code/datums/gamemode/objectives/objective.dm
  code/datums/gamemode/objectives/target/erase.dm
  code/datums/gamemode/objectives/target/locate.dm
  code/datums/gamemode/objectives/target/rearrange.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/objectives/time_agent_extract.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/time_agent.dm
  code/datums/gamemode/role/timeagenttwin.dm
  code/datums/outfit/special_outfits/special.dm
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/nuclear/pinpointer.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/virus2/immune_system.dm
  icons/effects/effects.dmi
  icons/logos.dmi
  icons/obj/device.dmi
  icons/turf/areas.dmi
  maps/misc/timevoid.dmm
  vgstation13.dme
Labels: Content, Update WIKI

#30234 Fixes the outward lime couch being grey instead of lime
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Bug / Fix

#30235 Chemsprayer's nozzle switch now indicates the actual amount of reagents consumed
  code/modules/reagents/reagent_containers/spray.dm
Labels: Bug / Fix

#30197 1 year meme rule
  code/modules/flufftext/Dreaming.dm
Labels: Honk, why

#30258 Re-Added mouse opacity to biomass and spider webs, cocoons, etc...
  code/datums/gamemode/objectives/time_agent_extract.dm
  code/game/gamemodes/events/biomass.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/effects.dm
Labels: Bug / Fix, Hotfix

#30255 Request consoles no longer consider their message as read when read by ghosts
  code/game/machinery/requests_console.dm
Labels: Bug / Fix, Sanity / Ghosthands

#30256 Docking Lights are now anchored
  code/game/objects/structures/docking_port.dm
Labels: Bug / Fix

#30257 Fixes the toxins alert remaining displayed after acquiring NOBREATHE
  code/game/dna/genes/powers.dm
Labels: Bug / Fix, UI

#30264 Fixes the cereal makers not being faster when using better parts.
  code/modules/food/cooking_machines.dm
Labels: Bug / Fix

#30253 Reworked the Hostile mob friends list to use weakrefs
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/deer.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
  code/modules/mob/living/simple_animal/hostile/pitbull.dm
  code/modules/mob/living/simple_animal/hostile/slime.dm
  code/modules/power/gourmonger.dm
Labels: System, 100% tested

#30236 You can now re-insert screwdrivers in switchtools
  code/game/objects/items/weapons/switchtool.dm
Labels: Bug / Fix

#30254 Fixes conveyor lagging if too many items are on top of it
  code/modules/recycling/conveyor2.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, Hotfix, Performance

#30184 Band-aids closets spawning their items twice and adds some debug info to try and catch the bug in the act
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Bug / Fix, Logging / Administration

#30270 Spider cocoons now get different sprites depending on whether they wrapped a large object or a mob
  code/modules/mob/living/simple_animal/hostile/giant_spider/nurse.dm
  icons/effects/effects.dmi
Labels: Sprites

#30265 Make the time void teleport-to-station button work properly.
  code/datums/gamemode/factions/time_agency.dm
  maps/misc/timevoid.dmm
Labels: Bug / Fix

#30269 Airflow-induced knockdowns on non-human mobs now last depending on the airflow differential
  code/ZAS/Airflow.dm
Labels: Tweak

#30284 Fixed a rare bug where breaking tape would send you to nullspace
  code/game/objects/items/policetape.dm
Labels: Bug / Fix, Sanity / Ghosthands

#30238 Tentative fix for latejoin rulesets firing without the player being properly assigned
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
Labels: Bug / Fix, Role Datums

#30233 [mind UI] Added support for movable elements, that can also move the rest of the UI
  code/_onclick/hud/movable_screen_objects.dm
  code/_onclick/mindUI/_example.dm
  code/_onclick/mindUI/_mindUI.dm
  icons/mouse/mind_ui.dmi
  icons/ui/32x32.dmi
Labels: UI

#30276 show borgs how much max charge new cell has
  code/modules/mob/living/silicon/robot/robot.dm
Labels: ❤️ Quality of Life ❤️

#30278 You can click burnt out campfires once again.
  code/game/objects/effects/decals/Cleanable/misc.dm
Labels: Bug / Fix

#30282 Turned zombies are now referred to as looking quite fresh, instead of quite human
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: Muh Immulsions, Consistency Issue, Grammar / Formatting

#30280 Fixed the AME Blob pulsing using the regular blob sprites
  code/game/gamemodes/blob/blobs/core.dm
  icons/mob/blob/blob_AME_64x64.dmi
Labels: Bug / Fix, Sprites

#30267 Added admin buttons allowing them to easily contact an entire faction or individual role
  __DEFINES/setup.dm
  code/datums/gamemode/factions/blob.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/clockwork.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/junglefever.dm
  code/datums/gamemode/factions/legacy_cult/cult.dm
  code/datums/gamemode/factions/malf.dm
  code/datums/gamemode/factions/plague_mice.dm
  code/datums/gamemode/factions/spider_clan.dm
  code/datums/gamemode/factions/spider_infestation.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/factions/syndicate/traitor.dm
  code/datums/gamemode/factions/time_agency.dm
  code/datums/gamemode/factions/vampire_faction.dm
  code/datums/gamemode/factions/vox_shoal.dm
  code/datums/gamemode/factions/wizard.dm
  code/datums/gamemode/factions/wizard_apprenticeship.dm
  code/datums/gamemode/factions/xenomorph.dm
  code/datums/gamemode/role/alien.dm
  code/datums/gamemode/role/blob.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/clockwork.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/giant_spider.dm
  code/datums/gamemode/role/grinch.dm
  code/datums/gamemode/role/legacy_cultist.dm
  code/datums/gamemode/role/madmonkey.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/plague_mouse.dm
  code/datums/gamemode/role/prisoner.dm
  code/datums/gamemode/role/rambler.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/streamer.dm
  code/datums/gamemode/role/summonsurvivors.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/role/time_agent.dm
  code/datums/gamemode/role/timeagenttwin.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/role/vox_raider.dm
  code/datums/gamemode/role/wizard.dm
  code/datums/gamemode/role/wizard_apprentice.dm
  code/modules/admin/topic.dm
Labels: ❤️ Quality of Life ❤️, Logging / Administration

#30268 Silicons now receive a message when the Cyborg self-destruct sequence is halted
  code/game/machinery/computer/robot.dm
Labels: ❤️ Quality of Life ❤️

#30289 You can now catch thrown glass bottles without them shattering
  code/game/atoms_movable.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Bug / Fix, Consistency Issue

#30292 Fixes the screen being all white after getting de-brained
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/organs/organ_external.dm
Labels: Bug / Fix, UI

#30306 Fixed Generic Signaler Cartridges not actually giving you the signaler app.
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
Labels: Bug / Fix

#30308 Fixed being unable to use the handheld TV while buckled in a chair
  code/game/objects/items/devices/handtv.dm
Labels: Bug / Fix

#30307 You can now pet animals that you are holding
  code/modules/mob/living/holders.dm
Labels: Content

#30296 Grayy Soldier Suit Energy Resistance Fix
  code/modules/clothing/spacesuits/grey_rig.dm
Labels: Tweak

#30295 Turf bullshit
  code/game/turfs/turf.dm
Labels: System

#30252 Create the Judge Strike team
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/objectives/restore_order.dm
  code/datums/gamemode/role/judge.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/names.dm
  config/names/judge_female.txt
  config/names/judge_male.txt
  vgstation13.dme
Labels: Content

#30259 Prevents nuke disk carriers from trying to ride a gravpult
  code/game/objects/structures/gravpult.dm
Labels: Bug / Fix

#30290 Players now get feedback when shattering light tubes they are holding
  code/modules/power/lighting/lighting.dm
Labels: ❤️ Quality of Life ❤️, Muh Immulsions

#30325 Fixed Summon Snacks interaction with mobs who have more than 2 hands
  code/modules/spells/targeted/summon_snacks.dm
Labels: Bug / Fix

#30329 Added the Mind Machine's tech requirements to the Nanotrasen Tech Disk paper
  code/modules/research/research.dm
Labels: Tweak

#30327 You can now perform autopsy on skinless human species
  code/modules/medical/autopsy.dm
Labels: Bug / Fix

#30322 Adds some missing periods to the fueltank descriptions.
  code/modules/reagents/reagent_dispenser.dm
Labels: Grammar / Formatting

#30333 The Give Achievement button now provides players' real_name and key vars
  code/modules/admin/admin_verbs.dm
Labels: Logging / Administration

#30332 Fixed Ninja Posters becoming unusable after getting ripped from the wall
  code/datums/gamemode/role/ninja.dm
Labels: Bug / Fix

#30283 Fixed Blob Overminds getting thrown away by explosions
  code/game/gamemodes/blob/overmind.dm
Labels: Bug / Fix, Oversight, Emoji This :+1: :-1:

#30297 Grayy Greens and Stuffed Pitcher Tweak
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Balance

#30298 Avocado Soup Tweaks and Fixes
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Tweak

#30312 Sulphuric Acid Tanks (again)
  code/datums/supplypacks.dm
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/objects.dmi
Labels: Content

#30299 Plasmamen Are More In Touch With Their Human Origins
  code/modules/mob/living/carbon/human/plasmaman/species.dm
Labels: Balance, Muh Immulsions

#30313 Supply Forms now display your alt title properly if you chose one
  code/game/machinery/computer/cargo.dm
Labels: ❤️ Quality of Life ❤️

#30285 Fixed items slowing you down when worn on the back but not when wielded
  code/game/objects/items/weapons/shields.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Bug / Fix, Consistency Issue, Emoji This :+1: :-1:

#30287 Challengers now receive the identity of their target a minute after roundstart
  code/datums/gamemode/objectives/target/assassinate.dm
  code/datums/gamemode/objectives/target/delayedassassinate.dm
  code/datums/gamemode/objectives/target/target.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/gamemode/role/wizard.dm
  vgstation13.dme
Labels: Balance

#30344 Pillow Bugs can no longer smash tables and walls as if they were a goliath or something
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Labels: Bug / Fix, Tweak

#30309 Fixed Remote View and Project Mind not working after the target got cloned
  code/game/dna/genes/powers.dm
  code/modules/mob/mob.dm
  code/modules/spells/targeted/targeted.dm
Labels: Bug / Fix, Balance, ❤️ Quality of Life ❤️, Emoji This :+1: :-1:

#30330 Fixed a bug where supermatter crystals and shards could explode perpetually
  code/modules/supermatter/supermatter.dm
Labels: Bug / Fix

#30018 Things that used to check if you were walking now check your movement speed instead
  __DEFINES/math_physics.dm
  code/defines/obj/weapon.dm
  code/game/machinery/flasher.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/slipping.dm
Labels: Balance, Tweak

#30086 Suicide_act() update
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/ninja.dm
  code/defines/obj/weapon.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/kitchen/processor.dm
  code/game/machinery/machinery.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/instruments.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/soulstone.dm
  code/game/objects/items/stacks/cable.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/courtroom.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/explosives.dm
  code/game/objects/items/weapons/glowstick.dm
  code/game/objects/items/weapons/grenades/ghettobomb.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/null_rod.dm
  code/game/objects/items/weapons/paint.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/shard.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/storage/bluespace.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/objs.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/game/objects/structures/window.dm
  code/game/verbs/suicide.dm
  code/modules/RCD/RPD.dm
  code/modules/RCD/engie.dm
  code/modules/RCD/tile painter.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/fish/fish_items.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/guns/projectile/constructable/swords.dm
  code/modules/projectiles/guns/projectile/rocketlauncher.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/circuitprinter.dm
  code/modules/supermatter/supermatter.dm
Labels: Content

#30393 Fixed the holodeck not working at all
  code/modules/multiz/turfs.dm
Labels: Bug / Fix, Hotfix

#30401 Ammotree Fix
  code/game/objects/items/trader.dm
Labels: Bug / Fix, Tweak

#30384 Implant Pad QoL
  code/game/objects/items/weapons/implants/implantpad.dm
Labels: ❤️ Quality of Life ❤️

#30359 The Condiment Update (feat. Whipped Cream, Butter, Maple Syrup, PANCAKES, and a lot of other stuff actually now)
  __DEFINES/reagents.dm
  code/game/machinery/bees_apiary.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/in-hand/left/drinkingglass.dmi
  icons/mob/in-hand/right/drinkingglass.dmi
  icons/obj/condiment_overlays.dmi
  icons/obj/food.dmi
  icons/obj/food_condiment.dmi
Labels: Content, Fluff :teddy_bear:

#30365 Stamped Cargo Manifest Reward Increase
  code/controllers/subsystem/supply_shuttle.dm
Labels: Balance, Tweak

#30424 Fixed holodeck bricking after one use
  code/game/turfs/turf.dm
Labels: Bug / Fix

#30438 Fixed Cult buildings appearing over darkness, AI static, and HUDs
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Hotfix

#30404 Fixed photo cameras only capturing floors.
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
Labels: Bug / Fix, Hotfix
