Repository vgstation-coders/vgstation13, pull requests merged in 2021-01, with the labels that each got.

#28490 Aligns the CI with the main server version
  .github/workflows/ci.yml
Labels: Automation/CI

#28434 Geyser Spawn Tweak
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  maps/snaxi.dm
Labels: Emoji This :+1: :-1:, Gameplay / Gamemode

#28456 Adds ancient cryopods
  code/datums/helper_datums/command_alerts.dm
  code/datums/outfit/special_outfits/special.dm
  code/game/objects/structures/ancient_cryopod.dm
  code/modules/events/ancientpod.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  icons/obj/cryogenics.dmi
  maps/randomvaults/lightspeedship.dmm
  vgstation13.dme
Labels: Content

#28493 Fixes Talonjob Code
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Bug / Fix

#28517 Should significantly reduce cookie false positives
  code/modules/admin/IsBanned.dm
Labels: Logging / Administration

#28503 less wizard
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Gameplay / Gamemode

#28496 Faster sign function
  code/__HELPERS/maths.dm
Labels: Performance

#28423 Pre made grenade casings (attempt 2)
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/assembly/holder.dm
Labels: Content

#28527 remove red "armband" from player preview icons
  code/modules/mob/new_player/preferences_setup.dm
Labels: Bug / Fix

#28551 Improves advanced security camera zoom function
  code/modules/html_interface/map/map_shared.js
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#28559 Fixes centcomm sending the wrong nuclear codes
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/helper_datums/command_alerts.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
Labels: Bug / Fix

#28561 Runechat now shows *me emotes.
  code/modules/mob/emote.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#28550 Fixes mosin and obrez inhands
  code/game/objects/items/weapons/null_rod.dm
  icons/mob/back.dmi
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
Labels: Bug / Fix

#28566 Updates extools
  byond-extools.dll
Labels: T-Thanks BYOND

#28560 Fixes monkeymen/cloned men identities
  code/game/dna/genes/monkey.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/medical/cloning.dm
  code/modules/surgery/face.dm
Labels: Bug / Fix

#28553 Fixes a bug with ED209's tasers.
  code/game/machinery/bots/ed209bot.dm
Labels: Bug / Fix

#28556 Fix/rework droppers
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/dropper.dm
Labels: Bug / Fix, Tweak

#28567 Fixes alt-click not working on some grilles
  code/game/objects/structures/grille.dm
Labels: Bug / Fix

#28492 RD Shoes
  code/game/machinery/camera/camera.dm
  code/game/machinery/machinery.dm
  code/game/objects/items.dm
  code/game/objects/items/mountable_frames/paintings.dm
  code/game/objects/items/mountable_frames/posters/poster.dm
  code/game/objects/structures.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/signs.dm
  code/game/turfs/simulated/walls.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/power/lighting/lighting.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: 100% tested, Content

#28530 Adds Black Site Prism as a vault.
  code/modules/randomMaps/vault_definitions.dm
  maps/randomvaults/black_site_prism.dmm
  maps/randomvaults/objects.dm
Labels: Mapping (Vault :question:)

#28516 Adds "recall" artifact effect.
  code/__HELPERS/weakref.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_recall.dm
  vgstation13.dme
Labels: Content

#28564 Snails no longer recoil when they're dead
  code/modules/mob/living/simple_animal/snail.dm
Labels: Bug / Fix

#28420 Xenomorph Infestations (now with extra dynamic mode)
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_stats.dm
  code/datums/gamemode/factions/xenomorph.dm
  code/datums/gamemode/role/alien.dm
  code/datums/helper_datums/command_alerts.dm
  code/game/striketeams/striketeam_datums.dm
  code/modules/admin/topic.dm
  code/modules/events/alien_infestation.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  icons/logos.dmi
  sound/AI/directive710_generic.ogg
  vgstation13.dme
Labels: Tweak

#28578 Fixes plasmamen invisible gibs
  code/modules/mob/living/carbon/human/plasmaman/species.dm
Labels: Bug / Fix

#28592 Remove ALL instances of get_turf from playsound (again)
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/legacy_cult/cult_structures.dm
  code/datums/gamemode/role/ninja.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/newscaster.dm
  code/game/objects/items/devices/roganbot.dm
  code/game/objects/items/mountable_frames/posters/poster.dm
  code/game/objects/items/soulstone.dm
  code/game/shuttles/trade.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/suits/plate_carrier.dm
  code/modules/mining/materials.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/simple_animal/hostile/deer.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/surgery/generic.dm
  code/modules/virus2/items_devices.dm
Labels: Performance

#28591 Fixes announcements on request consoles
  code/game/machinery/requests_console.dm
Labels: Bug / Fix

#28580 Fixes the 'default language' links and verb.
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/complex/martian/martian.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/default_language.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/mannequin.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/headreattach.dm
  code/modules/virus2/effect/stage_2.dm
Labels: Bug / Fix

#28579 Fixes catbeast language. Adds a language unit test
  code/modules/mob/language.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/languages.dm
Labels: Bug / Fix

#28577 Added a voting pin for civic-duty minded players.
  code/datums/outfit/outfit.dm
  code/modules/client/client defines.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/mob/new_player/new_player.dm
  icons/mob/clothing_accessories.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/accessory_overlays.dmi
Labels: Content

#28589 Fixes an issue which could brick beepsky in some cases
  code/game/machinery/bots/secbot.dm
Labels: Bug / Fix

#28576 changelings get the victims memories when absorbing people
  code/modules/spells/changeling/absorb_dna.dm
Labels: Tweak

#28599 Custom striketeams can now choose a custom outfit.
  code/game/striketeams/striketeam_datums.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/striketeam.dm
  vgstation13.dme
Labels: Bug / Fix

#28570 holy hand grenades
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/holy_grenade.dm
  icons/obj/grenade.dmi
  vgstation13.dme
Labels: Content

#28611 HoS Powercreep - Surveyor Set
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/head.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/suit.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: 100% tested, Sprites

#28619 Rough and Hard
  code/game/turfs/unsimulated/walls.dm
Labels: Bug / Fix

#28615 Shallows
  code/game/turfs/unsimulated/beach.dm
  icons/misc/beach.dmi
Labels: Content

#28207 Introducing a new major antagonist role: "Syndicate Challengers", based on the Double-Agents of old.
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/syndicate/traitor.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/objectives/target/assassinate.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/traitor.dm
  code/game/machinery/newscaster.dm
  code/modules/client/preferences.dm
  code/modules/credits/episode_name.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/photography.dm
Labels: WiP

#28620 Bloodstone Fix
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
Labels: Bug / Fix, Gameplay / Gamemode

#28631 Fatcoats
  code/modules/clothing/suits/wintercoat.dm
  icons/mob/suit_fat.dmi
Labels: Content

#28558 Adds Three New Items to the Traitor Uplink for Cooperative Traitors
  code/datums/uplink_item.dm
Labels: Content

#28613 Cult 2020 (actually let's just call it Cult 4) Rework Part #3: Conversion rework, Deconversion, & Holy Implants
  __DEFINES/role_datums_defines.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/fullscreen.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/religions.dm
  code/datums/supplypacks.dm
  code/game/objects/items/soulstone.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantcase.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/null_rod.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/turfs/simulated/walls.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/human/life/handle_shock.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/simple_animal/hostile/shade.dm
  code/modules/organs/blood.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  icons/effects/64x64.dmi
  icons/effects/effects.dmi
  icons/mob/in-hand/left/drinkingglass.dmi
  icons/mob/in-hand/right/drinkingglass.dmi
  icons/mob/mob.dmi
  icons/obj/cuffs.dmi
  icons/obj/cult.dmi
  icons/obj/items.dmi
  sound/effects/deconversion_complete.ogg
  sound/effects/deconversion_failed.ogg
  sound/effects/deconversion_start.ogg
  vgstation13.dme
Labels: Gameplay / Gamemode

#28575 Fixes Cyborg Examine Text
  code/modules/mob/living/silicon/robot/examine.dm
Labels: Tweak

#28629 Barrels can now be destroyed.
  code/modules/reagents/reagent_dispenser.dm
Labels: Content

#28630 Banana peels now slip you further based on potency
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/clown_items.dm
Labels: Tweak

#28663 Wizards/nukies no longer keep the flavor text of their players
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/role/wizard.dm
Labels: Bug / Fix, Oversight

#28662 Speech synthetiser/speaker is now logged
  code/modules/assembly/speaker.dm
Labels: Logging / Administration

#28546 Sends a discord killphrase after a round has ended
  code/__HELPERS/files.dm
  code/controllers/configuration.dm
  code/modules/ext_scripts/discord.dm
Labels: ⛔ Requires Server Vote ⛔

#28626 Cleaver throw chance
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/kitchen.dm
Labels: Balance

#28654 Fixes a Few Uniforms for Greys, Insectoids and Vox
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/obj/clothing/uniforms.dmi
Labels: Bug / Fix, Sprites

#28689 Fixes a cult typo
  code/game/objects/items/weapons/storage/bible.dm
Labels: Grammar / Formatting

#28697 Fixes shades in Soul or Chaos Blades taking damage while over space
  code/modules/mob/living/simple_animal/shade.dm
Labels: Bug / Fix

#28694 Clientless simple mobs no longer spams observers
  code/datums/emotes.dm
  code/modules/mob/dead/observer/say.dm
Labels: ❤️ Quality of Life ❤️

#28702 Some cult-related sechud changes
  __DEFINES/setup.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/hud.dmi
Labels: Content

#28687 Snow Survival Guide
  code/datums/outfit/outfit.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/reagents/Chemistry-Reagents.dm
  maps/_map.dm
  maps/snaxi.dm
Labels: Content

#28691 Vehicle Beds
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  icons/obj/stools-chairs-beds.dmi
Labels: Content

#28719 custom swords now get their proper inhand base icons
  code/modules/projectiles/guns/projectile/constructable/swords.dm
Labels: Hotfix

#28676 Tesla Cannon: Engineering Traitor Weapon
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/modules/projectiles/guns/energy/tesla.dm
  code/modules/projectiles/guns/projectile/constructable/railgun.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/tesla.dm
  icons/obj/gun_experimental.dmi
  icons/obj/lightning.dmi
  icons/obj/projectiles_experimental.dmi
  vgstation13.dme
Labels: Content

#28703 Soulstone Shards can now be used to perform ghetto surgery as efficiently as glass shards.
  code/modules/surgery/butt.dm
  code/modules/surgery/eye.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  code/modules/surgery/robolimbs.dm
  code/modules/surgery/slimes.dm
Labels: Content

#28739 Fixes projectiles infinitely looping between windows
  code/game/objects/structures/window.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️

#28741 Cyborgs are now restricted from Challengers
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix

#28625 Snowman Tweak
  code/game/gamemodes/endgame/xmas/snow.dm
  code/game/gamemodes/endgame/xmas/snowman.dm
  code/modules/clothing/clothing.dm
  icons/mob/snowman.dmi
Labels: Tweak, 🚓Fun Police🚓

#28601 Tag mode : Changeling Clown Among Regular Mimes
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/objectives/freeform/changeling.dm
  code/datums/gamemode/objectives/survive.dm
  code/datums/gamemode/role/blob.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/grinch.dm
  code/datums/gamemode/role/madmonkey.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/prisoner.dm
  code/datums/gamemode/role/rambler.dm
  code/datums/gamemode/role/rev.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/streamer.dm
  code/datums/gamemode/role/summonsurvivors.dm
  code/datums/gamemode/role/tag_mode.dm
  code/datums/mind.dm
  code/datums/outfit/civilian.dm
  code/game/gamemodes/gameticker.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/tagmode.dm
  code/modules/mob/new_player/new_player.dm
  vgstation13.dme
Labels: Content, Gameplay / Gamemode

#28709 Remove ling from castle.
  maps/roidstation.dm
  maps/snaxi.dm
  maps/tgstation-sec.dm
Labels: Feature Loss

#28732 better CMC colors
  nano/css/cmc.css
Labels: Sprites
