Repository vgstation-coders/vgstation13, pull requests merged in 2021-02, with the labels that each got.

#28746 Fixed the name of both ectoplasm and diabeetusol
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#28753 Fixes projectiles infinitely looping between windoors
  code/game/machinery/doors/windowdoor.dm
Labels: Bug / Fix

#28655 Tweaks Black Site Prism
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
  icons/mob/animal.dmi
  maps/randomvaults/black_site_prism.dmm
Labels: Mapping (Vault :question:), Tweak, Unable To Reproduce

#28701 Performing a deconversion now requires the target to stand still for 5 seconds, and other tweaks
  code/game/objects/items/weapons/storage/bible.dm
Labels: Tweak

#28720 slimmer armor
  code/game/machinery/vending.dm
  code/game/objects/items/vouchers.dm
  code/modules/clothing/accessories/armor_shards.dm
  icons/mob/clothing_accessories.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/accessory_overlays.dmi
Labels: Sprites

#28760 maptext barsigns
  code/game/objects/structures/barsign.dm
  code/game/sound.dm
  icons/obj/barsigns.dmi
Labels: Content, ❤️ Quality of Life ❤️

#28772 Custom Barsigns Hotfix
  code/game/objects/structures/barsign.dm
Labels: Bug / Fix

#28762 Removes the ability to grab anvils with TK.
  code/modules/blacksmithing/anvil.dm
Labels: Feature Loss

#28783 Makes window movement not suck again
  code/game/objects/structures/fullwindow.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
Labels: ❤️ Quality of Life ❤️

#28763 Adds vox xenoarch jumpsuit sprite.
  code/modules/clothing/under/jobs/medsci.dm
  icons/mob/species/vox/uniform.dmi
Labels: Sprites

#28795 Deadharvest fixes & weakref improvements.
  code/__HELPERS/weakref.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
Labels: Bug / Fix

#28797 Fix admin rejuvenates clearing mutations list.
  code/modules/mob/living/living.dm
Labels: Bug / Fix

#28804 Pay2Use Xenoarch Large Artifact Trigger Tweaking
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  code/modules/research/xenoarchaeology/artifact/effect.dm
  code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_pay2use.dm
Labels: Tweak, Update WIKI

#28805 Adds triggers to the Artifacts Panel
  code/modules/admin/artifacts_panel.dm
Labels: Logging / Administration

#28799 Makes the CI not run on PRs that can't possibly change whether or not it passes
  .github/workflows/ci.yml
Labels: Automation/CI

#28810 Fixes thrown objects hitting windows they shouldn't
  code/game/objects/objs.dm
Labels: Bug / Fix, Legacy Bug

#28750 Clown Language colour from yellow to mild pink - Mimes can now understand clown language.
  __DEFINES/stylesheet.dm
  code/datums/outfit/civilian.dm
  goon/browserassets/css/browserOutput.css
  goon/browserassets/css/browserOutput_dark.css
Labels: Tweak

#28751 Reduces roomba attack cooldown from 10 (TEN) seconds to 5
  code/game/machinery/bots/cleanbot.dm
Labels: Tweak

#28754 Adds a medical robot surgery upgrade board
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/research/designs/borg_upgrades.dm
Labels: Content

#28758 New Barsign
  code/game/objects/structures/barsigns/vg.dm
  icons/obj/barsigns.dmi
Labels: Sprites

#28768 Ricochet Taser
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/ricochet.dm
  icons/obj/projectiles_experimental.dmi
Labels: 100% tested, Content

#28770 Alcatraz QoL
  code/game/machinery/washing_machine.dm
  code/game/objects/items/trader.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/projectiles/guns/energy/stun.dm
  icons/obj/items.dmi
Labels: Tweak, ❤️ Quality of Life ❤️

#28808 Fixes lasers flying through the AI fortify effect
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Bug / Fix

#28809 Should fix most of the remaining bugs with projectiles
  code/game/objects/items/weapons/storage/lockbox.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/effects.dm
  code/modules/mob/living/simple_animal/hostile/glow_orb.dm
  code/modules/mob/living/simple_animal/hostile/human/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/mob/living/simple_animal/hostile/mushroom.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#28814 Bar Sign Refurb Pack I.I
  code/game/objects/structures/barsigns/bay.dm
  icons/barsigns.dmi
Labels: Sprites

#28816 Fixes all problems detected by Dreamchecker locally
  code/datums/shuttle.dm
  code/game/gamemodes/events/dust.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/martian_printer.dm
  code/game/machinery/mommi_spawner.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/admin/ToRban.dm
  code/modules/admin/verbs/debug.dm
  code/modules/awaymissions/maploader/writer.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/projectiles/guns/projectile/rocketlauncher.dm
  code/modules/spells/general/undeath.dm
Labels: File Cleanup

#28802 Custom Barsign Sound Changes
  code/game/objects/structures/barsign.dm
  sound/items/barsign/bsign_bassdrum_1.ogg
  sound/items/barsign/bsign_bassdrum_2.ogg
  sound/items/barsign/bsign_bassdrum_3.ogg
  sound/items/barsign/bsign_bongo_1.ogg
  sound/items/barsign/bsign_clap.ogg
  sound/items/barsign/bsign_oh_yeah.ogg
  sound/items/barsign/bsign_slapbass.ogg
  sound/items/barsign/bsign_snare.ogg
Labels: Tweak

#28818 Examining the Jukebox or a sound system while a song is playing shows the name of the song
  code/modules/media/broadcast/receiver.dm
  code/modules/media/broadcast/transmitter.dm
  code/modules/media/jukebox.dm
  code/modules/media/machinery.dm
Labels: Content

#28840 Fixes Amish Floorsprite
  code/modules/clothing/under/miscellaneous.dm
Labels: 0% tested, Hotfix

#28856 Removes some unused procs
  code/__HELPERS/game.dm
  code/modules/mob/living/carbon/slime/slime.dm
Labels: File Cleanup

#28826 Show Flavor Text Length Tweak
  code/modules/mob/mob.dm
Labels: Tweak

#28790 Enables local linter
  SpacemanDMM.toml
Labels: Discussion

#28848 Removes access requirement to fax HR.
  code/modules/paperwork/fax.dm
Labels: 100% tested, Easy Fix, Oversight

#28806 [Cult 4] Part #4-1: Constructs Changes Part 1
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/factions/bloodcult/_README_.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_projectiles.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/soulstone.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/projectiles/projectile.dm
  code/modules/spells/aoe_turf/conjure/construct.dm
  code/modules/spells/construct_spells.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
  icons/effects/effects.dmi
  icons/mob/mob.dmi
  icons/mob/screen_spells.dmi
  icons/obj/cult.dmi
  icons/obj/stationobjs.dmi
Labels: Gameplay / Gamemode

#28869 Plosky's Revenge
  code/game/objects/items/weapons/storage/backpack.dm
Labels: Hotfix

#28817 Fixes mice being able to interact with fire alarms
  code/game/machinery/alarm.dm
Labels: Oversight, 🚓Fun Police🚓

#28891 Fixes windows absorbing any and all rockets
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/rocket.dm
Labels: Bug / Fix

#28903 Change the law 4 of the corporate lawset (so it actually works this …
  code/game/objects/items/weapons/ai_modules/core.dm
Labels: 100% tested

#28868 [Cult 4] Part #4-2: Constructs Changes Part 2
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/defines/obj/weapon.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/shade.dm
  code/modules/mob/living/simple_animal/shade.dm
  icons/effects/64x64.dmi
  icons/mob/mob.dmi
  icons/obj/wizard.dmi
Labels: Gameplay / Gamemode

#28874 Tunes up zone rebuilding
  code/ZAS/Zone.dm
  code/controllers/subsystem/air.dm
Labels: Bug / Fix, System

#28875 Makes gas overlays ACTUALLY mouse transparent
  code/ZAS/Turf.dm
  code/ZAS/XGM_gases.dm
Labels: Bug / Fix, File Cleanup

#28877 Updates some hair sprites, cleans up a file, adds a new hair
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#28880 Better botany logs
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_machines.dm
Labels: Logging / Administration

#28833 He's the boss. Boss cultist.
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/cultist.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/constructs.dm
  icons/logos.dmi
  icons/role_HUD_icons.dmi
Labels: Tweak

#28842 Ambrosia Changes
  code/modules/hydroponics/seeds.dm
Labels: Tweak

#28894 Big Antimatter Jar
  code/datums/supplypacks.dm
  code/modules/power/antimatter/containment_jar.dm
  icons/obj/machines/antimatter.dmi
Labels: ❤️ Quality of Life ❤️

#28859 add 'use inhand object' button spells for jugger and arti
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/modules/mob/living/simple_animal/constructs.dm
Labels: ❤️ Quality of Life ❤️

#28917 Readds old parted hairstyle, makes new style alt
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Tweak

#28893 Fixes AIs being difficult to revive (due to a bug)
  code/game/verbs/suicide.dm
Labels: Bug / Fix
