Repository vgstation-coders/vgstation13, pull requests merged in 2021-12, with the labels that each got.

#31511 No MoMMis or AIs on purge day
  code/game/jobs/job/silicon.dm
  code/game/machinery/mommi_spawner.dm
  code/modules/mob/dead/observer/verbs.dm
Labels: Verified :white_check_mark:

#31329 Command level SPS
  code/game/gamemodes/steal_items.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/telesci/gps.dm
  icons/obj/telescience.dmi
Labels: Sprites, Content

#31463 Revised space ninja
  code/datums/gamemode/role/ninja.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/poddoor.dm
  code/game/objects/items/weapons/storage/belt.dm
Labels: Balance, Gameplay / Gamemode

#31484 Pressure valves
  code/ATMOSPHERICS/components/trinary_devices/pressure_valve.dm
  code/ATMOSPHERICS/pipe/construction.dm
  code/ATMOSPHERICS/pipe/pipe_dispenser.dm
  code/modules/RCD/RPD.dm
  code/modules/RCD/schematics/pipe.dm
  code/modules/atmos_automation/implementation/digital_pvalves.dm
  icons/obj/atmospherics/pressure_valve.dmi
  icons/obj/pipe-item.dmi
  vgstation13.dme
Labels: Content

#31446 Syndie scoreboard stuff
  __DEFINES/global.dm
  code/game/gamemodes/scoreboard.dm
  code/game/objects/items/weapons/implants/types/explosive_implant.dm
  code/modules/mob/living/say.dm
Labels: Content

#31506 Fixes shuttle_act gibbing astral projections
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
Labels: Bug / Fix

#31507 Mining bar fixes
  code/modules/components/ai/conversation.dm
  code/modules/mining/surprises/vg.dm
  maps/randomvaults/mining/mining_surprise_items.dm
Labels: Bug / Fix

#31409 Sends info about banned account cookies and multikeying to admin chats
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  goon/code/datums/browserOutput.dm
Labels: Logging / Administration

#31540 Fixes MoMMIs not being able to ventcrawl
  code/modules/mob/living/silicon/mommi/mommi_subtypes/sammi.dm
Labels: Bug / Fix

#31551 Bring back TRUE democracy
  code/modules/html_interface/voting/voting.dm
Labels: Emoji This :+1: :-1:, Verified :white_check_mark:

#31399 Baseball bat balance
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/weaponry.dm
Labels: Balance, Tweak

#31449 Makes time agents a latejoin ruleset too
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/role/time_agent.dm
Labels: Gameplay / Gamemode

#31532 Update minimum players to 20 for line
  code/datums/next_map.dm
Labels: Mapping (General :world_map:)

#31538 Stops new vaults rotating
  code/modules/randomMaps/vault_definitions.dm
Labels: Hotfix, Tweak

#31556 Voting cancelling clarification
  code/modules/html_interface/voting/voting.dm
  code/modules/html_interface/voting/voting.js
Labels: Logging / Administration

#31572 Adds DSES icon
  icons/obj/telescience.dmi
Labels: Sprites, Oversight

#31567 Fixes Eye Surgery
  code/modules/surgery/eye.dm
Labels: Bug / Fix, Oversight, 100% tested

#31589 Fixes tag mode
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix

#31594 adds shorthands for long emotes + does other stuff
  code/datums/emotes.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
Labels: Fluff :teddy_bear:

#31541 Slightly desouls the Atmos hardsuit sprite
  icons/mob/suit.dmi
Labels: Sprites

#31562 Cult 4 changes
  code/_onclick/mindUI/bloodcult/cultist.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Balance, Tweak

#31563 Custom painting revival
  code/datums/supplypacks.dm
  code/game/objects/items/mountable_frames/paintings.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/client/global cache.dm
  code/modules/html_interface/href_multipart_handler.dm
  code/modules/html_interface/nanotrasen/nanotrasen.css
  code/modules/html_interface/paintTool/canvas.css
  code/modules/html_interface/paintTool/canvas.js
  code/modules/html_interface/paintTool/canvas.tmpl
  code/modules/html_interface/paintTool/checkerboard.png
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/html_interface/paintTool/paintTool.js
  code/modules/painting/paint.dm
  code/modules/painting/painting_brush.dm
  code/modules/painting/paintings_custom.dm
  code/modules/painting/palette.dm
  code/modules/paperwork/pen.dm
  icons/mob/in-hand/left/misc_tools.dmi
  icons/mob/in-hand/right/misc_tools.dmi
  icons/obj/painting_items.dmi
  icons/obj/paintings.dmi
  nano/templates/palette.tmpl
  vgstation13.dme
Labels: Content

#31600 Fixes crafting not consuming secondary materials properly
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Bug / Fix

#31604 four unatomic fixes
  code/game/mecha/mecha.dm
  code/game/objects/structures/barsign.dm
  code/game/objects/structures/coatrack.dm
  code/modules/fish/fish_items.dm
Labels: ❤️ Quality of Life ❤️, Consistency Issue

#31571 Allows more variants of things in chemical reactions
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Consistency Issue, Tweak

#31574 Makes pdiff checks more accurate on border windows
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/window.dm
Labels: Logging / Administration, Tweak

#31587 Head Reattachment Surgery Fixes
  code/modules/organs/organ_external.dm
  code/modules/surgery/headreattach.dm
  code/modules/surgery/organs_internal.dm
Labels: Bug / Fix

#31624 Palettes are now craftable
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Content

#31631 Removes unnecessary admin PM link from admin relay chat broadcasts of centcomm/syndicate/etc sendings
  code/modules/admin/verbs/pray.dm
  code/modules/paperwork/fax.dm
Labels: Logging / Administration, Grammar / Formatting

#31603 Standardises opposite directional returns.
  code/__HELPERS/angles_dirs.dm
  code/game/machinery/camera/camera.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/structures/window.dm
  code/game/shuttle_engines.dm
  code/game/turfs/simulated.dm
  code/modules/client/edge_sliding/move_loop.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/surprise.dm
  code/modules/power/rust/fuel_injector.dm
  code/modules/projectiles/guns/lawgiver.dm
  code/modules/recycling/conveyor2.dm
Labels: Tweak

#31599 Improves required access direction checks
  code/game/jobs/access.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#31632 Some painting fixes
  code/datums/supplypacks.dm
  code/game/objects/items/mountable_frames/paintings.dm
  code/modules/html_interface/paintTool/canvas.css
  code/modules/html_interface/paintTool/canvas.js
  code/modules/html_interface/paintTool/canvas.tmpl
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/html_interface/paintTool/paintTool.js
  code/modules/painting/paintings_custom.dm
  code/modules/painting/palette.dm
Labels: Bug / Fix, Feature Request

#31648 Fix paintings not saving changes
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/painting/paintings_custom.dm
Labels: Bug / Fix

#31651 Fixes hobo-bombing exploit
  code/modules/mob/dead/observer/verbs.dm
Labels: Bug / Fix

#31658 Apparently I missed one
  code/game/objects/items/weapons/barricade_kit.dm
Labels: Bug / Fix, 100% tested, 0% tested

#31654 Fixes a Baseball Runtime
  code/game/objects/items/weapons/weaponry.dm
Labels: Bug / Fix

#31643 Fix palette color mixing
  code/modules/html_interface/paintTool/paintTool.js
  code/modules/painting/palette.dm
Labels: Bug / Fix

#31635 Fixed a bug where offhanded weapons with shields didn't actually count as having an additional shield
  code/modules/mob/living/carbon/combat.dm
Labels: Bug / Fix

#31676 Allows newscaster censors to hide channel titles
  code/game/machinery/newscaster.dm
Labels: Content

#31374 Make end-round credits invisible only after init is done
  code/modules/client/client procs.dm
  code/world.dm
Labels: Bug / Fix, Secret repo conflict., 0% tested

#31664 Make palettes open only if used in hand, rather than when picked up.
  code/modules/painting/palette.dm
Labels: Tweak

#31652 Evidence forgers can now scan computer record data
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/detectivework/detective_scanner.dm
Labels: Content, ❤️ Quality of Life ❤️, Update WIKI

#31593 Make plastic sortable for recycling, and make a multitude of items recyclable
  __DEFINES/setup.dm
  code/defines/obj/weapon.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/misc_items.dm
  code/game/objects/items/stacks/misc.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/stacks/teeth.dm
  code/game/objects/items/stacks/tiles/mineral.dm
  code/game/objects/items/weapons/boomerang.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/table_rack_parts.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/inflatable.dm
  code/modules/Economy/debit_card.dm
  code/modules/blacksmithing/blacksmithing.dm
  code/modules/blacksmithing/misc_components.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mining/materials.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/ores_coins.dm
  code/modules/projectiles/guns/projectile/constructable/swords.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Bug / Fix, ✋ Do Not Merge ✋, Tweak

#31667 Customisable radio channel information
  __DEFINES/communications.dm
  code/__HELPERS/unsorted.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/presets.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/machinery/telecomms/telemonitor.dm
  code/game/say.dm
Labels: Content, System

#31592 Ayy Laser Guns and UFO Vault Update
  code/game/gamemodes/wizard/rightandwrong.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/grey_rig.dm
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
  code/modules/projectiles/guns/energy/disintegrator.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/special.dm
  icons/mob/hostile_humanoid.dmi
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
  icons/mob/mob.dmi
  icons/obj/gun.dmi
  icons/obj/projectiles.dmi
  maps/randomvaults/brokeufo.dmm
  sound/weapons/ray1.ogg
  sound/weapons/ray2.ogg
  vgstation13.dme
Labels: Balance, Sprites, Content, Mapping (Vault :question:), Sound

#31623 Blether Noodle Soup
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/chemical.dmi
  icons/obj/food.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites, Content

#31689 Head Fixes
  code/modules/organs/organ_external.dm
  code/modules/surgery/generic.dm
Labels: Bug / Fix

#31709 Some Minor Vault Tweaks
  maps/randomvaults/brokeufo.dmm
  maps/randomvaults/podstation.dmm
Labels: Mapping (Vault :question:), Tweak

#31714 Fixes SAMMI possession not allowing re-entering old corpse
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/mommi/mommi_subtypes/sammi.dm
Labels: Bug / Fix, 100% tested

#31695 Easels and frames (or lack thereof)
  __DEFINES/planes+layers.dm
  code/game/objects/items/mountable_frames/paintings.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/painting/easel.dm
  code/modules/painting/paintings_custom.dm
  icons/obj/painting_items.dmi
  icons/obj/paintings.dmi
  vgstation13.dme
Labels: Needs Spritework

#31696 Fingerprint fixes
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/cargo.dm
  code/game/machinery/computer/computer.dm
  code/modules/power/turbine.dm
  code/modules/research/server.dm
Labels: Bug / Fix

#31665 Dragonshell Buff
  code/game/objects/effects/fire_blast.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/research/designs/weapons.dm
Labels: Balance

#31716 Kick ATMs to Release ID
  code/game/machinery/ATM.dm
Labels: Bug / Fix

#31699 Painting UI extras
  code/modules/html_interface/paintTool/canvas.js
  code/modules/html_interface/paintTool/canvas.tmpl
  code/modules/html_interface/paintTool/paintTool.js
Labels: ❤️ Quality of Life ❤️, UI

#31692 Palette crayon fix
  code/game/objects/items/crayons.dm
  code/game/objects/items/toys.dm
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/paperwork/paper_folded.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/ammunition/magazines.dm
Labels: Bug / Fix

#31690 Suicide act emote and tweaks
  code/game/verbs/suicide.dm
  code/modules/mob/living/emote.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Bug / Fix, Content, ❤️ Quality of Life ❤️

#31666 The Liberation is at Hand
  code/game/gamemodes/blob/theblob.dm
  code/game/machinery/ammolathe.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/designs/weapons.dm
  icons/obj/gun.dmi
Labels: Content

#31688 Requested pulse demon tweaks
  code/__HELPERS/text.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/machinery/computer/arcade/arcade_game.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/objs.dm
  code/game/objects/structures/vehicles/secway.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_attack.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Bug / Fix, Balance, Tweak

#31746 Time agent fixes
  code/datums/gamemode/factions/time_agency.dm
  code/datums/gamemode/objectives/target/locate.dm
  code/datums/gamemode/objectives/target/rearrange.dm
  code/datums/gamemode/role/time_agent.dm
  code/datums/gamemode/role/timeagenttwin.dm
  code/modules/mob/inventory.dm
  vgstation13.dme
Labels: Gameplay / Gamemode, Role Datums
