Repository vgstation-coders/vgstation13, pull requests merged in 2021-04, with the labels that each got.

#29122 mommi milk
  __DEFINES/reagents.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Honk

#29133 Combat rework 2021
  __DEFINES/setup.dm
  __DEFINES/weapons.dm
  code/_onclick/item_attack.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/rocket.dm
  icons/random_krit.dmi
  sound/weapons/criticalshit.ogg
Labels: Balance, i ded

#29134 Medical rework 2021
  code/modules/reagents/machinery/chem_master.dm
Labels: Content

#29126 Unlocking air alarms and APC's by alt-clicking
  code/game/machinery/alarm.dm
  code/modules/power/apc.dm
Labels: Tweak

#29136 Paroles *dab
  code/modules/mob/living/carbon/human/emote.dm
Labels: Gameplay / Gamemode

#29146 Ricochet taser projectiles no longer blow up fuel tanks, kill animals
  code/modules/projectiles/projectile/ricochet.dm
Labels: Consistency Issue

#29145 Lets stun helmets be recharged
  code/game/machinery/recharger.dm
Labels: Bug / Fix

#29051 Phazon and Bananium solidification.
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Consistency Issue

#29048 Supply borg xenoarchaeology upgrades
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/research/designs/borg_upgrades.dm
Labels: Content, Update WIKI

#29047 gromit mug
  code/modules/reagents/reagent_containers/food/drinks.dm
  icons/obj/drinks.dmi
Labels: ❤️ Quality of Life ❤️

#29087 Fixes vampire cloning losing spells
  code/modules/medical/cloning.dm
Labels: Bug / Fix

#29088 One-use spellbooks are no longer refundable
  code/game/gamemodes/wizard/spellbook_oneuse.dm
Labels: Bug / Fix

#29092 Adds new episode names based on number of turfs on fire
  code/modules/credits/episode_name.dm
Labels: Content

#29095 Plant-B-Gone and Bug Zapper spraybottle buff. Also replaced the Bug Zapper's Toxin with Insecticide.
  code/modules/reagents/reagent_containers/spray.dm
Labels: Consistency Issue, Tweak

#29096 Most likely almost certainly fixes the Holy Water+Potassium reaction not playing the hallelujah sound effect.
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#29097 Phazon tiles now randomly teleport between each other on clicking
  code/game/turfs/simulated/floor.dm
  code/game/turfs/turf.dm
Labels: 100% tested, Content

#29125 New gravitational karmotrine drinks
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/cafe.dmi
  icons/obj/drinks.dmi
Labels: Conflicts, Content

#29160 Centrifuge fix.
  code/modules/reagents/machinery/centrifuge.dm
Labels: Bug / Fix

#29104 Assistant Alt Job Uniforms
  code/datums/outfit/civilian.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/assistant.dmi
Labels: Sprites

#29171 FTL ship, space vaults fix
  vgstation13.dme
Labels: 100% tested, Mapping (Vault :question:)

#29177 Makes warping claws harder to find
  code/modules/research/xenoarchaeology/artifact/artifact.dm
Labels: 🚓Fun Police🚓

#29174 Fixes a bartender outfit runtime
  code/datums/outfit/outfit.dm
Labels: Bug / Fix

#29078 Mouser Pistol: Reloaded
  code/datums/uplink_item.dm
  code/modules/mob/death.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/change.dm
  icons/obj/gun.dmi
Labels: Content, Ready to Merge

#29113 ctrl+clicking firelocks as silicon opens them without popup
  code/game/machinery/doors/firedoor.dm
Labels: Ready to Merge, ❤️ Quality of Life ❤️

#29165 Blunts now use the entirety of the ambrosia's reagents.
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Bug / Fix, Consistency Issue

#29168 Allow players to change their vote after they cast it
  code/game/objects/items/weapons/implants/implant.dm
  code/modules/html_interface/voting/voting.dm
  code/modules/html_interface/voting/voting.js
  nano/templates/vote.tmpl
Labels: Tweak

#29204 Siege Cannon Bug Fix
  code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
Labels: Bug / Fix

#29181 Lowers Roulette Revolver odds
  code/modules/research/xenoarchaeology/finds/digsites.dm
Labels: 🚓Fun Police🚓

#29188 Removes dead code from reagent examination
  code/modules/reagents/Chemistry-Colours.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: File Cleanup

#29191 Adds a new corgi-flavoured life creating chemical
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content

#29194 fixes AIs being able to see shuttles they shouldn't see
  code/game/area/Space Station 13 areas.dm
Labels: Bug / Fix

#29197 changes several dark mode text colors to be readable
  goon/browserassets/css/browserOutput_dark.css
Labels: Hotfix, UI

#29182 Two budgets for dynamic mode
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_maths.dm
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/role/catbeast.dm
  code/modules/admin/topic.dm
Labels: Gameplay / Gamemode, Role Datums

#29164 Lowers revsquad threat cost
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Gameplay / Gamemode, Tweak

#29179 Make neo-Travis yell at coders if they include a raw dmm file
  .github/workflows/ci.yml
Labels: Automation/CI

#29178 crit logging
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living.dm
Labels: Logging / Administration

#29202 Fixes custom fridges not respecting access requirements
  code/game/machinery/constructable_frame.dm
  code/game/machinery/kitchen/smartfridge.dm
Labels: Bug / Fix

#29172 Renames "Anti-Toxin (Dylovene)" to just "Dylovene".
  code/game/mecha/equipment/tools/medical_tools.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Consistency Issue, Tweak

#29187 Locks rapid syringe gun behind medical access, adds normal one to protolathe
  code/modules/research/designs/weapons.dm
Labels: Tweak

#29214 Gives back the nuke ops last stand pill
  code/datums/outfit/striketeams/ert.dm
  code/datums/outfit/striketeams/nt_deathsquad.dm
  code/datums/outfit/striketeams/nukeop.dm
  code/datums/outfit/striketeams/syndie_deathsquad.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Bug / Fix

#29212 Megaphones now have in-hand sprites
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/toys.dm
  icons/mob/in-hand/left/newsprites_lefthand.dmi
  icons/mob/in-hand/right/newsprites_righthand.dmi
Labels: Sprites

#29208 Storage items don't auto-collapse at 7 items if not full
  code/game/objects/items/weapons/storage/storage.dm
Labels: UI, ❤️ Quality of Life ❤️

#29251 Some critical cult fixes
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_tattoos.dm
  code/datums/religions.dm
  code/game/objects/items/soulstone.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/shade_powers.dm
  code/modules/mob/mob_movement.dm
  code/modules/organs/blood.dm
Labels: Bug / Fix

#29238 credits mute button bandaid
  code/modules/credits/credits.html
Labels: Hotfix

#29235 Removes "/" from ends of map names in voting options
  code/__HELPERS/files.dm
  code/game/gamemodes/gameticker.dm
Labels: Grammar / Formatting

#29229 Economy-Class Raisins
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Content

#29232 fixes AI being unable to use Fire Alarms.
  code/game/machinery/alarm.dm
Labels: Bug / Fix

#29176 Add defcons levels to help the crew during blob.
  .github/workflows/ci.yml
  code/__HELPERS/math/time.dm
  code/_onclick/hud/screen_alarms.dm
  code/datums/gamemode/factions/blob.dm
  code/datums/helper_datums/command_alerts.dm
  code/game/jobs/access.dm
  code/game/machinery/computer/communications.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/unit_tests/__unit_test_includes.dm
  code/modules/unit_tests/hour_calculations.dm
  icons/mob/screen_alarms.dmi
  nano/templates/comm_console.tmpl
  vgstation13.dme
Labels: Balance, Update WIKI

#29205 SASS Doesn't Explode
  maps/RandomZLevels/hive.dm
Labels: Balance

#29215 Dont step on snell
  code/modules/mob/living/simple_animal/snail.dm
Labels: Tweak

#29223 Removed hunting rifle stuns
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Tweak

#29249 Fixes the Insect Control Crates having toxin glass bottles instead of Insecticide glass bottles.
  code/datums/supplypacks.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Consistency Issue

#29192 Floor pills now have black coloring
  code/modules/reagents/reagent_containers/pill.dm
Labels: Controversial, Emoji This :+1: :-1:, Tweak

#29256 Adds "Hogan" and "Randomize" AI module boards and puts them in the vault safe.
  code/datums/ai_laws.dm
  code/game/objects/items/weapons/ai_modules/AI_modules.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/maps/spawners/spawners.dm
Labels: Content

#29239 Warden uplink item: Remote explosive implants
  code/__HELPERS/global_lists.dm
  code/datums/uplink_item.dm
  code/game/machinery/computer/prisoner.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implantcase.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Content

#29274 fixes misc sql errors
  code/datums/feedback.dm
  code/datums/mind.dm
  code/datums/statistics/statcollection.dm
  code/defines/procs/statistics.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/topic.dm
Labels: Bug / Fix

#29273 Fixes prisonners sometimes given the wrong outfits
  code/datums/gamemode/role/prisoner.dm
Labels: Bug / Fix

#29272 Fixes identity not updating when removing your ID/PDA with an obscured face
  code/game/data_huds.dm
  code/game/dna/genes/monkey.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/admin/verbs/possess.dm
  code/modules/medical/cloning.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/alien/humanoid/inventory.dm
  code/modules/mob/living/carbon/alien/larva/inventory.dm
  code/modules/mob/living/carbon/complex/martian/inventory.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/silicon/mommi/mommi_inventory.dm
  code/modules/mob/living/simple_animal/hologram/hologram_inventory.dm
  code/modules/mob/living/simple_animal/hostile/grinch.dm
  code/modules/surgery/face.dm
Labels: Bug / Fix

#29270 Added basic autoprofiler
  code/world.dm
Labels: Logging / Administration, Performance

#29290 Sets the CI version back to the server version
  .github/workflows/ci.yml
Labels: Automation/CI

#29261 Adds unique hyperzine overdose effect
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Content

#29285 Fixes custom shuttles not working most of the time
  code/game/machinery/computer/shuttle_computers.dm
  code/game/objects/items/blueprints.dm
Labels: Bug / Fix, Content

#29241 Allows all jukeboxes to have holiday vinyls at times
  code/modules/media/jukebox.dm
Labels: Consistency Issue, Needs Fixing

#29267 Displays crew score on round end information relays
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Emoji This :+1: :-1:

#29276 Fixes seeing two, unrelated, cancel options in the voting window
  code/modules/html_interface/html_interface.dm
  code/modules/html_interface/voting/voting.js
Labels: Bug / Fix

#29306 fixes a second way to get blank votes
  code/modules/html_interface/voting/voting.dm
Labels: Bug / Fix

#29283 Supermatter chad during April Fools
  code/modules/supermatter/supermatter.dm
  icons/obj/engine.dmi
Labels: :thinking:, Content, Needs Fixing

#29293 The Clownnonball
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
  icons/obj/siege_cannon.dmi
Labels: Content

#29349 Vampires bugfixes
  code/datums/gamemode/role/vampire_role.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items/incense.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/null_rod.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/structures/mirror.dm
  code/modules/mob/hearing/virtualhearer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/spells/aoe_turf/glare.dm
  code/modules/spells/targeted/enthrall.dm
  code/modules/spells/vampire_helpers.dm
Labels: Bug / Fix

#29296 A bug bug was bugging me. Rads radically less radioactive. Bugs slightly more radical.
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/species.dm
Labels: Bug / Fix

#29316 Fixes newscaster photos for linux
  code/game/machinery/newscaster.dm
Labels: Bug / Fix

#29326 Fixes prisoner management consoles showing remote explosive header
  code/game/machinery/computer/prisoner.dm
Labels: Bug / Fix, Tweak

#29298 Assistant alt-title uniforms for vox, grey, and insectoids
  code/modules/clothing/under/jobs/civilian.dm
  icons/mob/species/grey/uniform.dmi
  icons/mob/species/insectoid/uniform.dmi
  icons/mob/species/vox/uniform.dmi
  icons/obj/clothing/assistant.dmi
Labels: Sprites

#29341 Allows gremlins to ventcrawl (and spiderling ventcrawl fixes)
  code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
  code/modules/mob/living/simple_animal/hostile/gremlin.dm
  code/modules/mob/living/simple_animal/hostile/grinch.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Tweak

#29398 Makes vending machines take the tag price from tagged items
  code/game/machinery/vending.dm
Labels: 100% tested, Tweak, ❤️ Quality of Life ❤️

#29375 La Fragrance du Café Noir
  __DEFINES/planes+layers.dm
  code/datums/outfit/civilian.dm
  code/datums/outfit/security.dm
  code/game/dna/genes/vg_powers.dm
  code/modules/mob/mob_helpers.dm
Labels: Bug / Fix

#29369 Ninjas smirk when they dodge attacks
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/combat.dm
  code/modules/mob/living/combat.dm
  code/modules/mob/living/living_defense.dm
Labels: Fluff :teddy_bear:, Muh Immulsions

#29345 head revolutionaries get megaphones
  code/datums/gamemode/role/rev.dm
Labels: Emoji This :+1: :-1:, Gameplay / Gamemode

#29368 Fixes roboticist PDA showing up in backpack
  code/datums/outfit/science.dm
Labels: Tweak

#29328 Player-controlled mobs are no longer stunned
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
Labels: Balance, Emoji This :+1: :-1:, Legacy Bug

#29323 Makes score show up on bots properly
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/gamemode.dm
  code/game/gamemodes/scoreboard.dm
Labels: Hotfix

#29312 Linux support (nanoui)
  code/modules/nano/nanoui.dm
  nano/js/json2.js
Labels: UI

#29321 fix DIY shuttle engine weirdness and confusing bugs
  code/game/objects/items/blueprints.dm
  code/game/shuttle_engines.dm
Labels: Bug / Fix, Oversight

#29331 Adds a new chemical, Midazoline
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/glass/jar.dm
Labels: Content

#29393 Dynamic mode NTAW7: higher chance of prisoner antag
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Emoji This :+1: :-1:, Role Datums

#29365 Items now play a miss sound when they miss
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/combat.dm
Labels: Conflicts, Sound
