Repository vgstation-coders/vgstation13, pull requests merged in 2021-11, with the labels that each got.

#31179 Fixes area portals including each other's target turfs.
  code/game/turfs/portal.dm
Labels: Bug / Fix

#31183 Blobtel Core 2 Duo
  code/game/gamemodes/meteor/meteors.dm
Labels: Bug / Fix

#31170 Adds baseball bats
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/weaponry.dm
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/swords_axes.dmi
  icons/obj/weapons.dmi
  sound/weapons/baseball_hit.ogg
  sound/weapons/baseball_hit_flesh.ogg
  sound/weapons/spikebat_hit.ogg
Labels: Content

#31173 Optimized Body Archive
  code/datums/body_archive.dm
  code/modules/admin/body_archive_panel.dm
Labels: Performance

#31154 Movecode update for 514 except it works this time
  code/ZAS/Atom.dm
  code/datums/datumvars.dm
  code/datums/shuttle.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/spawners/grille_window_spawner.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/fullwindow.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/RCD/schematics/rcd_window_spawner.dm
  code/modules/admin/buildmode.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/power/singularity/singularity.dm
  code/modules/power/treadmill.dm
  code/modules/spacepods/spacepods.dm
  code/world.dm
Labels: Bug / Fix, T-Thanks BYOND, System

#31188 allow straight jacketed people to resist out of being buckled to a chair
  code/modules/mob/living/living.dm
Labels: Tweak

#31202 Fixes thrower garbage
  code/game/objects/effects/step_triggers.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Hotfix

#31197 Sheriff Hats
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/mob/living/simple_animal/friendly/corgi_clothing.dm
  icons/mob/corgi_head.dmi
  icons/mob/dimma.dmi
  icons/mob/head.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/vox/head.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/dimma.dmi
Labels: Fluff :teddy_bear:

#31198 Fixes barrel throwforce not actually being removed
  code/modules/reagents/reagent_dispenser.dm
Labels: Bug / Fix

#31194 cleaned up world/New, unused stuff
  code/controllers/configuration.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/ToRban.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/say.dm
  code/modules/paperwork/pen.dm
  code/world.dm
  libs/LICENSE
  libs/markdown_byond.cpp
  libs/readme.md
  vgstation13.dme
Labels: System, File Cleanup

#31210 Move tgui logs to the href logs file
  code/__HELPERS/logging.dm
Labels: System, Logging / Administration

#31212 Border dummy fixes: 1 of assuredly more than 1
  code/game/atoms_movable.dm
Labels: Bug / Fix

#31196 Cult 4 November balance (mostly) and content (a bit) update
  __DEFINES/role_datums_defines.dm
  __DEFINES/stylesheet.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/objectives/bloodcult.dm
  code/datums/gamemode/objectives/freeform.dm
  code/datums/gamemode/objectives/objective.dm
  code/datums/gamemode/role/cultist.dm
  code/datums/gamemode/role/role.dm
  code/game/objects/items/soulstone.dm
  code/modules/mob/living/say.dm
  code/modules/organs/blood.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/ui/bloodcult/32x32.dmi
Labels: Balance, Content

#31217 Fixes some things no longer checking properly if they could enter a tile
  code/game/gamemodes/blob/theblob.dm
  code/game/gamemodes/events/biomass.dm
  code/game/machinery/bots/floorbot.dm
  code/game/objects/effects/effect_system.dm
  code/game/turfs/turf.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/mining/machine_base.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/ore_redemption.dm
  code/modules/projectiles/guns/hookshot.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Bug / Fix

#31224 Makes workaround not go nuclear sometimes
  code/game/atoms_movable.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Hotfix

#31228 Just fucking kills the movement workaround
  code/game/atoms_movable.dm
Labels: Bug / Fix

#31231 Various Fixes
  code/datums/gamemode/role/role.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
Labels: Bug / Fix, Hotfix

#31229 Minor window fixes
  __DEFINES/setup.dm
  code/game/atoms_movable.dm
  code/game/objects/structures/window.dm
Labels: Bug / Fix

#31237 Fixed religion UI bugs
  code/datums/religions.dm
  tgui/packages/tgui/interfaces/ChooseReligion.js
  tgui/public/tgui.bundle.js
Labels: Bug / Fix, UI

#31240 gult
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
Labels: Hotfix, :thinking:

#31239 Optimized loading vaults
  code/datums/shuttle.dm
  code/game/area/areas.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/debug.dm
  code/modules/awaymissions/maploader/reader.dm
  code/modules/randomMaps/vaults.dm
Labels: System

#31247 Fixed a bunch of errors when loading vaults
  code/modules/randomMaps/vaults.dm
Labels: Bug / Fix

#31195 allow resisting out of straight jackets (but you can break your arms doing it and broken arms let you do it faster)
  code/modules/mob/living/living.dm
Labels: Balance, Emoji This :+1: :-1:

#31216 Replace black player name in ahelps with red ones so they can be read on dark mode
  code/modules/admin/verbs/adminhelp.dm
Labels: Logging / Administration

#31244 Buffs the fists of the rockernaut
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mining/mine_turfs.dm
Labels: Content, Tweak

#31270 Fixes auto mining
  code/modules/mining/mine_turfs.dm
Labels: Bug / Fix

#31271 Fro-bot
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: Sprites

#31261 Allows fat people to wear a poncho
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit_fat.dmi
Labels: Sprites, Tweak

#31257 Knock tacklers away with baseball bats
  code/game/objects/items/weapons/weaponry.dm
  code/modules/mob/living/carbon/combat.dm
Labels: Balance

#31250 Reduces number of spawning Hobo Shacks
  code/controllers/subsystem/init/map.dm
Labels: Mapping (General :world_map:), Easy Fix, Tweak

#31232 Inverts CTRL and ALT modifiers on numpad def zone targeting hotkeys (makes CTRL main key)
  interface/skin.dmf
  interface/skin_azerty.dmf
Labels: Tweak, Emoji This :+1: :-1:

#31272 New Vault: Pod Station
  code/game/shuttles/salvage.dm
  code/modules/randomMaps/vault_definitions.dm
  maps/randomvaults/objects.dm
  maps/randomvaults/podstation.dmm
Labels: Content, Mapping (Vault :question:), 100% tested

#31285 briefcase cuff-to-wrist functionality + storage locking + storage key
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/items/weapons/storage/storage.dm
  icons/obj/cuffs.dmi
Labels: Feature Request

#31286 Sasha no longer looks like Ian when in the hands of someone
  code/modules/mob/living/holders.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  icons/mob/in-hand/left/mob_holders.dmi
  icons/mob/in-hand/right/mob_holders.dmi
Labels: Sprites

#31292 plasma ore can melt steel beams
  code/modules/blacksmithing/forge.dm
Labels: Balance

#31295 Tackling tweaks
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/mob_defines.dm
Labels: Tweak

#31296 Removes unnecessary comma in vermin event announcement
  code/datums/helper_datums/command_alerts.dm
  code/modules/events/infestation.dm
Labels: Grammar / Formatting

#31104 Player spawn reworks
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/vox_shoal.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/role/ninja.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/tag_mode.dm
  code/datums/gamemode/role/time_agent.dm
  code/datums/gamemode/role/wizard.dm
  code/datums/outfit/outfit.dm
  code/datums/outfit/special_outfits/special.dm
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job_controller.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/transform_procs.dm
Labels: Bug / Fix, Logging / Administration

#31282 Zam Foodery Update and Condiments Deluxe
  __DEFINES/reagents.dm
  __DEFINES/setup.dm
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/store/items.dm
  icons/obj/condiment_overlays.dmi
  icons/obj/food.dmi
  icons/obj/food_condiment.dmi
  icons/obj/trash.dmi
Labels: Balance, Sprites, Content

#31308 Fixed the soulstone code not preventing shading when a cultist captures a non-cultist
  code/game/objects/items/soulstone.dm
Labels: Bug / Fix, Hotfix

#31314 put custom pizza in the pizza box
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Oversight

#31321 Fixed several vault-related bugs
  code/game/objects/objs.dm
  maps/randomvaults/asteroid_temple.dmm
  maps/randomvaults/black_site_prism.dmm
  maps/randomvaults/goonesat.dmm
  maps/randomvaults/lightspeedship.dmm
Labels: Bug / Fix

#31315 Map element rotation fixes
  code/datums/map_elements.dm
  code/modules/admin/admin_verbs.dm
  code/modules/awaymissions/maploader/reader.dm
  code/modules/mining/surprises/vg.dm
  code/modules/power/terminal.dm
  code/modules/randomMaps/dungeons.dm
  code/modules/randomMaps/vault_definitions.dm
  code/modules/randomMaps/vaults.dm
  maps/randomvaults/snaxi/snaxivault_defines.dm
Labels: Bug / Fix

#31348 Yet another attempt at fixing the missing scrollbar for admins
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/mob/mob.dm
Labels: T-Thanks BYOND

#31373 Improved auto-deadmin
  code/modules/client/client procs.dm
Labels: System, Logging / Administration

#31391 Fixed latejoin traitors not getting uplinks
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix

#31401 Default religion voice fix
  code/datums/religions.dm
Labels: Bug / Fix, Oversight

#31392 Fixed mapped intercoms being on the common frequency
  code/game/objects/items/devices/radio/radio.dm
Labels: Bug / Fix

#31394 Improved vox raiders timer display
  code/datums/gamemode/role/vox_raider.dm
Labels: Bug / Fix, Grammar / Formatting

#31384 Ethylredoxrazine now also stops alcohol slurring when consumed.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Consistency Issue

#31383 Various Cult fixes
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/objectives/bloodcult.dm
  code/datums/gamemode/role/cultist.dm
  code/modules/spells/aoe_turf/conjure/construct.dm
Labels: Bug / Fix

#31370 Enhanced Trusty Tea
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Content

#31368 Mothership Broth and Cheesy Versatility
  code/game/objects/items/trash.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/trash.dmi
Labels: Sprites, Content

#31333 Allows "peeping" through holes in walls
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/projectile.dm
  icons/effects/96x96.dmi
Labels: Content

#31284 (Revival) Mining bar
  __DEFINES/component_signals.dm
  code/_hooks/events.dm
  code/game/area/areas.dm
  code/game/mecha/mecha.dm
  code/game/mecha/working/working.dm
  code/game/objects/structures/barsign.dm
  code/game/turfs/turf.dm
  code/modules/components/ai/area_territorial.dm
  code/modules/components/ai/conversation.dm
  code/modules/components/ai/hearing.dm
  code/modules/mining/surprises/vg.dm
  code/modules/mob/living/say.dm
  maps/randomvaults/mining/bar.dmm
  maps/randomvaults/mining/mining_surprise_items.dm
  vgstation13.dme
Labels: Content, Mapping (Vault :question:)

#31376 Better airlock electronics UI
  code/game/machinery/doors/airlock_electronics.dm
Labels: ❤️ Quality of Life ❤️, UI

#31359 Grayy Soldier and Leader Helmet Sprite Updates
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites, Tweak

#31063 Better Bunsen
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: ❤️ Quality of Life ❤️, Emoji This :+1: :-1:

#31385 Makes bananium floor sounds varedit-able
  code/game/turfs/simulated/floor.dm
Labels: Logging / Administration, Tweak

#31246 Adds common filter input function
  code/__HELPERS/lists.dm
  code/modules/admin/admin.dm
  code/modules/admin/buildmode.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/striketeam.dm
  code/modules/mob/transform_procs.dm
Labels: ❤️ Quality of Life ❤️

#31390 Pod Station Tweaks
  maps/randomvaults/podstation.dmm
Labels: Mapping (Vault :question:), Tweak

#31408 Improved baseball bat throwing logic
  __DEFINES/setup.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix, Tweak

#31417 Fixed Vox Simple Mobs in space suits dying to cold temperatures
  code/modules/mob/living/simple_animal/hostile/human/vox.dm
Labels: Bug / Fix

#31419 Zamitos Spicy Stok Jerky Has More Kick
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Tweak

#31426 You can no longer keep spawning hand labeler rolls out of thin air after removing its roll from a labeler once
  code/modules/paperwork/handlabeler.dm
Labels: Bug / Fix

#31432 Revert "Yet another attempt at fixing the missing scrollbar for admins"
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/mob/mob.dm
Labels: System, Logging / Administration

#31159 Mid-round/latejoin antagonists: Pulse Demons
  __DEFINES/_macros.dm
  __DEFINES/planes+layers.dm
  __DEFINES/role_datums_defines.dm
  __DEFINES/spell_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/spell_screen_objects.dm
  code/datums/emotes.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/objectives/pulsedemon.dm
  code/datums/gamemode/role/pulsedemon.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/machinery/computer/arcade/arcade_game.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/sound.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/hostile/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulsedemon_powers.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/powernet.dm
  code/modules/spells/helpers.dm
  icons/logos.dmi
  icons/mob/animal.dmi
  icons/mob/screen1_pulsedemon.dmi
  icons/mob/screen_spells.dmi
  sound/voice/pdwail1.ogg
  sound/voice/pdwail2.ogg
  sound/voice/pdwail3.ogg
  vgstation13.dme
Labels: Sprites, Content, Gameplay / Gamemode

#31442 Urgent pulse demon fixes
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/modules/mob/living/simple_animal/hostile/pulsedemon.dm
Labels: Bug / Fix, Hotfix

#31420 muzzle internals
  code/modules/clothing/masks/miscellaneous.dm
Labels: Content

#31396 Turning a wheelchair into an assembly no longer makes it lose its motorization and such
  code/game/objects/structures/vehicles/wheelchair.dm
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
Labels: Bug / Fix

#31398 Add new wrapping junction disposal sprites
  code/modules/recycling/disposal-construction.dm
  code/modules/recycling/disposal.dm
  icons/obj/pipes/disposal.dmi
Labels: Sprites

#31421 Refactored the new AI components
  code/_hooks/events.dm
  code/game/area/areas.dm
  code/modules/components/ai/area_territorial.dm
  code/modules/components/ai/conversation.dm
  code/modules/components/ai/hearing.dm
  code/modules/mob/living/say.dm
Labels: Bug / Fix, System

#31443 Grey Laborer Helmet Resprite and Suit Tweak
  code/modules/clothing/spacesuits/grey_rig.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Balance, Sprites, Tweak

#31468 More movecode updating
  code/datums/locking_category.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items/weapons/lance.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/shuttle.dm
  code/modules/events/immovablerod.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/media/machinery.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/simple_animal/hostile/scp_173.dm
  code/modules/power/cable.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/guns/hookshot.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
Labels: System

#31254 Makes red crowbars sound more accurate
  code/game/objects/items/weapons/tools.dm
  code/game/sound.dm
  code/game/turfs/simulated/walls.dm
  sound/weapons/cbar_hit1.ogg
  sound/weapons/cbar_hit2.ogg
  sound/weapons/cbar_hitbod1.ogg
  sound/weapons/cbar_hitbod2.ogg
  sound/weapons/cbar_hitbod3.ogg
  sound/weapons/cbar_miss1.ogg
Labels: Sound, Tweak

#31462 Grayy Laborer Helmet Resprite Part 2
  icons/mob/head.dmi
Labels: Sprites
