Repository vgstation-coders/vgstation13, pull requests merged in 2022-04, with the labels that each got.

#32335 Fixes hobo shack windows
  code/modules/awaymissions/maploader/reader.dm
Labels: Bug / Fix

#32342 Fixes aistatic hard del
  code/modules/mob/living/silicon/ai/freelook/chunk.dm
Labels: Bug / Fix, Performance

#32352 fixes LOOC color
  __DEFINES/stylesheet.dm
  code/game/verbs/ooc.dm
  goon/browserassets/css/browserOutput.css
  goon/browserassets/css/browserOutput_dark.css
Labels: Bug / Fix, UI

#32322 Insectoid monkeycubes for sale in cargo.
  code/datums/supplypacks.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/reagents/reagent_containers/food/mobcube.dm
Labels: Content

#32348 Camera bugs no longer have an attack animation or make a sound when attached to objects.
  code/game/objects/items/devices/camera_bug.dm
Labels: 100% tested

#32353 Makes mobcube boxes consistent with monkeyboxes.
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Consistency Issue

#32321 Fixes seed vendor Plastellium category.
  code/modules/hydroponics/seeds.dm
Labels: Bug / Fix

#32356 Light power check runtime fix
  code/modules/power/lighting/lighting.dm
Labels: Bug / Fix, Runtime Log, 100% tested

#32362 Fixing the vox nuggets and drumsticks II: Electric Boogaloo
  code/__HELPERS/cmp.dm
  code/datums/recipe.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/kitchen/processor.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#32365 Fixes cargo crate forwarding runtime
  code/game/cargo_forwarding.dm
Labels: Bug / Fix, Runtime Log

#32363 Camera bugs can now be directly stuck onto human's clothes
  code/game/objects/items/devices/camera_bug.dm
Labels: Tweak

#32380 Electrocute act grammar fix
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Grammar / Formatting

#32377 Fixes APC settings going Off instead of Auto when they run out of power after having been forced On
  code/modules/power/apc.dm
Labels: Bug / Fix

#32374 Changes ore smelted score to reflect ore value
  code/game/gamemodes/endgame/scoreboard/department_score.dm
  code/game/gamemodes/endgame/scoreboard/scoreboard.dm
  code/game/objects/items/robot/robot_items/robot_furnace.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/ore_redemption.dm
  code/modules/mining/ores_coins.dm
Labels: Tweak

#32370 horizontal silicon fixing
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
Labels: Tweak

#32369 I'm The Joker(tm) baby!
  code/modules/games/cards/playing_cards.dm
  icons/obj/toy.dmi
Labels: Sprites

#32376 Fixes Poutine Oceans and Citadels erasing plates used on them
  code/modules/food/customizables.dm
  code/modules/reagents/reagent_containers/food.dm
Labels: Bug / Fix

#32282 Slime extract grenade fixes
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/modules/mob/living/carbon/slime/slime.dm
Labels: Bug / Fix, Tweak

#32318 Do not prevent dragging a thing onto a table if it's already on the table
  code/game/machinery/OpTable.dm
  code/game/objects/structures/tables_racks.dm
Labels: Bug / Fix

#32271 Reagent tank costs are a bit more sensible
  code/datums/supplypacks.dm
Labels: Tweak

#31944 Mulebot update (stolen content)
  code/__HELPERS/global_lists.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  code/game/objects/effects/decals/Cleanable/tracks.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/mob/mob.dm
  icons/mob/screen1.dmi
  sound/machines/horn1.ogg
  sound/machines/horn2.ogg
  sound/machines/horn3.ogg
Labels: WiP

#32391 Fix item breaking message before being kicked message.
  code/game/objects/items.dm
Labels: Bug / Fix

#32193 Two singularities in the world can link on some occasions
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/power/singularity/singularity.dm
  code/modules/telesci/bscrystal.dm
Labels: Content

#32337 Admin-only custom proc call reagent: Procizine
  __DEFINES/reagents.dm
  code/game/machinery/scp_294.dm
  code/game/objects/items/trader.dm
  code/modules/admin/admin_verbs.dm
  code/modules/projectiles/guns/procgun.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Content, Logging / Administration

#32349 Fixed a bug that caused the whisper for prayers to be delayed by a few seconds
  code/modules/ext_scripts/discord.dm
  code/modules/ext_scripts/irc.dm
Labels: Bug / Fix

#32355 fixes vox hairs not setting properly on vox monkeymen
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/hair_styles.dmi
Labels: Bug / Fix

#32361 Fixed a bug that made the all-in-one grinder always consume all stacks
  code/modules/reagents/machinery/reagentgrinder.dm
Labels: Bug / Fix

#32368 clowns can pull out funny objects when digging in a surgical incision
  code/game/objects/items/toys.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/implant.dm
Labels: Fluff :teddy_bear:

#32386 fix ais not being able to toggle digital valves
  code/ATMOSPHERICS/components/binary_devices/valve.dm
Labels: Bug / Fix

#32387 pAIs can wirejack windoors
  code/game/machinery/doors/windowdoor.dm
Labels: Consistency Issue, Tweak

#32390 Fix grue scoreboard text requiring an intact body.
  code/datums/gamemode/role/grue.dm
Labels: Bug / Fix

#32397 volume pump stalling fix
  code/ATMOSPHERICS/components/binary_devices/volume_pump.dm
Labels: Easy Fix

#32408 Perhaps fix the problem with people unable to connect to ss13.moe
  code/world.dm
Labels: T-Thanks BYOND

#32410 Improved "Perhaps fix the problem with people unable to connect to s13.moe"
  code/controllers/subsystem/openport.dm
  code/world.dm
  vgstation13.dme
Labels: System

#32411 Some rune lying sanity
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
Labels: Bug / Fix

#32417 Fixed human hard dels
  code/game/objects/items/soulstone.dm
  code/game/objects/structures/misc_structures.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_internal.dm
  code/modules/surgery/organs_internal.dm
Labels: Bug / Fix, System

#32423 Removed logging from the new OpenPort workaround
  code/controllers/subsystem/openport.dm
Labels: Logging / Administration

#32414 test_very_tiny
  __DEFINES/__compile_options.dm
  maps/_map_override.dm
  maps/test_very_tiny.dm
  maps/test_very_tiny.dmm
Labels: System

#32373 should I call it the mailman or the courier?
  code/datums/outfit/cargo.dm
  code/game/jobs/job/civilian.dm
Labels: Role Datums

#32416 Mostly fixes Z-stairs
  code/modules/multiz/structures.dm
Labels: Bug / Fix

#32418 maybe prevent clown cannonballs from going bananas
  code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
Labels: Bug / Fix

#32421 Fixed suspension field deleting mobs
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
Labels: Bug / Fix

#32384 Cargo Automation
  code/datums/supplypacks.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/stacks/packagewrap.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/research/designs/boards/machine_misc.dm
  icons/obj/machines/logistics.dmi
  icons/obj/recycling.dmi
Labels: WiP

#32444 Fixes broken Automation construction steps
  code/game/machinery/constructable_frame.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Hotfix, 100% tested

#32439 Mice can no longer nibble silicon's non-existent toes
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Bug / Fix, Sanity / Ghosthands

#32435 Allows Comms Console to make multi-line announcements
  code/__HELPERS/text.dm
  code/game/machinery/computer/communications.dm
Labels: Tweak

#32433 straitjackets no longer automatically remove handcuffs
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Tweak

#32428 Wearable emags
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/mob/living/carbon/combat.dm
Labels: 100% tested

#32431 Allows you to take photos through camera bugs.
  code/game/objects/items/devices/handtv.dm
  code/modules/paperwork/photography.dm
Labels: Tweak

#32468 Fixed remove ID verb
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Bug / Fix

#32396 Adds a delay to holy water/potassium reactions
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix, Sound, Tweak

#32404 Combines internal and external bleeding modifiers
  code/modules/organs/blood.dm
  code/modules/organs/organ_external.dm
Labels: Balance

#32413 Optimizations
  code/controllers/configuration.dm
  code/controllers/subsystem/init/more_init_stuff.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/game/dna/dna2.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life/handle_random_events.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/mommi/login.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/mommi/mommi_hud.dm
  code/modules/mob/living/silicon/mommi/mommi_subtypes/soviet.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob_defines.dm
  vgstation13.dme
Labels: Feature Loss, System

#32405 Tentative fix for an implant-related infinite loop
  code/game/objects/items/weapons/implants/implant.dm
Labels: Bug / Fix

#32407 Sleeper Tweaks including Sleep Chem Purging
  code/game/machinery/Sleeper.dm
Labels: Balance, ❤️ Quality of Life ❤️

#32424 Targeting-based reagent mob reaction, attempt 2
  __DEFINES/limb_defines.dm
  code/__HELPERS/mobs.dm
  code/game/objects/breakable.dm
  code/game/objects/items/weapons/mop.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/jar.dm
Labels: System, 100% tested, Tweak

#32440 Renames c20r ammo to be distinct from standard 12mm ammo
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/research/designs/weapons.dm
Labels: Consistency Issue, Grammar / Formatting

#32442 Artifact analyser cleanup
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/research/xenoarchaeology/machinery/artifact_scanner.dm
Labels: ❤️ Quality of Life ❤️, 100% tested, Tweak

#32415 Soporific Rejuvenant rework
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance

#32464 Adds overalls to janitor's closet
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
Labels: Content

#32473 Fixes Scrambler and Microwave Ray Effects Ignoring Shield Blocks
  code/modules/projectiles/projectile/special.dm
Labels: Bug / Fix

#32470 Actually fixes multi-z infinite loops
  code/controllers/configuration.dm
  code/modules/multiz/falling.dm
  code/modules/multiz/turfs.dm
  config-example/config.txt
  maps/test_euclidean.dm
  maps/test_euclidean.dmm
Labels: Bug / Fix, 100% tested

#32472 Roboticist's Tears, the best soup you'll eat.
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Sprites

#32471 Species exclusive and discounted uplink item support
  code/datums/components/uplink.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/uplink_item.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Content

#32459 The emag telefrag
  code/datums/helper_datums/teleport.dm
  code/game/objects/items/beacon.dm
  sound/effects/telefrag.ogg
Labels: Content, 100% tested

#32465 Adds a new traitor bundle and adds/adjusts items in it.
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/weaponry.dm
  icons/mob/in-hand/left/flashlights_n_lamps.dmi
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/flashlights_n_lamps.dmi
  icons/mob/in-hand/right/swords_axes.dmi
  icons/obj/lighting.dmi
Labels: Sprites, 100% tested, Unatomic Uncle

#32462 Cigarette Radio Bugs
  __DEFINES/communications.dm
  code/__HELPERS/unsorted.dm
  code/datums/uplink_item.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
Labels: Gameplay / Gamemode, 100% tested

#32485 Random mob cargo forward fixes
  code/game/objects/structures/cage.dm
Labels: Bug / Fix

#32477 Better fake adminbus explosions
  code/game/objects/explosion.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Content, Logging / Administration, 100% tested
