Repository vgstation-coders/vgstation13, pull requests merged in 2022-06, with the labels that each got.

#32664 Refactor tinfoil hat snowflake code
  __DEFINES/setup.dm
  code/datums/gamemode/powers/changeling.dm
  code/game/data_huds.dm
  code/game/dna/genes/goon_powers.dm
  code/game/dna/genes/powers.dm
  code/game/gamemodes/setupgame.dm
  code/game/machinery/camera/tracking.dm
  code/game/machinery/mind_machine.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/spells/targeted/targeted.dm
  maps/randomvaults/dungeons/research.dmm
Labels: System

#32707 Tweaks luck-related values for slots and lotto tickets
  code/game/machinery/computer/slot_machine.dm
  code/modules/games/cards/lotto.dm
Labels: Bug / Fix, Tweak

#32712 Ventcrawl mutli-Z code cleanup
  code/ATMOSPHERICS/atmospherics.dm
  code/modules/multiz/ventcrawl.dm
  maps/test_multiz.dmm
Labels: 100% tested

#32716 Allows amauri noreact property to interact with xenobotany genes
  code/modules/hydroponics/prehistoric_plants.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Content, 100% tested

#32715 Fixes trade and wage subsystem runtimes on maps without accounts for either
  code/modules/Economy/Wages.dm
  code/modules/trader/trade_system.dm
Labels: Bug / Fix, Runtime Log

#32757 Hotfix Absorb DNA
  code/modules/spells/changeling/absorb_dna.dm
Labels: Bug / Fix, Hotfix

#32753 Power Monitor fixes
  code/game/objects/items/devices/PDA/cart/engineering.dm
  code/modules/power/monitor.dm
Labels: Bug / Fix

#32748 Voucher Description Tweaks
  code/game/objects/items/vouchers.dm
Labels: 100% tested, Tweak

#32743 Makes maint access revoke and readding more customisable
  code/game/jobs/access.dm
  code/modules/events/radiation_storm.dm
  code/modules/security levels/keycard authentication.dm
Labels: 100% tested

#32741 Game can now only pick prison break event if people are actually in prison
  code/modules/events/prison_break.dm
Labels: 100% tested, Tweak

#32739 Removes unreadied requirement for slot editing
  code/modules/mob/new_player/new_player.dm
Labels: ❤️ Quality of Life ❤️, 100% tested, Tweak

#32738 Added a small sound to signal to revheads that they have been converted
  code/datums/gamemode/role/rev.dm
  sound/misc/wideismymotherland.ogg
Labels: Fluff :teddy_bear:

#32733 Removing corn oil from deep fryer with beakers
  code/modules/food/cooking_machines.dm
  code/modules/reagents/reagent_containers.dm
Labels: 100% tested, Tweak

#32609 Hydroponics refactoring
  __DEFINES/hydroponics.dm
  code/game/machinery/bots/farmbot.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/hydroponics/hydroponics_reagents.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seeds.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/mob/living/carbon/monkey/diona.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_plantkiller.dm
  code/modules/spells/targeted/genetic.dm
  code/modules/virus2/effect/stage_2.dm
  icons/obj/hydroponics/hydro_tools.dmi
Labels: System, WiP

#32763 Fixes missing PDA cartridge app menus
  code/game/objects/items/devices/PDA/cart/civilian.dm
  code/game/objects/items/devices/PDA/cart/engineering.dm
Labels: Bug / Fix

#32768 Vampire bugfix
  code/datums/gamemode/role/vampire_role.dm
Labels: Bug / Fix, Hotfix

#32736 Refactors Reagent Nutrition, Bugfixes (buffs) Dan Snacks and Condiments
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix, Consistency Issue

#32751 Shuttle automatically called if round lasts 8 hours
  code/controllers/shuttle_controller.dm
  code/datums/gamemode/dynamic/dynamic.dm
  code/game/machinery/computer/communications.dm
  code/modules/mob/living/silicon/ai/death.dm
Labels: Content

#32752 Makes shifts start at exactly 12:00
  code/__HELPERS/time.dm
  code/controllers/mc/master.dm
Labels: Consistency Issue, 100% tested, Tweak

#32760 Banana peel tweaks
  code/defines/obj/weapon.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/grenades/clowngrenade.dm
  code/game/objects/items/weapons/teleportation.dm
  code/modules/randomMaps/vault_definitions.dm
  maps/randomvaults/objects.dm
Labels: Bug / Fix, Consistency Issue, Tweak

#32744 Adds the Meat Fridge vendor
  code/datums/supplypacks.dm
  code/game/machinery/vending.dm
  code/game/machinery/vending_packs.dm
  code/game/objects/items/vouchers.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/reagents/reagent_containers/food/mobcube.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  icons/obj/vending.dmi
  icons/obj/vending_pack.dmi
Labels: Content, 100% tested

#32742 ablative, bulletproof and antichrist helmets(adminspawn only)
  code/modules/clothing/head/tactical.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Content

#32765 Runtime fix in hydro_tray_process
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/hydroponics_mutations.dm
Labels: Bug / Fix, Hotfix

#32687 Non-humans turn into zombies
  code/game/objects/items/potions.dm
  code/game/objects/items/trader.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
  code/modules/virus2/effect/stage_4.dm
Labels: Content, WiP

#32745 Improved biological debris field storm
  code/game/gamemodes/meteor/meteors.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/modules/events/meteors.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Content, 100% tested

#32802 Fixes non-constant expression in switch block.
  code/modules/cmc/crew.dm
Labels: Bug / Fix

#32792 Robustharvest weed rate too high
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix, Hotfix, Balance, Tweak

#32758 Changeling: Monkeyform duplicate icons
  code/datums/gamemode/powers/changeling.dm
  code/game/gamemodes/changeling/changeling_procs.dm
  code/modules/spells/changeling/changeling_spell.dm
  code/modules/spells/changeling/lesser_form.dm
  code/modules/spells/changeling/unstun.dm
Labels: Bug / Fix, Balance, Unatomic Uncle

#32812 fix telecomms emagging
  code/game/machinery/telecomms/traffic_control.dm
Labels: Bug / Fix

#32747 Add American football (sic) items.
  code/datums/supplypacks.dm
  code/game/machinery/vending.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Content

#32746 T-Ray Scanners should see invisible objects
  __DEFINES/setup.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/datums/gamemode/role/vampire_role.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/potions.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/recycling/disposal.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
  code/modules/spells/targeted/feint.dm
Labels: Tweak, Emoji This :+1: :-1:

#32779 The game will no longer pick a random place to check for armor when it hit something
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Bug / Fix

#32790 Reformatted special roles menu
  code/modules/client/preferences.dm
  html/browser/common.css
Labels: Grammar / Formatting, UI, Role Datums

#32794 Improved Admin Logging on Field Generator Failure
  code/modules/power/singularity/field_generator.dm
Labels: Logging / Administration

#32797 Hide Shunted AI Copies from OOC Manifest
  code/defines/obj.dm
Labels: Bug / Fix, Exploitable

#32810 Removes global map multiZ variable, makes checks more dynamic
  __DEFINES/rcd.dm
  code/ATMOSPHERICS/pipe/pipe_dispenser.dm
  code/game/jobs/access.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/RCD/RCD.dm
  code/modules/RCD/RPD.dm
  code/modules/RCD/schematics/pipe.dm
  maps/_map.dm
  maps/test_euclidean.dm
  maps/test_multiz.dm
  maps/tgstation-snow.dm
Labels: Tweak

#32816 Robust Harvest balance
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance, ❤️ Quality of Life ❤️, Tweak

#32827 Electro disability fix
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
Labels: Balance

#32815 Disables auto signups for roles while adminned
  code/__HELPERS/game.dm
Labels: ❤️ Quality of Life ❤️, Logging / Administration

#32820 Fixes Football uniforms not having icons.
  code/modules/clothing/head/misc.dm
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Hotfix, Oversight, 100% tested

#32833 Using a material synth on fabricators allows scanning materials inside
  code/game/objects/items/devices/mat_synth.dm
Labels: Content, ❤️ Quality of Life ❤️, 100% tested

#32824 Speech filter fixes
  code/game/dna/genes/goon_disabilities.dm
  code/game/dna/genes/speech.dm
Labels: Bug / Fix, 100% tested

#32814 Vampire Shapeshifting changes + Screech breaks light bulbs
  __DEFINES/_macros.dm
  __DEFINES/setup.dm
  code/datums/gamemode/powers/vampire.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/helper_datums/butchering.dm
  code/game/dna/dna2_helpers.dm
  code/game/gamemodes/meteor/meteors.dm
  code/modules/medical/autopsy.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/carbon/species_powers.dm
  code/modules/mob/living/simple_animal/hostile/grue_powers.dm
  code/modules/mob/mob.dm
  code/modules/organs/internal/eyes/eyes.dm
  code/modules/organs/organ_objects.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/spells/aoe_turf/screech.dm
  code/modules/spells/general/shapeshift.dm
Labels: WiP

#32860 Fixes disposal cross runtime
  code/modules/recycling/disposal.dm
Labels: Bug / Fix, Runtime Log
