Repository vgstation-coders/vgstation13, pull requests merged in 2022-09, with the labels that each got.

#33111 Bombermen can no longer tackle
  code/modules/mob/living/carbon/combat.dm
Labels: Tweak

#33118 Mothership Lab Vault: Floor Fixin' (Simulated -> Unsimulated) and Some Addons
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/dungeons/research.dmm
  maps/randomvaults/mothership_lab.dmm
Labels: Content, Mapping (Vault :question:)

#33130 Gallon of PCP
  __DEFINES/reagents.dm
  code/datums/supplypacks.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Content

#33131 Ayy Uniform Shipments: Boots Now Included, Military Surplus Addition
  code/datums/supplypacks.dm
Labels: Tweak

#33120 Mothership Lab: Vox Raider Deadeye Nerf
  code/modules/mob/living/simple_animal/hostile/human/vox.dm
Labels: Tweak

#33147 Adds a full range of tatami designs to the Tile Painter
  code/modules/RCD/schematics/tile.dm
  icons/turf/floors.dmi
  maps/misc/dojo.dmm
Labels: Sprites

#33173 fixes bleach bottles
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Bug / Fix, Hotfix

#33179 Matsynths don't recycle.
  code/modules/research/rdmachines.dm
Labels: Bug / Fix, Hotfix, 100% tested

#33188 Pregame Lobby Message
  code/game/gamemodes/gameticker.dm
Labels: Hotfix

#33116 MDF Grenadier Changes, plus nu Ayy Soldier Type
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
  icons/mob/hostile_humanoid.dmi
Labels: Content, Mapping (Vault :question:)

#33204 Mothership Lab Hotfix: Hobos Need Air To Survive
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/mothership_lab.dmm
Labels: Bug / Fix, Hotfix

#33195 Wood planks crate now has 50 planks instead of 25.
  code/datums/supplypacks.dm
Labels: Consistency Issue

#33226 Fix some runtimes
  code/datums/gamemode/role/role.dm
  code/game/objects/explosion.dm
Labels: Hotfix

#33234 Fix explosion runtime
  code/game/objects/explosion.dm
Labels: Hotfix

#33235 Flash except it's incredibly sus (featuring me fucking up conflict resolution)
  code/modules/mob/living/simple_animal/amogusflash.dm
  code/modules/spells/amogus_spells.dm
  icons/mob/animal.dmi
  icons/mob/screen_spells.dmi
  vgstation13.dme
Labels: Sprites, Content

#33215 Staff of Necromancy bugfix
  code/modules/projectiles/guns/energy/special.dm
Labels: Hotfix

#33247 Drowsy B Gone: auto380 and fortyfive || And glock pain train
  code/modules/projectiles/projectile/bullets.dm
Labels: Balance, Tweak

#33257 Vampire shriek now heard
  code/modules/spells/aoe_turf/screech.dm
Labels: Hotfix

#33253 Fix some hydro_tray_process runtimes and bugfix
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/hydroponics_reagents.dm
Labels: Hotfix

#33145 Improves ninja shurikens
  code/datums/gamemode/role/ninja.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#33270 Fixes fireballs not causing any station damage
  code/modules/spells/targeted/projectile/fireball.dm
Labels: Bug / Fix

#33271 People thrown by the Punch spell while frozen in time will no longer have funky sprites
  code/modules/spells/targeted/punch.dm
Labels: Bug / Fix

#33272 Gives extra clarity to the Grand Slam Stellar Lottery event
  code/modules/events/money_lotto.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#33267 Fix hydroponics seeds never being able to lose some traits through mutations
  code/modules/hydroponics/hydroponics_mutations.dm
Labels: Bug / Fix

#33150 Removes Line Station from the voting pool
  code/datums/next_map.dm
Labels: Controversial, ⛔ Requires Server Vote ⛔

#33284 Rigsuit hotfix
  icons/mob/head.dmi
Labels: Hotfix

#33263 The radiation gene emits less radiation by default but multiplies with user radiation
  code/game/dna/genes/goon_disabilities.dm
Labels: Balance, Tweak

#33278 Mothership Uniforms: Fixes Soldier Uniforms Not Coming In Shipments
  code/datums/supplypacks.dm
Labels: Bug / Fix

#33286 Fix AI control light not working on APC's
  code/datums/wires/apc.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/power/apc.dm
Labels: Bug / Fix

#33330 Fixes power monitor runtiming if an APC is broken or being disassembled
  code/modules/power/monitor.dm
Labels: Bug / Fix

#33308 Fixes observe verb defaulting to cyborg when cancelled
  code/modules/mob/dead/observer/verbs.dm
Labels: Bug / Fix

#33341 Bugfix: Poly Pudding Crumb Color
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#33335 Conveyor belt metal cost tweaks
  code/modules/recycling/conveyor_assembly.dm
Labels: Bug / Fix, Tweak

#33329 "THE TRAITOR THEY KILL PEOPLE": New Brain Damage Line
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
Labels: Content

#33301 Airshield Bugfixes and Power Changes
  code/game/objects/structures/airshield.dm
Labels: Bug / Fix, 100% tested

#33327 Some space hobo QoL
  code/datums/outfit/special_outfits/special.dm
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
  maps/misc/hoboshack.dmm
Labels: ❤️ Quality of Life ❤️, Needs Spritework, Tweak

#33317 Yantar Consistency
  code/game/objects/items/trader.dm
  code/modules/trader/trade_datums.dm
Labels: Tweak

#33297 Emag Chem Dispenser
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Content

#33356 Haunting people as a ghost now displays a list that prioritizes players first
  code/__HELPERS/unsorted.dm
Labels: ❤️ Quality of Life ❤️

#33319 makes discount dan's special sauce a real condiment
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  icons/obj/condiment_overlays.dmi
  icons/obj/food_condiment.dmi
  icons/obj/trash.dmi
  maps/misc/holodeck_olympics.dmm
Labels: Sprites

#33261 Gym Rat Quality of Life Changes, and ROID RATS
  __DEFINES/spell_defines.dm
  code/modules/mob/living/simple_animal/hostile/gym_rats.dm
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/spells/targeted/roidrat_punch.dm
  icons/mob/animal.dmi
  vgstation13.dme
Labels: Content, Tweak

#33302 Screwsolder
  code/game/machinery/constructable_frame.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/modules/media/broadcast/transmitters/broadcast.dm
  icons/obj/items.dmi
Labels: Content

#33274 Wizard Batteries
  code/modules/fish/fish_tank.dm
Labels: Content

#33290 Flatpacks now print with upgraded parts if they were researched from upgraded machines
  code/game/machinery/machinery.dm
  code/modules/research/designs.dm
  code/modules/research/mechanic/flatpacker.dm
  code/modules/research/mechanic/mechanic_designs.dm
Labels: Bug / Fix, Consistency Issue, 100% tested

#33372 small dansauce icon hotfix
  code/modules/reagents/reagent_containers/food/condiment.dm
Labels: Bug / Fix, Hotfix

#33365 Fixes powercreeper layering
  code/game/gamemodes/events/powercreeper.dm
Labels: Bug / Fix

#33387 removes admin pm overmind verb
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Logging / Administration

#33364 Towercap Log doors.
  code/game/machinery/doors/mineral.dm
  code/modules/hydroponics/grown_inedible.dm
Labels: 100% tested

#33367 Fix photos again
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
Labels: Bug / Fix

#33371 Reverts limb targeting requirements for pepperspray
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Balance

#33381 Raises Blob Midround Threat Cost
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Tweak

#33386 Fixes for Haunt verb
  code/__HELPERS/unsorted.dm
Labels: Hotfix

#33398 sanity check for briefcase full of bees
  code/game/objects/items/weapons/storage/briefcase.dm
Labels: Bug / Fix

#33401 fix upgraded chemmaster bottling
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Bug / Fix

#33390 Fixes several botany chemical reactions
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
Labels: Bug / Fix, 100% tested

#33312 Round Randomized Reagent
  code/controllers/subsystem/init/more_init_stuff.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/randomized_reagent.dm
  vgstation13.dme
Labels: Gameplay / Gamemode, help wanted

#33273 Wearing the Championship Belt and the Luchador Mask at the same time will double your unarmed damage and tackle power
  __DEFINES/_macros.dm
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/human/combat.dm
Labels: Honk, Tweak
