Repository vgstation-coders/vgstation13, pull requests merged in 2022-05, with the labels that each got.

#32497 Transit tube construction fixes
  code/game/objects/structures/transit_tubes/station.dm
  code/game/objects/structures/transit_tubes/transit_tube.dm
  code/game/objects/structures/transit_tubes/transit_tube_assembly.dm
Labels: Bug / Fix

#32502 Fixes access issue on shard crates
  code/datums/supplypacks.dm
Labels: Hotfix

#32438 Fixes Swiss Tool tech values
  code/game/objects/items/weapons/switchtool.dm
Labels: Bug / Fix, Balance, Sanity / Ghosthands

#32490 Reenables events when few players
  code/modules/events/event_dynamic.dm
Labels: Gameplay / Gamemode, Emoji This :+1: :-1:

#32508 comment out rune hallucuination animations
  code/modules/virus2/effect/stage_1.dm
Labels: Hotfix, Feature Loss

#32506 Changes the sound for sending a message over the radio
  code/game/objects/items/devices/radio/headset.dm
  sound/effects/radio_beep.ogg
Labels: Tweak

#32510 Makes coins initialize with random orientation.
  code/modules/mining/ores_coins.dm
Labels: Consistency Issue, Tweak

#32500 Makes heavy disintegrator discounted for greys
  code/datums/uplink_item.dm
Labels: Tweak

#32499 Makes the organics extractor traitor item discounted for vox and traders
  code/datums/uplink_item.dm
Labels: Tweak

#32498 Bicaridine's and Inaprovaline's bleeding slowdown now stacks.
  code/modules/organs/blood.dm
Labels: Tweak

#32493 Increase grue healing in darkness rate
  code/modules/mob/living/simple_animal/hostile/grue.dm
Labels: Tweak

#32534 Mothership Lab Mob Door Interaction Fix
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
  code/modules/mob/living/simple_animal/hostile/human/vox.dm
Labels: Bug / Fix

#32536 Fixes Mothership Lab Nurse Door Interact
  code/modules/mob/living/simple_animal/hostile/human/greynurse.dm
Labels: Bug / Fix

#32488 Can live after being nuked
  code/game/gamemodes/gameticker.dm
  code/modules/mob/living/living.dm
Labels: Tweak

#32522 Changes Cargo and Medical Job Preference Colors
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/medical.dm
Labels: UI, Tweak

#32537 Mothership Lab: Prevent AI Peeping, and some Mapping Tweaks
  __DEFINES/cameranet.dm
  __DEFINES/setup.dm
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/dungeons/research.dmm
  maps/randomvaults/mothership_lab.dmm
Labels: Mapping (Vault :question:), Tweak

#32544 Bugfix: Ayy Heavy Using Heavy Disintegrator Like Double Barrel Shotgun
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
Labels: Bug / Fix, Hotfix

#32366 Time agent objective code cleanup
  code/__HELPERS/lists.dm
  code/datums/gamemode/objectives/target/locate.dm
  code/datums/gamemode/objectives/target/rearrange.dm
Labels: Tweak

#32505 Adds beekeeping attire to hydroponics lockers
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
Labels: ❤️ Quality of Life ❤️, Emoji This :+1: :-1:

#32520 Spider QoL
  code/game/objects/effects/rooting_trap.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#32532 Jetpacks work on any hardsuit storage slot.
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: :up: Powercreep :up:

#32518 Changes Cargo Requests Reason to Reason/Destination
  code/game/machinery/computer/cargo.dm
Labels: UI, Tweak

#32535 Fixes emag issues
  code/game/machinery/bots/bots.dm
  code/game/machinery/machinery.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/turfs/simulated/shuttle.dm
  code/modules/power/port_gen.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Bug / Fix, Hotfix

#32539 A Few More Mothership Lab Mapping Tweaks
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/mothership_lab.dmm
Labels: Mapping (Vault :question:), Tweak

#32543 Grey Leader Suit Plasma Protection Tweak
  code/modules/clothing/spacesuits/grey_rig.dm
Labels: Balance, Tweak

#32504 Roundstart Blood Supply Nerf
  code/datums/supplypacks.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
Labels: Controversial, Tweak

#32547 BAD TO THE BONE
  code/game/objects/effects/decals/remains.dm
  code/game/objects/items/weapons/clown_items.dm
  sound/items/badtothebone.ogg
Labels: Content

#32489 Wizard: Staff of Polymorph and Pollywogs
  __DEFINES/global.dm
  code/game/gamemodes/wizard/artifacts.dm
  code/modules/clothing/masks/transmog.dm
  code/modules/mob/death.dm
  code/modules/mob/living/simple_animal/pollywog.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_menagerie.dm
  icons/mob/back.dmi
  icons/mob/in-hand/left/wiz_left.dmi
  icons/mob/in-hand/right/wiz_right.dmi
  icons/mob/mob.dmi
  icons/obj/wizard.dmi
  vgstation13.dme
Labels: Content, 100% tested

#32554 Simple mobs can toggle light floor tiles
  code/game/turfs/simulated/floor.dm
Labels: Tweak

#32564 Adds newline to end of pulse demon scoreboard.
  code/datums/gamemode/role/pulsedemon.dm
Labels: Bug / Fix

#32557 Fixes/Improves Some Ayy Clothing Sprites
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/species/grey/head.dmi
  icons/mob/species/grey/masks.dmi
  icons/mob/species/grey/suit.dmi
  icons/mob/species/grey/uniform.dmi
Labels: Sprites

#32553 Adds new glove sprites to pre-existing gloves
  code/modules/clothing/gloves/miscellaneous.dm
  icons/mob/animal.dmi
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Sprites

#32548 Fix for palettes getting gunked by empty brushes, and minor palette refactor
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/painting/palette.dm
Labels: Bug / Fix

#32542 New custodial crate entry for the supply console
  code/datums/supplypacks.dm
Labels: Controversial

#32555 Flipping chocolate coins
  __DEFINES/_macros.dm
  __DEFINES/setup.dm
  code/_hooks/events.dm
  code/datums/components/coinflip.dm
  code/game/atoms.dm
  code/game/objects/items.dm
  code/modules/food/customizables.dm
  code/modules/mining/ores_coins.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  vgstation13.dme
Labels: Content

#32560 Antag and non-antag roles
  code/__HELPERS/unsorted.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/streamer.dm
  code/game/verbs/who.dm
Labels: Logging / Administration, Role Datums

#32570 typofix
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Grammar / Formatting

#32568 Nerf Emagged Pod Explosion
  code/game/shuttles/emergency.dm
Labels: Balance

#32603 Removes Airless Tile (Mothership Lab Vault)
  maps/randomvaults/mothership_lab.dmm
Labels: Bug / Fix, Hotfix

#32607 Fix banana cream pies permanently blinding simple mobs
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#32598 Black Site Prism Tweaks and Fixes
  code/game/machinery/turrets.dm
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/mob/living/simple_animal/hostile/human/vox.dm
  code/modules/spells/vampire_helpers.dm
  icons/mob/hostile_humanoid.dmi
  maps/randomvaults/black_site_prism.dmm
Labels: Content, Mapping (Vault :question:), Tweak

#32597 IV Drip Tweaks
  code/game/machinery/iv_drip.dm
  code/game/objects/structures/stool_bed_chair_nest/rollerbed.dm
Labels: Bug / Fix

#32579 Shows episode name reason as mouseover alt text on credits
  code/modules/credits/credits.dm
  code/modules/credits/episode_name.dm
Labels: Content, 100% tested

#32601 Ayy Head Poke
  code/modules/mob/living/carbon/carbon.dm
Labels: Tweak

#32569 Updates insectoid monkey form
  code/datums/supplypacks.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/mob/living/carbon/monkey/roach.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/reagents/reagent_containers/food/mobcube.dm
  icons/mob/monkey.dmi
Labels: Bug / Fix, Sprites, Tweak, help wanted

#32561 Cooking jecties now results in actual jecties
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/objectives/cookjectie.dm
  code/datums/gamemode/role/jectiecooker.dm
  code/datums/gamemode/role/role.dm
  code/datums/recipe.dm
  code/game/machinery/kitchen/microwave.dm
  code/modules/food/recipes_microwave.dm
  vgstation13.dme
Labels: Content, 100% tested

#32580 Human zombies can force open doors
  code/modules/mob/death.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: Balance

#32596 Refactoring Invisibility and Transparency for specific objs and mobs
  __DEFINES/invisibility_defines.dm
  code/datums/gamemode/role/vampire_role.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/objects/items/potions.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/spells/general/cloak.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
Labels: System, ❤️ Quality of Life ❤️

#32604 Telepathy Refactor and Changes
  __DEFINES/setup.dm
  code/datums/outfit/medical.dm
  code/game/centcomm_orders/orders_medical.dm
  code/game/dna/genes/powers.dm
  code/game/gamemodes/setupgame.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/mob/living/carbon/racial_spells.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/carbon/species_powers.dm
  code/modules/spells/targeted/targeted.dm
  code/modules/virus2/effect/stage_3.dm
  maps/randomvaults/dungeons/research.dmm
  vgstation13.dme
Labels: System, ❤️ Quality of Life ❤️

#32605 Makes some broken away missions a bit less broken
  __DEFINES/setup.dm
  code/__HELPERS/unsorted.dm
  code/modules/awaymissions/_awaymission.dm
  code/modules/events/ion_storm.dm
  config-example/custom_items.txt
  maps/RandomZLevels/broken/challenge.dmm
  maps/RandomZLevels/broken/jungle.dmm
  maps/RandomZLevels/broken/spacebattle.dmm
  maps/RandomZLevels/broken/zresearchlabs.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/fileList.txt
  maps/RandomZLevels/leviathan.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/unused/backup/Academy.dmm
  maps/RandomZLevels/unused/example.dmm
  maps/RandomZLevels/unused/leviathan.dmm
  maps/randomvaults/objects.dm
  maps/rust_test.dmm
  maps/test_asteroid.dmm
Labels: Bug / Fix, Content, Tweak, WiP

#32566 Hiding tiny items under floortiles
  __DEFINES/planes+layers.dm
  code/game/objects/items.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/gum.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/dice.dm
  code/game/objects/items/weapons/grenades/clowngrenade.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/shard.dm
  code/game/objects/items/weapons/soap.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/turfs/simulated/floor.dm
  code/modules/assembly/mousetrap.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Content

#32608 Zombie buttons
  __DEFINES/spell_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
  code/modules/mob/living/simple_animal/hostile/necro_powers.dm
  code/modules/spells/helpers.dm
  vgstation13.dme
Labels: UI

#32635 Fixes Saucer Drone Runtime
  code/modules/projectiles/projectile.dm
Labels: Bug / Fix, Hotfix

#32636 Fixes Missing Wallet ID Sprites
  icons/obj/wallet.dmi
Labels: Bug / Fix, Hotfix

#32637 Squashes Stray Camera (Mothership Lab Vault)
  maps/randomvaults/mothership_lab.dmm
Labels: Bug / Fix, Hotfix

#32629 A Few More Mothership Lab Vault Tweaks
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/mothership_lab.dmm
Labels: Mapping (Vault :question:), Tweak

#32623 Allows initializing turfs with miscellaneous gases
  code/ZAS/Turf.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
Labels: Bug / Fix

#32625 Fixes items not being removed from inventory slots on bite-harm intent
  code/game/objects/breakable.dm
Labels: Bug / Fix

#32643 Fixes Mothership Boots (Mothership Lab Vault)
  code/modules/awaymissions/corpse.dm
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/dungeons/research.dmm
  maps/randomvaults/mothership_lab.dm
  maps/randomvaults/mothership_lab.dmm
Labels: Bug / Fix, Tweak

#32649 Maybe Fix A Raider Tunnel Depressurization Issue (Mothership Vault)
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/mothership_lab.dm
  maps/randomvaults/mothership_lab.dmm
Labels: Mapping (Vault :question:), Tweak

#32648 Adds Screwtoggle to Trade Shuttle Computer
  code/game/shuttles/trade.dm
Labels: Bug / Fix

#32639 Railings
  __DEFINES/planes+layers.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/structures/railings.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  icons/obj/structures/railing.dmi
  vgstation13.dme
Labels: Sprites, Content

#32519 Luck
  __DEFINES/setup.dm
  code/game/jobs/job/civilian.dm
  code/game/machinery/computer/shuttle_computers.dm
  code/game/machinery/computer/slot_machine.dm
  code/game/machinery/vending.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/structures/mirror.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/events/radiation_storm.dm
  code/modules/games/cards/lotto.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seeds.dm
  code/modules/luck/luck.dm
  code/modules/luck/luck_blesscurse.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/obj/hydroponics/clover.dmi
  vgstation13.dme
Labels: Content, System

#32650 Fixes non-constant expressions in switch-block if-statements
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/vehicles/clowncart.dm
  code/modules/clothing/suits/plate_carrier.dm
  code/modules/mob/living/silicon/robot/robot_hud.dm
  code/modules/organs/internal/lungs/lung.dm
Labels: Bug / Fix

#32634 Rudimentary thrown food and drink targeted reagent reaction
  code/game/atoms_movable.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/egg.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Balance, Tweak

#32633 Biting and kicking while handcuffed but not being pulled, grabbed, or buckled.
  code/_onclick/other_mobs.dm
  code/controllers/configuration.dm
Labels: Content

#32662 Fixes plant harvesting runtime
  code/modules/hydroponics/seed_datums.dm
Labels: Hotfix

#32618 Electromagnetic Hypersensitivity
  __DEFINES/setup.dm
  code/game/dna/genes/disabilities.dm
  code/game/gamemodes/setupgame.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
Labels: Content

#32658 Some Ayy Mask Fixes And CMO Hud Fits More Species
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/masks/gasmask.dm
  icons/mob/species/grey/eyes.dmi
  icons/mob/species/grey/masks.dmi
  icons/mob/species/insectoid/eyes.dmi
  icons/mob/species/vox/eyes.dmi
Labels: Sprites

#32660 Replaces glass blocking open spaces with railings on multi-Z maps
  maps/test_euclidean.dmm
  maps/test_multiz.dmm
  maps/tgstation-snow.dmm
Labels: Mapping (General :world_map:)

#32668 Various, primarily muzzle-related tweaks and fixes.
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/clothing/clothing.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/stripping.dm
  code/modules/projectiles/guns/projectile/constructable/tomahawk.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/monkey.dmi
Labels: Bug / Fix, Tweak

#32682 Mushroom Fixes
  code/game/dna/genes/powers.dm
  code/modules/mob/living/carbon/species.dm
Labels: Bug / Fix

#32677 Fixes railings allowing clipping into walls
  code/game/objects/structures/railings.dm
Labels: 100% tested

#32688 The Walls, They Crumble (Mothership Lab Vault)
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/dungeons/research.dmm
  maps/randomvaults/mothership_lab.dmm
Labels: Bug / Fix, Hotfix, Mapping (Vault :question:)

#32689 Changes the names of the raider loadout boxes.
  code/datums/gamemode/factions/vox_shoal.dm
Labels: Tweak

#32666 Suicide act improvements sans controversy
  code/game/machinery/machinery.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/weapons/explosives.dm
  code/game/objects/items/weapons/grenades/ghettobomb.dm
  code/game/verbs/suicide.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Content, 100% tested

#32697 Clownnonball Fix?
  code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
Labels: Bug / Fix, Hotfix

#32696 Resmooths Ayy Vault Walls (Mothership Lab Vault)
  code/game/smoothwall.dm
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/dungeons/research.dmm
  maps/randomvaults/mothership_lab.dm
  maps/randomvaults/mothership_lab.dmm
Labels: Bug / Fix, Tweak

#32700 Fixed runtime errors related to muzzles
  __DEFINES/_macros.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/factions/legacy_cult/ritual.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/spells/spell_code.dm
Labels: Bug / Fix

#32698 Fixed throw_impact runtime
  code/game/atoms_movable.dm
Labels: Bug / Fix, Runtime Log

#32701 Runtime fix
  code/modules/virus2/effect/stage_3.dm
Labels: Bug / Fix, Hotfix

#32706 Remove greytide implant issue
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/types/greytide_implant.dm
Labels: Feature Loss

#32672 Smoother roid floors
  __DEFINES/planes+layers.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/rock_overlay.dmi
Labels: Sprites

#32594 We have you surrounded, come drink your corn syrup
  __DEFINES/reagents.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Controversial, Content

#32708 Fixes camera bug ventcrawling.
  code/_onclick/ventcrawl.dm
Labels: Bug / Fix
