Repository vgstation-coders/vgstation13, pull requests merged in 2022-08, with the labels that each got.

#33012 Fixes Rare NanoUI Bug
  nano/js/nano_template.js
Labels: Bug / Fix, UI

#32946 Limits challengers to only appear at a minimum of about 20 players
  code/datums/gamemode/dynamic/dynamic_rulesets.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Emoji This :+1: :-1:

#32955 Biogenerators can make butter.
  code/game/machinery/biogenerator.dm
Labels: Emoji This :+1: :-1:

#32957 Increase Max Explosion Radius
  __DEFINES/setup.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/weapons/dice.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/projectiles/guns/projectile/constructable/blastcannon.dm
  config-example/game_options.txt
Labels: Balance

#32967 fix icon state of syndie football helmet
  icons/mob/head.dmi
Labels: Bug / Fix, Sprites

#32974 Hydroponics bugfixes
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Hotfix

#32999 Fixes autolathes needing wood to make spades.
  code/modules/mining/mine_items.dm
Labels: Bug / Fix

#33000 Adds hatchets to the autolathe.
  code/game/machinery/autolathe.dm
  code/game/objects/items/weapons/switchtool.dm
  code/modules/hydroponics/hydro_tools.dm
  icons/obj/weapons.dmi
Labels: Content

#33001 Adds some cave clothing in xeno wardrobes
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
Labels: 100% tested

#33042 Makes cauldrons/barrels deconstructable with welders/crowbars
  code/modules/reagents/reagent_dispenser.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#33046 typofix and (minor) bugfix
  code/game/machinery/kitchen/snackbarmachine.dm
  code/modules/hydroponics/seed_machines.dm
Labels: Bug / Fix, Grammar / Formatting

#33069 Fixes the antichrist helmet.
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Hotfix, Sprites

#32987 2 new plants for material production: Shardlime and Purple Shardlime
  code/modules/hydroponics/seeds.dm
  icons/obj/hydroponics/purpleshardlime.dmi
  icons/obj/hydroponics/shardlime.dmi
Labels: Content

#33024 Ectoplasm now grants spookyvision.
  code/modules/reagents/Chemistry-Reagents.dm
Labels: 100% tested

#33070 Delete linearclown.dm
  maps/linearclown.dm
Labels: Hotfix

#33078 move radio
  code/controllers/mc/master.dm
  code/controllers/subsystem/init/more_init_stuff.dm
Labels: Hotfix

#33067 Exosuit clamp and drill effects
  code/game/mecha/equipment/tools/tools.dm
Labels: Sound, 100% tested

#33071 Fixes the new NanoUI bug that the last fix caused
  nano/js/nano_template.js
Labels: Bug / Fix, Hotfix, help wanted

#33087 Fixes Mothership Lab Tile Exposed To Space
  maps/randomvaults/mothership_lab.dmm
Labels: Bug / Fix

#33083 Weeds
  code/modules/hydroponics/hydro_tray.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_plantkiller.dm
  code/modules/virus2/effect/stage_2.dm
Labels: Hotfix

#33091 [Revival] Inflatable Dispensers can hold shelters.
  code/game/objects/items/robot/robot_items/robot_inflatable_dispenser.dm
Labels: 100% tested

#33088 Ayy Leader Spacewalk Fix
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
Labels: Tweak

#32966 Weekend Primetime NO HOLDS BARRED
  code/modules/html_interface/voting/voting.dm
Labels: ⛔ Requires Server Vote ⛔

#33090 Mothership Lab Hobo Enrichment and Other Tweaks
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/dungeons/research.dmm
Labels: Mapping (Vault :question:), Tweak

#33121 fix rates for voracious
  code/modules/hydroponics/hydro_tray_process.dm
Labels: Hotfix

#33107 Re-adds flashbang protection to hos/warden hats
  code/modules/clothing/head/jobs.dm
Labels: Balance

#33109 Add log for mmi/posibrain being put inside a mech
  code/game/mecha/mecha.dm
Labels: Logging / Administration

#33122 Grey jumpsuits dissolvable in water
  maps/randomvaults/mothership_lab.dm
Labels: Hotfix

#33112 Remaps the Dojo to actually be a Dojo
  icons/turf/floors.dmi
  icons/turf/walls.dmi
  maps/misc/dojo.dmm
Labels: Sprites

#33144 Move .PostSetup() to after characters are equipped
  code/game/gamemodes/gameticker.dm
Labels: Hotfix

#33164 Fixes Mobs With The OPEN_DOOR_SMART Flag Killing Themselves
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bug / Fix
