Repository vgstation-coders/vgstation13, pull requests merged in 2022-01, with the labels that each got.

#31682 Fixes lone lattice icon
  icons/obj/smoothlattice.dmi
Labels: Sprites

#31754 fixes wiki links for time agent and pulse demon
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/role/time_agent.dm
  code/modules/client/preferences.dm
Labels: Hotfix

#31757 Standardises time-based reagent effects
  __DEFINES/_macros.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Consistency Issue, Tweak

#31765 Revert "Make end-round credits invisible only after init is done"
  code/modules/client/client procs.dm
  code/world.dm
Labels: Secret repo conflict.

#31705 Adds "Curator" as a librarian alt-title.
  code/datums/outfit/civilian.dm
  code/game/jobs/job/civilian.dm
Labels: Content, Role Datums

#31790 More time agent fixes
  code/datums/gamemode/objectives/target/erase.dm
  code/datums/gamemode/objectives/target/locate.dm
  code/datums/gamemode/objectives/target/rearrange.dm
  code/datums/gamemode/objectives/time_agent_extract.dm
  code/datums/gamemode/role/time_agent.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Bug / Fix, Gameplay / Gamemode, Role Datums, Tweak

#31756 Turrets can shoot blobs
  code/game/machinery/portable_turret.dm
  code/game/machinery/turrets.dm
Labels: Balance, Emoji This :+1: :-1:

#31748 Cruciatus' Spiritbreaker increases with potency
  code/modules/hydroponics/seeds.dm
Labels: ❤️ Quality of Life ❤️, Consistency Issue

#31732 Adminspawn-only proc call gun
  code/game/sound.dm
  code/modules/admin/admin.dm
  code/modules/projectiles/guns/procgun.dm
  code/modules/projectiles/guns/projectile/roulette.dm
  icons/obj/projectiles_experimental.dmi
  sound/weapons/procgun1.ogg
  sound/weapons/procgun2.ogg
  vgstation13.dme
Labels: Content, Logging / Administration

#31801 Sends transaction info to PDAs as alert to user with banking app
  code/controllers/subsystem/supply_shuttle.dm
  code/game/machinery/ATM.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/games/spess pets.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/Economy/Accounts.dm
  code/modules/Economy/Wages.dm
  code/modules/Economy/utils.dm
  code/modules/events/money_hacker.dm
  code/modules/events/money_lotto.dm
  code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_pay2use.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#31719 Changeling Balance
  __DEFINES/invisibility_defines.dm
  code/datums/gamemode/changeling.dm
  code/datums/gamemode/powers/changeling.dm
  code/datums/gamemode/role/changeling.dm
  code/game/gamemodes/changeling/changeling_procs.dm
  code/game/gamemodes/changeling/horror.dm
  code/game/machinery/doors/door.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/spells/changeling/absorb_dna.dm
  code/modules/spells/changeling/hivedownload.dm
  code/modules/spells/changeling/hiveupload.dm
  code/modules/spells/changeling/horrorform.dm
  code/modules/spells/changeling/regenerative_stasis.dm
  code/modules/spells/changeling/split.dm
  code/modules/spells/changeling/stings/fat.dm
  code/modules/spells/changeling/voicechange.dm
  vgstation13.dme
Labels: Gameplay / Gamemode

#31812 curator wood and beret fix
  code/datums/outfit/civilian.dm
  code/game/objects/items/stacks/sheets/bigstacks.dm
Labels: Hotfix

#31815 Botanist belts
  code/datums/outfit/civilian.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/awaymissions/corpse.dm
  icons/mob/belt.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/cuffs.dmi
  icons/obj/cuffs_monkey.dmi
Labels: Sprites, Content

#31823 Plague mouse buff
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Gameplay / Gamemode

#31827 New karmotrine drink: Changeling Stab
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: Sprites, Content

#31829 No-fruit juice and phazon salt random chemical reaction
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content

#31830 SCP-294 tweaks and improvements
  code/game/machinery/scp_294.dm
  nano/templates/scp_294.tmpl
Labels: Content, Tweak

#31839 Fixes time agent locate objective attempting to create duplicate nuke disk
  code/datums/gamemode/objectives/target/locate.dm
Labels: Bug / Fix

#31859 Fixes particle shifting
  code/modules/power/singularity/particle_accelerator/particle.dm
Labels: Bug / Fix

#31860 Fixes light replacer boxes
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/weapons/storage/boxes.dm
Labels: Bug / Fix

#31863 removes sleeps from coinflipping
  code/modules/mining/ores_coins.dm
Labels: File Cleanup

#31832 Fixes power machinery terminals not shuttle rotating (and a runtime)
  code/modules/power/terminal.dm
Labels: Bug / Fix, Runtime Log

#31840 Body archive mind transfer on spawning option.
  code/__HELPERS/game.dm
  code/datums/body_archive.dm
  code/datums/datumvars.dm
  code/modules/admin/body_archive_panel.dm
  code/modules/admin/topic.dm
Labels: ❤️ Quality of Life ❤️, Logging / Administration

#31713 2 painting typo fixes
  code/modules/painting/paintings_custom.dm
Labels: Grammar / Formatting

#31878 Fixes remote explosive implants not showing up
  code/game/machinery/computer/prisoner.dm
  code/game/objects/items/weapons/implants/types/chemical_implant.dm
  code/game/objects/items/weapons/implants/types/explosive_implant.dm
Labels: Bug / Fix, Oversight

#31876 Logs spawning of ghost roles
  code/game/machinery/mommi_spawner.dm
  code/modules/mob/dead/observer/verbs.dm
  code/modules/mob/new_player/new_player.dm
Labels: Logging / Administration

#31867 Fixed that one error about `dependencies.sh` that prevented using build.bat
  .gitignore
  .vscode/tasks.json
  BUILD.cmd
  bin/tgui-bench.cmd
  code/modules/client/global cache.dm
  dependencies.sh
  tgui/packages/tgfont/static/tgfont.css
  tgui/packages/tgfont/static/tgfont.eot
  tgui/packages/tgfont/static/tgfont.woff2
  tgui/yarn.lock
  tools/build/build.js
  tools/build/juke/index.d.ts
  tools/build/juke/index.js
Labels: Bug / Fix, System

#31755 High shovel
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/game/objects/items/weapons/butterfly.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/tables_racks.dm
  code/game/sound.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/simple_animal/hostile/viscerator.dm
Labels: Content, 100% tested

#31687 Grues Revisited
  __DEFINES/_macros.dm
  __DEFINES/reagents.dm
  __DEFINES/role_datums_defines.dm
  __DEFINES/setup.dm
  __DEFINES/spell_defines.dm
  __DEFINES/stylesheet.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/spell_screen_objects.dm
  code/_onclick/ventcrawl.dm
  code/controllers/configuration.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/objectives/grue.dm
  code/datums/gamemode/role/grue.dm
  code/datums/helper_datums/butchering.dm
  code/game/dna/dna_modifier.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/effects/gibs.dm
  code/modules/client/preferences.dm
  code/modules/medical/autopsy.dm
  code/modules/medical/computer/cloning.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/racial_spells.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/bees/bees_species.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/grue_egg.dm
  code/modules/mob/living/simple_animal/hostile/grue.dm
  code/modules/mob/living/simple_animal/hostile/grue_egg.dm
  code/modules/mob/living/simple_animal/hostile/grue_powers.dm
  code/modules/mob/living/simple_animal/hostile/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulsedemon_powers.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/organs/internal/eyes/eyes.dm
  code/modules/organs/organ_objects.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/unit_tests/icons.dm
  goon/browserassets/css/browserOutput.css
  html/changelogs/Hinaichigo.yml
  icons/logos.dmi
  icons/mob/grue.dmi
  icons/mob/screen1_grue.dmi
  icons/mob/screen_spells.dmi
  icons/obj/food.dmi
  sound/effects/grue_burn.ogg
  sound/effects/grue_moult.ogg
  vgstation13.dme
Labels: Content, Gameplay / Gamemode, WiP

#31894 grue darkmode fix
  goon/browserassets/css/browserOutput_dark.css
Labels: Hotfix

#31891 Changeling fixes
  code/datums/gamemode/role/changeling.dm
  code/game/gamemodes/changeling/changeling_procs.dm
  code/modules/spells/changeling/absorb_dna.dm
  code/modules/spells/changeling/changeling_spell.dm
  code/modules/spells/changeling/hivedownload.dm
  code/modules/spells/changeling/hiveupload.dm
  code/modules/spells/changeling/regenerative_stasis.dm
  code/modules/spells/changeling/stings/dnaextract.dm
  code/modules/spells/changeling/transform.dm
  code/modules/spells/changeling/voicechange.dm
Labels: Bug / Fix

#31850 adds sound effects to surgery steps
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/game/objects/items.dm
  code/game/objects/items/soulstone.dm
  code/game/objects/items/stacks/cable.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/shard.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/assembly/mousetrap.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/surgery/butt.dm
  code/modules/surgery/eye.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/slimes.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/tooth.dm
  sound/items/bonegel.ogg
  sound/items/bonesetter.ogg
  sound/items/cautery.ogg
  sound/items/circularsaw.ogg
  sound/items/fixovein.ogg
  sound/items/hatchetsurgery.ogg
  sound/items/hemostat.ogg
  sound/items/hemostatdig.ogg
  sound/items/retractor.ogg
  sound/items/scalpel.ogg
  sound/items/surgicaldrill.ogg
Labels: Sound

#31947 Fixes IED construction runtime
  code/game/objects/items/weapons/grenades/ghettobomb.dm
Labels: Runtime Log

#31934 PA interaction with SM
  code/modules/power/singularity/particle_accelerator/particle.dm
Labels: Tweak

#31918 Fixed Alien HUD (can see in the dark)
  code/datums/gamemode/role/catbeast.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/alien/humanoid/life.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/projectiles/projectile/energy.dm
Labels: Bug / Fix, Gameplay / Gamemode, Unatomic Uncle

#31909 Vox chicken foods: Vox Nuggets and Vox Drumsticks
  code/game/machinery/kitchen/processor.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/carbon/monkey/vox.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  icons/obj/food.dmi
Labels: Oversight, Consistency Issue

#31880 Adds missing items to botanist belt acceptance
  code/game/objects/items/weapons/storage/belt.dm
Labels: Bug / Fix

#31874 Fixes roundstart silicons keeping form as wizard
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix, Gameplay / Gamemode, Role Datums

#31926 Pax bans
  __DEFINES/setup.dm
  code/modules/admin/admin.dm
  code/modules/admin/banpax.dm
  code/modules/admin/topic.dm
  code/modules/mob/mob.dm
  code/world.dm
  vgstation13.dme
Labels: Content, Logging / Administration, 100% tested

#31950 Grue Directional Sprites
  icons/logos.dmi
  icons/mob/grue.dmi
  icons/mob/screen_spells.dmi
Labels: Sprites

#31946 Ling balance
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/datums/gamemode/powers/changeling.dm
  code/datums/gamemode/role/changeling.dm
  code/modules/spells/changeling/absorb_dna.dm
  code/modules/spells/changeling/changeling_spell.dm
  code/modules/spells/changeling/horrorform.dm
  code/modules/spells/changeling/split.dm
Labels: Balance

#31949 Attack log admin message tweaks
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Logging / Administration

#31951 Fixes PDA uplinks not opening
  code/game/objects/items/devices/PDA/apps/messenger.dm
Labels: Bug / Fix, 100% tested
