Repository vgstation-coders/vgstation13, pull requests merged in 2022-11, with the labels that each got.

#33637 Moves in-hand quick equip priority to bottom
  code/modules/mob/mob.dm
Labels: Tweak

#33638 Fixes broken baguloosing
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bluespace.dm
  code/modules/mob/living/simple_animal/hostile/grinch.dm
Labels: Bug / Fix, 100% tested

#33634 Fixes full windows not smoothing when anchored
  code/game/objects/structures/window.dm
Labels: Bug / Fix

#33632 Pajamas Fit Vox
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/uniform.dmi
Labels: Sprites

#33614 bomberman arenas can now be called even after the round has ended
  code/modules/mob/dead/observer/verbs.dm
Labels: Logging / Administration

#33666 fix false alarm debug message for mushroom people
  code/modules/client/preferences.dm
Labels: Bug / Fix

#33639 Swaps gunk kabob and roaches on a stick recipes.
  code/modules/food/recipes_microwave.dm
Labels: Emoji This :+1: :-1:

#33664 Allows syndicate chems to convert their normal equivalents
  code/datums/uplink_item.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content, Tweak

#33328 Buddha mode + Hell
  __DEFINES/setup.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/init/map.dm
  code/datums/datumvars.dm
  code/datums/map_elements.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/dice.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/structures/dorfpod.dm
  code/game/turfs/unsimulated/floor.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/medical/cloning.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/alien/death.dm
  code/modules/mob/living/carbon/alien/humanoid/death.dm
  code/modules/mob/living/carbon/alien/humanoid/life.dm
  code/modules/mob/living/carbon/alien/larva/death.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/brain/death.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/complex/life.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life/handle_regular_status_updates.dm
  code/modules/mob/living/carbon/monkey/death.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/slime/death.dm
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/death.dm
  code/modules/mob/living/silicon/decoy/death.dm
  code/modules/mob/living/silicon/pai/death.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/simple_animal/hostile/shade.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/organs/organ_external.dm
  code/modules/randomMaps/vaults.dm
  config-example/config.txt
  maps/_map.dm
  maps/misc/HELL.dmm
Labels: Content, Logging / Administration

#33682 Hobo shack piping fixes
  maps/misc/hoboshack.dmm
Labels: Mapping (General :world_map:)

#33647 Should fix most issues with bots.
  __DEFINES/setup.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/floorbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/bots/secbot.dm
  code/game/machinery/navbeacon.dm
Labels: Bug / Fix

#33677 Makes diagonal shuttle walls show up on mesons
  code/game/objects/structures/false_walls.dm
  code/game/turfs/simulated/shuttle.dm
  code/modules/clothing/glasses/scanners.dm
Labels: Bug / Fix

#33654 Reduce false positive spam from ban evasion alert
  goon/code/datums/browserOutput.dm
Labels: Logging / Administration

#33672 Fixes rune drawing offset
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
Labels: Bug / Fix

#33673 Wall rot event improvements
  code/modules/events/wallrot.dm
Labels: Bug / Fix, Tweak

#33651 Alternate dimension vendor large artifact find
  code/game/machinery/machinery.dm
  code/game/machinery/vending.dm
  code/modules/events/old_vendotron_event/old_vendotron.dm
  code/modules/reagents/reagent_containers/food/snacks/egg.dm
  code/modules/research/xenoarchaeology/artifact/artifact.dm
  code/modules/research/xenoarchaeology/artifact/artifact_vendor.dm
  vgstation13.dme
Labels: Content

#33605 Dice Additions: Dice Cups, Fudge Dice, Bags of d6
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/dice.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  icons/obj/dice.dmi
Labels: Content, 100% tested

#32761 Space Hogs
  code/defines/obj/weapon.dm
  code/modules/mob/living/simple_animal/hostile/hog.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/mob/hog.dmi
  vgstation13.dme
Labels: Content

#33153 Scale miner output with power
  code/ZAS/_gas_mixture.dm
  code/game/machinery/atmoalter/gas_mine.dm
Labels: Balance, Tweak

#33688 Auto-clothing items
  code/datums/supplypacks.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/stacks/packagewrap.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/research/mechanic/flatpack.dm
  code/modules/trader/crates/alcatrazfour.dm
Labels: Content

#33710 Gas Miner Hotfix
  code/game/machinery/atmoalter/gas_mine.dm
Labels: Hotfix, 100% tested

#33674 Creates new type of asteroid boss
  __DEFINES/turfs.dm
  code/datums/helper_datums/butchering.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Content

#33694 Makes R&D stock parts crate contain correct amount of assembly parts
  code/datums/supplypacks.dm
Labels: Tweak

#33697 In-hand Jumpsuit Adjustments
  code/modules/clothing/under/jobs/engineering.dm
  icons/mob/in-hand/left/items_lefthand.dmi
  icons/mob/in-hand/right/items_righthand.dmi
Labels: Sprites, Oversight, Consistency Issue

#33708 Fix network_expansion() for pressure valves
  code/ATMOSPHERICS/components/trinary_devices/pressure_valve.dm
Labels: Bug / Fix

#33715 Windoor opening time method change
  code/game/machinery/doors/windowdoor.dm
Labels: Consistency Issue, Tweak
