Repository vgstation-coders/vgstation13, pull requests merged in 2022-12, with the labels that each got.

#33669 Attempt at fixing arcane door nerve gas
  code/game/machinery/doors/door.dm
Labels: Bug / Fix, Performance

#33726 fixes some missing food names
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix, Hotfix

#33733 Fixes a Dice Cup Runtime
  code/game/objects/items/weapons/storage/firstaid.dm
Labels: Bug / Fix, 100% tested

#33735 Power monitor demand fixes
  code/game/machinery/antiquemattersynth.dm
  code/game/machinery/shieldgen.dm
  code/modules/power/components.dm
Labels: Bug / Fix

#33738 Ensures the antique mattersynth's power priority is locked to the lowest level
  code/game/machinery/antiquemattersynth.dm
  code/modules/power/components.dm
  code/modules/power/power.dm
  tgui/packages/tgui/interfaces/PowerMonitor.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Exploitable

#33741 Vampire deadchat
  code/datums/gamemode/role/vampire_role.dm
  code/modules/mob/say.dm
Labels: Bug / Fix, Hotfix

#33742 Fixes magic door air and other minor changes
  code/ZAS/Zone.dm
Labels: Bug / Fix

#33753 Updates a bunch of actions in the CI
  .github/workflows/ci.yml
Labels: Automation/CI

#33765 fix tertiary languages not working
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix

#33470 Adds Portable Crew Monitoring Console for Paramedics
  code/datums/outfit/medical.dm
  code/game/objects/items/devices/pcmc.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/suits/jobs.dm
  icons/mob/belt.dmi
  icons/mob/belt_mirror.dmi
  icons/mob/in-hand/left/pcmc.dmi
  icons/mob/in-hand/right/pcmc.dmi
  icons/obj/pda.dmi
  tgui/packages/tgui/interfaces/PCMC.js
  tgui/public/tgui.bundle.js
  vgstation13.dme
Labels: Controversial, Sprites, Content, 100% tested, Secret repo conflict.

#33690 pulse demon tweaks
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
Labels: Balance, Emoji This :+1: :-1:

#33763 Turk roaches from Gunk Soup Embassy now lay turk eggs.
  code/modules/mob/living/simple_animal/roach.dm
  code/modules/reagents/reagent_containers/food/snacks/eggs/roach.dm
  icons/obj/food.dmi
Labels: Emoji This :+1: :-1:

#33779 necrovision runtime
  code/modules/mob/living/simple_animal/hostile/necro.dm
Labels: Hotfix

#33790 Brig Medics spawn with medic armor instead of paramedic vest
  code/datums/outfit/medical.dm
Labels: Tweak

#33819 Sanitize tcomms machine inputs
  code/game/machinery/telecomms/machine_interactions.dm
Labels: Exploitable

#33820 sanitize lots of inputs for lots of things!
  code/_onclick/mindUI/blob.dm
  code/datums/gamemode/role/malf/hackabilities.dm
  code/game/gamemodes/blob/powers.dm
  code/game/machinery/ATM.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/scp_294.dm
  code/game/machinery/status_display.dm
  code/game/machinery/telecomms/logbrowser.dm
  code/game/machinery/telecomms/telemonitor.dm
  code/game/machinery/telecomms/traffic_control.dm
  code/game/machinery/vending.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/devices/beacon_designator.dm
  code/game/objects/items/devices/reportintercom.dm
  code/game/objects/items/robot/robot_items/robot_pen.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/structures/musician.dm
  code/game/objects/structures/vehicles/clowncart.dm
  code/game/objects/structures/vehicles/secway.dm
  code/game/verbs/suicide.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/power/rust/fuel_control.dm
  code/modules/telesci/gps.dm
  code/modules/telesci/rcs.dm
Labels: Exploitable

#33809 adds logging to admins accessing logs; better log access handling
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/getlogs.dm
  code/world.dm
Labels: Logging / Administration

#33857 remove admin immunity to view reset called in Login()
  code/modules/mob/login.dm
Labels: Logging / Administration

#33836 Building and upgrading artifact scanners and harvesters
  code/game/machinery/constructable_frame.dm
  code/modules/research/designs/boards/machine_science.dm
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
  code/modules/research/xenoarchaeology/machinery/artifact_harvester.dm
  code/modules/research/xenoarchaeology/machinery/artifact_scanner.dm
Labels: Content, 100% tested

#33824 Applies overdark to everyone and moves some planes
  __DEFINES/planes+layers.dm
  code/game/machinery/station_map.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/unsimulated/floor.dm
  code/modules/clothing/glasses/scanners.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/grue.dm
  code/modules/mob/login.dm
Labels: Bug / Fix, System

#33818 sleeping people no longer considered dying on admin roundstart logout report
  code/datums/gamemode/misc_gamemode_procs.dm
Labels: Logging / Administration

#33864 artifact analyzer ghosthands
  code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm
Labels: Bug / Fix

#33705 Ullapool Caber, a new Syndicate weapon.
  code/datums/uplink_item.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/swords_axes.dmi
  icons/obj/weapons.dmi
  sound/misc/caber_hitsound.ogg
  sound/misc/demomankablooie.ogg
  sound/misc/demomankaboom.ogg
  sound/misc/tf2critsound.ogg
Labels: Controversial, Content

#33876 Fixes cam console offset, allegedly
  code/_onclick/hud/map_popups.dm
Labels: Bug / Fix, 0% tested

#33871 Fixes various layering issues
  __DEFINES/planes+layers.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/game/objects/structures/cage.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/glasses/scanners.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/spells/aoe_turf/fall.dm
Labels: Bug / Fix

#33840 SAMMI tweaks and changes
  code/modules/mob/living/silicon/mommi/login.dm
  code/modules/mob/living/silicon/mommi/mommi_subtypes/sammi.dm
Labels: ❤️ Quality of Life ❤️, Tweak, Emoji This :+1: :-1:

#33893 Fixes Maria's Hive telecrystal ore leaving a regular asteroid tile behind, instead of a corrupted tile.
  code/modules/mining/mine_turfs.dm
Labels: Bug / Fix, Hotfix

#33889 Water cooler tops are now transparent and show reagent volume
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/vending.dmi
Labels: Sprites

#33884 Possible hell population syntax fix
  code/modules/randomMaps/vaults.dm
Labels: Bug / Fix

#33890 Auto-make option on upgraded microwaves
  code/game/machinery/kitchen/microwave.dm
  code/modules/research/rdmachines.dm
Labels: Content

#33867 Personal airbags now prevent fall damage
  code/ZAS/Airflow.dm
  code/modules/multiz/fall_hit.dm
Labels: Content

#33900 Fixes manifold nodes
  code/ATMOSPHERICS/atmospherics.dm
Labels: Bug / Fix, Hotfix

#33845 further improvements to sortmob proc
  code/__HELPERS/unsorted.dm
Labels: Bug / Fix

#33866 Makes emote keys less case sensitive
  code/modules/mob/emote.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#33911 Combat borg mobility module sprite fix
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Bug / Fix
