Repository vgstation-coders/vgstation13, pull requests merged in 2022-07, with the labels that each got.

#32799 pulse demon SMES and APC draining tweak
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
Labels: Gameplay / Gamemode

#32861 Faster server startup
  code/ATMOSPHERICS/components/binary_devices/valve.dm
  code/__HELPERS/logging.dm
  code/controllers/mc/master.dm
  code/controllers/mc/subsystem.dm
  code/controllers/subsystem/objects.dm
  code/game/area/areas.dm
  code/game/machinery/alarm.dm
  code/game/machinery/doors/windowdoor.dm
  code/modules/awaymissions/maploader/reader.dm
  code/modules/power/antimatter/shielding.dm
  code/modules/randomMaps/vaults.dm
Labels: Performance

#32863 PDA power monitor fixes
  code/__HELPERS/text.dm
  code/game/objects/items/devices/PDA/cart/engineering.dm
Labels: Bug / Fix, UI

#32835 Sorts R&D designs by name
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
Labels: ❤️ Quality of Life ❤️, Tweak, Emoji This :+1: :-1:

#32852 Vampire Tweaks
  code/datums/gamemode/powers/vampire.dm
  code/datums/gamemode/role/vampire_role.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/spells/aoe_turf/screech.dm
  code/modules/spells/general/menace.dm
  code/modules/spells/general/shapeshift.dm
  code/modules/spells/vampire_helpers.dm
  vgstation13.dme
Labels: Gameplay / Gamemode, Emoji This :+1: :-1:

#32800 Adds console screens (plus new upgrade types) to protolathes
  code/game/dna/dna_modifier.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/game/objects/items/weapons/storage/RPED.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/events/old_vendotron_event/old_vendotron.dm
  code/modules/mining/surprises/tg.dm
  code/modules/research/designs/stock_parts.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  icons/obj/stock_parts.dmi
Labels: Sprites, Content, ❤️ Quality of Life ❤️

#32830 Replaces money lotto event with an actual six number lotto
  code/__HELPERS/maths.dm
  code/controllers/subsystem/init/persistence_misc.dm
  code/datums/helper_datums/command_alerts.dm
  code/game/machinery/vending.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/events/money_lotto.dm
Labels: Content, 100% tested

#32855 Ghosting refactor
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/verbs.dm
  interface/interface.dm
  interface/skin.dmf
  interface/skin_azerty.dmf
Labels: ❤️ Quality of Life ❤️, 100% tested, Tweak

#32858 Vampires can listen to the dead
  code/datums/gamemode/role/vampire_role.dm
  code/modules/mob/say.dm
Labels: Content, IT'S A FEAAAATUUUUREEEEEEEEE

#32869 Fixes equipping special outfits with ID runtime
  code/datums/outfit/outfit.dm
Labels: Bug / Fix, Runtime Log, 100% tested

#32870 Staff of Necromancy tweaks
  code/game/objects/items/potions.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/virus2/effect/stage_4.dm
Labels: Bug / Fix, Tweak

#32873 Fixes Single Play Mode (Repeat the same song) on Jukes
  code/modules/media/jukebox.dm
Labels: Bug / Fix

#32874 Standardizes Capitalization of Chemicals
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Consistency Issue, Tweak

#32886 fixes missing period on grand slam centcomm alert
  code/datums/helper_datums/command_alerts.dm
Labels: Hotfix, Grammar / Formatting

#32885 Fixes tracking glasses icon timing and adds a mobsprite.
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Hotfix

#32884 New ways to get blood as vampires
  code/datums/gamemode/powers/vampire.dm
  code/datums/gamemode/role/vampire_role.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/spells/general/silentbite.dm
  vgstation13.dme
Labels: Content, Role Datums

#32878 Explosion and Initialization Performance
  __DEFINES/global.dm
  __DEFINES/tick.dm
  code/__HELPERS/unsorted.dm
  code/controllers/mc/master.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/empulse.dm
  code/game/objects/explosion.dm
  code/game/objects/explosion_recursive.dm
  code/game/objects/structures/flaps.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/support_rail.dm
  code/game/objects/structures/universal_generators/radial_generator.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/multiz/_HELPERS.dm
  vgstation13.dme
Labels: Performance

#32853 Hydroponics Mutations Rework
  __DEFINES/hydroponics.dm
  __DEFINES/reagents.dm
  code/game/gamemodes/events/spacevines.dm
  code/game/machinery/bees_apiary.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/hydroponics/hydroponics_reagents.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/hydroponics/seeds.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: System, Emoji This :+1: :-1:

#32905 Player voting fix
  code/modules/html_interface/voting/voting.dm
Labels: Hotfix

#32889 Ingesting reagent mob reaction rework
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/game/objects/items/gum.dm
  code/game/objects/items/robot/robot_items/robot_hypospray.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/mob/living/carbon/alien/humanoid/life.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/complex/martian/life.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/projectiles/guns/projectile/constructable/swords.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/surgery/other.dm
Labels: Tweak

#32911 Robust Harvest
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Hotfix

#32930 Meat Fridge Bugfixes
  code/game/machinery/vending.dm
Labels: Bug / Fix, 100% tested

#32916 More directly correlates blood drank to total for vampires
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Tweak

#32924 Hydroponics bugfixes
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/hydroponics/hydroponics_reagents.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Hotfix

#32926 Allows protolathes to recycle materials
  code/game/machinery/ammolathe.dm
  code/game/machinery/autolathe.dm
  code/modules/research/mechanic/mechanic_fabs.dm
  code/modules/research/protolathe.dm
  code/modules/research/rdmachines.dm
  code/modules/unit_tests/autolathe.dm
Labels: Content, ❤️ Quality of Life ❤️, 100% tested

#32927 Kicking reverse engines processes queue
  code/modules/research/mechanic/reverse_engine.dm
Labels: Content, ❤️ Quality of Life ❤️, Consistency Issue

#32933 Assorted typofixes.
  code/datums/gamemode/factions/bloodcult/bloodcult_rituals.dm
  code/game/machinery/computer/buildandrepair.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Hotfix, Grammar / Formatting

#32959 Fixes biomass packets.
  code/game/gamemodes/events/powercreeper.dm
  code/game/objects/items/deployable_packet.dm
Labels: Hotfix

#32976 Fixes infinite loop disease cargo forward generation
  code/game/centcomm_orders/orders_medical.dm
  code/modules/virus2/disease2.dm
Labels: Bug / Fix

#32979 Fixes signal spamming
  code/modules/assembly/signaler.dm
Labels: Oversight

#32983 Skeleton liches can no longer increase debilitating debuffs to sky-high numbers
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
Labels: Balance, Oversight
