Repository vgstation-coders/vgstation13, pull requests merged in 2023-10, with the labels that each got.

#35066 Leathermaking de-hairing step message for dull blades
  code/game/objects/items/stacks/sheets/leather.dm
Labels: ❤️ Quality of Life ❤️

#35103 Makes /obj/machinery/initialize() supercall
  code/game/machinery/machinery.dm
Labels: Bug / Fix

#34974 add logging for ghosting (incl. special log for admin ghosting)
  code/modules/mob/dead/observer/observer.dm
Labels: Logging / Administration

#35045 radiation absorbtion device mutual exclusivity
  code/modules/clothing/spacesuits/rig_modules/rig_modules.dm
Labels: Tweak

#35133 Revert Custom Emojis
  code/game/objects/items/devices/PDA/emoji.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, Exploitable

#35124 Admin custom bomb warnings and logs
  code/modules/admin/admin_verbs.dm
Labels: Logging / Administration

#35146 Fix Engi Coffee Overdose
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#35127 Fire heat2color
  code/ZAS/Fire.dm
  icons/effects/fire.dmi
Labels: ❤️ Quality of Life ❤️, Tweak

#35126 Fix noreact trait not being passed to mutated seeds
  code/modules/hydroponics/seed_datums.dm
Labels: Bug / Fix, Conflicts

#35164 Makes the atmos analyzer use XGM instead of hardcoded gasses.
  code/game/objects/items/devices/scanners.dm
Labels: Bug / Fix

#35147 Blob meat, blob food, blob drinks, blob reagents
  __DEFINES/reagents.dm
  __DEFINES/setup.dm
  code/datums/supplypacks.dm
  code/game/gamemodes/blob/blobs/core.dm
  code/game/gamemodes/blob/theblob.dm
  code/game/objects/structures/blobvolcano.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/spells/aoe_turf/conjure/spore.dm
  icons/mob/blob/blob.dmi
  icons/mob/in-hand/left/drinkingglass.dmi
  icons/mob/in-hand/left/food.dmi
  icons/mob/in-hand/right/drinkingglass.dmi
  icons/mob/in-hand/right/food.dmi
  icons/mob/screen_spells.dmi
  icons/obj/drinks.dmi
  icons/obj/food.dmi
  vgstation13.dme
Labels: Gameplay / Gamemode, Needs Spritework, WiP

#35205 Fixes bees runtiming when thrown
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
Labels: Bug / Fix, Runtime Log, NOT THE BEES

#35181 Buff cannonball recycle material gain to 100%
  code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
Labels: Tweak

#35182 Fix brass windows disappearing when anchored (workaround)
  code/game/objects/structures/fullwindow.dm
  code/game/objects/structures/window.dm
Labels: Needs Spritework

#35212 Make dionae slightly faster than a wheelchair
  code/modules/mob/living/carbon/species.dm
Labels: Controversial, ❤️ Quality of Life ❤️, Tweak

#35222 Several Events Which Shouldn’t Fire During Deadpop Will No Longer Fire During Deadpop
  code/__HELPERS/lists.dm
  code/modules/events/carp_migration.dm
  code/modules/events/event_dynamic.dm
  code/modules/events/immovablerod.dm
  code/modules/events/meteors.dm
  code/modules/events/powercreeper.dm
  code/modules/events/spacevine.dm
Labels: Bug / Fix, Gameplay / Gamemode, 100% tested

#35200 Solars Improvements
  code/datums/sun.dm
  code/modules/power/solars/control.dm
  code/modules/power/solars/panel.dm
  code/modules/power/solars/tracker.dm
  icons/obj/power.dmi
Labels: Sprites, Content, ❤️ Quality of Life ❤️

#35249 Catwalks tedium reduction
  code/game/objects/items/stacks/misc.dm
Labels: Balance, ❤️ Quality of Life ❤️

#35251 Catwalks now prevent space slipping
  code/modules/mob/mob_movement.dm
Labels: ❤️ Quality of Life ❤️, Muh Immulsions

#35252 Fixed an edge case where manually placing cables in space didn't check for proper support
  code/modules/power/cable.dm
Labels: Bug / Fix

#35254 Player-controlled mice can now visibly rest
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Bug / Fix

#35282 Paramedic Winter Coat Storage Fix
  code/modules/clothing/suits/wintercoat.dm
Labels: Consistency Issue

#35241 Rapid Cable Layer rewrite & Cable Coilours
  __DEFINES/_macros.dm
  __DEFINES/reagents.dm
  code/datums/outfit/engineering.dm
  code/game/machinery/vending.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/items/stacks/cable.dm
  code/game/objects/items/weapons/RCL.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/painting/paint.dm
  code/modules/power/cable.dm
  code/modules/power/cable_heavyduty.dm
  code/modules/reagents/Chemistry-Colours.dm
  code/modules/reagents/Chemistry-Reagents.dm
  icons/mob/in-hand/left/electronics.dmi
  icons/mob/in-hand/left/items_lefthand.dmi
  icons/mob/in-hand/right/electronics.dmi
  icons/mob/in-hand/right/items_righthand.dmi
  icons/obj/cuffs.dmi
  icons/obj/items.dmi
  icons/obj/power.dmi
  icons/obj/power_cond_white.dmi
Labels: Sprites, Content, ❤️ Quality of Life ❤️

#35221 Radstorms Now Need 7+ Pop
  code/modules/events/radiation_storm.dm
Labels: Gameplay / Gamemode, Tweak

#34765 update turret targeting to be less expensive
  code/game/machinery/turrets.dm
Labels: Performance, System
