Repository vgstation-coders/vgstation13, pull requests merged in 2023-01, with the labels that each got.

#33910 Allows bodies to be dragged out of airbags
  code/game/objects/items/airbag.dm
Labels: Tweak

#33912 Changes snowprint holder object into overlay
  code/datums/climate.dm
  code/game/turfs/unsimulated/snow.dm
Labels: Tweak

#33934 Makes TGUI work on 515 clients
  tgui/public/tgui.html
Labels: T-Thanks BYOND, System, UI

#33882 Baseball bat updates, sans new types
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/mob/living/living.dm
Labels: Content, Tweak

#33901 Multi-Z falling velocity update
  code/modules/multiz/fall_hit.dm
  code/modules/multiz/falling.dm
Labels: Content, Tweak

#33946 Fixes xeno thermals
  code/modules/mob/hearing/virtualhearer.dm
Labels: Bug / Fix

#33968 Updates Yarn and webpack
  tgui/.yarn/releases/yarn-3.0.1.cjs
  tgui/.yarn/releases/yarn-3.3.1.cjs
  tgui/.yarnrc.yml
  tgui/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: dependencies

#33970 Buff plasmaglass and rplasmaglass when constructing solars
  code/game/objects/items/stacks/sheets/glass.dm
Labels: Discussion

#33983 Fixes eye tracking glasses not having a sprite when equipped
  icons/mob/eyes.dmi
Labels: Bug / Fix

#33982 Vault map enlargements now respect non-standard base turfs
  code/modules/awaymissions/maploader/reader.dm
Labels: Bug / Fix

#33981 Custom vault loading test map
  .github/workflows/ci.yml
  config-example/testvaults.txt
  maps/_map_override.dm
  maps/test_vault.dm
  maps/test_vault.dmm
Labels: Mapping (General :world_map:), Mapping (Vault :question:)

#33971 slips some medium sized emergency gas tanks to space suit crates + your suit storage slot
  code/datums/supplypacks.dm
  code/modules/clothing/clothing.dm
Labels: Tweak

#34020 mommi MMI fixening
  code/modules/mob/living/carbon/brain/MMI.dm
Labels: Bug / Fix

#34019 Fixes pulse demons being affected by airflow
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
Labels: Bug / Fix

#34025 Max News Feed Length 1024 -> 9216 characters PLUS Large Input window
  code/game/machinery/newscaster.dm
Labels: Tweak

#34023 RCD/RPD investigation logging
  __DEFINES/setup.dm
  code/modules/RCD/schematics/engi.dm
  code/modules/RCD/schematics/pipe.dm
  code/modules/admin/admin_investigate.dm
  code/world.dm
Labels: Logging / Administration

#34048 Fixes pre-mapped chill bug packets such as those on Vox Trading Posts spawning regular bees
  code/controllers/mc/master.dm
  code/controllers/subsystem/init/more_init_stuff.dm
Labels: Bug / Fix, NOT THE BEES
