Repository vgstation-coders/vgstation13, pull requests merged in 2023-02, with the labels that each got.

#34076 Connection bullshit logging
  code/ZZZ/ZZZ_stupid_logging.dm
  vgstation13.dme
Labels: Logging / Administration

#34001 Friday the 13th causes 250 less luck to everyone
  code/modules/luck/luck.dm
Labels: Tweak

#34002 Makes the station alert computer not take a goddamn eon to initialize
  code/game/machinery/computer/station_alert.dm
Labels: Performance

#34009 Dropping an item from generic body pain now produces a user message
  code/modules/organs/pain.dm
Labels: Tweak

#33916 Grue shadow shunt
  code/game/objects/effects/effect_system.dm
  code/modules/mob/living/simple_animal/hostile/grue.dm
  code/modules/mob/living/simple_animal/hostile/grue_powers.dm
  icons/effects/effects.dmi
  icons/mob/screen_spells.dmi
  sound/effects/grue_shadowshunt.ogg
Labels: WiP

#34079 Revert "Connection bullshit logging"
  code/ZZZ/ZZZ_stupid_logging.dm
  vgstation13.dme
Labels: Logging / Administration

#34024 Makes cyber trophy belts hold items they're meant to
  code/game/objects/items/weapons/storage/belt.dm
Labels: Bug / Fix, Hotfix

#34047 Fixes Vox Mannequin Hair
  code/game/objects/structures/mannequin.dm
Labels: Bug / Fix

#34061 Roach farms can now make up to 100 cockroaches instead of just 50.
  code/modules/mob/living/simple_animal/roach.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Tweak

#34046 The Biometric Data Update
  code/__HELPERS/game.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/weapons/cards_ids.dm
Labels: Content, ❤️ Quality of Life ❤️

#34036 Emote typecheck refactoring
  code/datums/emotes.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/emote.dm
Labels: Tweak

#34085 Biogenerator hotfix
  code/game/machinery/biogenerator.dm
Labels: Hotfix

#33913 Smoother cryotube health bars + icon cleanup
  code/game/machinery/cryo.dm
  icons/obj/cryogenics.dmi
Labels: Sprites, 100% tested

#34053 Floor tile dragging over plating and reinforced flooring
  code/_onclick/hud/draggable.dm
  code/game/objects/items/stacks/tiles/tiles.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
Labels: Content, ❤️ Quality of Life ❤️

#34074 Adds an extra ghost warning to defibrilations when pads start setting up
  code/game/dna/dna_modifier.dm
  code/game/objects/items/weapons/defib.dm
  code/modules/medical/computer/cloning.dm
  code/modules/medical/patientprocessor.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkrevive.dm
Labels: Tweak

#34062 Makes clothing items not cause slowdown when not explicitly worn
  code/modules/mob/living/carbon/carbon.dm
Labels: Bug / Fix

#34089 Space Drugs and Mescaline mutate biomolecules
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Oversight, Consistency Issue

#34129 Adds hivelord boss Maria to the boss mob blacklist
  __DEFINES/global.dm
Labels: Oversight, Consistency Issue, Tweak

#34128 Fixes snow not going away on some turf changes
  code/game/turfs/unsimulated/snow.dm
Labels: Bug / Fix

#34126 Slow explosion effect debug logging + a fix
  code/game/machinery/turrets.dm
  code/game/objects/explosion.dm
Labels: Performance, Logging / Administration
