Repository vgstation-coders/vgstation13, pull requests merged in 2023-08, with the labels that each got.

#34829 Fixed engineering events never firing
  code/modules/events/event_dynamic.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️

#34838 A simple fix to Confusion runes + admin logging
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Labels: Bug / Fix, Logging / Administration

#34832 Ayy Rigsuit Kits and Balance (Cargo)
  code/datums/supplypacks.dm
  code/game/objects/items/devices/rigbuilding.dm
  code/modules/clothing/spacesuits/grey_rig.dm
  icons/mob/head.dmi
  icons/mob/species/grey/head.dmi
  icons/mob/species/grey/suit.dmi
  icons/mob/suit.dmi
  icons/obj/device.dmi
  icons/obj/storage/storage.dmi
  maps/randomvaults/mothership_lab.dm
Labels: Balance, Sprites, Content, Tweak

#34856 Scarves Fit Grayys (And other misc sprite fixes)
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/living/carbon/alien/larva/facehugger.dm
  icons/mob/species/grey/masks.dmi
Labels: Sprites

#34824 Blood-stain-related examine fixes
  code/game/atoms.dm
  code/game/objects/structures/mannequin.dm
  code/modules/mob/living/carbon/complex/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/monkey/examine.dm
Labels: Bug / Fix

#34891 fix clearing colors from mobs in some chem reactions
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#34739 VV tweaks
  code/datums/datumvars.dm
Labels: Bug / Fix, Logging / Administration

#34800 Reloading with ammo boxes as a loop of quick single-bullet reloads
  code/modules/projectiles/ammunition.dm
  sound/weapons/magazine_load_click.ogg
Labels: Gameplay / Gamemode

#34827 Xcom Armor Update (Sprites and Stats)
  code/datums/gamemode/role/judge.dm
  code/datums/outfit/special_outfits/special.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/maps/spawners/spawners.dm
  code/modules/research/designs/armor.dm
  icons/mob/head.dmi
  icons/mob/species/insectoid/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/randomvaults/oldarmory.dmm
  sound/misc/xcom_female1.ogg
  sound/misc/xcom_female2.ogg
  sound/misc/xcom_female3.ogg
  sound/misc/xcom_male1.ogg
  sound/misc/xcom_male2.ogg
  sound/misc/xcom_male3.ogg
  sound/misc/xcom_male4.ogg
Labels: Balance, Sprites, Content, Tweak

#34828 Item kicking tweaks
  code/game/objects/breakable.dm
  code/game/objects/items.dm
Labels: Content

#34845 revert chemmaster to old behavior on beaker detach
  code/modules/reagents/machinery/chem_master.dm
Labels: 100% tested

#34863 adjust light fixture layering to be above humans and potted plants
  __DEFINES/planes+layers.dm
  code/game/objects/structures/flora/flora.dm
  code/modules/power/lighting/lighting.dm
Labels: Tweak

#34865 fix decals not appearing properly on glass tiles
  code/game/turfs/simulated/floor_glass.dm
Labels: Bug / Fix

#34878 MDF Heavy Armor Buff
  code/datums/uplink_item.dm
  maps/randomvaults/mothership_lab.dm
Labels: Balance, Tweak

#34818 Cult Ghosts Don't Attack Deconverters On Denied Deconvert Anymore
  code/game/objects/items/weapons/storage/bible.dm
Labels: Tweak

#34905 Fix speedloaders reloading bullets one by one
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/speedloaders.dm
Labels: Bug / Fix

#34914 Paramedic outfit tweak for vox and plasmamen
  code/datums/outfit/medical.dm
Labels: Bug / Fix

#34895 grammar fix for reflexively firing during hostage-taking
  code/modules/projectiles/gun.dm
Labels: Grammar / Formatting

#34894 potential fix for crash+runtime with hookshotting
  code/modules/projectiles/projectile/hookshot.dm
Labels: Exploitable, Runtime Log

#34912 Small Vault Update (Pod Station, Broke UFO)
  code/datums/shuttle.dm
  code/game/shuttles/brokeufo.dm
  code/modules/mining/mine_turfs.dm
  maps/randomvaults/brokeufo.dmm
  maps/randomvaults/objects.dm
  maps/randomvaults/podstation.dmm
Labels: Mapping (Vault :question:)

#34918 Sound called stored in variable for adminbus: Desk bells and Ian
  code/game/objects/items/devices/deskbell.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Content, Easy Fix

#34923 Investigation Glasses Sprite Update (Grey and Insectoid Fits)
  code/modules/clothing/glasses/glasses.dm
  icons/mob/species/grey/eyes.dmi
  icons/mob/species/insectoid/eyes.dmi
Labels: Sprites

#34927 blacklist rabid slimes from being chosen to be playable by amorphous mask
  __DEFINES/global.dm
Labels: Bug / Fix

#34929 Adds a failsafe to the Blast Cannon loop preventing endless lag should the projectile end up on another Z level + fixed teleportation interaction
  code/datums/helper_datums/teleport.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Bug / Fix

#34930 Explosions now have an ID on the Bhangmeter Database so players can easily refer to one in particular.
  code/game/machinery/computer/bhangmeter.dm
Labels: ❤️ Quality of Life ❤️

#34932 Fix Gloves Not Showing (Mysterious Armor)
  code/modules/clothing/suits/armor.dm
Labels: Bug / Fix

#34948 Fixes manuals being printed as books
  code/game/objects/items/weapons/manuals.dm
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/library/computers/checkout.dm
Labels: Bug / Fix

#34943 Fix long range AI upload origin_tech string
  code/game/machinery/computer/buildandrepair.dm
Labels: Bug / Fix

#34945 Mednanobots Actually Fix Internal Organ Damage
  code/modules/reagents/Chemistry-Reagents.dm
Labels: Bug / Fix

#34955 Fix Changeling Being Unable to Split After Failing
  code/modules/spells/changeling/split.dm
Labels: Bug / Fix

#34902 More Renovations and Additions (Mothership Lab Vault)
  code/game/atoms_movable.dm
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
  code/modules/mob/living/simple_animal/hostile/human/greynurse.dm
  code/modules/mob/living/simple_animal/hostile/human/vox.dm
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  code/modules/projectiles/projectile/beams.dm
  icons/mob/head.dmi
  icons/mob/hostile_humanoid.dmi
  icons/mob/mask.dmi
  icons/mob/species/grey/head.dmi
  icons/mob/species/grey/masks.dmi
  icons/mob/species/grey/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  maps/randomvaults/dungeons/habitation.dmm
  maps/randomvaults/dungeons/research.dmm
  maps/randomvaults/mothership_lab.dm
  maps/randomvaults/mothership_lab.dmm
  sound/effects/alien_psy.ogg
  sound/effects/bullet_ricocchet.ogg
  sound/effects/ufo_appear.ogg
Labels: Sprites, Content, Mapping (Vault :question:)

#34951 Fix Runtimes When Mech Punching Objects
  code/game/mecha/combat/combat.dm
  code/game/mecha/mecha.dm
Labels: Bug / Fix, Consistency Issue

#34957 Mimosas and Lemon Drops
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/drinks.dmi
Labels: Sprites

#34934 Fixes barrels not receiving reagents and wooden barrels becoming metallic when getting inside it.
  code/modules/reagents/reagent_dispenser.dm
Labels: Bug / Fix, Hotfix, Oversight, 100% tested

#34928 Adds Lunchboxes and Premade Lunches (Content)
  code/datums/uplink_item.dm
  code/game/machinery/vending.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/storage/lunchbox.dm
  code/modules/store/items.dm
  icons/mob/in-hand/left/toolbox_ihl.dmi
  icons/mob/in-hand/right/toolbox_ihr.dmi
  icons/obj/kitchen.dmi
  vgstation13.dme
Labels: Sprites, Content

#34936 Mouser gun victims can eat their way to freedom.
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Bug / Fix

#34842 Scalding people by splashing them with hot reagents
  __DEFINES/setup.dm
  code/game/objects/items/weapons/pan.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/helper_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers.dm
Labels: Content

#34959 Pill making hotfix
  code/modules/reagents/machinery/chem_master.dm
Labels: Hotfix

#34950 Vox Mining and Engineer Helmet Lights
  code/modules/clothing/spacesuits/alien.dm
  icons/mob/species/vox/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites, Oversight, 100% tested
