Repository vgstation-coders/vgstation13, pull requests merged in 2024-10, with the labels that each got.

#37179 Adds a bunch of transparent pixels to spacepod parts
  icons/48x48/pod_construction.dmi
  icons/pods/pod_parts.dmi
Labels: ❤️ Quality of Life ❤️

#37176 Admin Cookies are now entropy immune
  code/modules/admin/topic.dm
Labels: Logging / Administration

#37115 Makes newscaster news "events" actually used
  __DEFINES/subsystem.dm
  code/controllers/subsystem/init/more_init_stuff.dm
  code/controllers/subsystem/news.dm
  code/datums/periodic_news.dm
  code/game/machinery/newscaster.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/news/news.dm
  code/modules/news/news_events.dm
  code/modules/news/news_events_mundane.dm
  code/modules/news/news_trade_destinations.dm
  code/modules/news/news_types.dm
  vgstation13.dme
Labels: Bug / Fix, Content

#37106 Allows station blueprints to show an archive of how somewhere looked
  code/game/objects/items/blueprints.dm
Labels: Content

#37178 Minor Space Pod Fixes
  code/modules/spacepods/construction.dm
Labels: Bug / Fix

#37188 Clumsy Peg Limb Gun Fixes
  code/modules/projectiles/gun.dm
Labels: Bug / Fix

#37159 Adds ways to check for arcane tampering and confirm removal of it
  code/game/atoms.dm
  code/game/objects/items/weapons/null_rod.dm
Labels: ❤️ Quality of Life ❤️

#37209 New artifact vendor icon
  code/modules/research/xenoarchaeology/artifact/artifact_vendor.dm
  icons/obj/vending.dmi
Labels: Sprites

#37211 Quick equip fixes
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/clothing/clothing.dm
Labels: Bug / Fix

#37207 Fixes Most Screwdriver/Wrench/Wirecutter Special Tool Interactions
  code/datums/helper_datums/construction_datum.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/vending_packs.dm
  code/game/objects/items/devices/deskbell.dm
  code/game/objects/items/devices/rigbuilding.dm
  code/game/objects/items/gum.dm
  code/game/objects/items/stacks/sheets/light.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/switchtool.dm
  code/game/objects/items/weapons/tools.dm
  code/game/turfs/simulated/floor.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/fish/fish_items.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mining/ores_coins.dm
  code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
  code/modules/spacepods/construction.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/brainrepair.dm
  code/modules/surgery/butt.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/eye.dm
  code/modules/surgery/face.dm
  code/modules/surgery/genderchange.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/headreattach.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  code/modules/surgery/robolimbs.dm
  code/modules/surgery/slimes.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/tooth.dm
  code/modules/trader/crates/cloudnine.dm
Labels: Bug / Fix

#37019 Ports most emag attackby() to emag_act()
  code/_onclick/item_attack.dm
  code/game/atoms.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/bots/secbot.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/cargo.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/unpowered.dm
  code/game/machinery/machinery.dm
  code/game/machinery/vending.dm
  code/game/objects/items/beacon.dm
  code/game/objects/items/cookie_synth.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/devices/maracas.dm
  code/game/objects/items/devices/mat_synth.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/sound_synth.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/ai_modules/AI_modules.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/vehicles/clowncart.dm
  code/modules/Economy/Accounts.dm
  code/modules/Economy/EFTPOS.dm
  code/modules/RCD/tile painter.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/hydroponics/floral_somatoray.dm
  code/modules/media/jukebox.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/power/apc.dm
  code/modules/power/rust/fuel_compressor.dm
  code/modules/power/rust/fuel_compressor_construction.dm
  code/modules/projectiles/guns/energy/temperature.dm
  code/modules/projectiles/guns/projectile/rocketlauncher.dm
  code/modules/projectiles/projectile/rocket.dm
  code/modules/recycling/compactor.dm
  code/modules/research/mechanic/component_exchanger.dm
  code/modules/research/server.dm
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
  code/modules/telesci/rcs.dm
  goon/code/obj/machinery/bot/chefbot.dm
Labels: Bug / Fix, Consistency Issue

#37165 More slime extract uses
  __DEFINES/obj_defines.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/datums/recipe.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/pan.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/objs.dm
  code/modules/RCD/RPD.dm
  code/modules/food/recipes_microwave.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/minerals.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/paperwork/photography.dm
  code/modules/power/port_gen.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: Content

#37214 Crate Shelf Fixes
  code/game/objects/structures/crateshelf.dm
Labels: Bug / Fix, Tweak

#37192 Proto-Kinetic Pump-Shotgun
  code/game/machinery/vending.dm
  code/game/objects/items/devices/modkit.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special.dm
  icons/mob/in-hand/left/guns.dmi
  icons/mob/in-hand/right/guns.dmi
  icons/obj/device.dmi
  icons/obj/gun.dmi
  icons/obj/projectiles.dmi
Labels: Sprites, Content

#37210 Allows AI to retrack people who come back on cameras
  code/game/dna/genes/goon_powers.dm
  code/game/machinery/camera/tracking.dm
  code/game/objects/items/devices/megaphone.dm
Labels: Content

#37217 Makes your action progress bars show up for targets too
  code/__HELPERS/unsorted.dm
  code/datums/gamemode/role/vampire_role.dm
  code/modules/mob/living/carbon/stripping.dm
Labels: Bug / Fix

#37220 Killer pheromones
  __DEFINES/reagents.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents/reagents_bio.dm
Labels: Content

#37224 Ingesting phazon now randomizes blood and gib colors
  code/__HELPERS/unsorted.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Content

#37208 Spacepod Cargo Bay Equipment and Pod Fabricator Spruce Up
  code/game/objects/effects/effect_system.dm
  code/modules/mob/living/living.dm
  code/modules/research/designs/spacepod/weapons.dm
  code/modules/research/fabricators.dm
  code/modules/spacepods/equipment.dm
  code/modules/spacepods/spacepods.dm
  nano/templates/podfab.tmpl
Labels: Bug / Fix, Balance, Content

#37215 Cigarette Radio Bug QOL
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: ❤️ Quality of Life ❤️

#37246 Fixes timer assemblies not repeating
  code/modules/assembly/timer.dm
Labels: Bug / Fix

#37247 Excludes 1 TC items from round discounts
  code/datums/uplink_item.dm
Labels: Gameplay / Gamemode, Tweak

#37248 Buffs H.U.E.Y upgrades (plus advanced mk2 weedkill one)
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/glass/bottle/robot.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/designs/borg_upgrades.dm
Labels: Content, ❤️ Quality of Life ❤️

#37253 Fixes shoesnatch not putting the shoes in caster's hands
  code/modules/spells/targeted/shoesnatch.dm
Labels: Bug / Fix

#37257 doubles the time it takes to smoke a pipe
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Balance, Consistency Issue

#37239 Adds Confirmation to Reload Admins Verb
  code/modules/admin/verbs/diagnostics.dm
Labels: Logging / Administration, i ded

#37267 Makes sheet snatchers actually accept sheets
  code/game/objects/items/weapons/storage/bags.dm
Labels: Bug / Fix

#37268 Fixes all improper uses of a/an
  code/datums/datumvars.dm
  code/game/machinery/syndicate_beacon.dm
  code/game/objects/items/devices/hologram_projector.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/paperwork/papers_preformatted.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents/reagents_tools.dm
  code/modules/research/designs/AI_modules.dm
  code/modules/research/designs/boards/machine_science.dm
  code/modules/research/designs/borg_upgrades.dm
  code/modules/research/designs/mecha/odysseus.dm
  code/modules/telesci/telesci_computer.dm
  maps/lampreystation/lamprey.dm
Labels: Grammar / Formatting

#37233 Advanced RCD plasma window reinforcement
  code/modules/RCD/engie.dm
  code/modules/RCD/schematics/engi.dm
Labels: Content

#37259 Mecha Graveyard and Mech Wreckage Update
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/items/trader.dm
  code/modules/maps/spawners/pick_spawner.dm
  code/modules/mining/mine_turfs.dm
  icons/mecha/mecha.dmi
  maps/randomvaults/dungeons/mecha_graveyard.dmm
Labels: Balance, Content

#37273 Makes arcane tampered doors only link on current z-level
  code/game/machinery/doors/door.dm
Labels: Balance

#37288 Fixes bot and borg emagging (and bot pAI slotting)
  code/_onclick/item_attack.dm
  code/game/machinery/bots/bots.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Bug / Fix

#37295 Fixes Compiler Warnings by Removing a Single Space
  code/game/machinery/bots/bots.dm
Labels: Hotfix
