Repository vgstation-coders/vgstation13, pull requests merged in 2024-08, with the labels that each got.

#36875 Fixes attack_self() override for energy guns
  code/modules/projectiles/guns/energy.dm
Labels: Bug / Fix

#36868 Paint overlay parity for the new library carpets and wooden floors
  code/game/turfs/paint_overlay.dm
  icons/turf/paint_overlays_floors.dmi
Labels: Sprites

#36871 juicy fruit splashes in an area
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Content, 100% tested

#36858 Stinking up a location via having carp pheromones will no longer be prevented by someone in the vicinity being dead
  code/modules/reagents/reagents/reagents_bio.dm
Labels: Bug / Fix, 0% tested

#36881 Fixes runtime in bloodcult_projectiles.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_projectiles.dm
Labels: Bug / Fix, Runtime Log

#36883 Fixes cult hood anonymity toggle
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
Labels: Bug / Fix

#36865 Grugstation Event Content
  code/datums/outfit/special_outfits/special.dm
  code/game/events/naturify.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/structures/flora/flora.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/mining/mine_structures.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  icons/mob/in-hand/left/swords_axes.dmi
  icons/mob/in-hand/right/swords_axes.dmi
  icons/obj/doors/rockdoor.dmi
  icons/obj/fish_items.dmi
  icons/obj/flora/trees.dmi
  icons/obj/weapons.dmi
  sound/effects/fishslap.ogg
  vgstation13.dme
Labels: Content

#36754 New plant and reagent: Squash
  __DEFINES/reagents.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/carbon/human/combat.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/reagents/reagents/reagents_drug.dm
  icons/obj/hydroponics/squash.dmi
Labels: Content, 100% tested

#36861 killdozer v2 - ripleydozer with guns
  code/datums/uplink_item.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/passive/passive.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/research/designs/robotics.dm
  icons/mecha/mecha.dmi
Labels: Content

#36866 Tweaks to the caber
  code/game/objects/items/weapons/swords_axes_etc.dm
Labels: Balance, Tweak

#36873 Makes meth a chemmable drug instead of just vault loot.
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagents/reagents_drug.dm
  icons/obj/food_condiment.dmi
Labels: Balance, Content

#36876 A hostile Old Vendotron will no longer destroy itself with the creatures it creates + Old Vendotron plate throwing fix
  code/modules/events/old_vendotron_event/old_vendotron.dm
  code/modules/reagents/reagent_containers/food/snacks/egg.dm
Labels: Bug / Fix, Balance

#36877 Slimes become ravenous when near monkeys and store a little more nutrition
  code/modules/mob/living/carbon/slime/life.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/carbon/slime/slime.dm
Labels: Balance

#36887 Surgery box now flashes with a players brain inside.
  code/game/objects/structures/crates_lockers/crates.dm
  icons/obj/storage/storage.dmi
Labels: Sprites, ❤️ Quality of Life ❤️

#36891 The Dust Motes Update: What if you could see ZAS?
  __DEFINES/setup.dm
  code/ZAS/ConnectionGroup.dm
  code/ZAS/Zone.dm
  code/game/objects/effects/particles_system.dm
  code/modules/mob/living/carbon/human/emote.dm
  icons/effects/effects_particles.dmi
Labels: Sprites, Content

#36915 Wooden Buckets and Grugstation Changes
  code/game/events/naturify.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/mob/head.dmi
  icons/mob/in-hand/left/items_lefthand.dmi
  icons/mob/in-hand/right/items_righthand.dmi
  icons/mob/species/insectoid/head.dmi
  icons/obj/janitor.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites, Content, Gameplay / Gamemode, 100% tested, Tweak

#36916 Circular Saws can Chop Trees
  code/game/objects/structures/flora/flora.dm
Labels: Balance, 100% tested

#36917 Friendly Carp Ranching Fixes
  code/modules/mob/living/simple_animal/hostile/carp.dm
Labels: Bug / Fix

#36919 Tool Sound Fixes/Backup Sounds for Tools/Surgery
  code/game/objects/items.dm
Labels: Bug / Fix, Balance, Sound

#36918 Wooden Wall Chopping Nerfs
  code/__HELPERS/unsorted.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/walls_mineral.dm
  code/modules/hydroponics/hydro_tools.dm
Labels: Balance, 100% tested

#36913 Easier (Grug) Leatherworking
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/structures/watercloset.dm
Labels: Balance, 100% tested, Tweak

#36893 Vomit electrolysis
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Content

#36909 lich hardsuit uses the correct helmet
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
Labels: Bug / Fix

#36923 Fixes taclights not properly setting light values when attached to something.
  code/modules/clothing/accessories/tactical_light.dm
Labels: Bug / Fix

#36928 Fixes dust motes remaining forever on turfs that change type
  code/game/turfs/turf.dm
Labels: Bug / Fix

#36892 Tweak to blacksmithing materials
  code/modules/mining/materials.dm
Labels: Balance, Feature Loss, ❤️ Quality of Life ❤️, Tweak

#36839 Automatic Fire Suppression
  code/game/machinery/alarm.dm
  code/game/machinery/computer/atmos_control.dm
  nano/templates/air_alarm.tmpl
  nano/templates/atmos_control.tmpl
Labels: Content

#36840 Flatpack Printer Bluespace Bins
  code/modules/research/mechanic/flatpacker.dm
Labels: Bug / Fix

#36902 Bookcases Burning
  code/ZAS/Fire.dm
  code/game/objects/objs.dm
  code/modules/library/lib_items.dm
Labels: Bug / Fix, 100% tested, Tweak

#36924 implants are now TINY instead of NORMAL sized
  code/game/objects/items/weapons/implants/implant.dm
Labels: Tweak

#36925 nanopaste is now small instead of normal
  code/game/objects/items/stacks/nanopaste.dm
Labels: Tweak

#36931 Hydro Tray lights now update immediately after pouring a reagent into it
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/hydroponics_reagents.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagents/reagents_basic.dm
  code/modules/reagents/reagents/reagents_bio.dm
  code/modules/reagents/reagents/reagents_drink.dm
  code/modules/reagents/reagents/reagents_ethanol.dm
  code/modules/reagents/reagents/reagents_food.dm
  code/modules/reagents/reagents/reagents_medical.dm
  code/modules/reagents/reagents/reagents_paint.dm
  code/modules/reagents/reagents/reagents_plant.dm
  code/modules/reagents/reagents/reagents_religious.dm
  code/modules/reagents/reagents/reagents_tools.dm
  code/modules/reagents/reagents/reagents_toxin.dm
  code/modules/reagents/reagents/reagents_xenoarch.dm
  icons/obj/hydroponics/hydro_tools.dmi
Labels: ❤️ Quality of Life ❤️, Tweak

#36934 Allows Admins to Toggle Dexterity for Monkeys and Brain Damaged Humans
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/monkey/vox.dm
  code/modules/mob/mob_defines.dm
Labels: Content, Logging / Administration

#36936 Phazon weapons will now blink themselves to a random tile nearby instead of deleting themselves.
  code/modules/mining/materials.dm
Labels: Feature Loss, Content, Tweak

#36938 buffs lotto number jackpot event odds
  code/game/machinery/vending.dm
Labels: Balance, Tweak

#36940 Botany chems now tick and get consumed at the same rate.
  code/modules/reagents/reagents/reagents_basic.dm
  code/modules/reagents/reagents/reagents_drug.dm
  code/modules/reagents/reagents/reagents_material.dm
  code/modules/reagents/reagents/reagents_medical.dm
  code/modules/reagents/reagents/reagents_toxin.dm
Labels: Balance, ❤️ Quality of Life ❤️, Tweak

#36867 Silencing Spray
  code/datums/uplink_item.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/say.dm
  code/game/sound.dm
  code/modules/reagents/reagents/reagents_basic.dm
  icons/obj/items.dmi
  maps/RandomZLevels/hive.dm
  maps/RandomZLevels/hive.dmm
Labels: Content

#36946 Fixing a bunch of hydro tray and canister related issues
  code/game/atoms.dm
  code/game/machinery/atmoalter/canister.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/reagents/reagent_containers.dm
Labels: Bug / Fix, Tweak

#36958 Fixes seconds in worldtime2text
  code/__HELPERS/time.dm
Labels: Bug / Fix, Grammar / Formatting

#36952 Fixes jail and sleeper deactivation messages
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/sec_tools.dm
Labels: Grammar / Formatting

#36948 Holomen don't suffocate nor get intoxicated by gases
  code/modules/mob/living/simple_animal/hologram/hologram.dm
Labels: Tweak

#36911 Semi-randomized beer kegs on the Cargo supply shuttle.
  __DEFINES/reagents.dm
  code/datums/supply_packs/hospitality.dm
  code/datums/uplink_item.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Content, Needs Spritework

#36942 Grue Health Regen scaling adjustment
  code/modules/mob/living/simple_animal/hostile/grue.dm
Labels: Balance, Gameplay / Gamemode

#36944 Allows new weeds to overtake trays containing dead weeds
  code/modules/hydroponics/hydro_tray_process.dm
Labels: Tweak

#36945 The plant analyzer will also tell you the chems in planted seeds.
  code/modules/hydroponics/hydro_tools.dm
Labels: Oversight

#36947 Hydroponic plants now react to radiation!
  code/modules/events/radiation_storm.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/power/singularity/collector.dm
Labels: Content

#36966 typofix
  code/modules/reagents/reagent_dispenser.dm
Labels: Hotfix, Grammar / Formatting

#36383 Smoother AI tracking
  code/_hooks/events.dm
  code/datums/gamemode/powers/changeling.dm
  code/datums/gamemode/role/ninja.dm
  code/game/dna/genes/goon_powers.dm
  code/game/machinery/camera/tracking.dm
  code/game/machinery/hologram.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/mob.dm
  code/modules/trader/crates/alcatrazfour.dm
Labels: Tweak

#36930 RPD list icons
  code/modules/RCD/RCD.dm
  code/modules/RCD/RPD.dm
  code/modules/RCD/schematic.dm
  code/modules/RCD/schematics/pipe.dm
  code/modules/html_interface/RCD/RCD.css
Labels: ❤️ Quality of Life ❤️, UI

#36970 Igniter Hotfix
  code/game/machinery/igniter.dm
Labels: Hotfix

#36951 Makes catbeast room defilation instantaneous
  code/datums/gamemode/role/catbeast.dm
Labels: Tweak

#36490 Braindamage speech proc change.
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
Labels: Content, ✋ Do Not Merge ✋, 100% tested, Tweak, Fluff :teddy_bear:

#36950 Hydroponic Tray moody lights pass, lid re-sprite, and other visual goodness
  __DEFINES/planes+layers.dm
  code/game/atoms.dm
  code/game/machinery/atmoalter/portable_atmospherics.dm
  code/game/machinery/bees_apiary.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/vehicles/carts/cargo.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/prehistoric_plants.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seeds.dm
  code/modules/hydroponics/soil.dm
  code/modules/reagents/Chemistry-Holder.dm
  icons/mob/radial.dmi
  icons/obj/hydroponics/amauri.dmi
  icons/obj/hydroponics/ambrosiadeus.dmi
  icons/obj/hydroponics/ambrosiavulgaris.dmi
  icons/obj/hydroponics/angel.dmi
  icons/obj/hydroponics/bloodtomato.dmi
  icons/obj/hydroponics/bluespacetomato.dmi
  icons/obj/hydroponics/bluetomato.dmi
  icons/obj/hydroponics/carrot.dmi
  icons/obj/hydroponics/chanter.dmi
  icons/obj/hydroponics/chili.dmi
  icons/obj/hydroponics/chilighost.dmi
  icons/obj/hydroponics/chiliice.dmi
  icons/obj/hydroponics/cinnamomum.dmi
  icons/obj/hydroponics/deathnettle.dmi
  icons/obj/hydroponics/dionanode.dmi
  icons/obj/hydroponics/eggplant.dmi
  icons/obj/hydroponics/eggy.dmi
  icons/obj/hydroponics/flax.dmi
  icons/obj/hydroponics/glowberry.dmi
  icons/obj/hydroponics/glowshroom.dmi
  icons/obj/hydroponics/harebell.dmi
  icons/obj/hydroponics/hydro_tools.dmi
  icons/obj/hydroponics/jurlmah.dmi
  icons/obj/hydroponics/kudzu.dmi
  icons/obj/hydroponics/liberty.dmi
  icons/obj/hydroponics/moonflower.dmi
  icons/obj/hydroponics/mustardplant.dmi
  icons/obj/hydroponics/nettle.dmi
  icons/obj/hydroponics/novaflower.dmi
  icons/obj/hydroponics/pitcher.dmi
  icons/obj/hydroponics/plump.dmi
  icons/obj/hydroponics/potato.dmi
  icons/obj/hydroponics/pumpkin.dmi
  icons/obj/hydroponics/purpleshardlime.dmi
  icons/obj/hydroponics/replicapod.dmi
  icons/obj/hydroponics/shardlime.dmi
  icons/obj/hydroponics/squash.dmi
  icons/obj/hydroponics/tomato.dmi
  icons/obj/hydroponics/walkingmushroom.dmi
  icons/obj/plants.dmi
Labels: Sprites, Content

#36960 Hydroponic Trays now consume a bit of power
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/hydro_tray_process.dm
Labels: Tweak

#36980 Revert "Makes the emergency shuttle and status display process timed to the second"
  code/controllers/shuttle_controller.dm
  code/controllers/subsystem/emergency_shuttle.dm
  code/controllers/subsystem/supply_shuttle.dm
  code/game/machinery/status_display.dm
Labels: Bug / Fix

#36632 Some subsystem init speedups
  code/controllers/subsystem/init/map.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/objects.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/window.dm
  code/game/smoothwall.dm
  code/game/turfs/simulated/shuttle.dm
  code/game/turfs/space/space.dm
  code/game/turfs/unsimulated/walls.dm
  code/modules/lighting/lighting_setup.dm
  maps/RandomZLevels/wildwest_props.dm
  maps/lampreystation/lamprey.dm
  maps/randomvaults/mothership_lab.dm
  maps/randomvaults/objects.dm
  vgstation13.dme
Labels: Performance

#36961 Rampant Brand Intelligence random event tweaks
  code/datums/helper_datums/command_alerts.dm
  code/modules/events/brand_intelligence.dm
Labels: Tweak, i ded

#36959 New chem: Metastable Mutagen - A way to reliably remove chems from plants. And smallish hydroponics feature.
  __DEFINES/reagents.dm
  code/modules/hydroponics/hydroponics_mutations.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagents/reagents_toxin.dm
Labels: Content, ❤️ Quality of Life ❤️

#36984 Fixes chameleon alpha not resetting on removal
  code/game/dna/genes/goon_powers.dm
Labels: Bug / Fix

#36615 Possess/release fixes
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/possess.dm
  code/modules/mob/mob_movement.dm
Labels: Bug / Fix

#36967 Beekeeping 3.7
  code/game/machinery/bees_apiary.dm
  code/game/sound.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mob/living/simple_animal/bees/bees_items.dm
  code/modules/trader/crates/zincsaucier.dm
  icons/effects/fire.dmi
  icons/mob/in-hand/left/beekeeping.dmi
  icons/mob/in-hand/right/beekeeping.dmi
  icons/obj/apiary_bees_etc.dmi
  icons/obj/food.dmi
  icons/obj/food_condiment.dmi
  icons/obj/items_weird.dmi
  maps/randomvaults/mothership_lab.dm
Labels: Sprites, Content, Tweak

#36964 Blacksmithing Quality of Life Pass
  code/__HELPERS/unsorted.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/objs.dm
  code/modules/blacksmithing/blacksmithing.dm
  code/modules/blacksmithing/forge.dm
  code/modules/lighting/lighting_atom.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️, 100% tested

#36652 Removes unused heist random event
  code/modules/events/heist.dm
Labels: File Cleanup

#36668 Vendor coinbox and vendpack qol
  code/game/machinery/constructable_frame.dm
  code/game/machinery/vending.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/storage/lockbox.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#36975 Beepsky Non-Human Target Bugfix
  code/game/machinery/bots/secbot.dm
Labels: Bug / Fix, Unatomic Uncle

#36976 Cows will mutate their milk type if exposed to phazon
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Content

#36977 Tweaked Victorian Christmas (fixed lights and snow adjustments and fixes)
  code/game/gamemodes/endgame/xmas/lights.dm
  code/game/gamemodes/endgame/xmas/snow.dm
  code/game/gamemodes/endgame/xmas/victorianstation.dm
  icons/turf/snow.dmi
Labels: Bug / Fix, Sprites

#36978 atmos suits now have a higher pressure resistance
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
Labels: Tweak

#36979 RPD menu floats
  code/modules/RCD/RCD.dm
  code/modules/RCD/RPD.dm
  code/modules/html_interface/RCD/RCD.css
Labels: ❤️ Quality of Life ❤️, UI

#36983 Fixes mech syringe guns not working at all
  code/game/mecha/equipment/tools/medical_tools.dm
Labels: Bug / Fix

#36709 Stack storage fixes
  code/game/objects/items/stacks/sheets/sheets.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#36968 Mob Ignition Fixes/Cleanup
  code/ATMOSPHERICS/hvac/spaceheater.dm
  code/ZAS/Fire.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/religions.dm
  code/game/dna/genes/goon_powers.dm
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/game/machinery/cryo.dm
  code/game/machinery/firefoam_popper.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/fire_blast.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/robot/robot_items/robot_axe.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/objs.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species/plasmaman.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/reagents/reagents_basic.dm
  code/modules/reagents/reagents/reagents_religious.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
  code/modules/spells/targeted/feint.dm
Labels: Bug / Fix, File Cleanup, Tweak

#36981 Adds Missing Shuttlecrush Edit to Shuttle Magic
  code/modules/admin/topic.dm
Labels: Bug / Fix, Logging / Administration

#37009 Fixes caught typos
  code/game/objects/items/weapons/butterfly.dm
  code/game/objects/items/weapons/dice.dm
Labels: Grammar / Formatting

#37014 Gives slimefolk a feedback message on their regen ability.
  code/modules/mob/living/carbon/species_powers.dm
Labels: Bug / Fix, 0% tested

#37008 unpowered uvent overlay fix
  code/ATMOSPHERICS/components/unary/vent_pump.dm
Labels: Bug / Fix

#36989 blue portable pumps update the pipe network
  code/game/machinery/atmoalter/pump.dm
  code/game/machinery/atmoalter/scrubber.dm
Labels: Bug / Fix

#36990 Adds mining surprise and hobo shack areas to global areas list
  code/game/area/Space Station 13 areas.dm
  code/modules/mining/surprise.dm
Labels: Bug / Fix

#36710 adds safety logging for quick equip baguloosing
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/storage/bluespace.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/objs.dm
  code/modules/clothing/clothing.dm
Labels: Logging / Administration

#36994 Allows normal ghosts to haunt the chapel again
  code/modules/mob/mob_movement.dm
Labels: Bug / Fix
