Repository vgstation-coders/vgstation13, pull requests merged in 2024-03, with the labels that each got.

#36116 fixes tailed human eye colors
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug / Fix

#36126 Moves the robot tail on the mechfab from Robot to Misc.
  code/modules/research/designs/robot.dm
Labels: Tweak

#36084 Adds an icon for Sunflowers, Novaflowers and Moonflowers when worn as a head accessory, and lets you wear Sunflowers and Moonflowers as accessory (previously only novaflower).
  code/modules/hydroponics/grown_inedible.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/mob/head.dmi
  icons/obj/hydroponics/novaflower.dmi
  icons/obj/hydroponics/sunflower.dmi
Labels: Sprites, 100% tested, Fluff :teddy_bear:

#36078 A bunch of small wizard changes
  __DEFINES/spell_defines.dm
  code/_onclick/hud/spell_screen_objects.dm
  code/datums/gamemode/role/wizard.dm
  code/game/gamemodes/wizard/artifacts.dm
  code/game/gamemodes/wizard/spellbook.dm
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/spells.dm
  code/modules/mob/transform_procs.dm
  code/modules/spells/passive/no_clothes.dm
  code/modules/spells/passive/no_gun_allowed.dm
  code/modules/spells/targeted/pacify.dm
  code/modules/spells/targeted/projectile/fireball.dm
  code/modules/spells/targeted/projectile/firebreath.dm
Labels: Bug / Fix

#36125 Adds 2 new PACMAN engines.
  code/game/machinery/constructable_frame.dm
  code/modules/power/port_gen.dm
  code/modules/research/designs/boards/machine_engie.dm
  icons/obj/power.dmi
Labels: Content

#36055 Fixes Dynamic midround rulesets that polled ghosts counting less candidates than they should
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Labels: Bug / Fix, Gameplay / Gamemode

#36056 Certain latejoin rulesets now have the same requirements as their midround equivalents
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
Labels: Gameplay / Gamemode

#36111 landline cord formatting
  code/game/machinery/landline.dm
Labels: Grammar / Formatting

#36112 bigger and clearer vampire thrall deconvert text
  code/datums/gamemode/role/vampire_role.dm
Labels: Grammar / Formatting, Tweak

#36100 damage-based disabilities now make a lot more sense
  code/modules/reagents/reagents/reagents_medical.dm
Labels: Oversight, ❤️ Quality of Life ❤️, Consistency Issue, Tweak

#36082 add tech origin for goonecode
  __DEFINES/setup.dm
  code/game/objects/items/toys.dm
  code/modules/research/mechanic/device_analyser.dm
Labels: Balance

#36015 The Changeling armblade now has a spin attack
  code/datums/gamemode/powers/changeling.dm
  code/game/objects/items/weapons/armblade.dm
  sound/weapons/blade_whirlwind.ogg
Labels: Content, Gameplay / Gamemode

#36057 Midround rulesets will now roll more often
  __DEFINES/role_datums_defines.dm
Labels: Gameplay / Gamemode

#36046 Darkness-changing vision stuff such as mesons will no longer fade in and out, instead applying instantly
  code/modules/clothing/glasses/scanners.dm
  code/modules/mob/mob.dm
Labels: UI

#36033 Shards now screech in rage when destroyed
  code/modules/supermatter/supermatter.dm
  sound/effects/delamination.ogg
Labels: Sound

#36130 skeleton suit hides tail, fixes tail hiding also fixes skeleton suit not hiding hair/facial hair
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug / Fix

#36145 hotfix for imidazoline blindness curing
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagents/reagents_medical.dm
Labels: Bug / Fix

#36137 fix flesh-to-stone victims being muted after staff of animation'd
  code/game/objects/structures/mannequin.dm
Labels: Bug / Fix

#36133 mob deletion fix 1: giftwrap
  code/game/objects/items/weapons/gift_wrappaper.dm
Labels: Bug / Fix

#36132 you remove the dead plant from the the soil
  code/modules/hydroponics/hydro_tray.dm
Labels: Grammar / Formatting

#36138 mob deletion fix 2: bodybag recycler
  code/game/objects/items/bodybag.dm
Labels: Tweak

#36091 Castle Station now allows building silicons again
  maps/tgstation-sec.dm
Labels: Balance, Mapping (Bus :bus:)

#36066 RPD UI: slime extract edition
  code/modules/RCD/RPD.dm
  code/modules/html_interface/RCD/RCD.css
Labels: Bug / Fix, ❤️ Quality of Life ❤️, UI

#36148 Remove random item from discounted surplus
  code/datums/uplink_item.dm
Labels: Bug / Fix

#36146 Less Annoying Tail Surgery
  __DEFINES/span.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/robolimbs.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/tail.dm
  vgstation13.dme
Labels: Tweak

#36095 Suit mod machine now actually replaces the alien suit rather than painting it.
  code/game/machinery/suit_modifier.dm
Labels: Balance, System

#36149 Cookable Sugar and Salt cubes
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Content

#36051 Bioballistic Delivery System Multi-Splice Option
  code/modules/hydroponics/seed_machines.dm
  nano/templates/botany_editor.tmpl
Labels: ❤️ Quality of Life ❤️

#36136 More wizard changes and fixes
  code/datums/gamemode/role/wizard.dm
  code/datums/gamemode/role/wizard_apprentice.dm
  code/game/dna/genes/vg_powers.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/gamemodes/wizard/artifacts.dm
  code/modules/mob/living/simple_animal/hostile/pitbull.dm
  code/modules/mob/spells.dm
  code/modules/spells/aoe_turf/conjure/snakes.dm
  code/modules/spells/aoe_turf/magic_wardrobe.dm
  code/modules/spells/passive/no_gun_allowed.dm
  code/modules/spells/spell_code.dm
  code/modules/spells/targeted/absorb.dm
  code/modules/spells/targeted/genetic.dm
  code/modules/spells/targeted/push.dm
  code/modules/spells/targeted/recall.dm
  code/modules/surgery/butt.dm
Labels: Bug / Fix, Balance, Grammar / Formatting

#36156 Vox and plasmaman orderlies will no longer spawn with an extra paralytic injector
  code/datums/outfit/medical.dm
Labels: Balance, Consistency Issue

#36166 The holopipe and blunts now fit vox
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/species/vox/masks.dmi
Labels: Sprites

#36165 fixes the pAI "Update Scan" medical supplement button not working.
  code/modules/mob/living/silicon/pai/software.dm
Labels: Bug / Fix, Hotfix

#36155 RPD favorite symbol change
  code/modules/RCD/schematic.dm
  code/modules/html_interface/RCD/RCD.css
Labels: UI, 100% tested, Tweak

#36181 Fixes an issue where managing to put food on a plate without directly touching it will cause it to be invisible in the plate.
  code/modules/food/customizables.dm
Labels: Bug / Fix

#36157 Shields now protect against even more stuff
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackanimal.dm
  code/modules/mob/living/simple_animal/hostile/monster.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  vgstation13.dme
Labels: Balance, Gameplay / Gamemode

#36158 Vampires now get extra examination text when examining people
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/vampire_role.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Gameplay / Gamemode

#36160 Sleight of Teeth is now quiet.
  code/datums/gamemode/role/vampire_role.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Balance

#36180 Modular Particles System
  code/datums/components/cooktop.dm
  code/game/atoms.dm
  code/game/objects/effects/particles_system.dm
  code/game/objects/items/weapons/pan.dm
  code/game/objects/objs.dm
  code/modules/food/customizables.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
  code/modules/supermatter/supermatter.dm
  vgstation13.dme
Labels: System

#36192 The Stranger Vault
  code/modules/randomMaps/vault_definitions.dm
  maps/randomvaults/thestranger.dmm
Labels: Mapping (Vault :question:)

#36193 Winning Vaults Added
  code/modules/randomMaps/vault_definitions.dm
  maps/randomvaults/ButtonPusher.dmm
  maps/randomvaults/pod_dock_crash.dmm
Labels: Mapping (Vault :question:)

#36004 Clicking improvements for combat
  code/_onclick/click.dm
  code/_onclick/drag_drop.dm
  code/modules/client/client defines.dm
Labels: Bug / Fix, Gameplay / Gamemode, Secret repo conflict.

#36179 A human's head will now always drop when they are gibbed
  code/modules/mob/living/carbon/human/death.dm
Labels: Balance

#36212 Transit tube station fixes
  code/game/objects/structures/transit_tubes/station.dm
  code/game/objects/structures/transit_tubes/transit_tube.dm
Labels: Bug / Fix

#36209 Makes autoharvest happen as soon as produce is ready
  code/modules/hydroponics/hydro_tray_process.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: Bug / Fix

#36206 Pulse demons now ignore vines properly
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
Labels: Bug / Fix

#36205 Some grammar and formatting fixes
  code/game/gamemodes/blob/blobs/core.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/paperwork/papers_preformatted.dm
  code/modules/projectiles/projectile/gravitywell.dm
Labels: Bug / Fix, Grammar / Formatting

#36194 chicken suit hides tail
  code/modules/clothing/suits/miscellaneous.dm
Labels: Bug / Fix

#36214 Blob quarantine typo fix
  code/datums/gamemode/factions/blob.dm
Labels: Grammar / Formatting

#36189 tail attach retractor step only works on non-opened groins
  code/modules/surgery/tail.dm
Labels: Bug / Fix

#36202 Wall peeping fixes
  code/game/turfs/simulated/walls.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Bug / Fix

#36215 Fixed Tailed Species Invis Issues
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug / Fix

#36241 Fix's mimes using telepathy
  code/game/dna/genes/powers.dm
Labels: Bug / Fix

#36242 Fixes godmode not preventing pressurised lung ruptures
  code/modules/mob/living/carbon/human/life/handle_breath.dm
Labels: Bug / Fix, Consistency Issue

#36244 revert "remove attack delay affecting picking up and storing/retrieving items"
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects.dm
Labels: Bug / Fix

#36245 Valuable asteroids will now properly recycle
  code/game/objects/items/weapons/misc.dm
Labels: Bug / Fix, 0% tested

#36247 Renames arcade machines on emag
  code/game/machinery/computer/arcade/arcade_game.dm
Labels: Bug / Fix

#36250 Fixes wallrot event can_start()
  code/modules/events/wallrot.dm
Labels: Bug / Fix

#36252 Fixes gold slime extract mimic behaviour in grenades
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#36267 Circulator Crate Description Fix
  code/datums/supply_packs/engineering.dm
Labels: Bug / Fix, Grammar / Formatting

#36263 Book of the Long Sun religion
  code/datums/religions.dm
Labels: Content

#36237 Makes sensed explosions show up on bhangmeter database properly without holominimaps
  code/controllers/subsystem/init/more_init_stuff.dm
  code/modules/html_interface/map/station_map.dm
Labels: Bug / Fix, Runtime Log

#36238 Fixes wall reset_view() runtime
  code/game/turfs/simulated/walls.dm
Labels: Runtime Log

#36243 HF machete's anti kudzu properties now also applies to powercreeper
  code/game/objects/items/weapons/melee/energy.dm
Labels: Balance

#36251 Plant analyzers now give more detailed information.
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydroponics_reagents.dm
Labels: ❤️ Quality of Life ❤️, 100% tested

#36253 Makes "on station" a bit more literal and inclusive for scoreboards
  code/game/gamemodes/endgame/scoreboard/department_score.dm
  code/game/gamemodes/endgame/scoreboard/scoreboard.dm
  code/game/objects/effects/decals/cleanable.dm
Labels: Tweak

#36234 Appearance bans block showing flavor text in game
  code/modules/mob/living/carbon/human/human.dm
Labels: Consistency Issue, Tweak

#36233 Fixes missing attack verbs breaking grammar
  code/game/objects/breakable.dm
Labels: Bug / Fix, Grammar / Formatting

#36229 Allows pulse demons to be affected by ion projectiles directly
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
Labels: Balance, Gameplay / Gamemode, Tweak

#36232 Fixes lazarus injectors not working on held mobs
  code/_onclick/item_attack.dm
  code/modules/mining/mine_items.dm
Labels: Bug / Fix, Grammar / Formatting

#36273 Wiz card descriptions now only show when flipped
  code/modules/games/cards/wizard_cards.dm
Labels: Bug / Fix, Consistency Issue

#36221 Vox raider non-shuttle deletion fix
  code/datums/gamemode/factions/vox_shoal.dm
Labels: Bug / Fix

#36218 Easier alt click window and railing rotation
  code/game/objects/structures/railings.dm
  code/game/objects/structures/window.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#36220 Allows kinetic accelerator warp vouchers in miner belts
  code/game/objects/items/weapons/storage/belt.dm
Labels: Consistency Issue, Tweak

#36261 greytide improvements, implant improvements, and some critical fixes
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/implants/types/greytide_implant.dm
Labels: Bug / Fix, 100% tested

#36262 Sundays in April are also April Fool's Day
  code/game/gamemodes/events/holidays/Holidays.dm
Labels: Honk, Balance

#36163 Grues should hopefully always force their victims to drop their items now
  code/modules/mob/living/simple_animal/hostile/grue.dm
Labels: Bug / Fix

#36203 Fixes cargo crate forwards not treating stacked items right
  code/controllers/subsystem/supply_shuttle.dm
  code/game/cargo_forwarding.dm
Labels: Bug / Fix

#36207 Processor conveyor actions now only check if humans are lying down
  code/game/machinery/kitchen/processor.dm
Labels: Bug / Fix

#36213 allow admins to force extended ruleset in dynamic
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Bug / Fix, Logging / Administration

#36219 More quick equip compatiability and fixes
  code/game/objects/items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart/cart.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/cash.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/clothing.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/gun.dm
Labels: Content, Tweak

#36231 Moves nukeop and rev score info to their respective factions on board
  code/datums/gamemode/factions/faction.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/syndicate/rev.dm
  code/datums/gamemode/objectives/escape.dm
  code/game/gamemodes/endgame/scoreboard/antag_score.dm
  code/game/gamemodes/endgame/scoreboard/scoreboard.dm
  code/game/gamemodes/nuclear/nuclearbomb.dm
Labels: Bug / Fix, Tweak

#36225 Multi-Z look up verb
  __DEFINES/_macros.dm
  code/modules/mob/mob.dm
  code/modules/multiz/_HELPERS.dm
  code/modules/multiz/movement.dm
Labels: Content

#36222 Makes pulse demons not affected by bee stings or thrown pies
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/game/objects/items.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
Labels: Bug / Fix

#36289 Fixes keycard vault load error message
  maps/randomvaults/keycard_vault.dm
Labels: Bug / Fix, Mapping (Vault :question:)

#36282 Fixes most known occurences of "The the" in messages
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/legacy_cult/runes.dm
  code/datums/gamemode/role/ninja.dm
  code/game/machinery/antiquemattersynth.dm
  code/game/machinery/atmoalter/vaporizer.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/shieldgen.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/structures/blobvolcano.dm
  code/modules/clothing/spacesuits/grey_rig.dm
  code/modules/media/broadcast/transmitters/broadcast.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  code/modules/mob/living/simple_animal/hostile/necro.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/vox.dm
  code/modules/multiz/structures.dm
  code/modules/paperwork/nano_paper_bin.dm
  code/modules/power/gourmonger.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/research/mechanic/reverse_engine.dm
Labels: Grammar / Formatting

#36288 BOTLS bible fix
  code/datums/religions.dm
Labels: Bug / Fix

#36230 Pulse demon possession fixes
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_attack.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
Labels: Bug / Fix, Tweak

#36248 Animal recycler fixes
  code/game/machinery/kitchen/monkeyrecycler.dm
  code/modules/mob/living/simple_animal/hostile/gym_rats.dm
Labels: Bug / Fix, Grammar / Formatting

#36249 Fixes glass tile floor parallax and decals
  code/game/objects/effects/decals/floor_decals.dm
  code/game/turfs/simulated/floor_glass.dm
  code/game/turfs/turf.dm
  code/modules/multiz/turfs.dm
Labels: Bug / Fix

#36295 Snowbox improvements and fixes
  code/modules/multiz/turfs.dm
  maps/tgstation-snow.dmm
Labels: Bug / Fix, Tweak, Mapping (Snowbox 🧊 )

#36279 Railing fixes
  __DEFINES/planes+layers.dm
  __DEFINES/setup.dm
  code/game/gamemodes/events/biomass.dm
  code/game/gamemodes/events/powercreeper.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/recharger.dm
  code/game/objects/effects/beam.dm
  code/game/objects/effects/decals/chemical_puff.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items.dm
  code/game/objects/structures/railings.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/media/broadcast/receivers/radio.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/simple_animal/bees/bees_mob.dm
  code/modules/mob/living/simple_animal/cricket.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/hostile/bigroach.dm
  code/modules/mob/living/simple_animal/hostile/grinch.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  code/modules/mob/living/simple_animal/hostile/viscerator.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/roach.dm
  code/modules/mob/living/simple_animal/snail.dm
  code/modules/projectiles/guns/hookshot.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  code/modules/reagents/splashplosion.dm
  code/modules/spells/aoe_turf/conjure/spore.dm
Labels: Bug / Fix, Tweak

#36290 Some clearer map element loading error messages
  code/datums/map_elements.dm
  code/modules/awaymissions/maploader/reader.dm
  code/modules/randomMaps/vaults.dm
Labels: Logging / Administration

#36236 Lamborghini Mob Update Icons [PHENOMENAL IMPROVEMENT]
  __DEFINES/setup.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_mobs_and_constructs.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/structures/mannequin.dm
  code/game/objects/structures/window.dm
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/tactical_light.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/dead/death.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/complex/martian/update_icons.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/mommi/update_icons.dm
  code/modules/mob/living/simple_animal/hologram/hologram.dm
  code/modules/mob/living/simple_animal/hologram/hologram_inventory.dm
  code/modules/mob/living/simple_animal/hostile/grinch.dm
  code/modules/overlays/mobs.dm
  code/modules/reagents/reagents/reagents_paint.dm
  code/modules/reagents/reagents/reagents_tools.dm
  icons/mob/OnFire.dmi
  icons/mob/horror.dmi
  vgstation13.dme
Labels: Honk, System
