Repository vgstation-coders/vgstation13, pull requests merged in 2024-06, with the labels that each got.

#36582 Bulk order empty lunchboxes from Cargo
  code/datums/supply_packs/hospitality.dm
Labels: 100% tested, Fluff :teddy_bear:

#36592 Adds the Golden Vault of the Space King to rotation
  code/modules/randomMaps/vault_definitions.dm
Labels: Mapping (Vault :question:)

#36594 Makes it so dexalin plus also works for hydroponics xenophysiology mutations.
  code/modules/reagents/reagents/reagents_medical.dm
Labels: Consistency Issue

#36618 Fire Heat Hotfix
  code/ZAS/Fire.dm
Labels: Hotfix

#36607 Gives pulse demon action to jump to any camera in an APC's area
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
Labels: ❤️ Quality of Life ❤️

#36625 Welding Fuel Ignites Instantly
  code/ZAS/Fire.dm
Labels: Tweak

#36626 Burning Mob Fix
  code/ZAS/Fire.dm
Labels: Bug / Fix

#36583 Firefoam Poppers
  code/game/machinery/firefoam_popper.dm
  code/modules/research/designs/boards/machine_engie.dm
  icons/obj/atmos.dmi
  sound/effects/hiss.ogg
  vgstation13.dme
Labels: Content

#36591 Paintable Atmos Suits
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
  icons/mob/head.dmi
  icons/mob/in-hand/left/clothing.dmi
  icons/mob/in-hand/right/clothing.dmi
  icons/mob/species/grey/head.dmi
  icons/mob/species/grey/suit.dmi
  icons/mob/species/insectoid/head.dmi
  icons/mob/species/insectoid/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Content

#36600 makes welderbombs not give bubble sound or message on heating anymore
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix, Tweak

#36640 remove antique matter synthesizer access requirements
  code/game/machinery/antiquemattersynth.dm
Labels: Tweak

#36605 Wizard stuff fixes
  code/datums/gamemode/role/rambler.dm
  code/game/dna/genes/goon_disabilities.dm
  code/game/dna/genes/goon_powers.dm
  code/game/dna/genes/powers.dm
  code/game/gamemodes/wizard/artefact.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/simple_animal/hostile/arcane_golem.dm
  code/modules/mob/living/simple_animal/hostile/grue_powers.dm
  code/modules/spells/general/lightning.dm
  code/modules/spells/spell_code.dm
  code/modules/spells/targeted/buttbots_revenge.dm
  code/modules/spells/targeted/card.dm
  code/modules/spells/targeted/disease.dm
  code/modules/spells/targeted/disorient.dm
  code/modules/spells/targeted/enthrall.dm
  code/modules/spells/targeted/equip/cape.dm
  code/modules/spells/targeted/equip/clowncurse.dm
  code/modules/spells/targeted/equip/frenchcurse.dm
  code/modules/spells/targeted/equip/horsemask.dm
  code/modules/spells/targeted/equip/robesummon.dm
  code/modules/spells/targeted/fist.dm
  code/modules/spells/targeted/flesh_to_stone.dm
  code/modules/spells/targeted/genetic.dm
  code/modules/spells/targeted/heal.dm
  code/modules/spells/targeted/hypnotise.dm
  code/modules/spells/targeted/ice_barrage.dm
  code/modules/spells/targeted/invoke_emotion.dm
  code/modules/spells/targeted/mind_transfer.dm
  code/modules/spells/targeted/parrotmorph.dm
  code/modules/spells/targeted/projectile/projectile.dm
  code/modules/spells/targeted/punch.dm
  code/modules/spells/targeted/retard.dm
  code/modules/spells/targeted/roidrat_punch.dm
  code/modules/spells/targeted/shoesnatch.dm
  code/modules/spells/targeted/summon_snacks.dm
  code/modules/spells/targeted/targeted.dm
  code/modules/spells/targeted/wrap.dm
Labels: Bug / Fix

#36598 Fixes grues and pulse demons freezing in place after jaunting from cages
  code/game/objects/structures/mouse_cage.dm
  code/modules/mob/living/simple_animal/hostile/grue.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
Labels: Bug / Fix, Hotfix

#36606 Patron Des Arts tweak
  code/game/machinery/vending.dm
Labels: Fluff :teddy_bear:

#36634 Shuttle wall destruction fixes
  code/game/turfs/simulated/shuttle.dm
  code/game/turfs/simulated/walls.dm
Labels: Bug / Fix

#36587 pulse demon balance
  code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
  code/modules/power/cable.dm
  code/modules/power/powernet.dm
Labels: Balance, Gameplay / Gamemode

#36616 Fixes lighting on shuttle diagonal walls
  code/game/turfs/simulated/shuttle.dm
  icons/lighting/moody_lights.dmi
Labels: Bug / Fix

#36573 Lambo open space overlays
  code/modules/multiz/turfs.dm
Labels: Performance

#36611 Ghost follow and teleport fixes
  code/datums/emotes.dm
  code/datums/recruiter.dm
  code/game/gamemodes/blob/overmind.dm
  code/game/objects/items/devices/PDA/apps/messenger.dm
  code/game/say.dm
  code/modules/bomberman/bomberman.dm
  code/modules/events/immovablerod.dm
  code/modules/events/old_vendotron_event/vendor_teleport_event.dm
  code/modules/hydroponics/seed_mobs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/death.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/alien/larva/alien_embryo.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/silicon/pai/recruit.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/borer/captive_brain.dm
  code/modules/mob/say.dm
  code/modules/power/singularity/singularity.dm
  goon/code/datums/browserOutput.dm
Labels: Bug / Fix

#36595 Allows more decals to be painted with the tile painter
  code/modules/RCD/schematics/tile.dm
  icons/effects/floor_decals.dmi
Labels: Sprites, Content

#36621 Stops AI jobbanned players from accepting malf
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/client/preferences.dm
Labels: Bug / Fix

#36461 Scoreboard purchase display fixes
  code/datums/gamemode/role/changeling.dm
  code/datums/gamemode/role/pulsedemon.dm
  code/datums/gamemode/role/role.dm
  code/datums/gamemode/role/summonsurvivors.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/gamemode/role/wizard.dm
  code/datums/gamemode/role/wizard_apprentice.dm
Labels: Consistency Issue, Grammar / Formatting

#36623 Speeds up lights on at roundstart
  code/controllers/configuration.dm
  code/game/area/areas.dm
  code/game/gamemodes/gameticker.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/power/lighting/lighting.dm
  config-example/config.txt
  icons/lighting/moody_lights.dmi
  icons/obj/power.dmi
Labels: Performance, ❤️ Quality of Life ❤️

#36604 Makes plastic flap, airshield and beach water mouse clicking easier to deal with
  code/game/objects/structures/airshield.dm
  code/game/objects/structures/flaps.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/unsimulated/beach.dm
  icons/obj/stationobjs.dmi
Labels: ❤️ Quality of Life ❤️

#36635 Vampires don't get as much usable blood out of their victims anymore
  code/datums/gamemode/role/vampire_role.dm
  code/modules/reagents/reagents/reagents_bio.dm
Labels: Balance, Gameplay / Gamemode, Tweak

#36636 Plague mice will now get a message detailing their virus details when spawning
  code/datums/gamemode/factions/plague_mice.dm
Labels: ❤️ Quality of Life ❤️

#36637 Made the Plague Mice disease far more dangerous
  code/datums/gamemode/factions/plague_mice.dm
Labels: Balance, Gameplay / Gamemode

#36638 Cleans up mineral spread runtime
  code/modules/mining/mine_turfs.dm
Labels: Runtime Log

#36639 Ninjas will now always hit what they're aiming for.
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/human/combat.dm
  code/modules/mob/living/combat.dm
Labels: Balance, Tweak

#36641 Fixes problems regarding hitting missing limbs
  code/modules/mob/living/carbon/combat.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/organs/organ_external.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#36664 Fixes deadchat message formatting
  code/modules/mob/say.dm
Labels: Bug / Fix

#36628 Midround rulesets now have an initial delay of 30 minutes before they can fire
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic.dm
Labels: Balance

#36683 logging of player numbers at roundstart
  code/game/gamemodes/gameticker.dm
Labels: Logging / Administration

#36633 Improved wizard & survivor scoreboard and a few other things
  code/datums/gamemode/role/summonsurvivors.dm
  code/datums/gamemode/role/wizard.dm
  code/datums/gamemode/role/wizard_apprentice.dm
  code/game/gamemodes/wizard/apprentice_contract.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/game/gamemodes/wizard/spellbook.dm
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/modules/spells/targeted/absorb.dm
Labels: Bug / Fix

#36660 Fixes light tube and bulb layering
  code/modules/power/lighting/lighting.dm
Labels: Consistency Issue

#36619 Secret Repo Decommissioning 1: Cult Runes
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells_special.dm
Labels: File Cleanup

#36620 Secret Repo Decommissioning 2: Custom Harm Alarm Lines
  __DEFINES/global.dm
  code/game/objects/items/robot/robot_items/robot_harm_alarm.dm
  config-example/custom_lines.txt
Labels: File Cleanup

#36374 Cryo tube gib and output fixes
  __DEFINES/atom_locking_and_control.dm
  code/ATMOSPHERICS/atmospherics.dm
  code/datums/locking_category.dm
  code/game/atoms_movable.dm
  code/game/machinery/cryo.dm
  code/game/objects/effects/gibs.dm
  code/modules/organs/organ_external.dm
  nano/templates/cryo.tmpl
Labels: Bug / Fix, Oversight, Consistency Issue

#36676 FIXES BAGULOOSE QUICK EQUIP EXPLOIT
  code/game/objects/items/weapons/storage/bluespace.dm
Labels: Bug / Fix, ⚠️ OH GOD IT'S LOOSE ⚠️, Exploitable

#36670 Adds a lower bound on mols of oxygen for combustion
  code/ZAS/Fire.dm
Labels: Bug / Fix, Tweak

#36627 Secret Repo Decommissioning 3: Account Age Checks
  code/_secrets.dm
  code/modules/atmos_automation/console.dm
  code/modules/mob/new_player/new_player.dm
Labels: File Cleanup

#36684 Makes deconstructing reinforced walls a bit faster
  code/game/turfs/simulated/walls_reinforced.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#36672 Fixes mythril coins recycling but giving no mythril.
  code/modules/mining/ores_coins.dm
Labels: Bug / Fix, Oversight

#36718 Possible fix to boomerangs killing the server
  code/game/objects/items/weapons/boomerang.dm
Labels: Bug / Fix, Oversight

#36659 Cleans up disintegrator ray code
  code/modules/mob/living/simple_animal/hostile/human/grey.dm
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  code/modules/projectiles/guns/energy/disintegrator.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Bug / Fix, File Cleanup

#36682 Converts hand and mop washing in sinks to normal action delays
  code/game/objects/structures/watercloset.dm
Labels: Consistency Issue

#36671 Machine frame stack component adding cleanup
  code/game/machinery/constructable_frame.dm
Labels: Bug / Fix, Tweak

#36685 Tones down the mouse plague
  code/datums/gamemode/factions/plague_mice.dm
Labels: Balance, Feature Loss, Tweak

#36688 AI grues will now respect the egg-laying config
  code/modules/mob/living/simple_animal/hostile/grue.dm
Labels: Bug / Fix, Honk

#36695 Fixes possible molar ratio runtime
  code/ZAS/_gas_mixture.dm
Labels: Runtime Log

#36698 Attempts to fix CWC apprentices
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/wizard/apprentice_contract.dm
Labels: Bug / Fix, 0% tested

#36712 reduced AAC restrictions
  code/modules/atmos_automation/console.dm
Labels: Tweak

#36692 Slightly better Push code
  code/modules/spells/targeted/push.dm
Labels: Bug / Fix

#36724 fixes colour mishap
  code/modules/reagents/reagents/reagents_medical.dm
Labels: Bug / Fix, Hotfix

#36707 Makes lightswitch right click icon better looking
  icons/lighting/moody_lights.dmi
Labels: Sprites

#36729 Fixes IED casings being deleted when not made in hands
  code/game/objects/items/weapons/grenades/ghettobomb.dm
Labels: Bug / Fix

#36696 Magic is stored in the brain
  code/game/gamemodes/wizard/spellbook.dm
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/surgery/butt.dm
Labels: Balance, Feature Loss, Tweak

#36700 Adds an Alert Message to Silicons
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/mommi/login.dm
  code/modules/mob/living/silicon/robot/login.dm
Labels: Logging / Administration
