Repository vgstation-coders/vgstation13, pull requests merged in 2024-09, with the labels that each got.

#37035 Cigarette Hotfix
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Bug / Fix, Hotfix

#37027 Fixes anim() interaction with firedoor causing them to become crossable
  __DEFINES/atom_locking_and_control.dm
  code/datums/locking_category.dm
  code/game/turfs/turf_flick_animations.dm
Labels: Bug / Fix

#37026 Fixes Door Moody Lights
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
Labels: Bug / Fix

#37032 Fixes Richter gloves
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Hotfix

#37033 Fixes stuff landing in disposals through windows
  code/modules/recycling/disposal.dm
Labels: Bug / Fix

#36997 Makes gun targeting actually work with item and vehicle usage
  code/_hooks/events.dm
  code/game/atoms.dm
  code/game/mecha/mecha.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/targeting.dm
Labels: Bug / Fix

#37043 Fixes stack materials not updating when in storage
  code/game/objects/items/weapons/storage/storage.dm
Labels: Bug / Fix

#37044 Full Client Build Logging
  code/modules/mob/login.dm
Labels: Logging / Administration

#37045 Silicons Burning & Endless Smoke Fixes
  code/ZAS/Fire.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/objs.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Bug / Fix

#36963 Insulted gloves that call you names and insult you when you get shocked.
  code/game/machinery/vending.dm
  code/modules/clothing/gloves/color.dm
  code/modules/power/powernet.dm
Labels: Honk, Content

#37048 Makes self heating cup ramen saner
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: ❤️ Quality of Life ❤️, Consistency Issue, Grammar / Formatting, Tweak

#37018 Adds attack sounds for pickaxes and derived tools
  code/game/objects/items/robot/robot_items/robot_axe.dm
  code/modules/mining/mine_items.dm
Labels: Oversight, Sound

#37020 Adds hostile mob spawn logging to mob cubes
  code/modules/reagents/reagent_containers/food/mobcube.dm
Labels: Consistency Issue, Logging / Administration

#37021 Allows mobs forcemoved into wooden crates to spawn when pried open
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Consistency Issue, Logging / Administration

#37023 You can now empty ashtrays in disposals
  code/game/objects/items/ashtray.dm
  code/game/objects/items/trash.dm
  code/modules/recycling/disposal.dm
  icons/ashtray.dmi
  icons/obj/trash.dmi
Labels: Sprites, ❤️ Quality of Life ❤️

#37024 Paintable Clay Pots & Easier Recipe
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/flora/flora.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydro_tray.dm
  icons/mob/in-hand/left/misc_tools.dmi
  icons/mob/in-hand/right/misc_tools.dmi
  icons/obj/hydroponics/hydro_tools.dmi
Labels: Content, ❤️ Quality of Life ❤️, Fluff :teddy_bear:

#37028 Better Area Alert Visuals
  code/game/area/areas.dm
Labels: Sprites, ❤️ Quality of Life ❤️

#37072 Fixes issue with airlocks blinking their lights in areas that don't have dynamic lighting
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
Labels: Bug / Fix, Hotfix

#37038 Allows medical belts to hold thermometers and stethoscopes
  code/game/objects/items/weapons/storage/belt.dm
Labels: Consistency Issue

#37031 Makes timers and proximity sensors actually count down to the second from activation
  code/modules/assembly/holder.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/timer.dm
Labels: Bug / Fix

#37015 Mapping verb cleanup
  __DEFINES/tick.dm
  code/controllers/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/mapping.dm
  config-example/config.txt
  maprendering/maprendering.dm
Labels: ❤️ Quality of Life ❤️

#37067 Gives Admins Power to VV Gun Projectile Variables
  code/game/machinery/turrets.dm
  code/modules/admin/admin_verbs.dm
  code/modules/projectiles/gun.dm
Labels: Content, Logging / Administration

#37079 Fixes borgs catching on fire during repairs
  code/game/objects/items/weapons/tools.dm
  code/modules/mob/living/silicon/robot/life.dm
Labels: Hotfix

#37077 Fixes beartraps on the meteorological vault
  maps/randomvaults/meteorlogical_station.dmm
Labels: Mapping (Vault :question:)

#37070 Secret Repo Decommissioning 6: secret_hwaccel_check
  code/modules/client/secret_hwaccel_check.dm
  icons/secret/x.png
  vgstation13.dme
Labels: Secret repo conflict., File Cleanup

#37068 Secret Repo Decommissioning 4: get_rev()
  code/controllers/configuration.dm
  code/datums/helper_datums/getrev.dm
  config-example/config.txt
Labels: Secret repo conflict., File Cleanup

#37088 Secret Repo Decommissioning 7: client defines
  code/datums/helper_datums/getrev.dm
  code/modules/client/client defines.dm
  config-example/config.txt
Labels: Secret repo conflict., File Cleanup

#37089 Secret Repo Decommissioning 8: client procs
  code/controllers/configuration.dm
  code/modules/client/client procs.dm
  config-example/config.txt
Labels: Secret repo conflict., File Cleanup

#37084 Fixes butchering drops on various robot type simplemobs
  maps/randomvaults/objects.dm
  maps/randomvaults/spessmart.dm
Labels: Bug / Fix, Consistency Issue

#37116 Fixes runtime in paint_overlay.dm
  code/game/turfs/paint_overlay.dm
Labels: Bug / Fix, Runtime Log

#37123 Fixes Plasmaman Suit Spam
  code/modules/mob/living/carbon/human/species/plasmaman.dm
Labels: Bug / Fix, Hotfix

#37074 Suit Modification Station Quality of Life Pass
  code/game/machinery/suit_modifier.dm
  icons/obj/stationobjs.dmi
Labels: Bug / Fix, Sprites, Sound

#37082 Plate cutting fixes
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#37085 Adds blind messages for forcefeeding
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Oversight

#37127 Updates TGUI bundle & yarn
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: File Cleanup

#37126 Adds bunker.txt to .gitignore
  data/.gitignore
Labels: File Cleanup

#37131 Runtime cleanups
  code/game/objects/items.dm
  code/modules/client/global cache.dm
  code/modules/events/old_vendotron_event/vendor_teleport_event.dm
  code/modules/hydroponics/seed_datums.dm
Labels: Runtime Log, File Cleanup

#37096 Fixes snowball projectiles having been invisible for the past 9 years
  code/game/gamemodes/endgame/xmas/snowman.dm
Labels: Bug / Fix

#36357 Disposal bin shortcuts
  code/modules/recycling/disposal.dm
Labels: ❤️ Quality of Life ❤️

#37099 Fixes a ton of sentence starts with non capitalised improper nouns.
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/defines/obj/weapon.dm
  code/game/cargo_forwarding.dm
  code/game/dna/dna_modifier.dm
  code/game/gamemodes/endgame/xmas/snow.dm
  code/game/gamemodes/endgame/xmas/snowman.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/bees_apiary.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/cryo.dm
  code/game/machinery/kitchen/monkeyrecycler.dm
  code/game/machinery/landline.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/telecomms/multicaster.dm
  code/game/machinery/wishgranter.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/devices/healthanalyzerpro.dm
  code/game/objects/items/movable_dispenser.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/weapons/airlock_painter.dm
  code/game/objects/items/weapons/soap.dm
  code/game/objects/items/weapons/storage/RPED.dm
  code/game/objects/structures/vehicles/adminbus.dm
  code/modules/RCD/RCD.dm
  code/modules/RCD/RPD.dm
  code/modules/food/cooking_machines.dm
  code/modules/medical/autopsy.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/hostile/balloon.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/effects.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/nurse.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/painting/paintings_custom.dm
  code/modules/power/rust/gyrotron.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/projectile/stickylauncher.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/gravitywell.dm
  code/modules/projectiles/projectile/ricochet.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/recycling/disposal.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
  code/modules/research/xenoarchaeology/tools/suspension_generator.dm
  code/modules/spells/targeted/hypnotise.dm
  code/modules/telesci/rcs.dm
  code/modules/trader/crates/zincsaucier.dm
Labels: Grammar / Formatting

#37111 Collared Security Jumpsuit Sprite Fix/Additions
  code/modules/clothing/under/jobs/security.dm
  icons/mob/species/grey/uniform.dmi
  icons/mob/species/vox/uniform.dmi
  icons/mob/uniform.dmi
Labels: Sprites

#37103 Admin VV Typesetting Changes
  code/__HELPERS/lists.dm
  code/datums/datumvars.dm
  code/game/machinery/turrets.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/roulette.dm
Labels: Bug / Fix, Logging / Administration

#37147 Fixes OpenDream Linters
  code/datums/uplink_item.dm
  code/game/atoms_movable.dm
  code/game/dna/dna_modifier.dm
  code/game/dna/genes/goon_powers.dm
  code/game/machinery/atmo_control.dm
  code/game/machinery/rechargestation.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/logbrowser.dm
  code/game/machinery/telecomms/telemonitor.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/Economy/debit_card.dm
  code/modules/admin/buildmode.dm
  code/modules/media/jukebox.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/power/solars/panel.dm
  code/modules/spells/general/area_teleport.dm
  code/modules/trader/crates/zincsaucier.dm
Labels: Bug / Fix, 0% tested, OpenDream

#37110 Fixes Odd Damage Behaviors
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/organ_external.dm
Labels: Bug / Fix, Balance

#37104 Makes chocolate, avocados, peanuts, garlic and grapes harmful to dogs (plus their products)
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/reagents/reagents/reagents_drink.dm
  code/modules/reagents/reagents/reagents_food.dm
Labels: Content, Muh Immulsions

#37118 Fixes area overlays being additive when using blueprints or admin buildmode
  code/game/objects/items/blueprints.dm
  code/modules/admin/buildmode.dm
Labels: Bug / Fix

#37138 Advanced pocket satellite vault
  maps/randomvaults/advanced_pocketsat.dm
  maps/randomvaults/advanced_pocketsat.dmm
  vgstation13.dme
Labels: Mapping (Vault :question:)

#37137 Adds More Ways to Stop No Shoe Slowdown
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Balance, Consistency Issue

#37168 Fixes Infinite Respawns
  code/modules/mob/living/carbon/brain/brain.dm
Labels: Bug / Fix, Hotfix, Exploitable

#37125 Plated Catwalks
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/turf.dm
  icons/obj/tiles.dmi
  icons/turf/catwalks.dmi
Labels: Content, Port

#37149 Linter Improvements
  .github/workflows/ci.yml
  .gitignore
  ___odlint.dm
  dependencies.sh
  tools/bootstrap/python
  tools/bootstrap/python36._pth
  tools/bootstrap/python_.ps1
  tools/ci/annotate_dm.sh
  tools/ci/annotate_od.sh
  tools/ci/od_lints.dm
  tools/dm_annotator/__main__.py
  tools/od_annotator/__main__.py
  tools/requirements.txt
  vgstation13.dme
Labels: Port, Automation/CI, OpenDream

#37151 Crate Shelves
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/table_rack_parts.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crateshelf.dm
  code/modules/mob/living/living.dm
  icons/obj/items.dmi
  icons/obj/objects.dmi
  vgstation13.dme
Labels: Content, Port

#37136 The Honkgiver [Ready for Review]
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/lawgiver.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/honkgiver_projectiles.dm
  code/modules/projectiles/projectile/ricochet.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  icons/obj/projectiles.dmi
  sound/effects/boink.ogg
  sound/effects/doomlazor.ogg
  sound/effects/pop_toony.ogg
  sound/effects/squeeze_pop.ogg
  vgstation13.dme
Labels: Gameplay / Gamemode

#37142 N2 Locker Additions
  __DEFINES/reagents.dm
  code/game/objects/items/plushies.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents/reagents_medical.dm
  icons/mob/in-hand/left/items_lefthand.dmi
  icons/mob/in-hand/right/items_righthand.dmi
  icons/obj/plushie.dmi
  icons/obj/storage/storage.dmi
  icons/obj/syringe.dmi
Labels: Content
