Repository vgstation-coders/vgstation13, pull requests merged in 2024-04, with the labels that each got.

#36256 deployable dispenser for april fools
  code/game/objects/items/movable_dispenser.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  sound/items/dispenser_explode.wav
  sound/items/dispenser_generate_metal.wav
  sound/items/wrench_hit_build_success2.wav
  vgstation13.dme
Labels: Honk, Content

#36305 Adds a user pref to enable pixel movement
  code/modules/client/preferences.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob_movement.dm
Labels: Controversial, Honk, Balance, T-Thanks BYOND, Content, System, 100% tested, Tweak, why, Verified :white_check_mark:

#36303 pedestale -> pedestal
  code/game/objects/items/trash.dm
Labels: Grammar / Formatting

#36274 Fixes human cube interaction with ez bake machines
  code/modules/food/cooking_machines.dm
Labels: Bug / Fix, 100% tested

#36314 Fixes Get Flat Icon Deluxe failing to grab any of the icon's overlays or underlays. Fixing Photography and Photo Booth.
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
Labels: Bug / Fix

#36320 Fixes derelict MoMMI laws when spawning
  code/game/machinery/mommi_spawner.dm
Labels: Bug / Fix, 100% tested

#36332 Fixes reagent scanner showing time in system on non mobs
  code/game/objects/items/devices/scanners.dm
Labels: Bug / Fix, Grammar / Formatting

#36339 Revert "Sundays in April are also April Fool's Day"
  code/game/gamemodes/events/holidays/Holidays.dm
Labels: Hotfix

#36312 fix slimepeople still showing on CMC after death
  code/modules/mob/living/carbon/species.dm
Labels: Bug / Fix

#36319 weak sport chems buff
  __DEFINES/setup.dm
Labels: Balance, Tweak

#36321 Prevents ore processors from working as flatpacks
  code/modules/mining/machine_processing.dm
Labels: Bug / Fix, 100% tested

#36322 You can now fill water balloons using sinks
  code/game/objects/items/toys.dm
  code/game/objects/structures/watercloset.dm
Labels: Consistency Issue, 100% tested

#36323 Fixing missing hair from the round end scoreboard and probably other places
  code/_onclick/mindUI/adminbus.dm
  code/datums/datacore.dm
  code/datums/gamemode/role/role.dm
  code/datums/hud/account_hud.dm
  code/game/gamemodes/endgame/scoreboard/department_score.dm
  code/game/gamemodes/endgame/scoreboard/misc_score.dm
  code/game/gamemodes/gameticker.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/hologram.dm
  code/game/mecha/mecha_control_console.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
  code/libs/Get Flat Icon/Get Flat Icon.dm
  code/modules/food/cooking_machines.dm
  code/modules/food/customizables.dm
  code/modules/paperwork/photography.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  goon/code/datums/browserOutput.dm
Labels: Bug / Fix

#36329 Makes suicides show proper unrevivable message on scanners and HUDs
  code/modules/mob/living/carbon/carbon.dm
Labels: Bug / Fix, Consistency Issue

#36347 partial revert of #36066
  code/modules/RCD/RPD.dm
Labels: Bug / Fix

#36358 Fixes PDA messaging while dead
  code/game/objects/items/devices/PDA/apps/messenger.dm
Labels: Bug / Fix, Sanity / Ghosthands

#36316 Removes minimum population requirement for Meta
  code/datums/next_map.dm
Labels: Mapping (Meta :no_mobile_phones:), Tweak

#36376 Fixes Dimensional Push Apocalypse
  code/modules/spells/targeted/push.dm
Labels: Hotfix, 0% tested

#36331 Fixes diagonal shuttle walls not meson updating on transit
  code/_hooks/events.dm
  code/datums/hud/meson_hud.dm
Labels: Bug / Fix

#36333 Pulse demon cable zap fixes
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Bug / Fix, Tweak

#36351 Makes LAssailant a weakref
  code/__HELPERS/logging.dm
  code/__HELPERS/mobs.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/datums/gamemode/factions/legacy_cult/ritual.dm
  code/datums/gamemode/role/vampire_role.dm
  code/datums/statistics/documentation/statfile_1.0.md
  code/game/machinery/kitchen/gibber.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/robot/robot_items/robot_elec_arm.dm
  code/game/objects/items/stacks/packagewrap.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/dna_injector.dm
  code/game/objects/items/weapons/explosives.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/null_rod.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/slime/powers.dm
  code/modules/mob/living/combat.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/faguette.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/guns/projectile/constructable/swords.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/research/xenoarchaeology/tools/ano_device_battery.dm
  code/modules/runescape/runescape_pvp.dm
  code/modules/trader/crates/alcatrazfour.dm
  maps/randomvaults/mothership_lab.dm
Labels: Performance

#36379 Fixed a bug that allowed for possibly infinite implants, maybe.
  code/game/objects/items/weapons/implants/implant.dm
Labels: Bug / Fix

#36350 Fixes laser raycasts not properly deleting
  code/modules/projectiles/projectile/beams.dm
Labels: Performance, 100% tested

#36352 MoMMIs no longer drop modules when below 100 charge
  code/game/objects/items/devices/mat_synth.dm
  code/modules/mob/living/silicon/mommi/mommi_inventory.dm
Labels: Bug / Fix

#36353 Makes certain foods edible with spoons
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Consistency Issue

#36355 More cryotheum balancing and bugfixes.
  code/ATMOSPHERICS/hvac/cryotheum_resonator.dm
  code/ZAS/XGM_gases.dm
  code/ZAS/XGM_reactions.dm
  code/ZAS/Zone.dm
  code/game/turfs/turf.dm
Labels: Bug / Fix

#36356 Makes eye protecting head and eyewear protect monkeys too
  code/modules/mob/living/carbon/monkey/life.dm
Labels: Bug / Fix, Consistency Issue

#36370 Add DMI editor VSCode extension
  .vscode/extensions.json
Labels: ❤️ Quality of Life ❤️, Tools

#36385 Fixes mints taking two bites to eat
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Bug / Fix

#36389 Fixes runtimes on heaters
  code/ATMOSPHERICS/components/unary/heat_source.dm
Labels: Bug / Fix

#36387 Updates server revision finding info in issue template
  .github/ISSUE_TEMPLATE.md
Labels: Grammar / Formatting

#36393 Fixes glue becoming permanent when applied twice
  code/game/objects/items/weapons/clown_items.dm
Labels: Bug / Fix

#36382 Fixes crate weigher not going back up when pulled from under crate
  code/game/cargo_forwarding.dm
Labels: Bug / Fix, Consistency Issue

#36354 Fixes isolation centrifuge runtime
  code/modules/virus2/centrifuge.dm
Labels: Bug / Fix, Runtime Log

#36407 Adds admintesting pulse demon to mob blacklist
  __DEFINES/global.dm
Labels: Bug / Fix, Consistency Issue

#36406 Fixes runtime on clumsy checking
  code/game/objects/objs.dm
Labels: Bug / Fix, Consistency Issue, Runtime Log

#36404 Fixes gas sensor runtime on detecting no gases
  code/game/machinery/atmo_control.dm
Labels: Bug / Fix, Runtime Log

#36400 Fixes hair and facial hair always appearing black and on top on photos
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
Labels: Bug / Fix

#36378 Fire Breath and Ring of Fire are now unleashed.
  code/game/objects/effects/fire_blast.dm
  code/modules/spells/targeted/projectile/firebreath.dm
Labels: Balance, Content

#36416 Fixes some cult bugs
  code/datums/gamemode/factions/bloodcult/bloodcult_effects.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_rituals.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runes.dm
  code/datums/gamemode/role/cultist.dm
Labels: Bug / Fix

#36371 R&D UI cleanup
  code/modules/research/rdconsole.dm
  html/browser/common.css
Labels: UI

#36420 Fixes zeroes in station time
  code/__HELPERS/time.dm
Labels: Bug / Fix, Hotfix

#36424 Screwdriving False Walls Works and Does Not Runtime
  code/datums/hud/meson_hud.dm
  code/game/objects/structures/false_walls.dm
Labels: Bug / Fix, Runtime Log

#36087 The nasa, exca., anom. suits, and cult robes from xenoarch finds are now contained in boxes. These contain both pieces of the suits.
  code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/finds/finds_misc.dm
  code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
Labels: Balance, Content

#36428 actually enable new dmi editor extension
  .vscode/settings.json
Labels: Logging / Administration

#36396 added send back to lobby button on player panel
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Logging / Administration

#36362 Telekinesis sanity fixes
  code/_onclick/telekinesis.dm
  code/datums/helper_datums/construction_datum.dm
  code/defines/obj/weapon.dm
  code/game/gamemodes/endgame/xmas/snow.dm
  code/game/machinery/alarm.dm
  code/game/machinery/landline.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/items/stacks/misc.dm
  code/game/objects/items/weapons/pan.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/target_stake.dm
  code/game/objects/structures/transit_tubes/transit_tube_assembly.dm
  code/game/objects/structures/vehicles/janicart.dm
  code/game/objects/structures/vehicles/vehicle.dm
  code/game/turfs/simulated/snow.dm
  code/game/turfs/unsimulated/snow.dm
  code/modules/blacksmithing/misc_components.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/masks/transmog.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/library/lib_items.dm
  code/modules/medical/autopsy.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/mine_structures.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  code/modules/paperwork/fax.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/nano_paper_bin.dm
  code/modules/paperwork/paperbin.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/photography.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/lasmusket.dm
  code/modules/projectiles/guns/lawgiver.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/constructable/blastcannon.dm
  code/modules/projectiles/guns/projectile/constructable/blinder.dm
  code/modules/projectiles/guns/projectile/constructable/blunderbuss.dm
  code/modules/projectiles/guns/projectile/constructable/gunsmithing.dm
  code/modules/projectiles/guns/projectile/constructable/railgun.dm
  code/modules/projectiles/guns/projectile/constructable/revialver.dm
  code/modules/projectiles/guns/projectile/constructable/subspacetunneler.dm
  code/modules/projectiles/guns/projectile/constructable/swords.dm
  code/modules/projectiles/guns/projectile/constructable/tomahawk.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/recycling/conveyor_assembly.dm
  code/modules/research/xenoarchaeology/artifact/artifact_communication.dm
  code/modules/surgery/implant.dm
  code/modules/trader/trade_window.dm
  code/modules/virus2/diseasesplicer.dm
Labels: Bug / Fix, Sanity / Ghosthands

#36401 Exotic Seed crate tweak
  code/datums/supply_packs/hydroponics.dm
Labels: Tweak

#36402 Fixes racks dropping parts less frequently on less severe explosions
  code/game/objects/structures/tables_racks.dm
Labels: Bug / Fix, Consistency Issue

#36411 Adds [stationname], [logo] macros for paperwork, and station name to hop paperwork
  code/modules/paperwork/nano_paper.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/papers_preformatted.dm
  code/modules/paperwork/pen.dm
Labels: Content

#36415 Fixes drinking water extinguishing cigarettes
  code/modules/reagents/reagents/reagents_basic.dm
Labels: Bug / Fix

#36429 some GetFlatIconDeluxe fixes
  code/libs/Get Flat Icon/Get Flat Icon Deluxe.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bug / Fix

#36412 Shuttle Chair Next to Intercom Welder Fix
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Bug / Fix

#36426 Code cleanup of "chemCandH" file and minor visual bugfix.
  code/game/machinery/chemHandC.dm
  code/game/machinery/constructable_frame.dm
  code/modules/reagents/machinery/thermometer.dm
Labels: File Cleanup
