Repository vgstation-coders/vgstation13, pull requests merged in 2024-12, with the labels that each got.

#37329 Fat Robo Sprite Fix
  code/modules/organs/organ_external.dm
  icons/mob/human_races/o_robot.dmi
Labels: Bug / Fix

#37338 Fixes Map Spawner Hard Dels
  code/game/objects/effects/decals/floor_decals.dm
  code/modules/maps/spawners/pick_spawner.dm
  code/modules/maps/spawners/spawners.dm
Labels: Bug / Fix, Performance

#37341 Fixes cricket spawn
  code/modules/events/crickets.dm
Labels: Bug / Fix

#37334 Add new midround antag: the divergent clone
  __DEFINES/_macros.dm
  __DEFINES/role_datums_defines.dm
  code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
  code/datums/gamemode/factions/legacy_cult/cult.dm
  code/datums/gamemode/factions/plague_mice.dm
  code/datums/gamemode/factions/syndicate/nukeops.dm
  code/datums/gamemode/factions/vox_shoal.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/datums/gamemode/objectives/divergentclone.dm
  code/datums/gamemode/powers/powers.dm
  code/datums/gamemode/role/catbeast.dm
  code/datums/gamemode/role/divergentclone.dm
  code/datums/gamemode/role/syndicate.dm
  code/datums/mind.dm
  code/datums/outfit/outfit.dm
  code/game/jobs/job/whitelisted.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items/devices/PDA/cart/misc.dm
  code/game/objects/items/weapons/implants/types/adrenalin_implant.dm
  code/game/objects/items/weapons/implants/types/compressed_matter_implant.dm
  code/game/objects/items/weapons/implants/types/explosive_implant.dm
  code/game/objects/items/weapons/implants/types/freedom_implant.dm
  code/game/objects/items/weapons/implants/types/uplink_implant.dm
  code/modules/client/preferences.dm
  code/modules/medical/cloning.dm
  code/modules/medical/computer/cloning.dm
  code/modules/mob/living/carbon/alien/humanoid/death.dm
  code/modules/mob/living/carbon/alien/larva/death.dm
  code/modules/mob/living/carbon/brain/death.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/spells/changeling/absorb_dna.dm
  code/modules/spells/changeling/split.dm
  icons/logos.dmi
  vgstation13.dme
Labels: Gameplay / Gamemode
