Repository vgstation-coders/vgstation13, pull requests merged in 2025-06, with the labels that each got.

#37661 Itty Bitty ghettomed bugfix
  code/modules/surgery/organs_internal.dm
Labels: Grammar / Formatting, Legacy Bug

#37655 Milk hard dels, snacks hard dels, ghosts hard dels
  code/game/atoms.dm
  code/game/machinery/firefoam_popper.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/mecha/equipment/tools/tools.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/silicon/mommi/mommi.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/mothership_creatures.dm
  code/modules/paperwork/pen.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/spells/spell_code.dm
  code/modules/virus2/items_devices.dm
Labels: Performance

#37673 Fixes mobs runtiming on Destroy() on worldgen
  code/modules/mob/living/living.dm
Labels: Runtime Log

#37699 Fixes certain toggles not saving for admins & ex-admins
  code/modules/client/preferences/pref_datums.dm
Labels: Bug / Fix

#37709 Fixes limbs and organs not saving between round + other things
  code/modules/client/preferences/pref_datums_character.dm
  code/modules/client/preferences/preferences_ui.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Hotfix

#37701 Fixes Betris anti-cheat
  code/game/machinery/computer/tetris.dm
Labels: Bug / Fix

#37687 Fixes some DB queries failing on some systems
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
Labels: Bug / Fix

#37475 WELCOME TO THE JUNGLE
  __DEFINES/atmos.dm
  code/controllers/subsystem/daynightcycle.dm
  code/controllers/subsystem/lighting.dm
  code/datums/helper_datums/butchering.dm
  code/datums/next_map.dm
  code/datums/shuttle.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/alarm.dm
  code/game/objects/structures/flora/flora.dm
  code/game/objects/structures/ladder_jungle.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/jungle.dm
  code/modules/RCD/schematics/engineering_rcd.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/lighting/lighting_source.dm
  code/modules/luck/luck.dm
  code/modules/maps/spawners/jungle_spawns.dm
  code/modules/mob/living/simple_animal/friendly/jungle_capybara.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/dino.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/panther.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/mob/animal.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/decals.dmi
  icons/obj/map/spawners.dmi
  icons/turf/areas.dmi
  icons/turf/floors.dmi
  icons/turf/junglestation_plaque.xcf
  icons/turf/walls.dmi
  maps/_map.dm
  maps/junglestation.dm
  maps/junglestation.dmm
  maps/randomvaults/snaxi/snaxivault_defines.dm
  vgstation13.dme
Labels: Mapping (General :world_map:), Gameplay / Gamemode, Help Wanted, WiP

#37731 Fixes searches being borked on TGUI
  tgui/packages/tgui/interfaces/CameraConsole.tsx
  tgui/packages/tgui/interfaces/ChooseReligion.tsx
  tgui/packages/tgui/interfaces/Merch.tsx
  tgui/packages/tgui/interfaces/Uplink.tsx
Labels: Bug / Fix

#37669 Allows certain welders and solders to accept plasma and pacid respectively for faster work.
  code/game/machinery/constructable_frame.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/modules/Economy/Accounts.dm
  code/modules/media/broadcast/transmitters/broadcast.dm
  code/modules/reagents/Chemistry-Holder.dm
Labels: Content

#37754 fixed iced beer bug
  code/modules/reagents/reagents/reagents_ethanol.dm
Labels: Bug / Fix, Oversight

#37733 Gives kidneys a function, buffs advanced kidneys
  code/modules/organs/internal/kidney/filter.dm
Labels: Content, Tweak

#37763 hotfix: now you can print glock pepperball ammo
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/research/designs/weapons.dm
Labels: Hotfix

#37792 Removes stand_broken completely (unused, caused a warning)
  code/modules/organs/organ.dm
Labels: Hotfix

#37747 Adds AMAZING new burgers and sliders you MUST KNOW ABOUT
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
Labels: Content

#37822 fix sound runtime
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bug / Fix

#37824 fix derpspeech runtime
  code/modules/mob/mob_helpers.dm
Labels: Bug / Fix

#37825 fix lightreplacer runtime
  code/game/objects/items/devices/lightreplacer.dm
Labels: Bug / Fix

#37830 fix infinite zombies
  code/modules/projectiles/guns/energy/special.dm
Labels: Bug / Fix

#37826 fix candle runtime
  code/game/objects/items/trash.dm
Labels: Bug / Fix

#37775 Blacksmithing quality affects tool-use speed.
  __DEFINES/math_physics.dm
  code/game/objects/items.dm
  code/modules/blacksmithing/blacksmithing.dm
Labels: Balance, Content

#37864 View Variables Hotfix
  code/modules/admin/verbs/modifyvariables.dm
Labels: Bug / Fix, Hotfix, Logging / Administration, 100% tested

#37852 fix infinite money
  code/modules/Economy/Wages.dm
Labels: Bug / Fix

#37883 min to max for mob runtime
  code/modules/mob/living/simple_animal/hostile/human/halloween.dm
Labels: Hotfix
