Repository vgstation-coders/vgstation13, pull requests merged in 2025-03, with the labels that each got.

#37459 Linters
  code/modules/RCD/RCD.dm
  code/modules/RCD/engie.dm
  code/modules/RCD/schematics/engineering_rcd.dm
Labels: Automation/CI

#37314 Blowing on hot things and putting out item fire fixes
  code/game/objects/items.dm
  code/modules/reagents/reagent_containers.dm
Labels: Bug / Fix

#37317 Standardizes item blending, no refactor
  code/modules/reagents/machinery/mortar.dm
  code/modules/reagents/machinery/reagentgrinder.dm
Labels: Hotfix, Consistency Issue

#37453 Fix battlemat again
  code/modules/mob/inventory.dm
Labels: Bug / Fix

#37436 Create Racial Fallbacks
  code/modules/mob/living/carbon/human/species/vox.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bug / Fix, 100% tested

#37402 Makes vendors less likely to freeze up when trying to click links
  code/game/machinery/vending.dm
  code/modules/research/xenoarchaeology/artifact/artifact_vendor.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#37460 adds to and fixes yet more fission things
  code/controllers/subsystem/machinery.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/fissionreactor/fission_datums.dm
  code/modules/fissionreactor/fuelmaker.dm
  code/modules/fissionreactor/objects_external.dm
  code/modules/research/designs/boards/computer_engie.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#37462 N2O high temperature decomposition
  code/ZAS/XGM_reactions.dm
Labels: Controversial, Tweak

#37467 Fixes constant temperature runtimes
  code/game/objects/objs.dm
Labels: Bug / Fix, 0% tested

#37432 Enables items to be used while ventcrawling
  code/game/objects/items.dm
  code/game/objects/items/devices/sound_synth.dm
  code/modules/mob/mob.dm
  tgui/public/tgui-panel.bundle.js
Labels: Tweak

#37472 Arcane tampered closet escape balance hotfix
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/living/living.dm
Labels: Hotfix, Balance

#37463 New Clown Bikehorn: Ankh Horn
  code/game/objects/items/weapons/clown_items.dm
  code/modules/mining/ores_coins.dm
  icons/mob/in-hand/left/items_lefthand.dmi
  icons/mob/in-hand/right/items_righthand.dmi
  icons/obj/items.dmi
  sound/items/curseofra.ogg
Labels: Honk, Content, 0% tested

#37469 fixes some nu-RCD things
  code/modules/RCD/RCD.dm
  code/modules/RCD/engie.dm
  code/modules/RCD/schematics/engineering_rcd.dm
Labels: Bug / Fix, Hotfix

#37454 HOG!
  code/__HELPERS/mobs.dm
  code/datums/helper_datums/command_alerts.dm
  code/modules/events/spacehog.dm
  code/modules/mob/living/simple_animal/hostile/hog.dm
  vgstation13.dme
Labels: Content

#37482 chicken-of-the-stars now works as wheat for vox chickens
  code/modules/mob/living/carbon/monkey/vox.dm
Labels: Content
