Repository vgstation-coders/vgstation13, pull requests merged in 2025-07, with the labels that each got.

#37860 Mr. Laser (now conflict free!)
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/energy.dm
  icons/mob/in-hand/left/guninhands_left.dmi
  icons/mob/in-hand/right/guninhands_right.dmi
  icons/obj/gun.dmi
  icons/obj/projectiles.dmi
  sound/effects/mooninitebleep.ogg
  sound/weapons/mrlaser.ogg
Labels: Content

#37850 Fix fuel temp forgetfulness
  code/modules/blacksmithing/forge.dm
Labels: Bug / Fix, 0% tested

#37865 Crate Affordability Messaging Fix
  code/game/machinery/computer/cargo.dm
Labels: Bug / Fix, Grammar / Formatting, 100% tested

#37882 Fixes search function for 3/4 tgui interfaces
  tgui/packages/tgui/interfaces/CameraConsole.tsx
  tgui/packages/tgui/interfaces/ChooseReligion.tsx
  tgui/packages/tgui/interfaces/Merch.tsx
Labels: Bug / Fix, UI

#37869 fix breath runtimes
  code/modules/mob/living/carbon/human/life/handle_breath.dm
Labels: Bug / Fix

#37868 Machine upgrades add to roundend score
  __DEFINES/setup.dm
  code/game/gamemodes/endgame/scoreboard/department_score.dm
  code/game/gamemodes/endgame/scoreboard/scoreboard.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/weapons/storage/RPED.dm
  code/modules/research/mechanic/component_exchanger.dm
Labels: Content

#37904 Actually fixes the interfaces
  tgui/packages/tgui/interfaces/ChooseReligion.tsx
  tgui/packages/tgui/interfaces/Merch.tsx
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Bug / Fix, System, UI

#37921 Snaxi fixes
  maps/snaxi.dmm
Labels: Mapping (Snaxi ❄)

#37916 Lets detectives use click drag to open the camera bugs cigarette packet
  code/game/objects/items/devices/radio/radio.dm
Labels: Tweak

#37931 Midrounds/Latejoins Roll Less Often
  __DEFINES/role_datums_defines.dm
Labels: Gameplay / Gamemode

#37938 Revert "Cleans up the R&D console code a little"
  code/modules/research/rdconsole.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️

#37949 Temporarily disable SMES hum sound
  code/modules/power/battery.dm
Labels: Hotfix

#37973 Fixes material scanner
  code/datums/hud/material_hud.dm
Labels: Bug / Fix

#37993 Disable AFS
  code/game/machinery/alarm.dm
Labels: Hotfix

#37910 Makes roundend score affect next round's broken light, broken camera, and filth persistence levels.
  code/controllers/subsystem/init/more_init_stuff.dm
  code/controllers/subsystem/init/persistence_misc.dm
  code/game/gamemodes/endgame/scoreboard/misc_score.dm
  code/game/gamemodes/endgame/scoreboard/scoreboard.dm
  code/game/machinery/camera/camera.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/persistence/map_persistence_type.dm
  code/modules/power/lighting/lighting.dm
Labels: Gameplay / Gamemode

#37994 vomit electrolysis oversight bugfix
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Bug / Fix

#38005 Gun Sprite Flippening
  icons/obj/fakegun.dmi
  icons/obj/gun.dmi
  icons/obj/gun_experimental.dmi
Labels: Sprites, Consistency Issue

#37990 Enables Browser Inspect for Admins
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
Labels: Logging / Administration

#37979 Pulse Demon powers should no longer show maxed levels for attributes that can't be upgraded
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
Labels: Tweak

#37889 Fixes occasional bug with charge.
  code/modules/dna/genes/vg_powers.dm
Labels: Bug / Fix

#37972 Health Analyzer Pro now folds up
  code/game/objects/items/devices/healthanalyzerpro.dm
  icons/obj/device.dmi
  sound/machines/HAPF2.ogg
Labels: Content

#38008 Blob Thematic Music Starts Sooner
  code/datums/gamemode/factions/blob.dm
Labels: Gameplay / Gamemode, Sound, 0% tested

#37977 Changes SMES charge designation from W to KW
  code/modules/power/battery.dm
  nano/templates/smes.tmpl
Labels: Controversial, Grammar / Formatting

#37980 Pulse Demons glow modifications
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
Labels: Gameplay / Gamemode, Tweak

#37981 Pulse Demons inside APCs will now lock silicons out of the local machinery
  code/game/machinery/machinery.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/power/apc.dm
Labels: Balance, Gameplay / Gamemode

#38002 Reduces splashing range for breaking glasses to 0.
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Balance, Gameplay / Gamemode, i ded

#38014 Changeling roundstart ruleset will spawn an additional changeling at 24 players and above.
  code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
Labels: Balance, Gameplay / Gamemode

#38035 Fixes issues with borg talksounds.
  code/modules/client/client_procs.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Oversight

#38025 Juke Update 1: Eclipse
  code/datums/gamemode/factions/bloodcult/bloodcult.dm
  code/modules/media/jukebox.dm
  code/modules/trader/crates/shoaljunk.dm
  code/modules/trader/crates/zincsaucier.dm
Labels: ✋ Do Not Merge ✋, Sound

#38022 New Changeling upgrade: Faster Absorb DNA
  code/datums/gamemode/powers/changeling.dm
  code/datums/gamemode/role/changeling.dm
  code/modules/spells/changeling/absorb_dna.dm
Labels: Balance, Gameplay / Gamemode, Tweak

#38043 Fixes Supermatter Explosions not giving hallucinations to humans in closets
  code/modules/supermatter/supermatter.dm
Labels: Bug / Fix

#38069 Fixes unavailable job button
  code/modules/client/preferences/pref_datums_character.dm
Labels: Bug / Fix

#38070 Fixes Autonomous Fire Suppression
  code/game/machinery/alarm.dm
Labels: Bug / Fix, 100% tested

#38084 Lockbox fixes
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/lockbox.dm
Labels: Bug / Fix, Hotfix

#38101 fixes oversight with metastable mutagen
  code/modules/hydroponics/hydroponics_mutations.dm
Labels: Bug / Fix

#38088 Small Somatoray QoL
  code/modules/hydroponics/floral_somatoray.dm
Labels: ❤️ Quality of Life ❤️, 100% tested, Tweak

#38058 Summon Guns now has a 20% chance of playing a special audio file
  code/game/gamemodes/endgame/scoreboard/scoreboard.dm
  code/game/gamemodes/wizard/artifacts.dm
  sound/misc/ak47.ogg
Labels: Sound, Tweak

#38062 Improves Pulse Demon pulselocking
  code/game/machinery/ai_slipper.dm
  code/game/machinery/alarm.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/machinery.dm
  code/game/machinery/turrets.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
  code/modules/power/apc.dm
  icons/obj/power.dmi
Labels: Balance, Content

#38079 Day/Night Cycle Subsystem Refactor
  code/controllers/subsystem/daynightcycle.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/jungle.dm
  maps/_map.dm
  maps/junglestation.dm
  maps/snaxi.dm
Labels: 100% tested, File Cleanup

#38095 Grues will now only spawn on Snaxi when it's night
  maps/snaxi.dm
Labels: Gameplay / Gamemode

#38100 Wizard robes can now carry a few more items
  code/modules/clothing/suits/wiz_robe.dm
Labels: Gameplay / Gamemode, Tweak

#38104 Vox hair color fix
  code/modules/client/preferences/pref_datums_character.dm
Labels: Bug / Fix

#38103 Adds two vox hair styles
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/hair_styles.dmi
Labels: Sprites

#38089 Call of Spess 13
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/blood.dm
  icons/effects/blood.dmi
Labels: Sprites, Content, Port, 100% tested

#38060 Better Random Keg Sprites
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/objects.dmi
Labels: Sprites, 100% tested, Tweak

#38078 Adds Stamps to Office Supplies Crate
  code/datums/supply_packs/supplies.dm
Labels: 100% tested, Tweak

#38096 Adjusts Flare Hotspot Temperature
  code/game/objects/items/devices/flashlight.dm
Labels: 100% tested, Tweak

#38098 Buffs Chemical Tampering Machines
  code/game/machinery/chemHandC.dm
Labels: 100% tested, Tweak

#38085 Mr. V.A.L.I.D. portable threat detectors can now log passerbys
  code/game/machinery/metaldetector.dm
Labels: Content, ❤️ Quality of Life ❤️

#38009 Pauses and resets roundstart countdown if no players online
  __DEFINES/global.dm
  __DEFINES/setup.dm
  code/__HELPERS/time.dm
  code/controllers/mc/master.dm
  code/game/gamemodes/gameticker.dm
  code/modules/admin/admin.dm
Labels: ❤️ Quality of Life ❤️, Gameplay / Gamemode
