Repository vgstation-coders/vgstation13, pull requests merged in 2025-01, with the labels that each got.

#37355 Fixes Visually Reversed Belts
  code/modules/recycling/conveyor2.dm
Labels: Bug / Fix

#37369 Adminproofing the Climate Panel
  code/modules/admin/topic.dm
Labels: Logging / Administration

#37381 Adds a .NET 9 SDK setup action to linters
  .github/workflows/ci.yml
Labels: Automation/CI

#37367 Add logging to Chef Excellence's Special Sauce and always log & adminwarn on reagent transfers of dangerous reagents
  code/game/objects/objs.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/reagents/reagents_toxin.dm
Labels: Logging / Administration

#37370 Masks now provide some insulation to your breath (in other words, scarves and ski masks are now viable on Snaxi)
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
Labels: Balance, ❤️ Quality of Life ❤️

#37383 Fix fire closet welded sprite
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Labels: Bug / Fix

#37376 Allow silicon emotes for spiderbots
  code/modules/mob/living/silicon/emote.dm
Labels: Fluff :teddy_bear:

#37389 Fix #37386
  code/game/objects/items/devices/roganbot.dm
Labels: Oversight

#37380 Fix cake hats setting things on fire
  code/modules/clothing/head/misc_special.dm
Labels: Bug / Fix, Tweak

#37335 Panacea will now also remove the "suiciding" status
  code/modules/reagents/reagents/reagents_medical.dm
Labels: Oversight

#37398 Updates Python
  dependencies.sh
Labels: Automation/CI

#37377 New Stage 1 Symptom: Glutenolactic Emesis Syndrome
  code/modules/mob/living/carbon/human/human.dm
  code/modules/virus2/effect/stage_1.dm
Labels: Content

#37390 Straitjacket for aliens
  code/modules/clothing/suits/miscellaneous.dm
Labels: Balance, Needs Spritework, Tweak

#37362 Reverts the Roulette Revolver nerf (#35752)
  code/modules/projectiles/guns/projectile/roulette.dm
Labels: Controversial, Content, ⛔ Requires Server Vote ⛔, Unable to Reproduce

#37399 Fixes linters
  tools/requirements.txt
Labels: Automation/CI

#37400 Straitjacket sprites and fixes
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/species/insectoid/suit.dmi
  icons/mob/species/vox/suit.dmi
Labels: Bug / Fix, Sprites
