Repository vgstation-coders/vgstation13, pull requests merged in 2025-09, with the labels that each got.

#38294 Plasmaman Firefighter Suit
  code/datums/outfit/engineering.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  icons/mob/species/plasmaman/head.dmi
  icons/mob/species/plasmaman/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#38270 The round will no longer end after one hour of no players online
  code/datums/gamemode/dynamic/dynamic.dm
  code/datums/gamemode/gamemode.dm
  code/datums/gamemode/sandbox.dm
  code/game/gamemodes/gameticker.dm
Labels: Tweak

#38272 Metastable and Metatable Mutagen tweak
  code/modules/reagents/reagents/reagents_toxin.dm
Labels: Balance, Content

#38307 Hopefully fixes tooltips once and for all
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/movable_screen_objects.dm
  code/_onclick/hud/radial.dm
  code/_onclick/hud/screen_alarms.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/spell_screen_objects.dm
  code/_onclick/mindUI/_mindUI.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/cmc/crew.dm
  code/modules/tooltip/eta.min.js
  code/modules/tooltip/tooltip.css
  code/modules/tooltip/tooltip.dm
  code/modules/tooltip/tooltip.html
  code/modules/tooltip/tooltip.js
Labels: ❤️ Quality of Life ❤️

#38236 Pluckening v2
  __DEFINES/mobs.dm
  code/datums/helper_datums/butchering.dm
  code/game/objects/items/feather_items.dm
  code/game/objects/items/stacks/feathers.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/vox.dm
  code/modules/mob/living/carbon/monkey/vox.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/vox_feather_pluck.dm
  icons/mob/animal.dmi
  icons/mob/head.dmi
  icons/mob/human_races/vox/r_def_voxplucked.dmi
  icons/mob/human_races/vox/r_voxplucked.dmi
  icons/mob/human_races/vox/tails.dmi
  icons/mob/in-hand/left/bureaucracy.dmi
  icons/mob/in-hand/left/clothing.dmi
  icons/mob/in-hand/left/items_lefthand.dmi
  icons/mob/in-hand/right/bureaucracy.dmi
  icons/mob/in-hand/right/clothing.dmi
  icons/mob/in-hand/right/items_righthand.dmi
  icons/mob/monkey.dmi
  icons/mob/radial.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/mob/suit_fat.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/butchering_products.dmi
  icons/obj/christmas.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items.dmi
  vgstation13.dme
Labels: Honk, Content, Fluff :teddy_bear:

#38377 Adds Dragging Crates onto Crate Weighers
  code/datums/cargo_forwarding.dm
Labels: ❤️ Quality of Life ❤️, 100% tested

#38400 Table door fixes
  code/game/machinery/doors/table.dm
  icons/obj/doors/tabledoor.dmi
Labels: Bug / Fix, ❤️ Quality of Life ❤️, Tweak

#38405 Pluckening Icon Fixes
  icons/mob/head.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Bug / Fix, Hotfix, Sprites

#38363 Crate Jiggling Update
  code/controllers/subsystem/supply_shuttle.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/recycling/disposal.dm
Labels: 100% tested, Tweak

#38376 Plasma Cutter Changes
  code/game/objects/items/devices/modkit.dm
  code/modules/mining/mine_items.dm
  code/modules/research/designs/mining.dm
  code/modules/research/research.dm
  icons/mob/in-hand/left/guns.dmi
  icons/mob/in-hand/right/guns.dmi
  icons/obj/items.dmi
Labels: Balance, Sprites, 100% tested

#38390 Removes packed station increased uplink prices
  maps/packedstation/uplink_item.dm
Labels: Tweak

#38462 Mining Pickaxe Speed Hotfix
  code/__HELPERS/unsorted.dm
  code/game/objects/items/stacks/stack_recipes.dm
Labels: Hotfix, 100% tested

#38452 Makes more admin tools use filtered type lists with text matches
  code/datums/gamemode/objectives/target/syndicate/steal.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  maps/_map.dm
Labels: ❤️ Quality of Life ❤️, Logging / Administration

#38463 Xenoarch Debug Small Find Spawn Tool
  code/modules/admin/artifacts_panel.dm
  code/modules/admin/topic.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Logging / Administration, 100% tested
