Repository vgstation-coders/vgstation13, pull requests merged in 2025-05, with the labels that each got.

#37505 New wiz spell: Curse of Norwood
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/structures/mirror.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/spells/targeted/norwood.dm
  vgstation13.dme
Labels: Content, Needs Spritework

#37537 May fix the login failure issue on 516
  code/modules/client/client procs.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, T-Thanks BYOND, Secret repo conflict.

#37512 I am become Honk... Destroyer of Rounds... New Amino-Reagent: Aminocorydon
  __DEFINES/reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/reagents/reagents_reactive.dm
Labels: Honk, Content, 100% tested

#37525 Some fixes for wrapper code
  code/game/objects/items/stacks/packagewrap.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️

#37522 Fixes a define from 2017
  __DEFINES/economy.dm
  code/game/machinery/ATM.dm
  code/modules/Economy/Accounts.dm
  code/modules/Economy/utils.dm
  vgstation13.dme
Labels: File Cleanup

#37521 Fixes Lazarus injector not reviving simple animals who died of heat
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bug / Fix

#37519 Add an icon for the norwood spell
  code/game/gamemodes/wizard/spellbook_oneuse.dm
  code/modules/spells/targeted/norwood.dm
  icons/mob/screen_spells.dmi
  icons/obj/library.dmi
Labels: Sprites

#37517 Makes fire alarms always check for shelter inside before putting one in
  code/game/machinery/alarm.dm
Labels: Bug / Fix, Sanity / Ghosthands

#37542 Fixes compile for norwood
  code/modules/spells/targeted/norwood.dm
Labels: Hotfix

#37511 Custom sounds for ladders
  code/game/objects/structures/ladders.dm
Labels: Content, Logging / Administration

#37527 fission reactor extended options menu
  code/modules/fissionreactor/fission.css
  code/modules/fissionreactor/fission_datums.dm
  code/modules/fissionreactor/objects_external.dm
Labels: ❤️ Quality of Life ❤️

#37507 Fixes/refactors Simpolinol
  code/modules/reagents/random_reagent_effect.dm
  code/modules/reagents/randomized_reagent.dm
  code/modules/reagents/reagents/reagents_medical.dm
  vgstation13.dme
Labels: Bug / Fix, Content

#37546 makes fission reactors much cheaper
  code/datums/supply_packs/engineering.dm
  code/modules/fissionreactor/misc.dm
Labels: Balance, Tweak

#37529 cryotheum canister
  code/game/machinery/atmoalter/canister.dm
  icons/obj/atmos.dmi
Labels: Sprites, Content

#37555 Fridges were using wrong dir
  maps/derelicts/derelict_cult.dmm
  maps/derelicts/derelict_pool.dmm
Labels: Bug / Fix, Mapping (General :world_map:)

#37564 Fixes ghosted mobs duplicating their attack logs
  code/datums/mind.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Bug / Fix, Logging / Administration

#37582 Fixes some HTML interfaces
  code/game/machinery/ai_slipper.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/turrets.dm
  code/modules/power/rust/fuel_compressor.dm
  code/modules/power/solars/control.dm
  code/modules/power/turbine.dm
Labels: Bug / Fix, UI

#37583 Fixes security cameras prev/next buttons
  code/game/machinery/computer/camera.dm
  tgui/packages/tgui/interfaces/CameraConsole.tsx
  tgui/public/tgui.bundle.js
Labels: Bug / Fix

#37566 Removes white space from `modules/client` files
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  vgstation13.dme
Labels: File Cleanup, skub

#37554 Adds more variety to detective's fake ID names
  code/game/objects/items/weapons/cards_ids.dm
Labels: Fluff :teddy_bear:, Verified :white_check_mark:

#37556 Bloodstone Melee Vulnerability
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
Labels: Balance

#37591 Fixes CTRL+F on 516
  code/modules/mob/login.dm
Labels: Bug / Fix

#37589 update SpacemanDMM from 1.8 to 1.10
  .github/workflows/ci.yml
Labels: Automation/CI

#37567 Gets rid of painting replicas on the scoreboard
  code/modules/html_interface/paintTool/custom_painting_datum.dm
  code/modules/painting/paintings_custom.dm
Labels: Bug / Fix, Oversight

#37563 Add logging for mobs being bumped into grille/suppermatter
  code/__HELPERS/mobs.dm
  code/game/objects/structures/grille.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Logging / Administration

#37599 Fixes AI state laws
  nano/templates/state_laws.tmpl
Labels: Bug / Fix

#37598 Should fix all the remaining malformed HTML (5 real this time)
  code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
  code/datums/profiling.dm
  code/game/machinery/ATMOSPHERICS/components/binary_devices/pump.dm
  code/game/machinery/ATMOSPHERICS/components/binary_devices/volume_pump.dm
  code/game/machinery/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/game/machinery/ATMOSPHERICS/components/trinary_devices/mixer.dm
  code/game/machinery/ATMOSPHERICS/hvac/chiller.dm
  code/game/machinery/ATMOSPHERICS/hvac/spaceheater.dm
  code/game/machinery/ATMOSPHERICS/pipe/pipe_dispenser.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/ed209bot.dm
  code/game/machinery/bots/farmbot.dm
  code/game/machinery/bots/floorbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/bots/secbot.dm
  code/game/machinery/computer/HolodeckControl.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/shuttle_computers.dm
  code/game/objects/items/devices/healthanalyzerpro.dm
  code/modules/admin/verbs/SDQL_2/SDQL_2.dm
  code/modules/hydroponics/eggincubator.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/library/lib_items.dm
  code/modules/media/mediamanager.dm
  code/modules/mining/ore_box.dm
  code/modules/mining/ore_redemption.dm
  code/modules/power/port_gen.dm
  code/modules/reagents/machinery/pandemic.dm
  code/modules/research/server.dm
  code/modules/virus2/isolator.dm
Labels: Bug / Fix

#37616 Fixes investigate logs
  code/modules/admin/admin_investigate.dm
  code/world.dm
Labels: ⚠️ OH GOD IT'S LOOSE ⚠️, Logging / Administration

#37622 very inelegantly fixes TGUI black squares
  code/__HELPERS/datum.dm
  code/controllers/subsystem/tgui.dm
  code/game/machinery/computer/camera.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_window.dm
Labels: Bug / Fix

#37624 Fixes manuals
  code/modules/library/lib_items.dm
Labels: Bug / Fix

#37627 The security camera console tgui will now fully close
  code/game/machinery/computer/camera.dm
Labels: Oversight

#37635 Weakrefs don't harddel
  code/__HELPERS/weakref.dm
Labels: Performance

#37631 distinguishes between roundstart hdels and in-round hdels
  __DEFINES/atoms.dm
  code/controllers/subsystem/garbage.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
Labels: Performance

#37629 Policy on account blocking added to the code of conduct.
  CODE_OF_CONDUCT.md
Labels: Logging / Administration

#37626 Fixes writing on paper without a pen
  code/modules/paperwork/paper.dm
Labels: Bug / Fix

#37597 Fur Trapper Suit
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/wintercoat.dm
  icons/mob/head.dmi
  icons/mob/in-hand/left/clothing.dmi
  icons/mob/in-hand/right/clothing.dmi
  icons/mob/suit.dmi
  icons/mob/suit_fat.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Content

#37641 Fixes meat hard dels, fixes new player hard del
  code/controllers/mc/failsafe.dm
  code/controllers/mc/master.dm
  code/controllers/subsystem/garbage.dm
  code/datums/gamemode/misc_gamemode_procs.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/gameticker.dm
  code/game/procs/statistics.dm
  code/modules/client/secret_hwaccel_check.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/recycling/disposal.dm
  code/world.dm
  vgstation13.dme
Labels: Performance
