Repository vgstation-coders/vgstation13, pull requests merged in 2025-04, with the labels that each got.

#37485 Pixel Shifting
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_movement.dm
  interface/skin.dmf
  interface/skin_azerty.dmf
Labels: Honk

#37488 Revert "THE HANDHOLDING UPDATE"
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature Loss

#37477 Making unit tests and map compiling work in CI again
  code/modules/flufftext/Dreaming.dm
  tools/travis/travis_utils.py
Labels: Automation/CI

#37478 Fixes grille spawned windows not having proper density
  code/game/objects/effects/spawners/grille_window_spawner.dm
Labels: Bug / Fix

#37490 Readds missing killdozer icons
  icons/mecha/mecha.dmi
Labels: Bug / Fix

#37489 Phytochemistry Chemical mutation tweak
  code/modules/hydroponics/hydroponics_mutations.dm
Labels: Balance, Tweak

#37493 Fixes non existant escape pods crashing into shuttle
  code/game/turfs/simulated/shuttle.dm
Labels: Bug / Fix

#37504 Ladders (the adminbus update)
  code/game/objects/structures/ladders.dm
Labels: ❤️ Quality of Life ❤️, Logging / Administration

#37481 Buffs to Ironrot Reagent
  code/modules/reagents/reagents/reagents_bio.dm
Labels: Balance, Content

#37499 Derelict and Derelict Area fixes
  code/game/area/Space Station 13 areas.dm
  maps/fixedvaults/oldstation.dmm
Labels: Mapping (General :world_map:)

#37503 Makes medical nanobots heal broken bones
  code/modules/reagents/reagents/reagents_medical.dm
Labels: Bug / Fix, Balance, Oversight

#37497 The lockbox access update
  code/_onclick/hud/screen_objects.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/objects/items/stacks/stack_recipes.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/windoor_assembly.dm
  code/modules/research/designs/data.dm
  code/modules/research/designs/medical.dm
  code/modules/research/designs/misc.dm
Labels: Content
