Repository vgstation-coders/vgstation13, pull requests merged in 2025-08, with the labels that each got.

#38135 Fixes HOGs Spawning Clownlings
  code/modules/mob/living/simple_animal/hostile/hog.dm
Labels: Hotfix

#38146 Fixes Upgraded Welders
  code/game/objects/items/weapons/tools.dm
Labels: Hotfix, 0% tested

#38107 Remove the cooldown from regenerative stasis
  code/modules/spells/changeling/regenerative_stasis.dm
Labels: Balance

#38116 Gun Ammo Casings Fly Out
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/minigun.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: 100% tested, Tweak

#38118 PDA polls now obey text sending cooldown (+ notifying user of it)
  code/game/objects/items/devices/PDA/apps/messenger.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️, Consistency Issue

#38138 Using a fire source in an offhand with fuel filled sprays for ghetto flamethrower.
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Content

#38137 Recharge stations describe mob inside them on examine.
  code/game/machinery/rechargestation.dm
Labels: Content

#38167 Sanity check on list pointers
  code/_onclick/hud/screen_objects.dm
Labels: File Cleanup

#38144 Ups the base engineering hardsuit radiation resistance to 80%
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
Labels: Balance, Tweak

#38124 Fixes Ethereal Jaunt a bit
  code/datums/hud/hud.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
Labels: Bug / Fix

#38086 Loneliness syndrome
  code/controllers/subsystem/ambient_sound.dm
  code/datums/chat_message.dm
  code/datums/emotes.dm
  code/datums/gamemode/factions/faction.dm
  code/datums/hud/cult_construct_hud.dm
  code/datums/hud/cult_conversion_hud.dm
  code/datums/hud/diagnostic_hud.dm
  code/datums/hud/implant_hud.dm
  code/datums/hud/job_hud.dm
  code/datums/hud/medical_hud.dm
  code/datums/hud/nullrod_hud.dm
  code/datums/hud/security_hud.dm
  code/game/area/ambience_datums.dm
  code/game/area/areas.dm
  code/game/objects/structures/musician.dm
  code/game/sound.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/hostile/duck.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/mob.dm
  code/modules/sound/sound_emitter.dm
  code/modules/virus2/effect/stage_4.dm
  sound/ambience/nobodyhere.ogg
Labels: Content

#38117 Simple animals should now get intermediary temperature alarms.
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: ❤️ Quality of Life ❤️, Tweak

#38170 Optimizes sparks to somewhat impede lag
  code/game/machinery/antiquemattersynth.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/structures/electricchair.dm
Labels: T-Thanks BYOND, Tweak

#38166 Fixes monkey-to-human animation being far longer than it should be.
  __DEFINES/mobs.dm
  code/modules/dna/genes/monkey.dm
  code/modules/mob/transform_procs.dm
Labels: Bug / Fix, Sprites

#38162 Vampire Nerf: Thralls now get affected by being splashed with holy water
  code/datums/gamemode/role/vampire_role.dm
Labels: Balance, Tweak

#38154 Ninja can now block flashes with the hologram
  code/game/objects/items/devices/flash.dm
Labels: Balance, Tweak

#38185 Fixes spaces and full stops on small xenoarch finds
  code/modules/research/xenoarchaeology/finds/finds.dm
Labels: Grammar / Formatting

#38178 Mr. V.A.L.I.D. logging fixes
  code/game/machinery/metaldetector.dm
Labels: Bug / Fix

#38207 Nerfs Supermatter
  code/modules/supermatter/supermatter.dm
Labels: Bug / Fix, Honk, Unable to Reproduce

#38204 Mice now wake up when you step on them, and have visible messages when they take a nap or wake up
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_diseases.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  vgstation13.dme
Labels: Bug / Fix, Tweak

#38202 The necklace update
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/teeth.dm
  code/modules/clothing/masks/necklaces.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/trader/crates/misc_variety.dm
  icons/mob/clothing_accessories.dmi
  icons/mob/mask.dmi
  icons/mob/species/insectoid/clothing_accessories.dmi
  icons/mob/species/insectoid/mask.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/accessory_overlays.dmi
  icons/obj/clothing/masks.dmi
  maps/randomvaults/spacepond.dmm
Labels: ❤️ Quality of Life ❤️, Tweak

#38191 Avocados deshittified
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
Labels: Bug / Fix, 100% tested

#38190 Allows all kinds of floor tiles to be click dragged, not just metal/plasteel
  code/_onclick/hud/draggable.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/stacks/tiles/tiles.dm
  icons/mob/screen_draggable.dmi
Labels: Consistency Issue

#38189 Adds the ability to re-name plants
  code/modules/hydroponics/seeds.dm
Labels: Content, ❤️ Quality of Life ❤️, 100% tested

#38181 Gym Rat (and children) standing up / laying down tweak
  code/modules/mob/living/simple_animal/hostile/gym_rats.dm
Labels: Balance

#37933 Sound system v2
  __DEFINES/setup.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystem/sounds.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/camera/camera.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob_movement.dm
  code/modules/sound/managed_sound.dm
  code/modules/sound/sound_channel_manager.dm
  code/modules/sound/sound_emitter.dm
  code/modules/sound/sound_listener_context/sound_listener_context.dm
  code/modules/sound/sound_listener_context/sound_listener_context_ai.dm
  code/modules/sound/sound_zone_manager.dm
  vgstation13.dme
Labels: System, Sound, WiP

#38226 Transparent pipe painting
  __DEFINES/setup.dm
  code/game/machinery/ATMOSPHERICS/atmospherics.dm
  code/game/machinery/ATMOSPHERICS/components/unary/cap.dm
  code/game/machinery/ATMOSPHERICS/datum_pipe_network.dm
  code/game/machinery/ATMOSPHERICS/datum_pipeline.dm
  code/game/machinery/ATMOSPHERICS/pipes.dm
  code/modules/RCD/schematics/pipe.dm
  icons/obj/atmospherics/gas_overlays.dmi
Labels: Sprites

#38238 Fixes non-metal tables disassembling into less metal than they should
  code/game/objects/items/weapons/table_rack_parts.dm
Labels: Bug / Fix

#38237 Freezers/heaters now cool/heat faster with better stock parts.
  code/game/machinery/Freezer.dm
Labels: Balance, Tweak

#38231 fission tweaks: the reboot
  code/datums/supply_packs/engineering.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/fissionreactor/fission_datums.dm
Labels: Balance, Tweak

#38232 R&D fixes and tweaks
  code/modules/research/fabricators.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
Labels: Bug / Fix, ❤️ Quality of Life ❤️, Tweak

#38261 Reverts Powercreep "Ups the base engineering hardsuit radiation resistance to 80%" Due to Unpopularity
  code/modules/clothing/spacesuits/rig_subtypes/rig_subtypes.dm
Labels: Controversial, Balance, Tweak

#38251 Fixes skull capture objective on low populations
  code/datums/gamemode/objectives/target/syndicate/skulls.dm
Labels: Oversight

#38244 Restores the Fission Reactor's plasma into phazon reaction.
  code/modules/reagents/fission.dm
  code/modules/reagents/reagents/reagents_material.dm
Labels: Balance

#38250 Item printing fix and R&D recycling exploit patch
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/switchtool.dm
  code/modules/research/designs.dm
  code/modules/research/designs/medical.dm
  code/modules/research/designs/robotics.dm
  code/modules/research/designs/surgery.dm
  code/modules/research/fabricators.dm
Labels: Bug / Fix, Balance

#38253 Lets blueprints create areas on the mine
  code/modules/mining/mine_areas.dm
Labels: Bug / Fix, Oversight, Tweak

#38247 ZKZ transactional rifle
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/projectiles/guns/projectile/zkz.dm
  code/modules/projectiles/projectile/bullets.dm
  sound/weapons/vag.ogg
  sound/weapons/vag2.ogg
  vgstation13.dme
Labels: Content

#38264 Caps the amount of sheets a material synthesizer can produce at a time to 50
  code/game/objects/items/devices/mat_synth.dm
Labels: Balance, Tweak
